rust-windowing/winit

Cargo.toml, src/api/wayland/context.rs, src/api/wayland/window.rs, src/os/unix.rs
This removes all EGL-specific code from the wayland backend.
Notable unresolved question: due to wayland design, the resizing
methods will only get/set the size of the drawn borders, not of the
actual content drawn. This latter size cannot be controlled by winit.
This will require some more work on my side on `wayland-client` for it to work with glutin, but it will only impact glutin, not winit. This PR should be enough for first Vulkan steps.
=> wayland: Remove EGL-dependent code.

Cargo.toml, src/api/x11/ffi.rs, src/api/x11/window.rs, src/api/x11/xdisplay.rs, src/os/unix.rs
Due to XCB and Xlib compability, we can take a shortcut and use X11's
underlying xcb_connection. This way, a complete XCB backend implementation can
be avoided.
Once this is merged and published, I also have a PR for vulkano to fall back to xcb if nothing else works.
=> Add support for xcb

src/api/win32/callback.rs, src/api/win32/init.rs, src/lib.rs, src/platform/windows/mod.rs
When creating a window in win32, `winit` would previously not show the window resize cursors when the user attempted to resize the window. This fixes that, so that the resize cursors show properly. Also fixes some warnings when building for Windows.
=> Fix win32 bug where window resize cursors would not show

src/api/wayland/window.rs
Without that, the border actually drawn do not match the size the window believe it has.
=> wayland: sync drawn border size on window creation

src/platform/linux/api_dispatch.rs
The wayland backend has been active for some time, but for some reason the comment was not removed (most likely I forgot it).
=> linux: remove outdated comment

examples/window.rs, src/lib.rs, src/window.rs
This allows for passing the window_resize_callback fn during the window
building stage. More importantly, this allows setting the callback
without the need for mutable access to the Window, making it possible
to set the callback in the downstream glium crate.
This may solve tomaka/glium#1232 for most folk.
=> Add a `WindowBuilder::with_window_resize_callback` method.

examples/cursor.rs, examples/fullscreen.rs, examples/grabbing.rs, examples/min_max_size.rs, examples/multiwindow.rs, examples/transparent.rs, examples/window.rs
No longer needed with android-rs-glue 0.2
The examples probably weren't compiling on Android without this change.
=> Remove android_main! call

Cargo.toml
Primarily to pick up https://github.com/tomaka/winit/pull/89.
=> Bump version to 0.5.6.

Cargo.toml, src/platform/macos/mod.rs
Fixes https://github.com/tomaka/winit/issues/57.
=> Implement window transparency on macOS.

src/platform/macos/mod.rs
This fixes propagation of Event::Awakend when using poll_event() on
macOS
=> macos: Map our user generated event to Event::Awakened

src/api/x11/window.rs
Fix #120.
I didn't find if "hand2" is universally available, so I used the old value "hand1" as a fallback.
=> Use a hand pointing a finger in X11 as MouseCursor::Hand

src/platform/macos/mod.rs
These events are batched, and delievered en masse at the end of the resize. This isn't a great developer experience (and it should probably be called out in the docs), but it makes it possible for winit client applications to detect and respond to resizes without special-casing Mac OS targets.
See #39. This is only a partial fix, and does not provide on-the-fly resize events.
=> Naive implementation of resize events for OS X.

src/api/x11/window.rs
WaitEventsIterator implements waiting by first calling XPeekEvent which
will block until at least 1 event is queued, and then it delegates to
PollEventsIterator to actually handle the new event. PollEventsIterator
was previously picky about which events it would process. Events of
other types would get stuck at the head of the X event queue, and
PollEventsIterator would return None. This initiated a busy loop in the
WaitEventsIterator because it would XPeekEvent, see that something is
there, and then PollEventsIterator would return None, and the process
would repeat.
This is resolved by using XNextEvent in the PollEventsIterator instead
of XCheckTypedEvent. Any event in the queue will be popped. Even if
winit isn't interested in the event, this means XPeekEvent will block
again to wait …
=> Fix busy loop in X11 WaitEventsIterator

examples/cursor.rs, examples/fullscreen.rs, examples/grabbing.rs, src/api/wayland/context.rs, src/api/wayland/keyboard.rs, src/api/x11/input.rs, src/events.rs, src/platform/macos/events_loop.rs, src/platform/windows/callback.rs, src/platform/windows/event.rs
Making applications track modifier keys results in unnecessary work for
consumers, it's error prone, and it turns out to have unavoidable bugs.
For example, alt-tabbing with x11 results in the alt modifier state
getting stuck.
To resolve these problems, this patch adds a Mods value to the keyboard
input event.
Based on this patch: jwilm/glutin@d287fa9
This PR resolves issues #77 and #108
=> Add keyboard modifiers to input event

src/api/x11/window.rs
Implement Window::hidpi_factor() for X11.
It calculates a geometric mean of x and y scale factor then quantize it with 1/12 step size.
Quantization is required because X returns display size in integer mm, calculated dpi value has an error even if dpi is exactly 96.
=> implement Window::hidpi_factor() for X11.

src/platform/linux/mod.rs
=> linux: Add missing Window2::id() impl

src/platform/linux/x11/window.rs, src/platform/macos/window.rs
macOS already had some code in place trying to remove the title bar, but it was not correct. Also, transparent windows on macOS always had a title bar, which may not always be desired.
Tested on Arch Linux with kwin (on KDE5 with Plasma) and i3 window managers. And on macOS El Capitan, 10.11.
@mitchmindtree: You might wanna take a look, since you mentioned the macOS problem in [my glutin PR](https://github.com/tomaka/glutin/pull/865).
=> Support removing window decorations in x11 and macOS

Cargo.toml, src/platform/android/mod.rs
Implement android events and wake event loop.
=> Implement android events and wake event loop

Cargo.toml, src/platform/linux/wayland/context.rs
This updates the wayland dependencies to their last versions.
Due to the version bump, it is a breaking change to unix::WindowExt::get_wayland_client_{display,surface}. However these methods are not part of winit's public API, and only to be used with glutin.
The transition glutin-side can be easily made in conjunction with the update of glutin to the new API of winit, by making the next version of glutin to directly depend on winit-0.6.2 and updating its wayland dependencies.
This way, no breakage will be exposed to glutin's nor winit's users.
=> wayland: Update to wayland 0.8.6

Cargo.toml, src/os/unix.rs
This pub import was accidentally removed in #150, and is used by glutin.
However it exposes the integrality of winit's guts regarding x11, which is probably not wanted... ? Maybe a more selective import should be appropriate, and in this case, what should we expose?
(glutin needs at least `XError`, `XNotSupported`, and `XConnection`)
=> Readd pub import erroneously removed

src/platform/macos/events_loop.rs, src/platform/macos/mod.rs, src/platform/macos/window.rs
While updating `glutin` and `glium` and testing their examples, several bugs in the macOS backend started to show themselves. See the individual commits and their messages for details on each of the fixes.
Closes #73.
=> Several fixes for the macOS backend

src/events.rs
This allows to have an array of `bools` for the key states.
Fixes #87
=> Set #[repr] of VirtualKeyCode to u32

src/platform/linux/x11/mod.rs, src/platform/macos/events_loop.rs
All platforms should now receive events in the following order:
1. KeyboardInput(ElementState::Pressed, ..)
2. ReceivedCharacter
3. KeyboardInput(ElementState::Released, ..)
cc https://github.com/tomaka/glutin/issues/878
=> Make keyboard input event order consistent

src/platform/linux/x11/mod.rs
If the interrupted flag were set going into poll_events, it would only
ever handle the first event in the queue. Now, the flag is reset at the
start so events are processed until the caller requests otherwise.
=> Fix poll_events on x11 not draining completely

src/platform/linux/wayland/event_loop.rs
cc https://github.com/tomaka/glutin/issues/884
=> wayland: Fix deadlock in poll_events

README.md
The existing README no longer compiles.
=> Update README example to use EventsLoop

README.md
It now matches the current release line, 0.6.x
=> Update 'winit' dependency in README

Cargo.toml, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/mod.rs, src/platform/linux/wayland/window.rs
This adds a dependency on the tempfile crate, but this was already a transitive dependency via wayland-window.
This PR uses the basic mechanism of wayland for passing memory buffers to paint the window content white once at creation, to ensure the window actually exists and can receive events, to avoid the issues like https://github.com/tomaka/glutin/issues/884
This mechanism is guaranteed to always be available by the wayland spec, and does not pose any problem to initialize an EGL or Vulkan context afterwards.
closes #109
=> wayland: Initially paint the window white so that they always exist

Cargo.toml, src/lib.rs, src/os/unix.rs, src/platform/linux/wayland/event_loop.rs
This PR removes the two methods from the unix `WindowExt` trait exposing wayland_client's types, as glutin does not need them any more (see https://github.com/tomaka/glutin/pull/893) and the next release will already contain breaking changes.
As wayland_client is no longer exposed in winit's API, this also upgrades the wayland dependencies.
=> Stop exposing wayland_client's types

src/lib.rs, src/platform/linux/mod.rs, src/window.rs
Will prefer X over wayland when the environment variable `WINIT_PREFER_UNIX_BACKEND=x11` is set.
This came out as the simplest and least destructive way of actually having winit work under wayland at the moment, without redesigning the API to remove static initialisation of the unix backend see #182.
=> Allow usage of XWayland

Cargo.toml, src/platform/ios/ffi.rs, src/platform/macos/window.rs
Nightly recently fixed some soundness issues related to `Sized`. This had to be fixed in the cocoa crates as well, and also affects our ios bindings. We'll need to flow this update through to glium and glutin to fix this problem for them as well.
=> Update Mac OS dependencies

src/platform/windows/events_loop.rs, src/platform/windows/window.rs
This PR implement's @Ralith's original `Motion` API for Windows.
The event names will be be out of date if/when #192 lands, but it should be an easy change.
=> Implement raw mouse motion for Windows

Cargo.toml, src/lib.rs
I was wondering why my Vulkan projects had a dependency on `gl_generator`.
@mitchmindtree I suppose this was a mistake?
=> Remove dependency on cgl on OSX

Cargo.toml, src/platform/linux/x11/mod.rs
Fixes: https://github.com/tomaka/winit/issues/217
*   Direction issue was resolved by swapping the order of the operands in `(unsafe { *value } - info.position)`
*   "Stored up" scrolls issue was resolved by updating the scroll position, stored in the relevant Device, every XI_Enter event
=> Fix x11 mouse scroll wheel

Cargo.toml, src/platform/linux/x11/mod.rs
Fixes half of https://github.com/tomaka/winit/issues/226
The modifier fields were changed AFTER callback(..) is callled.
=> Fix x11 WindowEvent ModifiersState

src/events.rs, src/lib.rs, src/platform/linux/x11/mod.rs
Per IRC discussion, this replaces the `AxisId`/`ButtonId` newtypes with type aliases, and relocates them to the `events` module. This makes generic input events usable in practice, and is more consistent with the existing `ScanCode` type.
Replaces #172.
=> Transparent axis/button IDs

src/platform/windows/events_loop.rs
An inconsistency was introduced by the independent merging of #211 with #213.
=> Fix windows build

src/platform/linux/x11/mod.rs
This was inconsistent with the documented semantics of MouseScrollDelta.
Partially addresses #233.
=> Fix X11 scroll direction

src/platform/windows/events_loop.rs
Right now, `winit` uses a `PeekMessageA` call to initialize the message queue for the thread that owns the window.
The specific function to use in this case is [`IsGUIThread`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633525(v=vs.85).aspx), which has a `bConvert` parameter, which asks Windows to convert the thread to a GUI thread with a message queue.
=> Use `IsGUIThread` to initialize message queue

Cargo.toml, examples/cursor.rs, examples/fullscreen.rs, examples/grabbing.rs, examples/min_max_size.rs, examples/multiwindow.rs, examples/proxy.rs, examples/transparent.rs, examples/window.rs, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/mod.rs, src/platform/linux/wayland/window.rs
This upgrades the wayland-window dependency to support the xdg_shell wayland protocol, which is largely recognized as the way forward for wayland apps (thanks to @mitchmindtree for helping implementing that).
As a result, winit has a slightly different behavior, depending on which of wl_shell or xdg_shell is used, and I don't see any reasonable way to fix that, however I believe it's relatively minor.
- If using wl_shell (the legacy protocol), winit will blank the window at creation. This is necessary because otherwise the window don't exist in wayland while it has not yet been drawn, and the events loop gets stuck receiving nothing.
- if using xdg_shell, we cannot blank it at this point of time (the protocol forbids doing it this early). However, the events loop cannot get stuck. This …
=> Update wayland-window to support xdg_shell

src/platform/linux/x11/window.rs
X11 always return the geometry in pixel units. Since
window.get_inner_size returns the size in points in other window manager
implementations X11 should also return in points instead of pixels.
This commit also fixes https://github.com/tomaka/glutin/issues/903
=> Fixes window inner size calc for hidpi windows X11

examples/multiwindow.rs, src/platform/windows/events_loop.rs, src/platform/windows/window.rs
WM_CLOSE is used instead of WM_DESTROY
A simple test is also added to multiwindow to test impl Drop for Window.
=> Issue 240 alternative fix

src/platform/macos/events_loop.rs, src/platform/macos/window.rs
Also hide the cursor when grabbed, to prevent the cursor being in an inconsistent state after both hiding and grabbing.
=> Implement raw mouse movement for Mac

src/platform/windows/events_loop.rs
Before this change, when a `WM_SIZE` message was received it would throw a `Resized` event at the parent `EventLoop` thread and return immediately. There are two issues with that approach: win32 would proceed to resize the window before the application had been redrawn leading to visible black bars, and the immediate return would lead to win32 generating resize events at a rate far higher than any renderer could handle. The result of that is visible [here](https://gfycat.com/DecimalCavernousBlobfish).
This PR makes the win32 event loop thread sleep until the `Resized` event is processed by the `EventsLoop` struct, only returning after the event closure returns. This vastly decreases the number of resize messages sent, and delays resizing until after the application has handled the …
=> Fix window contents not resizing in lockstep with window resize on win32

src/events.rs, src/platform/macos/window.rs
Here's an implementation for drag and dropping files on Mac OS. I needed to add two events for `HoveredFile` and `HoveredFileCancelled`, as without them how are you supposed to update your gui? :)
At the moment, the DropFile only supports one FileBuf, and not an array... which is harder to deal with and you can't reject the drop during hover based on a file filter (say the user drops four valid files and one invalid one). But since there's a windows implementation of this (though it seems buggy/limited to 255 chars) I decided to leave it for now.
I wasn't too sure of winits code conventions, it seems to repeat code in places (like dispatching events) so I have stayed away from adding convenience methods etc. Please let me know if I should do something else to conform to winits approach …
=> Mac file drag and drop

src/lib.rs, src/os/macos.rs, src/os/unix.rs, src/os/windows.rs, src/platform/android/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/window.rs, src/platform/macos/monitor.rs, src/platform/macos/window.rs, src/platform/windows/monitor.rs, src/platform/windows/window.rs, src/window.rs
This PR removes `MonitorId::get_native_identifer()` and replaces it with platform-specific functions in the various `os` modules.
This makes the design consistent with the other platform-specific retrieval methods.
=> Rework MonitorId::get_native_identifier

Cargo.toml, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/window.rs
This PR does three things:
- fix #254 by properly waiting for the configure xdg event from the compositor, this is done by introducing an internal buffer to collect events dispatched internally, while `Window::new()` may be blocking
- automatically insert a `WindowEvent::Refresh` in this internal buffer whenever a window is created, this guarantees the event loop will have something to dispatch when first started, and should solve for good any issue of deadlock of the event loop as previously saw with wayland (without that, the multiwindow example of glutin _still_ deadlocked)
- update the `wayland_window` dependency, which provides a better handling of said configure event
=> wayland: internal event buffer & wait for xdg configure

examples/fullscreen.rs, src/api_transition.rs, src/lib.rs, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/mod.rs, src/platform/macos/mod.rs, src/platform/macos/monitor.rs, src/platform/windows/mod.rs, src/platform/windows/monitor.rs, src/window.rs
Based on #267 
cc @alexheretic
This PR ties the `EventsLoop` to a specific X11 or Wayland connection on Linux. Creating the `EventsLoop` also creates the connection. We still use a `lazy_static` for the X11 connection though, because of the badly-designed `XSetErrorHandler` function.
Also adds an `EventsLoopExt` trait in `os::linux` that allows choosing whether the `EventsLoop` uses X11 or Wayland. The default `new()` function has the same behaviour as today.
Breaking changes:
- Removes `os::linux::get_x_connection()`. I don't remember what it was used for, but it was a bad design anyway. We can always reintroduce an equivalent through the `EventsLoopExt` trait if required.
- `get_available_monitors()` and `get_primary_monitor()` are now methods of `EventsLoop` instead of being …
=> Events loop backend

.travis.yml, examples/fullscreen.rs, src/lib.rs, src/platform/android/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/ffi.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/window.rs, src/platform/linux/x11/xdisplay.rs, src/platform/macos/monitor.rs, src/platform/macos/window.rs, src/platform/windows/monitor.rs, src/platform/windows/window.rs, src/window.rs
The previous XF86 resolution switching was broken and everything seems to have moved on to xrandr. Use that instead while cleaning up the code a bit as well. Right now everything seems to work fine. The only bug I've noticed is that at least in Unity after the resolution change the top bar is still there. Doing an alt-tab from and to the app again makes `_NET_WM_STATE_FULLSCREEN` take effect. Don't know how to fix that right now but this is already much better than what was before.
=> Move fullscreen modes to not touch physical resolutions

CHANGELOG.md, Cargo.toml
Now with a changelog.
If relevant, PRs should now modify the changelog before being merged.
=> Publish 0.8.0

CHANGELOG.md, src/platform/linux/x11/mod.rs
Remove the `+8` offset from x11 keyboard scancodes, thus uniformizing them with wayland (and linux's definition).
Fixes #293
=> x11: uniformize keyboard scancodes with linux

CHANGELOG.md, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/window.rs
This PR does a few things:
- cleanup the wayland implementation of event loop, by not creating a 2nd wayland event queue (it is no longer needed now that each event loop has its own wayland connection)
- buffer the events generated by the wayland dispatch rather than calling the user callback on the go. This has two advantages:
- it simplifies the events loop code
- it allows to call Window methods such as `set_inner_size` and `set_title` from within a callback without deadlocking
- add an interface to query readiness of the window for drawing. Indeed, it is illegal to draw on a window before it has been configured by the server with an appropriate event when using xdg_shell. Doing so causes the connection to be terminated by the server. This exposes an `Arc<AtomicBool>` that becomes …
=> Wayland: rework the event loop & expose readiness signal

CHANGELOG.md, src/platform/windows/window.rs
Right now, this example will not terminate on windows:
```
extern crate winit;
fn main() {
let events_loop = winit::EventsLoop::new();
let window = winit::WindowBuilder::new().build(&events_loop).unwrap();
window.set_inner_size(200, 200);
}
```
According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633545(v=vs.85).aspx), `user32::SetWindowPos` can block if it is called from a thread other than the one that created the window, without the flag `SWP_ASYNCWINDOWPOS`. Since windows are created in the event loop background thread, calling `Window::set_inner_size` anywhere else will block the calling thread.
For some reason that is not clear to me, the same problem doesn't happen on my machine using `Window::set_position`, which also calls `user32::SetWindowPos`, so I …
=> Fix thread blocking during resize on win32.

.travis.yml, CHANGELOG.md, src/platform/linux/x11/window.rs
One would hope 32bit X11 was dead by now but apparently not :). Fix the window hint setting code to not assume window IDs are 32bit as apparently they are not in 32bit arches.
=> Fix X11 on 32bit architectures

CHANGELOG.md, src/platform/linux/x11/events.rs
On practically all keyboard layouts on Linux, Shift+Tab generates ISO_Left_Tab. This keysym is currently ignored, so applications can't detect Shift-Tab.
=> Make ISO_Left_Tab generate VirtualKeyCode::Tab

src/platform/linux/wayland/window.rs
This should trigger the compositor's mechanism for sending a configure event, which should most of the time be processed before any winit user actually tries to draw.
This fixes the crash of glutin examples at init under weston.
=> wayland: commit the empty surface at init

.travis.yml
Using the matrix functionality it's possible to enumerate all the travis targets and have them be separate runs in the build. This makes the run look cleaner and makes it easier to know what specifically is failing at a glance.
=> Use travis matrix for the ios/linux variants

CHANGELOG.md, src/events.rs, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/context.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/window.rs, src/platform/macos/monitor.rs, src/platform/windows/monitor.rs, src/window.rs
As discussed in #105. This pull request contains only changes to the winit API, no implementation in any of the backends yet.
1. Add `MonitorId::get_hidpi_factor() -> f32` method. Currently returns 1 for all backends.
2. Add `WindowEvent::HiDPIFactorChanged(f32)`.
3. Remove `Window::get_inner_size_points` and  `Window::get_inner_size_pixels` .
=> Implement public API for high-DPI

CHANGELOG.md, src/lib.rs, src/os/unix.rs, tests/events_loop_proxy_send.rs, tests/send_objects.rs
**This is a breaking change.**
This formalizes the final suggestion of #320 regarding thread-safety of the types:
- `EventsLoop` gains a marker field assuring it is `!Send` and `!Sync`, this way, some backends can rely of this fact without users depending on one of them on an over platform accidentally being `Send` of `Sync`
- `Window` must be `Send`, this adds a test for it.
=> Formalize thread-safety garantees

CHANGELOG.md, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/context.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/window.rs, src/platform/macos/monitor.rs, src/platform/windows/monitor.rs, src/window.rs
At least on Windows monitor position can be negative. Primary monitor always has position (0, 0), if there is a monitor to the left or to the top of it then it will have negative position.
For the sake of experiment I configured my monitors as follows:
Winit reports the following:
Without these changes:
Monitor 1: size = (3840, 2160), pos = (0, 0)
Monitor 2: size = (1920, 1080), pos = (0, 4294966216)
With these changes:
Monitor 1: size = (3840, 2160), pos = (0, 0)
Monitor 2: size = (1920, 1080), pos = (0, -1080)
=> Make MonitorId::get_position() return (i32, i32) instead of (u32, u32)

CHANGELOG.md, src/os/windows.rs, src/platform/windows/monitor.rs
This PR changes monitor enumeration on Windows to use `EnumDisplayMonitors` instead of `EnumDisplayDevices`. The difference between them is that `EnumDisplayDevices` returns raw information while `EnumDisplayMonitors` returns mapped and modified information that applications should actually use.
More specifically:
1. When there are two monitors which duplicate each other, `EnumDisplayDevices` will list both monitors while `EnumDisplayMonitors` will only list just one.
2. `EnumDisplayMonitors` will allow us to get correct DPI value for monitor using `GetDpiForMonitor`. `EnumDisplayDevices` also gives us DPI in the `dmLogPixels` field but this is the raw DPI of the monitor, not the actual value that user has set in the settings. This PR does not yet implement any support for DPI, I intend …
=> Use EnumDisplayMonitors to enumerate monitors on Windows

src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/window.rs
This ensures the `WlDisplay` is the last thing to be dropped, whatever the order in which the `EventsLoop` or `Window`s are dropped (thanks to [RFC#1857](https://github.com/rust-lang/rfcs/blob/master/text/1857-stabilize-drop-order.md) we can rely on this drop order).
Not doing so could lead in a winit program segfaulting on exit when all its destructors are run, rather than exiting cleanly. This is because dropping the `WlDisplay` kills the wayland connection and frees its resources, so it must be the last wayland thing to be dropped.
=> wayland: Fix drop order for display

CHANGELOG.md, src/lib.rs, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/x11/mod.rs, src/platform/macos/events_loop.rs, src/platform/windows/events_loop.rs
For context, this is needed to use winit with the latest webrender, which needs to wake up the event loop from a `RenderNotifier` which must be both `Send` and `Clone`. Servo doesn't have this issue because it still uses an old version of glutin with `WindowProxy` which can be cloned.
=> Derive Clone for EventsLoopProxy

Cargo.toml, src/lib.rs, src/platform/macos/events_loop.rs, src/platform/macos/monitor.rs, src/platform/macos/window.rs
Basically I started with looking at #329 and tried upgrading macos dependencies (`cocoa`, `core-graphics`, `core-foundation`).
before:
```
├── cocoa v0.9.2
│   ├── bitflags v0.9.1
│   ├── block v0.1.6
│   ├── core-graphics v0.8.2
│   │   ├── bitflags v0.9.1 (*)
│   │   ├── core-foundation v0.3.0
│   │   │   ├── core-foundation-sys v0.3.1
│   │   │   │   └── libc v0.2.33
│   │   │   └── libc v0.2.33 (*)
│   │   └── libc v0.2.33 (*)
│   ├── libc v0.2.33 (*)
│   └── objc v0.2.2
│       └── malloc_buf v0.0.6
│           └── libc v0.2.33 (*)
├── core-foundation v0.4.4
│   ├── core-foundation-sys v0.4.4
│   │   └── libc v0.2.33 (*)
│   └── libc v0.2.33 (*)
├── core-graphics v0.8.2 (*)
├── lazy_static v0.2.9
├── libc v0.2.33 (*)
└── objc v0.2.2 (*)
```
after:
```
├── cocoa v0.11.0
│   ├── …
```
=> update macos deps

Cargo.toml, examples/cursor.rs, examples/fullscreen.rs, examples/grabbing.rs, examples/min_max_size.rs, examples/multiwindow.rs, examples/proxy.rs, examples/transparent.rs, examples/window.rs, src/os/unix.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/mod.rs, src/platform/linux/wayland/window.rs
This new version of wayland window considerably simplifies the window handling for winit, meaning much of the previous juggling is no longer needed, and the windows will appear even if nothing is drawn.
This also brings some shiny features, such as actual buttons for minimize/maximize/close being displayed, and the color of the border changing depending on whether the window is active or not!
Note that with this, the linux-specific `os::unix::WindowExt::is_ready()` is no longer needed. This PR simply stubs it out by always returning `true`, and marking it as deprecated. Though given next winit release already contains breaking changes, we can also consider removing it.
=> wayland: upgrade wayland-window

src/lib.rs
Generating the crate's docs on the latest nightly produces the following warning:
```
WARNING: documentation for this crate may be rendered differently using the new Pulldown renderer.
See https://github.com/rust-lang/rust/issues/44229 for details.
WARNING: rendering difference in `[iOS only] Enable multitouch, see [UIView#multipleTouchEnabled]`
```
Basically, the new docs parser requires a link's `[ ]` to be on the same line as the `( )`. This pull request fixes that. Also updated the link, since it linked to an unexistent page.
=> Fix docs rendering

src/platform/linux/x11/mod.rs, src/platform/macos/events_loop.rs, src/platform/windows/events_loop.rs
This is a first pass at updating the mouse's position after a CursorEntered/Focused event. I ran `cargo test` but haven't done any manual testing.
There's a lot of copy/paste in the macos code. I'm also not sure how best to send a second event in that situation.
fixes #348
=> Send mouse position after focused/cursorenter events

CHANGELOG.md, Cargo.toml, src/lib.rs, src/platform/linux/x11/dnd.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util.rs, src/platform/linux/x11/window.rs
This pull request implements the `DroppedFile`, `HoveredFile`, and `HoveredFileCancelled` events for the X11 backend. It makes no changes to the public API.
Some notes:
- Only accepts drops of type `text/uri-list`
- Can handle drops containing multiple files
- Tested to work with UTF-8 paths (that's what `percent-encoding` is needed for)
- Paths are canonicalized before being passed along
=> x11: Implement file drag and drop

src/platform/linux/x11/window.rs
Fixes #282
Some tiling window managers (i3, dwm, etc.) determine how a window should behave based on
its name. If the name is set after mapping, then window managers will check the name before
we set it, followed by them detecting it as a change when the name is actually set. That
results in the window briefly behaving in an unexpected way, followed by a rapid switch to
the expected behavior.
In accordance to section 4.1.2 of ICCCM, the name, decorations, size hints, and window
deletion redirection have all been moved up to be set before mapping.
=> x11: Set window title prior to mapping window

src/platform/linux/x11/dnd.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util.rs, src/platform/linux/x11/window.rs
Previously, the maximization hints were being sent as two separate client messages: one for horizontal, and one for vertical. That resulted in the window only being maximized horizontally (at least with my WM). The corrected client message sets both of these hints at once.
In the process of implementing that, the relevant components were refactored to use the util module, as we gradually move towards a hopeful future of a more readable X11 backend.
=> x11: Send window maximization hints correctly

CHANGELOG.md, src/os/unix.rs, src/platform/linux/x11/window.rs
Fixes #256
`get_xlib_window` and `get_xlib_screen_id` previously returned `Option<*mut c_void>` by casting integer IDs into pointers, which while producing no functionality issues, is semantically incorrect and rather surprising. Worse still, the docs for `get_xlib_window` stated that it was in fact a valid pointer.
This is a breaking change, and will require some trivial changes to glutin. 
I chose to have `get_xlib_window` return `Option<libc::c_ulong>` rather than `Option<ffi::Window>`, since I assume `ffi::Window` isn't supposed to be exposed.
=> unix::WindowExt no longer returns pointers for things that aren't actually pointers

CHANGELOG.md, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/x11/window.rs, src/platform/macos/window.rs, src/platform/windows/window.rs, src/window.rs
This has been stubbed on all platforms other than X11. The X11 implementation has also been revised to toggle correctly, as it was previously only able to remove decorations.
(The various whitespace changes weren't intentional... I guess my editor did that.)
=> Add set_decorations method to Window

CHANGELOG.md, src/events.rs, src/platform/emscripten/mod.rs, src/platform/linux/wayland/pointer.rs, src/platform/linux/x11/mod.rs, src/platform/macos/events_loop.rs, src/platform/windows/events_loop.rs
This pull request adds modifier suppport to the `MouseMoved`, `MouseWheel`, and `MouseInput` events. This is modeled after the modifier support added for `KeyboardInput` in https://github.com/tomaka/winit/pull/112.
This will allow mouse events to achieve parity with keyboard events and support use cases like: https://github.com/jwilm/alacritty/issues/146.
=> Added modifier support to mouse events

src/platform/emscripten/ffi.rs, src/platform/emscripten/mod.rs
The old code requested element CSS side, where element is `ptr:null()` which effectively returns the whole window size. It might make sense from the pure window logic, but is rather useless for anything WebGL related. Not exactly sure how to properly address this, but we can hopefully start the discussion here.
=> [emscripten] request canvas size instead of CSS size

src/platform/linux/x11/mod.rs, src/platform/linux/x11/util.rs
The `CursorMoved` events that are used to send position updates alongside `Focused` and `CursorEntered` events were using incorrect values for the window ID. This is a direct result of the X11 backend being hard to understand, as those values came from variables in the top-level scope of the function, which one would assume to be valid throughout the entirety of their scope. In reality, their validity is dependent on the event belonging to the `XEvent` union, so very surprising things can happen if those variables are read in the case of XInput2/XKB/etc. events. To help prevent future accidents, the aforementioned variables have been removed, and are now defined per-event instead.
However, the `CursorMoved` event sent alongside `Focused` events is still imperfect. The associated …
=> x11: Always use correct window ID for XInput2 events

CHANGELOG.md, src/os/macos.rs, src/platform/macos/window.rs
On macOS by default windows can only be moved by clicking and
dragging on the titlebar, if we spawn a window without one we
need to set the `movableByWindowBackground` property.
Partial fix for #368
=> [macOS] Move the window if there is no title bar

CHANGELOG.md, src/events.rs, src/platform/macos/events_loop.rs
I'm using alacritty and got the problem that my caret key (^) in OSX, German Keyboard is not recognized correctly (Event returns None). This maps the keycode and makes it useable.
Reference: https://github.com/jwilm/alacritty/issues/680
=> Add support for Caret (^) Key in OSX (de_DE)

src/platform/linux/x11/window.rs
Some window managers like i3wm will actually nest application windows
(like those opened by winit) within other windows to, for example, add
decorations. Initially when debugging this method on i3, the x and y
positions were always returned as "2".
The solution that other xlib abstractions use is to climb up the window
hierarchy until just below the root window, and that window must be used
to determine the appropriate position.
This patch doesn't take into account borders or the window's offset
within its parent, but it's much more usable than the original
implementation on certain WMs.
=> Fix x11 Window::get_position wrong values

src/platform/linux/x11/monitor.rs, src/platform/linux/x11/xdisplay.rs
Fixes #392
Previously, initializing the member `xrandr` of `XConnection` resulted
in a panic when symbols from XRandR version 1.5 were missing. There was
already code to handle older versions of XRandR but it was never
executed because of the panic.
The member `XConnection.xrandr` now contains only functions that can
safely be used with older versions. Additionally, this commit adds a new
member to `XConnection` of type `Option<ffi::XRandr>` that only contains
a value if version 1.5 functionality is present. These newer functions are all
related to the handling of monitors and are exclusively used in the
`get_available_monitors` function.
=> x11: Support XRandR versions older than 1.5

CHANGELOG.md, src/platform/android/mod.rs
This is not absolutely right (the window could be smaller than the screen), but it's as good as get_position and get_hidpi_factor.
=> Implement MonitorId::get_dimensions for Android

src/platform/linux/x11/window.rs
The fix for returning accurate window position lead to a regression
computing inner size in pixels. This commit resolves that by getting
inner size from the window ID winit caches and still resolving position
by climbing the window hierarchy.
Resolves #398
=> Fix x11 window size calculations

CHANGELOG.md, src/platform/windows/events_loop.rs
This PR updates the win32 backend to capture mouse input when a user clicks and hold a mouse button in a window, allowing movement and other mouse events to be sent to a window without the cursor necessarily hovering over said window.
This feature is quite useful in GUI applications, where users may click-drag something and end up with the mouse outside the window. An example can be seen in Firefox or Chrome, by dragging the scroll bar and moving the mouse outside the window - the bar can still be moved, even though the mouse is outside the window and it wouldn't be receiving events had it not explicitly captured the mouse.
=> Add mouse event capturing when click-dragging out of a win32 window

src/os/android.rs, src/platform/android/mod.rs
Makes it possible for glutin to register a callback when a suspend event happens on Android.
We need it to unfork Glutin on Servo. See https://github.com/tomaka/glutin/pull/868 for more details:
=> Add set_suspend_callback method for Android

CHANGELOG.md, src/platform/android/mod.rs
This is necessary, otherwise the event loop callback is never called because no WindowEvent is available.
=> Send Awakened event on Android when event loop is woken up

src/platform/macos/window.rs
Due to the recent changes in the Rust compiler, unconstrained type variables are now deduced to `!` instead of `()`. There are some occurrences where `msg_send!` is used without constraining its return
type (relying on the assumption that they would be deduced to be `()`). As a result, the macOS port of winit stopped working.
- [Summary issue - stabilization of `!`](https://github.com/rust-lang/rust/issues/48950)
- [Promote `!` to a type.](https://github.com/rust-lang/rfcs/pull/1216)
See the new type deduction behavior [in action](https://play.rust-lang.org/?gist=318b5429d39fc215654b6b38b2979406&version=nightly).
This PR fixes the issue (#426) by adding explicit return types to such uses of `msg_send!`.
=> [macOS] Fix crashes due to the stabilization of the `!` (never) type

src/os/macos.rs, src/platform/macos/window.rs
fixes #323 
This is #389, rebased from current master, with a couple of extra commits to add `titlebar_hidden` and `titlebar_buttons_hidden`. I didn't get any response from @robertgzr on this so I decided to just open a new one. #389 was approved, not sure why it didn't get merged, so I'm hoping to get this merged soon.
NB: `titlebar_hidden` depends on #408 to be resizable.
=> 323 windowbuilder ext macos

CHANGELOG.md, examples/min_max_size.rs, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/util.rs, src/platform/linux/x11/window.rs, src/platform/macos/window.rs, src/platform/windows/window.rs, src/window.rs
Adds the ability to change the minimum and maximum sizes of a window, even after it's been created, with `set_min_dimensions` and `set_max_dimensions` functions on the Window struct.
I've only tested this on Windows, and I'm *pretty sure* the OSX and Linux code compiles, but it's much harder for me to test them personally than it is to test the Windows code. I'll probably be able to test the Linux code in the next couple of days but I don't think I can test the OSX code personally.
=> Add ability to change the min/max size of windows at runtime

CHANGELOG.md, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util.rs
Fixes #366 
I was originally planning to fix this by rewriting keyboard handling to use XInput2+XKB+libxkbcommon, and I do indeed have a fully functional implementation of that. However, I never managed to figure out how to handle IME, and I could seldom find the motivation to try to conquer yet another dimension of X11 eroticism. That only got worse when I discovered older libxkbcommon versions, which are still in use, [don't support compose sequences](https://github.com/francesca64/xkbcommon-dl/issues/1). As a result, this fairly important issue has gone unresolved for much longer than I ever intended.
This PR fixes the issue using a bold new solution: a single `if` that checks if the keycode is non-zero. A `KeyPress` with a keycode of 0 is received at the end of compose sequences and …
=> x11: Don't panic when using dead keys

CHANGELOG.md, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util.rs
XIM isn't thread-safe at all. Any call made to it from another thread will result in the event loop freezing (this is why the old implementation of `Drop` for `Window` had that problem).
XIM is now confined to one thread, and the existing API is maintained using channels. In testing this with Alacritty, I initially thought the occasional slight lag on updating the spot location was due to this change, but it's present without it as well.
=> x11: Only access XIM from the event loop thread

CHANGELOG.md, src/platform/macos/window.rs
Just #359 rebased onto master with a changelog entry.
Hopefully this can get merged soon.
Closes #359.
Closes #399.
=> Fix macOS window sizes to follow convention with changelog entry

CHANGELOG.md, src/platform/linux/x11/util.rs, src/platform/linux/x11/window.rs
It was brought to my attention via #430 that there are presently issues with how window geometry is calculated, and I soon found myself in a rather deep rabbit hole.
After testing on Xfwm4, Mutter, Muffin, Budgie, Marco, Compiz, KWin, Enlightenment, FVWM, Awesome, i3, xmonad, dwm, Openbox, Fluxbox, Blackbox, and IceWM, I believe I've arrived at a complete and correct solution.
Normally, this is where I'd explain in depth what this PR does and why it exists, but I wrote some rather extensive comments throughout the source, so I'll just outline the consequences of these changes.
I've verified on all of the WMs tested that `get_position`, `get_inner_position`, `get_inner_size`, `get_outer_size`, and `set_position` all work correctly, both with and without decorations enabled. The only caveat …
=> x11: More robust geometry calculations

CHANGELOG.md, src/platform/macos/window.rs
The error I was investigating https://github.com/servo/servo/pull/20474#issuecomment-379802897 turned out to be already be fixed by https://github.com/tomaka/winit/pull/428, but there was a few more cases of the same problem.
=> Fix some more unconstrained types in msg_send results

CHANGELOG.md, src/platform/macos/window.rs
* moving window to another screen
* changing resolution of screen
implement #105 for macos
fixes #441 (using `windowDidChangeBackingProperties` instead of `viewDidChangeBackingProperties`)
=> [macOS] implement HiDPIFactorChanged event on relevant events:

CHANGELOG.md, src/platform/windows/events_loop.rs
Fixes #180 
This is based on [the snippet](https://github.com/tomaka/winit/issues/180#issuecomment-302977662) provided by @LPGhatguy, with one key difference: rather than returning 0, we pass the event along to the default handler. The reason for this is made clear in [the docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd145137(v=vs.85).aspx):
> If an application processes a `WM_PAINT` message but does not call `BeginPaint` or otherwise clear the update region, the application continues to receive `WM_PAINT` messages as long as the region is not empty. In all cases, an application must clear the update region before returning from the `WM_PAINT` message.
Using the original snippet, event processing slows down massively and my laptop fan gets quite loud. With this, …
=> Windows: Implement Refresh event

CHANGELOG.md, src/platform/windows/events_loop.rs, src/platform/windows/window.rs
This fixes #196, although it does not update the documentation as suggested in the comments.
=> [Windows] Adjust min_dimensions and max_dimensions using AdjustWindowRectEx.

src/platform/macos/events_loop.rs
Solves the issues caused by calling `EventsLoopProxy::wakeup()` too early from a worker thread.
A global singleton instance of `NSApplication` is created when `[NSApplication sharedApplication]` is called for the first time. When this happens, the calling thread is registered as the main thread. This means that the main thread in a Cocoa application is determined when the application calls it for the first time.
`EventsLoopProxy::wakeup` calls it internally. As a result, if you call `EventsLoopProxy::wakeup` very early, a wrong thread will be registered as the main thread, causing the application to misbehave. The framework detects such situations and generates the following log output:
2018-04-10 13:34:43.495 ${ApplicationName}[90843:3858828] !!! BUG: The current event queue and the main …
=> [macOS] Register the Cocoa main thread at an earlier point

CHANGELOG.md, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/window.rs, src/platform/macos/window.rs, src/platform/windows/window.rs, src/window.rs
This differs from the current `get_position`, in that the current method gets the window's top-left position, including window decorations. This adds a `get_inner_position` method, which gets the client area's top-left position, not including decorations, relative to the desktop.
=> Add methods to get the position of a window's client area, relative to the desktop

CHANGELOG.md, examples/fullscreen.rs, src/platform/macos/monitor.rs, src/platform/macos/window.rs
This PR implemented following functions in MacOS:
- `Window::get_current_monitor`
- `Window::set_fullscreen`
- `Window::set_maximized`
- `Window::set_decorations`
- `WindowBuilder::with_maximized`
And the maximized and fullscreen behaviors are following safari's conventions. (See https://github.com/tomaka/winit/issues/460).
This PR should f-ixed #300, #72, #66, #129, and Part of #252
=>  Implement set_maximized, get_current_monitor, set_fullscreen and set_decorations for MacOS

CHANGELOG.md, src/platform/macos/events_loop.rs, src/platform/macos/window.rs
Relevant discussion [here](https://github.com/tomaka/winit/pull/465#issuecomment-382124999)
=> Revert 466 window resize mouse up fix

src/platform/linux/x11/mod.rs, tests/sync_object.rs
Fixes #472
This also adds a test ensuring that `Window` is `Sync`.
=> x11: Windows are Sync again

Cargo.toml
Without this pin, an existing cargo.lock for an older winit will not
update the x11-dl dependency, and thus will select a version that is
missing required new XIM features.
=> Set minimum x11-dl version to include Z

CHANGELOG.md, Cargo.toml
0.13.0 requires existing users to run `cargo update` to build on Linux (#484). 0.13.1 doesn't.
=> Release winit 0.13.1

CHANGELOG.md, src/platform/macos/window.rs
Fixes #67
This also accounts for the position changing during resizes, which I'm not sure if we do on other platforms.
=> macOS: Implement Moved

CHANGELOG.md, src/os/windows.rs, src/platform/windows/event.rs, src/platform/windows/events_loop.rs, src/platform/windows/mod.rs, src/platform/windows/monitor.rs, src/platform/windows/raw_input.rs, src/platform/windows/util.rs, src/platform/windows/window.rs
Fixes #467
All variants other than `Text` have been implemented. While `Text` can be implemented using `ToUnicode`, that doesn't play nice with dead keys, IME, etc.
Most of the mouse `DeviceEvent`s were already implemented, but due to the flags that were used when registering for raw input events, they only worked when the window was in the foreground.
This is also a step forward for #338, as `DeviceId`s are no longer useless on Windows. On `DeviceEvent`s, the `DeviceId` contains that device's handle. While that handle could ostensibly be used by developers to query device information, my actual reason for choosing it is because it's simply a very easy way to handle this. As a fun bonus, this enabled me to create this method:
```rust
DevideIdExt::get_persistent_identifier() -> …
```
=> Windows: Implement DeviceEvents

CHANGELOG.md, src/platform/linux/x11/mod.rs
Do not reset the pending_wakeup boolean at the start of run_forever so
that each call to EventsLoopProxy::wakeup results in an Awakened event.
Fixes #462
=> x11: Always receive Awakened event in run_forever

CHANGELOG.md, src/events.rs, src/platform/linux/wayland/keyboard.rs, src/platform/linux/x11/events.rs, src/platform/windows/event.rs
This is only a tiny update which introduces the `Copy` and `Paste` keys
which are present on X11/Wayland/Windows. I'm not sure if this exists on
MacOS too, but I'm not able to test that and it doesn't have names but
just matches on the hex key values.
The "Copy" element is a reserved keyword in Rust but shouldn't cause any
conflicts in this scenario, this behavior falls in line with
https://docs.rs/winit/0.13.1/winit/enum.MouseCursor.html#variant.Copy,
but it would be possible to rename it. However `Copy` seems like the
most intuitive choice.
I'd be willing to add a few other keys too, however I wanted to keep this minimal
to what I actually want and need. I'm not quite sure why the current selection of
keys is the way it is, so I'm keeping this PR to the bare minimum of what I would
like …
=> Add Copy/Paste keys

CHANGELOG.md, Cargo.toml, src/lib.rs, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/keyboard.rs, src/platform/linux/wayland/mod.rs, src/platform/linux/wayland/pointer.rs, src/platform/linux/wayland/touch.rs, src/platform/linux/wayland/window.rs
This PR migrates the wayland backend to using [Smithay's Client Toolkit](https://crates.io/crates/smithay-client-toolkit), which deprecates both wayland-kbd and wayland-window. It at the same time upgrades wayland-client to version 0.20, which significantly reworked its API. See [this blog post](https://smithay.github.io/wayland-rs-v-0-20.html) for some backgound on these changes and their reasons.
This PR moves a lot of code around, making it I expect rather difficult to review, however it brings very little functional changes, and I did not attempt to refactor the backend further than simply porting it to the new wayland-client API.
It also slightly simplifies the backend, as some of the logic is now handled by Smithay's Client Toolkit.
I've tested it using glutin on weston, more tests …
=> wayland: migrate to smithay-client-toolkit

CHANGELOG.md, src/platform/windows/window.rs
Fixes #501 
This circumvents a panic when one calls set_fullscreen(None) on a window that has never been in fullscreen mode prior to calling that method.
=> Windows: Fix panic when calling set_fullscreen(None)

CHANGELOG.md, src/platform/linux/x11/util/icon.rs
Number of goofs spotted in 0.14.0 so far: 1
=> Correct privacy for Icon::to_cardinals

CHANGELOG.md, Cargo.toml, src/platform/linux/mod.rs, src/platform/linux/wayland/event_loop.rs
Slightly improve the diagnostics in case where winit failed to initialize the wayland backend to differentiate between the cases where winit could not find the wayland libs vs. could not find a listening compositor.
=> wayland: improve diagnostic of failed init

CHANGELOG.md, src/platform/macos/events_loop.rs, src/platform/macos/window.rs
- closes https://github.com/tomaka/winit/issues/496
This PR intend to fix #496 - reason system doesn't switch input method is winit doesn't forward NSKeyDown to system specifically, so only application aware of it.
Still, it is bit unsure about historical reason why keydown event was prevented from first time. Creating PR to discuss if there's better / viable approach than this.
=> fix(mac_platform): forward keyevent to system

CHANGELOG.md, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/event_loop.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/util/geometry.rs, src/platform/linux/x11/util/mod.rs, src/platform/linux/x11/util/randr.rs, src/platform/linux/x11/window.rs, src/platform/macos/monitor.rs, src/platform/windows/monitor.rs, src/window.rs
Fixes #64 
This also adds an `eprintln!` to the X11 error handler. Since many X11 errors occur asynchronously, this should make debugging a bit easier. I still plan on adding proper logging in future work, but for now, this serves as a convenient preview for the panic that will happen soon afterwards.
Another notable change is that the monitor list is cached now. `XRRGetScreenResources` is [supposedly very slow](https://people.gnome.org/~ssp/randr/TODO), and XRandR can notify us when we need to invalidate the cached list. Previously, Alacritty would query and reconstruct the monitor list 3 times, but now it only needs to once, so hooray for minor startup time improvements. (This will be more important when full HiDPI support for X11 lands, since detecting DPI changes involves checking …
=> X11: Fix get_current_monitor

.gitignore, CHANGELOG.md, src/platform/macos/window.rs
Fixes #517
These properties are changed *only* when using `with_decorations(false)`, and *not* when calling `set_decorations(false)`: 
https://github.com/tomaka/winit/blob/d86f53a02c0b17f76551c6b8917ecafe4f1f5164/src/platform/macos/window.rs#L781-L784
Changing those properties back to the default when calling `set_decorations(true)` solves the problem. @sodiumjoe do you know why those calls are used for `with_decorations(false)`? It seems to work fine without them, especially considering they're never used when disabling decorations after the fact.
=> macOS: Fix re-enabling decorations after the window is built without them

.gitignore, CHANGELOG.md, Cargo.toml, src/platform/macos/monitor.rs, src/platform/macos/window.rs
This partially addresses #473, in case I haven't been putting out enough macOS PRs.
=> macOS: Fix Window::get_current_monitor

.gitignore, CHANGELOG.md, src/lib.rs, src/os/unix.rs, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/macos/events_loop.rs, src/platform/macos/ffi.rs, src/platform/macos/mod.rs, src/platform/macos/util.rs, src/platform/macos/view.rs, src/platform/macos/window.rs, src/platform/windows/window.rs, src/window.rs
Issues this hopefully fixes:
- #263
- jwilm/alacritty#61
- jwilm/alacritty#209
- jwilm/alacritty#372
- jwilm/alacritty#748 ✔️
- jwilm/alacritty#764 ✔️
- jwilm/alacritty#935 ✔️
- jwilm/alacritty#1040 ✔️
- jwilm/alacritty#1041 ✔️
- ~~jwilm/alacritty#1064~~ ❌
(I'm not sure about all of these. Hopefully we can get feedback on most of them.)
Alacritty branch for easy testing: https://github.com/francesca64/alacritty/tree/macos-kb
@kwonoj are you interested in trying this out?
=> macOS: Implement NSTextInputClient

CHANGELOG.md, src/platform/windows/events_loop.rs, src/platform/windows/mod.rs, src/platform/windows/monitor.rs, src/platform/windows/util.rs, src/platform/windows/window.rs
Fixes #523
Prior to changing the cursor state, we now check the current grab state, since it can be invalidated by alt-tabbing and other things.
`CursorState::Hide` is also implemented now.
The cursor name is now wrapped in a `Cursor` struct to allow multithreaded access.
`Window::set_cursor_state` has been reworked to use `execute_in_thread`. Two unneeded `transmute` calls were also removed.
The `WM_SETCURSOR` handler is much more readable now.
`MonitorId::get_adapter_name` has been removed, since it's dead code and appears to be a relic from 4 years ago.
=> Windows: CursorState improvements

CHANGELOG.md, src/lib.rs, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util/hint.rs, src/platform/linux/x11/window.rs, src/window.rs
Fixes #257
After this, Alacritty also won't have to directly make calls to Xlib anymore. The hints needed there seemed reasonable to provide out of the box, i.e. setting a hint that contains the PID. There's also a behavior change included here, in that `WM_CLASS` is no longer based on the window title. It was a semantically incorrect and rather surprising thing to do in the first place; now it defaults to the executable name (which the spec specifies as a fallback) and you can explicitly set `WM_CLASS` using `WindowBuilderExt::with_class`.
=> X11: Improve hint support

src/platform/linux/x11/dnd.rs, src/platform/linux/x11/ime/input_method.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/util/atom.rs, src/platform/linux/x11/util/client_msg.rs, src/platform/linux/x11/util/format.rs, src/platform/linux/x11/util/geometry.rs, src/platform/linux/x11/util/hint.rs, src/platform/linux/x11/util/input.rs, src/platform/linux/x11/util/memory.rs, src/platform/linux/x11/util/mod.rs, src/platform/linux/x11/util/randr.rs, src/platform/linux/x11/util/window_property.rs, src/platform/linux/x11/util/wm.rs, src/platform/linux/x11/window.rs
More internal changes:
- Most `util` functions are now `XConnection` methods, which means that they're a bit cleaner to write and no longer require being called on an `Arc`.
- `util` functions where the unsafety is properly encapsulated are no longer marked `unsafe`. This is fortunately most of them, since that's the point of `util` in the first place.
- `util::get_atom` no longer returns a `Result`, since handling that just ends up being boilerplate. `XInternAtom` failing would be too exceptional to be worth handling anyway, so it's simpler just to panic with a nice message.
- `util::PointerState::drop` only calls `XFree` if the relevant pointer isn't null.
- `util::send_client_msg_multi` exists now, and it's a truly beautiful monstrosity of unsafe code. I wrote it when I was trying to …
=> X11: util design improvements

CHANGELOG.md, src/lib.rs, src/platform/linux/x11/mod.rs, src/platform/linux/x11/util/mod.rs, src/platform/linux/x11/window.rs
X11 HiDPI will be finished soon, I promise! I'm actually very nearly done with it, but some internal design issues in the X11 backend were actively complicating my work. So, this is yet another refactor PR.
Before this PR:
- `Window` owns a `Window2`, which contains all the actual methods and additionally owns an `XWindow`.
- `Window2` owns `SharedState`, which is shared with `EventsLoop` via `RefCell<HashMap<WindowId, Weak<Mutex<window::SharedState>>>>`.
- `EventsLoop` shares `Arc<Mutex<HashMap<WindowId, WindowData>>>` with `Window`, but not with `Window2`. `Window` has it so it can remove itself from it in `drop`, and `EventsLoop` uses it to store various state related to the window. Nested in `WindowData` is `WindowConfig`.
- There's no way to call methods on `Window2` from …
=> X11: Flatten window model

appveyor.yml
In addition to nightly, also test the current stable version and Rust
1.24.1.
This might help with #531.
=> appveyor.yml: Test additional Rust channels

CHANGELOG.md, examples/no_resize.rs, src/lib.rs, src/platform/windows/window.rs, src/window.rs
Only implemented `WindowBuilder::with_resizable` for MS Windows.
regarding #540
=> Windows: implement with_resizable (#540)

.travis.yml
Fixes #531
Does this look good to everyone? I don't really know how to test the config in advance, so I'm worried I'll break things.
=> Test against Rust 1.24.1 on Travis

CHANGELOG.md, src/platform/linux/x11/util/randr.rs, src/window.rs
There is an issue with xorg reporting 0 width or height which leads to a division by zero with floating point numbers. This will result in a DPI factor of +inf. As a workaround to this when either width or height are 0 the DPI is now set to a fixed value (1.0).
In #543 the option of setting this as an environment variable has been discussed and I'd be happy to add this to the PR if it is desired.
This fixes #543.
=> Fix DPI with 0 width/hight reported by xorg

CHANGELOG.md, src/platform/linux/x11/window.rs
Fixes tomaka/glutin#1019
This simply removes the transparency code from winit. Trying to get transparency on X11 without a graphics context never worked to begin with. The relevant code was added way back in tomaka/glutin#484; with it removed, everything works exactly the same as with it present, just without the flickering.
This was apparently also a problem in SDL (https://bugzilla.libsdl.org/show_bug.cgi?id=2101) though I don't bother to explicitly specify the defaults here.
This also fixes `with_override_redirect`, since it was right next to the transparency code, and looking into this made me realize I implemented that incorrectly.
=> X11: Fix flickering when resizing with transparency enabled

CHANGELOG.md, src/platform/macos/window.rs, src/window.rs
Fixes jwilm/alacritty#1345
As a bonus, I threw in an implementation for `with_resizable` for #540 (and `set_resizable`, though it isn't exposed yet).
=> macOS: Resizable without decorations

CHANGELOG.md, Cargo.toml, src/platform/linux/mod.rs, src/platform/linux/wayland/window.rs
I believe this should be pretty trivial to review. :)
I tested it on weston, based on the glutin examples.
=> wayland: implement set_resizable

CHANGELOG.md, Cargo.toml
The good thing about this release is that it fixes various bugs that people weren't fond of.
The bad thing thing about this release is that I'll no longer be able to procrastinate on writing documentation for #548...
Though, this won't merge until after @vberger fills in Wayland support for `with_resizable`/`set_resizable`, so that still gives me some time for doing nothing.
=> Release winit 0.15.1

README.md
When using PNG for the Travis badge, GitHub fails to render it well on HiDPI screens.
=> Change Travis badge to SVG

CHANGELOG.md, src/platform/macos/events_loop.rs, src/platform/macos/view.rs
Fixes jwilm/alacritty#1375
For reasons unknown, some keys trigger `insertText` when held, and others don't. While I'd love to know why that happens, I just did the easy thing here by preventing key repeats from *ever* being processed further.
=> macOS: Fix doubled key repeats

CHANGELOG.md, src/platform/linux/mod.rs
Shares the XConnection between all event loops instead of just all event 
loops on the same thread.
This is needed for adding shared context support to [tomaka/glutin](https://github.com/tomaka/glutin), as contexts
must be made with the same native display (and therefore the same
connection.)
=> Shares the XConnection between all event pools instead of just all event pools on the same thread.

CHANGELOG.md, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/window.rs, src/platform/linux/x11/window.rs, src/platform/macos/window.rs, src/platform/windows/window.rs, src/window.rs
This is now consistent with `set_cursor_state`, and enables `window.set_cursor_position(x, y)?` in functions that return `Result<_, Box<Error>>`.
=> Change set_cursor_position to return Result<(), String>

src/platform/linux/wayland/window.rs
In retrospect, I was actually the one who put in this dummy code (https://github.com/francesca64/winit/commit/2dbe28e30079b3532cbca9aedea4f08f0a18d1ab#diff-7d4b937dfd8134b6a46e1cfc22ca80faR27). This explains a lot, since 64 is clearly a cheeky reference to @francesca64.
Sorry @vberger!
=> Wayland: Fix window creation dimensions

CHANGELOG.md, src/platform/ios/mod.rs
This, plus a bunch of other unrelated changes, let me get a triangle on screen on iOS with vulkano. I suspect this will fix a lot issues dependencies like glium have on iOS.
Let me know if you need more information from me.
=> set the UIViewController's view to the one that was just created

src/dpi.rs, src/window.rs
This is an attempt to clarify the relation between `WindowEvent::HiDpiFactorChanged` and `Window::get_hidpi_factor`.
Fixes #594
=> Clarify DPI docs to highlight WindowEvent::HiDpiFactorChanged

CHANGELOG.md, src/platform/macos/events_loop.rs
To reproduce the issue:
- on Mac, `cargo run --example window`
- press the `Cmd` key
- See that we get two consecutive `state:Release` `KeyboardInput` events
We should get `Pressed` then `Release`.
=> Fix key state on MacOS

CHANGELOG.md, src/os/ios.rs, src/platform/ios/ffi.rs, src/platform/ios/mod.rs
There are a lot of changes to iOS in this pull request.
- The `UIApplication` `setjmp` hacks now happen in `Window::new`. This allows `PlatformSpecificWindowBuilderAttributes` to customize the specific `UIView` class.
- The biggest breaking change here is that `winit` no longer sets up a `GLKView`. Putting responsibility on other libraries like `glutin` and `vulkano-win` to specify the exact `UIView` subclass.
- `EventsLoop` now explicitly checks that it's created on the main thread. AFAICT this was required before, but it was just UB to create it anywhere else.
- Only one `Window` can ever be created.
- `EventsLoop` cannot be polled until a `Window` has been created - in order for the `CFRunLoopRunInMode` calls to work.
I have been testing it with `glutin`. …
=> iOS Abstract Out the UIView type from winit

CHANGELOG.md, src/platform/macos/window.rs
There's stil future work with `DelegateState` that needs to be done, which I noticed when working on DPI support... `windowDidChangeBackingProperties` can be called before `windowDidChangeScreen` finishes, for instance.
All I've addressed here is unsoundness when hiding the cursor, since it's both easy to encounter and easy for me to fix.
=> macOS: Fix cursor hiding thread unsafety

CHANGELOG.md, src/platform/windows/dpi.rs, src/platform/windows/window.rs
use cached window dpi to fix panic on win 7
=> fix assertion failed: validate_hidpi_factor(dpi_factor) (#607)

CHANGELOG.md, Cargo.toml, README.md, src/platform/macos/ffi.rs, src/platform/macos/util.rs, src/platform/macos/view.rs
=> Update cocoa and core-graphics

CHANGELOG.md, src/platform/macos/events_loop.rs, src/platform/macos/view.rs
=> 625 macos modifiers

CHANGELOG.md, Cargo.toml, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/keyboard.rs
This PR adds the feature of key repetition to the wayland backend. This PR is requested prematurely so that it may be reviewed before the release of smithay-client-toolkit 0.3.0, currently it points to the git version as a dependency.
I have tested the changes and added a small update to the changelog (might need more explanation and better wording?), however I cannot find any documentation of key repetition (I assume this is just standard behavior).
Please look to https://github.com/Smithay/client-toolkit/pull/16 for further information about the new `map_keyboard_with_repeat()` function
=> Add key repetition for the wayland backend

CHANGELOG.md, src/platform/linux/wayland/event_loop.rs
This PR commits the surface of the wayland window frame on resize  as suggested by @vberger.
This is required by https://github.com/Smithay/client-toolkit/commit/acdfde234e0afa3513b276493696811986aa2322
=> Wayland: commit frame surface on resize

CHANGELOG.md, src/platform/windows/events_loop.rs
Reintroduces some visual bugs when resizing, but fixes the freezes in #574, #617, and #633.
=> Remove resize block on Windows

README.md
This makes it look more like other projects have it. I always thought the way winit had it looked odd.
However, I see a certain logic in which you have arranged them so just close this if you want to keep it like you have it.
=> Put badges next to each other instead of below eachother

CHANGELOG.md, src/platform/linux/x11/util/hint.rs
This just puts in all hints from [here](https://specifications.freedesktop.org/wm-spec/wm-spec-1.5.html#idm140200472629520). The old version used wm-spec v1.3.
This will help #403 at least a little for modern WMs.
=> Update wm spec hints

CHANGELOG.md, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/x11/window.rs
This change provides applications that use winit with the ability to set the `_GTK_THEME_VARIANT` property for X11 windows. [Alacritty](https://github.com/jwilm/alacritty) for example could make use of this feature to let users enable dark window decorations specifically for Alacritty without affecting other GNOME apps. The stock GNOME terminal already provides this functionality.
If my understanding of winit's current Wayland support is accurate, implementing this feature for native Wayland isn't yet possible. I'd very happily be corrected on that and amend my changes accordingly.
Since I'm making these changes specifically to enable the above-mentioned feature in Alacritty, I've only tested them on top of the 0.15.1 release that Alacritty depends on — getting it to build with winit …
=> Add X11-specific with_gtk_theme_variant option

CHANGELOG.md, src/platform/linux/x11/window.rs
> The contents of the property are not required to be null-terminated;
> any terminating null should not be included in text_prop.nitems.
https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/XmbTextPropertyToTextList.html
=> Don't include NUL byte in _NET_WM_NAME

CHANGELOG.md, src/platform/windows/mod.rs, src/platform/windows/window.rs
Fixes #656
This PR simply sets the cursor directly in `set_cursor`, in addition to updating the cursor the old way (`WM_SETCURSOR`). As a result, cursor changes are visible immediately, rather than only appearing after a mouse movement/etc.
=> Windows: Fix set_cursor delay

CHANGELOG.md, Cargo.toml, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/keyboard.rs, src/platform/linux/wayland/pointer.rs, src/platform/linux/wayland/touch.rs, src/platform/linux/wayland/window.rs
Upgrades to smithay-client-toolkit to version 4.0, biggest changes are
* Now uses wayland 0.21 (doesn't use pure rust implementation because of c lib dependency that can hopefully be removed in the future)
* Better 'ConceptFrame' for decorations which looks more visual appealing then 'BasicFrame'
* Window titles will now be displayed in the header of the window
* Fix wayland key repetition when keyboard loses focus
Fixes https://github.com/tomaka/winit/issues/657
=> Upgrade to smithay-client-toolkit 0.4

CHANGELOG.md, src/platform/windows/window.rs
Should fix issue #670
Tested on my Windows 10 machine, using the fullscreen example.
Restores the correct window.set_maxmized functionality, that appears to have been broken in PR #601
=> Windows: Fix window.set_maximized()

CHANGELOG.md, src/platform/macos/view.rs, src/platform/macos/window.rs
- ~[ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~
- ~[ ] Created an example program if it would help users understand this functionality~
=> macOS: fix modifiers during key repeat

CHANGELOG.md, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/keyboard.rs, src/platform/linux/wayland/pointer.rs
Tracks modifiers state from keyboards and then uses that to provide the modifiers state for pointer events
Fixes https://github.com/tomaka/winit/issues/653
=> Provide current modifiers state with pointer events on wayland

CHANGELOG.md, src/dpi.rs, src/platform/linux/x11/mod.rs
This change does 2 things to the x11 backend:
- change the order of processing of the contents of events so that checking the current monitor and retrieving the dpi is done *before* computing the logical size of the window
- whenever the dpi changes, always queue a `Resized` event with the new, correct logical size
- given on x11 the physical size is constant by default, a dpi change changes the logical size, so any previous logical size becomes wrong, hence the need for this event
This should hopefully fix #663, but I don't really have the environment to test it right now.
cc @chrisduerr
=> x11: compute resize logical size with new dpi

CHANGELOG.md, src/platform/linux/mod.rs
This PR refers to issue #678 .
The relevant panic message should primarily appear on linux systems without either Wayland or X11. This is true for example on the Windows Subsystem for Linux, on which I tested the changes. Please let me know if I should test on additional platforms.
The binary used to trigger the panic is the example `window`. After the change, the panic message looks as follows:
```bash
$ cargo run --example window
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', src/platform/linux/mod.rs:437:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
=> Unit testing: Panic messages should not contain control characters

CHANGELOG.md, src/platform/linux/x11/mod.rs
Fixes #687
`XdndFinished` isn't supposed to be sent when rejecting a `XdndPosition`; it should only be
sent in response to `XdndDrop`.
https://freedesktop.org/wiki/Specifications/XDND/
=> X11: Fix DND freezing the WM

CHANGELOG.md, Cargo.toml, src/platform/macos/window.rs
This is an alternate fix for tomaka/glutin#1069.
On Mojave, views automatically become layer-backed shortly after being added to a window. Changing the layer-backedness of a view breaks the association between the view and its associated OpenGL context. To work around this, on Mojave we explicitly make the view layer-backed up front so that AppKit doesn't do it itself and break the association with its context.
This was breaking the `window` example in `glutin`.
=> Make views explicitly layer-backed on macOS Mojave.

CHANGELOG.md, src/os/macos.rs, src/platform/macos/window.rs
This is blocking `0.18` and a PR didn't seem to be coming, so I threw this together. With cross-compilation Rust compiles it fine, but since I don't have convenient access to a MacOS machine it's untested.
cc #680
=> Remove From<NSApplicationActivationPolicy> impl from ActivationPolicy

CHANGELOG.md, Cargo.toml, README.md
- ~[ ] Tested on all platforms changed~
- ~[ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~
- ~[ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~
- ~[ ] Created an example program if it would help users understand this functionality~
=> version 0.18.0

CONTRIBUTING.md
This PR introduces a `CONTRIBUTING.md` file based on the discussion in #669. This is for now very WIP and intended to serve as a basis for discussion, like an RFC.
Regarding the most fundamental still-open questions:
- who exactly is a "maintainer" of winit, who has commit right and is willing to dedicate time to winit?
- For now I've left #252 as the "official list of features", but we might want to make it more formal maybe?
Rendered version of the file: https://github.com/vberger/winit/blob/contributing/CONTRIBUTING.md
=> [META] Add a CONTRIBUTING.md

CHANGELOG.md, src/platform/linux/x11/mod.rs
Fixes #691
Dropping a window before running the `EventsLoop` results in events still being queued when `XDestroyWindow` is called, so events like `XI_Enter` (the culprit in this case) will still be processed. Simply checking that the window still exists before calling `query_pointer` was enough to solve the problem.
=> X11: Fix panic when dropping window before running event loop

CHANGELOG.md, src/os/unix.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/window.rs
This was discussed some time ago, and allows applications to specify an application id that the wayland compositor will use to find the matching `.desktop` file.
=> Introduce WindowBuilderExt::with_app_id for wayland

CHANGELOG.md, src/platform/windows/events_loop.rs
Fixes #708, fixes #689, and fixes #550. This also stops window resizing from eating `Awakened` events.
=> Replace thread messages with messages to dummy window

CHANGELOG.md, Cargo.toml, src/lib.rs, src/platform/windows/events_loop.rs
=> On Windows, catch window callback panics and forward them to the calling thread

CHANGELOG.md, src/platform/linux/mod.rs, src/platform/linux/x11/monitor.rs, src/platform/linux/x11/util/randr.rs
Fixes #693
This just skips any output that returns `NULL` when passed to `XRRGetOutputInfo`, which seems to sometimes be the case with virtual monitors.
This also changes the X11 error `eprintln!` to use `error!` from `log` instead.
=> X11: Check if `XRRGetOutputInfo` returned `NULL`

CHANGELOG.md, src/events.rs
Motivation:
This allows VirtualKeyCode variants to be stored in a BTreeSet.
Unlike HashSets, BTreeSets implement Ord and Hash, allowing them to be
keys in a {Hash|BTree}Map. This is nice, e.g. when implementing
keyboard shortcuts functionality, which maps a set of pressed keys to
some action.
=> Add ordering traits to VirtualKeyCode

CHANGELOG.md, src/platform/linux/wayland/event_loop.rs, src/platform/linux/wayland/window.rs
I'm trying to use Alacritty on Wayland+Gnome in a mixed DPI environment. I run a laptop with a HiDPI screen attached to a regular DPI external screen. Being a laptop, I regularly disconnect the external screen, and Alacritty goes haywire when I switch between screens, as stated in https://github.com/jwilm/alacritty/issues/1801.
I traced this to the fact that Gnome does not send `wl_surface enter/leave` events to all surfaces when a `wl_output` is removed, only a `wl_output removed` is sent. The changes now listens for `wl_output removed` events, and handles them accordingly.
It's not the prettiest change, but there was no clean way to do this without a major refactoring.
=> Handle removed wl_outputs

CHANGELOG.md, examples/fullscreen.rs, src/platform/windows/events_loop.rs, src/platform/windows/util.rs, src/platform/windows/window.rs
Fixes #715. This seems to have been caused by the window style getting improperly set when leaving fullscreen mode.
The Windows fullscreen window restore code is a bit convoluted in general so I'd like to take some time to refactor and simplify that a bit, but this can be fixed without doing that.
=> On Windows, fix window shrinking when leaving fullscreen in some situations

CHANGELOG.md, src/platform/linux/x11/window.rs
=> X11: WindowBuilder min/max size accounts for DPI

CHANGELOG.md, src/platform/linux/x11/mod.rs
This commit restricts an Xfwm4-specific DPI-preserving hack to Xfwm4 only, fixing #706.
The hack saves and restores the DPI-adjusted size until the actual size matches. On tiling WMs like i3 this fails, since the size is constrained by the layout. This in turn causes a never-ending XResizeWindow vs. XConfigureWindow fight between the WM and the client, making the WM, winit client, and Xorg consume all CPU cycles available.
**Update:** I also tested this on fluxbox, and it worked (preserved the DPI.)
**Update 2:** I got paranoid that I might have removed the only point where the DPI is preserved, so I tested this on one more WM, icewm, and it also worked on it.
=> Fix high CPU usage on tiling WMs when moving windows across monitors (#706)

CHANGELOG.md, src/lib.rs, src/platform/android/mod.rs, src/platform/emscripten/mod.rs, src/platform/ios/mod.rs, src/platform/linux/mod.rs, src/platform/linux/wayland/mod.rs, src/platform/linux/x11/mod.rs, src/platform/macos/mod.rs, src/platform/macos/window.rs, src/platform/windows/mod.rs
=> Add support for generating dummy DeviceIDs and WindowIDs

CHANGELOG.md, src/platform/macos/window.rs
https://developer.apple.com/documentation/appkit/nsdraggingdestination/1416066-preparefordragoperation?language=objc
This method has been incorrect since v0.13, but through the joys of UB it worked anyway.
=> macOS: Correct `prepareForDragOperation:` signature

.travis.yml, CHANGELOG.md, README.md, appveyor.yml
As per discussion in #743. Closes #743.
=> Remove MSRV guarantee

CHANGELOG.md, Cargo.toml, src/lib.rs, src/platform/windows/events_loop.rs, src/platform/windows/mod.rs, src/platform/windows/monitor.rs, src/platform/windows/util.rs, src/platform/windows/window.rs, src/platform/windows/window_state.rs
This PR refactors the Windows state-setting code to make it significantly easier to read and modify going forward. It also fixes #723 and a few other miscellaneous untracked issues I found when doing the refactor.
=> Refactor win32 window state code

Cargo.toml, src/event_loop.rs, src/lib.rs, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/pointer.rs, src/platform_impl/linux/wayland/touch.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/windows/event_loop.rs, tests/send_objects.rs
This is the port of the wayland backend to events loop 2.0.
Notably:
- the X11-specific code in platform_impl / platform has been commented-out
- it also updates the wayland dependencies:
- wayland-client to 0.22
- SCTK to 0.5
=> Wayland's eventloop 2.0

CHANGELOG.md, src/platform/linux/wayland/window.rs
Wayland windows currently did not set their title when built with the `with_title()` function.
=> On wayland, fix `with_title()` not setting the windows title

CHANGELOG.md, src/platform/windows/events_loop.rs
- [-] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [-] Created an example program if it would help users understand this functionality
CHANGELOG, documentation and example should not be needed for this one? Or let me know if you think otherwise and I will fix it :)
=> Handle horizontal wheel input (Windows)

CHANGELOG.md, src/platform/macos/events_loop.rs, src/platform/macos/view.rs
This commit fixes the issue described in #752, and uses the advised
method to fix it.
I'm relatively new to contributing and Rust (this is my first real contribution), and I'm sure my lack of experience is shining through here.  Regardless, I hope that this PR fixes/assists in fixing the issue adequately!
=> Fix incorrect keycodes when using a non-US keyboard layout.

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, appveyor.yml, examples/window_icon.rs, src/icon.rs, src/lib.rs
Removes the `icon_loading` feature from the `eventloop-2.0` branch. This does *not* remove window icons as a feature - it just removes the `image` crate integration. This is because we've gotten [so](https://github.com/tomaka/winit/issues/707) [many](https://github.com/tomaka/winit/pull/758) [issues](https://github.com/tomaka/winit/issues/661)/[prs](https://github.com/tomaka/winit/pull/683) about the version of the `image` crate that maintaining our support for it seems to be far more trouble than it's worth. Not only that, but keeping the dependency will just lock us into a never-ending series of breaking changes every time `image` wants to bump its major version number - preventing us from ever stabilizing until `image` reaches `1.0`, and potentially forcing a major bump *after* that if …
=> Remove icon loading feature

CHANGELOG.md, src/platform/linux/x11/mod.rs, src/platform/linux/x11/xdisplay.rs
XNextEvent will block for input while holding the global Xlib mutex.
This will cause a deadlock in even the most trivial multi-threaded
application because OpenGL functions will need to hold the Xlib mutex
too.
Add EventsLoop::poll_one_event and EventsLoop::wait_for_input to provide
thread-safe functions to poll and wait events from the X11 event queue
using unix select(2) and XCheckIfEvent.
This is a somewhat ugly workaround to an ugly problem.
Fixes #779
=> x11: thread safe replacement for XNextEvent

CHANGELOG.md, src/platform/windows/event.rs
At some point we should more comprehensively change how Windows handles keyboard input so that pressing AltGr doesn't result in both `RAlt` and `LControl` being sent to the window, but in the meantime this fixes a downstream issue.
On Windows, addresses the issue behind #756 . I'm not closing that issue for a couple of reasons - this behavior still exists on MacOS, and that thread brings up some API changes that I think are worth considering.
=> Ignore the AltGr key when populating ModifersState

CHANGELOG.md, src/platform/linux/x11/monitor.rs
=> Use `XRRGetScreenResourcesCurrent` when avail.

CHANGELOG.md, Cargo.toml, README.md
Not much to see here. This is breaking since it updates the `image` dependency.
I'd maybe like to see #763 and #772 get merged for this release, but that requires another reviewer look at them and confirm that it's what we want to do (cc @francesca64, since #772 is X11)
=> Update winit to 0.19.0

CHANGELOG.md, src/platform/windows/events_loop.rs
The code that was sending it shouldn't even have been there to begin with. This PR removes said code.
=> On Windows, fix CursorMoved(0, 0) getting sent on focus

CHANGELOG.md, src/platform/linux/x11/mod.rs
```
error[E0432]: unresolved import `libc::__errno_location`
--> src/platform/linux/x11/mod.rs:22:85
|
22 | use libc::{select, fd_set, FD_SET, FD_ZERO, FD_ISSET, EINTR, EINVAL, ENOMEM, EBADF, __errno_location};
|                                                                                     ^^^^^^^^^^^^^^^^ no `__errno_location` in the root
```
__errno_location is called __error on FreeBSD and __errno on Open- and NetBSD.
Note that I only tested on FreeBSD.  The OpenBSD and NetBSD bits are a pure guess on my part based on libc documentation and their errno.h [2,3,4,5].
[1] FreeBSD: https://rust-lang.github.io/libc/x86_64-unknown-freebsd/libc/fn.__error.html
[2] NetBSD: https://rust-lang.github.io/libc/x86_64-unknown-netbsd/libc/fn.__errno.html
[3] NetBSD: …
=> Fix build on FreeBSD

CHANGELOG.md, src/platform/linux/x11/util/randr.rs, src/window.rs
This is @semtexzv's fix for DPI behaviour on x11 at #606 rebased onto master. I just tested both master and this rebased branch locally and this branch still fixes my DPI problem on x11.
- ~Created an example program if it would help users understand this functionality~
edit: cc @francesca64 I just noticed you were ready to merge this a while back, just thought I'd ping you!
=> [Rebased] [x11-backend] Retrieve DPI from Xft.dpi XResource

CHANGELOG.md, src/os/unix.rs, src/platform/linux/wayland/event_loop.rs
=> Add ability to get wayland display from events loop.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, FEATURES.md, SCOPE.md
[Rendered](https://github.com/Osspial/winit/blob/scope/FEATURES.md)
Adds `FEATURES.md` in place of `SCOPE.md`, as discussed in #674. Subsumes #252. I've replaced the tier 1/2/3 structure with a new Core, Platform, and Usability tier structure, as I think that aligns more with what we're trying to accomplish.
Discussion points highlighted in the document:
* Do we want to support WASM without Emscripten?
* I've introduced the concept of upgrading features from Platform to Core, as some features (window resize increments, child windows) may end up becoming core. Do we want to have this be an official process as I've described?
* Do we want to support child windows?
* Do we want to support gamepad and joystick events?
* Do we want to support device movement (gyroscope and joystick) events?
* …
=> Winit Features and Scope

src/platform_impl/windows/event_loop.rs
After clicking the window title bar or border (for a drag or resize), the event loop pauses until the mouse is moved. This change relays the `WM_NCLBUTTONDOWN` message to the dummy window where it queues a redraw and consumes the message. This effectively jumpstarts the modal loop and it continues to fire draw requests.
=> Prevent the event loop from pausing when entering modal loop (eventloop-2.0)

CONTRIBUTING.md, HALL_OF_CHAMPIONS.md
This includes de-listing @francesca64 from the table, as I suggested. I realize that this is a controversial decision, and it's not a decision I make lightly, but I believe I have justification for doing so:
I contacted @francesca64 last month asking her about her inactivity as a maintainer on this project. She replied on March 26th as follows. For the sake of her privacy, I've removed removed certain sections of her response, as it contains some personal details that I'm not comfortable sharing with the world at large without her explicit permission.
> Hello! Thanks for reaching out!❤
>
> In short, I've moved on. [removed] ...in November, I was hired by a company that recently started using Rust. I'm very happily building infrastructure there!
>
> I'm simply not interested in spending …
=> Makes changes to CONTRIBUTING.md's table as discussed in #830

Cargo.toml, examples/fullscreen.rs, examples/multithreaded.rs, src/lib.rs, src/platform/macos.rs, src/platform/unix.rs, src/platform_impl/linux/x11/ffi.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/window_property.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/observer.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/util/cursor.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/windows/event_loop.rs
I kind of fucked up and had to manually back port changes. Git is hard. It will all get squashed in the end, so doesn't matter.
I think this is correct, or maybe not. All I know is it compiles :)
=> [WIP] Macos Evlp2

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, FEATURES.md, HALL_OF_CHAMPIONS.md, README.md, examples/fullscreen.rs, src/platform/macos.rs, src/platform_impl/android/mod.rs, src/platform_impl/emscripten/mod.rs, src/platform_impl/ios/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Like the previous one (#833) I cherry-picked the commits.
=> Backport of master changes to eventloop-2.0

src/platform_impl/linux/dlopen.rs
```
warning: attribute must be of the form `#[link(name = "...", /*opt*/ kind = "dylib|static|...",
/*opt*/ cfg = "...")]`
--> src/platform/linux/dlopen.rs:9:1
|
9 | #[link="dl"]
| ^^^^^^^^^^^^
|
= note: #[warn(ill_formed_attribute_input)] on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #57571 <https://github.com/rust-lang/rust/issues/57571>
```
=> Fix warnings linux eventloops2

src/platform/linux/dlopen.rs, src/platform/linux/wayland/mod.rs
```
warning: attribute must be of the form `#[link(name = "...", /*opt*/ kind = "dylib|static|...",
/*opt*/ cfg = "...")]`
--> src/platform/linux/dlopen.rs:9:1
|
9 | #[link="dl"]
| ^^^^^^^^^^^^
|
= note: #[warn(ill_formed_attribute_input)] on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #57571 <https://github.com/rust-lang/rust/issues/57571>
warning: method is never used: `dummy`
--> src/platform/linux/wayland/mod.rs:20:5
|
20 |     pub unsafe fn dummy() -> Self {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: #[warn(dead_code)] on by default
warning: method is never used: `dummy`
--> src/platform/linux/wayland/mod.rs:29:5
|
29 |     pub unsafe fn dummy() …
```
=> Fix warnings on linux

Cargo.toml
The previous attempt to update parking_lot missed the windows platform.
The parking_lot dependency is now no longer specified twice to help prevent that mistake from happening again.
=> Update parking_lot to 0.8 for windows too (eventloop-2.0)

examples/fullscreen.rs
Fix compile error for macos in fullscreen example.
=> Fix macos compile error in fullscreen example (eventloop-2.0)

src/platform_impl/windows/event_loop.rs
Fixes #867.
@chrisduerr Can you confirm that this fixes the issue?
=> Fix Windows backend invoking unreachable! with Exit and run_return

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/windows/event_loop.rs
This PR fixes several issues in regards to `Window::request_redraw`.
1. The `RedrawRequested` callback was never fired on Windows when `request_redraw` was called from the `EventsCleared` callback and the control flow was set to `Poll`.
2. The `RedrawRequested` callback was never fired on Windows when `request_redraw` was called from the `EventsCleared` callback and the control flow was set to `WaitUntil(resume_time)` with `resume_time` in the past. (I believe this behavior was also in error when called from the `NewEvents` callback).
3. `WaitUntil(resume_time)` caused a panic in Linux/X11 when `resume_time` was in the past.
Having `WaitUntil(resume_time)` handle timestamps in the past correctly allows for very short durations to be used. This effectively results in the same behavior as …
=> Fix control flow issues with Window::request_redraw (eventloop-2.0)

src/platform_impl/windows/event_loop.rs
It looks like #890 introduced this warning to the code, which was missed during review:
```rust
warning[E0503]: cannot use `runner.runner_state` because it was mutably borrowed
--> src\platform_impl\windows\event_loop.rs:854:21
|
847 |                 let mut request_redraw = || {
|                                          -- borrow of `runner` occurs here
848 |                     runner.call_event_handler(Event::WindowEvent {
|                     ------ borrow occurs due to use of `runner` in closure
...
854 |                     RunnerState::Idle(..) |
|                     ^^^^^^^^^^^^^^^^^^^^^ use of borrowed `runner`
855 |                     RunnerState::DeferredNewEvents(..) => request_redraw(),
|                                                           -------------- borrow …
```
=> Fix compiler warning of undefined behavior on Windows

src/window.rs
The cursor visibility docs were still outdated from the rename and
talking about setting the invisibility, rather than visibility.
The platform-specific docs are unchanged since those should be fine and
the rest has been adapted using similar docs.
=> Update cursor visibility docs

CONTRIBUTING.md
This is a temporary change while `eventloop-2.0` is separate from `master`.
=> Direct new contributions to eventloop-2.0

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
This makes the macOS API style consistent with that of iOS. It also makes it easier to read long identifiers when they're added in the future.
----
=> Make `ns` identifiers use snake_case on macOS

examples/transparent.rs, src/window.rs
Should be fairly uncontroversial. These functions missed the first consistency pass.
=> Fix WindowBuilder function names that missed first pass

CHANGELOG.md, Cargo.toml, FEATURES.md, examples/video_modes.rs, src/lib.rs, src/monitor.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/windows/monitor.rs
Resolves #877.
Adds a new method `get_video_modes` to the `MonitorId` struct in the public API, and implements it on the Windows platform. I'm going to look into implementing this on macOS as well..
=> Support listing available video modes for a monitor

src/monitor.rs, src/platform_impl/android/mod.rs, src/platform_impl/emscripten/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs, src/window.rs
So I realize that three separate PRs for this is more than is ideal, but there are a bunch of small gaps that slip through. I've looked over all of our publicly exposed functions though and I'm 95% sure this covers all of them.
=> Change Monitor dimensions functions to size functions

CHANGELOG.md, Cargo.toml, src/platform_impl/linux/wayland/window.rs
**Note:** This work is on the eventloop-2.0 branch
This decorelates the window management from the actual user content,
meaning:
- the created window no longer needs the user to draw something to
start existing
- it reduces our need to do roundtrips during initialization to
avoid protocol errors
depends on #833
=> wayland: use an invisible surface as shell surface

src/platform/desktop.rs
Documents the downsides of using `run_return`, as I mentioned doing in https://github.com/jwilm/alacritty/pull/2438.
=> Document the caveats of run_return

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs
Fixes #891, my previous implementation of the event loop for x11/wayland was erroneous.
=> x11/wayland: Don't reset control flow between loop ticks

CHANGELOG.md, src/window.rs
Previously, creating a fullscreen window on Windows would result in the window spanning more than a single monitor since the DPI factor was not taken into account. A workaround was to manually specify the size for the window, but this is no longer necessary.
=> Fix initial dimensions of a fullscreen window on Windows

.gitattributes
We've had quite a few unnecessary merge conflicts due to git not knowing how to merge changes `CHANGELOG.md`. This should change the merge style on that file to just pull in all changes from everywhere, hopefully stopping that.
=> Set CHANGELOG.md merge style to union

examples/monitor_list.rs
Uses the [`dbg!()` macro](https://doc.rust-lang.org/std/macro.dbg.html) which was added in Rust 1.32.
=> Use `dbg!()` macro in monitor list example

README.md, examples/window.rs
I just realized that the example in `README.md` was still using the old API! Wouldn't have wanted to let that slip through...
This also makes the event closure in `window.rs` a `move` closure. That change isn't *technically* necessary, but most practical modifications to `window.rs` are going to require it, so I figure we might as well add it in to reduce friction for new users using it as a base.
=> Update example in README.md and add move prefix to window.rs example closure

CONTRIBUTING.md
The contributors table is a good idea, but it has a tendency to drift out of date since it needs a full PR to update it. My theory here is that moving the table to the Wiki (thus making the table editable by everyone and lowering the stakes for changes) will allow for easier self-reporting and make the table both more accurate and more comprehensive, though whether that is substantiated by reality is yet to be seen.
@mtak- I've re-listed you as an iOS tester on the table, since you mentioned that you weren't able to actively maintain the platform. If you'd like to be listed differently (or not listed at all) I can make that change before creating the wiki page.
@jdm You mentioned that you were able to test for MacOS in https://github.com/rust-windowing/winit/pull/922#issuecomment-502850287 …
=> Move contributors table to wiki

examples/multithreaded.rs, examples/resizable.rs, examples/window.rs, src/dpi.rs, src/event.rs, src/event_loop.rs, src/platform/desktop.rs, src/platform_impl/windows/dpi.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
Makes changes to the public API as discussed in #837, and implements them on Windows.
I was originally going to try and implement these changes on the other platforms, but given the number of DPI problems we've had in the past I figure it's unwise to attempt to hack on systems I don't understand and am unable to test.
=> WIP - Make EL2 DPI changes and implement on Windows

examples/timer.rs
It looks like a call to `set_inner_size` snuck into the `timer` example at some point, which isn't necessary for the example. This removes that.
=> Remove window resize call in timer example

CHANGELOG.md, Cargo.toml, README.md
As per https://github.com/rust-windowing/winit/issues/830#issuecomment-501180361. I want to get #911 merged and #891 resolved before this, but... yeah. We've still got a long way for Winit to go, but we've made it this far, and I can only see progress speeding up from here. I cannot express enough thanks to the people that have helped get it here, from those writing the code, to the people testing stuff out, the people contributing their thoughts in the issues, and everyone in-between.
It's kinda surreal to be able to do this.
🎉
Closes #825, closes #276, closes #794, closes #728, closes #413, closes #219, closes #459.
=> Release 0.20.0 Alpha 1

src/platform_impl/linux/x11/util/randr.rs
I won't tick any checkboxes as this is a bug, not a feature, so there is no documentation involved. 
Also it only impacts X11 and the fix is trivial.
=> [#963] Change XRandR display size check to also take height into account

CHANGELOG.md
This change was included in 0.19.1 ([diff](https://github.com/rust-windowing/winit/compare/e0340d52b0...cd5caf6a22#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)), not in 0.19.0 ([diff](https://github.com/rust-windowing/winit/compare/ddf133dd...e0340d52b0#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)).
Btw some git tags would be nice (see [api guide](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#release-notes-document-all-significant-changes-c-relnotes)):
```
git tag v0.19.0 e0340d52
git tag v0.18.1 ddf133dd
```
=> CHANGELOG.md: Move entries for #805 to 0.19.1

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, CHANGELOG.md, Cargo.toml, FEATURES.md, README.md
This should gather the remaining pieces of the winit-legacy branch that are not yet in master.
I did not dig too deep into the mega commits, so can't guarantee that there aren't any funny surprises lurking there, but over all, this has been easier than expected and only a few things came up.
Apart from the commits that had already been ported over, and the commits included here, these are not included because they have been forward-ported in some other way:
- PR #861 (legacy) => PR #963 (master).
PR #861 was originally merged as 594cd18. Missing commit message included in this PR in a separate commit.
- PR #879 (legacy) => #880 (master).
Equivalent: Both remove warnings on Linux.
- PR #880 (legacy) => #882 + #884 (master).
- PR #897 + #903 + [the last commit updating …
=> Forward porting

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/pointer.rs, src/platform_impl/linux/wayland/touch.rs
Partially resolves #962. Added support for zwp-relative-pointer and added DeviceEventsSink in addition to existing event queue.
=> Wayland: Add relative pointer movement

src/platform_impl/linux/x11/mod.rs
Internally, `XFlush` calls `_XSend` to write data. It then calls
`XEventsQueued(display, QueuedAfterReading)`, which reads data from the
X server connection. This prevents the event loop source callback from
being run, as there is no longer data waiting on the socket.
Ideally, we would want to call `_XSend` directly to ensure that no
output is buffered by Xlib. However, this function is not exported as
part of Xlib's public API.
Testing with the `XFlush` call removed does not appear to adversely
affect the performance of an application. If any bugs should eventually
arise from this change, perhaps another function may be used in place of
`XFlush`, such as `XPending`, which writes buffered output but does not
so aggressively read from the X server connection.
Closes #865
=> Remove `XFlush` call in event loop

CHANGELOG.md, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Fixes: https://github.com/rust-windowing/winit/issues/936
Updated the multiwindow example adding an invisible window
=> Fix: Invisible windows steal focus from visible windows Win32

src/event.rs, src/monitor.rs, src/window.rs
Looking around in the documentation I saw several links to mod DPI were broken. Tested and confirmed these new links work. 👍🏻
Other tasks not relevant for this tiny docfix
=> Fix broken links to mod DPI on various documentation pages

CHANGELOG.md, examples/cursor_grab.rs, src/platform_impl/macos/app.rs
Addresses #955.
This should do the trick, but I don't have a solid test case handy, since my application is still on 0.19.1 (via glium/glutin), and this code has all been refactored since that version.
=> Implement DeviceEvent::Button on Mac

CHANGELOG.md, Cargo.toml, src/platform_impl/linux/wayland/window.rs
This reverts commit 65587ef43a7d001ba3e1fa6c7ecd12bd47fffa84.
It introduced sublte bugs in its interaction with OpenGL and glutin,
so we should better revert it for now.
=> Revert "wayland: use an invisible surface as shell surface (#835)"

CHANGELOG.md, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/raw_input.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
This changes `FileDropHandler::iterate_filenames` to use the exact length returned by `DragQueryFileW` instead of relying on MAX_PATH.
I've additionally replaced all calls to `mem::uninitialized` with `mem::zeroed` (on windows only).
=> Improve handling of file paths in the windows DnD handler

CHANGELOG.md, src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/window.rs
Implements #947 for the X11 platform.
=> X11: Disable maximize on non-resizable windows

CHANGELOG.md, examples/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
If the user calls `request_redraw` multiple times during the `EventsCleared` handler, multiple redraw events would get dispatched. This fixes that.
Example displaying that behavior here:
```rust
use winit::{
event::{Event, WindowEvent},
event_loop::{ControlFlow, EventLoop},
window::WindowBuilder,
};
fn main() {
let event_loop = EventLoop::new();
let window = WindowBuilder::new()
.with_title("A fantastic window!")
.build(&event_loop)
.unwrap();
event_loop.run(move |event, _, control_flow| {
println!("{:?}", event);
match event {
Event::WindowEvent {
event: WindowEvent::CloseRequested,
window_id,
} if window_id == window.id() => *control_flow = ControlFlow::Exit,
Event::EventsCleared => {
window.request_redraw();
window.request_redraw();
}
_ => *control_flow = ControlFlow::Wait,
}
});
}
``` …
=> Fix issues with redraw_requested when called during EventsCleared

CHANGELOG.md, src/window.rs
We do this by removing the global dimension default. This may be a somewhat controversial change, but it's caused a good amount of pain in the window creation system (at least on the Windows backend) and I don't think it's worth keeping.
Fixes #1009
=> On Windows, fix `with_maximized` not properly setting window size to entire monitor

src/platform_impl/ios/event_loop.rs, src/platform_impl/windows/dpi.rs
Fixes warnings I've encountered testing new CI config in #1017.
=> Fix warnings

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/window.rs
=> MacOS: request_user_attention(bool -> enum)

examples/request_redraw.rs
The example previously didn't show how to handle redraw requests, only how to generate them.
I'm not sure why the formatting change. The only functional change here is:
```rust
Event::WindowEvent {
event: WindowEvent::RedrawRequested,
..
} => {
println!("{:?}", event);
}
```
=> Handle RedrawRequested event in request_redraw example

src/error.rs, src/event_loop.rs, src/icon.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/linux/mod.rs
=> Always use `f` as the argument name for `&mut std::fmt::Formatter`

src/platform_impl/windows/dpi.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/util.rs
Fixes #975 
Haven't tested on Windows 7, but it should work, since the POINTER events are only fired on Windows 8 or higher. It should be tested anyway because GetPointerFrameInfoHistory and SkipPointerFrameMessages doesn't exist in User32.dll on pre-Windows 8.
=> Handle WM_POINTER* events in favor of WM_TOUCH

src/platform_impl/linux/x11/mod.rs
On X11, `Event::NewEvents(StartCause::Init)` was not delivered as first event.
̃~~I added a test case to run on an event loop without any windows attached and check that first event is `NewEvents(Init)`, then `ControlFlow::Exit` and check that last event is `LoopDestroyed`.~~
I have ran this test on Linux/x11 platform only.
**Help wanted**: please run the new test on macos and windows.
=> Add NewEvents(Init) callback to x11

src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/client_msg.rs, src/platform_impl/linux/x11/util/geometry.rs, src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/util/input.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/util/window_property.rs, src/platform_impl/linux/x11/window.rs
=> Replace `std::mem::uninitialized` with `MaybeUninit`

src/platform_impl/linux/x11/mod.rs
=> X11: Fix `request_redraw` deadlock while handling `RedrawRequested`

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
Fixes #1002
I think this change should be reflected in CHANGELOG.md. Should i add it under "Unreleased"?
=> Touch events emit screen coordinates instead of client coordinates on Windows

CHANGELOG.md, src/platform_impl/macos/app_state.rs
=> macOS: Drop the closure on exit. (Fixes #1058)

examples/window_run_return.rs
- N/A
- N/A
- N/A
Fixes #1064. Tested `cargo build --examples` for macOS and iOS, iOS build now works with this change. I wrote a comment explaining the platform selection because most of the other examples don't have any platform-specific code.
=> Fix run_return example build error on non-desktop platforms

src/platform_impl/windows/event_loop.rs
For greater precision in Touch events introduced in issue #975.
=> Use himetric values in WM_POINTER events

.travis.yml, CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/window.rs
Sorry i haven't checked #821 for a while, here I reapplied the changes to the new master.
=> add macos with_disallow_hidpi

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/window.rs
Fixes #1047
Tested only on Windows 10, but should work on previous version.
=> Process WM_SYSCOMMAND to forbid screen savers in fullscreen mode

Cargo.toml
This is the same as https://github.com/rust-windowing/winit/pull/1066, but targeting the `winit-legacy` branch.
=> Update the percent-encoding crate to 2.0 in winit v0.19.2

CHANGELOG.md, examples/request_redraw.rs, src/event.rs, src/lib.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
Implements the changes described in #1041 for the X11 platform and for
platform-independent public-facing code.
=> Implement changes to `RedrawRequested` event

CHANGELOG.md, Cargo.toml, FEATURES.md, src/lib.rs, src/platform/ios.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs
Also fixes a bug with getting the monitor name on iOS.
r? @aleksijuvani
=> iOS: add support for controlling the home indicator, and Exclusive video mode

CHANGELOG.md, src/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/windows/event_loop.rs
This pull request removes the `T: Clone` restriction from the `Clone` impl of `EventLoopProxy<T>`.
----------------------------------
=> Do not require `T: Clone` for `EventLoopProxy<T>: Clone`

CHANGELOG.md, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/window.rs
=> Disable overscan compensation for external displays on iOS

CHANGELOG.md, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs
https://github.com/rust-windowing/glutin/issues/1184
=> Add new `EventLoopWindowTargetExtUnix` trait.

src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs
The changes here stop `winit` from automatically appending the window canvas to the document root in the web platform. I discussed this with @ryanisaacg on Discord and we seemed to agree.
I think this approach has multiple benefits:
* It reduces the scope of `winit` to simply providing a canvas with the proper event listeners attached.
* We get multiple canvas support for free, given that all the event listeners are currently local to the canvas (however, we still need to think if we should provide fullscreen support and how in #1072).
* The user decides how to embed the canvas freely in their own web document. This allows us to leave some functionality out of `winit`'s scope, like changing the document/tab title or updating the favicon. The user is expected to implement this on top of …
=> Stop appending canvas to document in web platform

CHANGELOG.md, src/platform_impl/windows/dpi.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
=> On Windows, make AdjustRect calls DPI-aware when possible

CHANGELOG.md, FEATURES.md, src/platform/ios.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/window.rs
I don't think the semantics of `set_decorations` really match with the intent of wanting to hide the status bar. On desktop platforms for example, fullscreen windows are expected to automatically get their decorations disabled. On iOS however, all windows are fullscreen but the status bar is still enabled by default. It's also a common use case to have a regular windowed application (with decorations!) on desktop platforms, but to also hide the status bar on iOS. It looks confusing to have the `set_decorations` call be only invoked for iOS. This pull request makes `set_decorations` a no-op on iOS and adds a new extension function `set_prefers_status_bar_hidden` to `WindowExtIOS` and `with_prefers_status_bar_hidden` to `WindowBuilderExtIOS`.
=> Replace `set_decorations` with `set_prefers_status_bar_hidden` on iOS

CHANGELOG.md, src/platform_impl/ios/event_loop.rs, src/platform_impl/macos/event_loop.rs
This pull request fixes `EventLoopProxy<T>`'s auto trait implementations.
- `EventLoopProxy<T>: Send` *only if* `T: Send`, because otherwise it would allow sending unsendable objects.
- `EventLoopProxy<T>: !Sync` because of `std::sync::mpsc::Sender` used under the hood. This restriction is congruent with other platforms' `EventLoopProxy`.
----------------------
=> macOS/iOS: Fix auto trait impls of `EventLoopProxy`

CHANGELOG.md, FEATURES.md, src/event.rs, src/platform_impl/android/mod.rs, src/platform_impl/emscripten/mod.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/view.rs, src/platform_impl/linux/wayland/touch.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/windows/event_loop.rs
=> Add touch pressure information for touch events on iOS

CHANGELOG.md, src/platform_impl/macos/view.rs
[drawRect](https://developer.apple.com/documentation/appkit/nsview/1483686-drawrect) takes an NSRect not a pointer.
=> macos: fix an incorrect type signature on NSView drawRect

src/platform/web.rs
Allows enabling `web-sys` or `stdweb` features and build for other targets than wasm32.
=> Disable web module on other targets than wasm32

CHANGELOG.md, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs
The implementation is mostly based on discussion here #1005. I'm not quite familiar with macOs internals, and probably doing something wrong, but alacritty was starting and kind of working with this implementation. window_run_return example is also working fine.
cc @chrisduerr 
Fixes: #1005
=> macos: Implement run_return

CHANGELOG.md, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs
Fixes #1087
See changelog for more info.
Mostly this PR should make implementing the new `RedrawRequested` API much simpler, and make contributing to the iOS backend more approachable.
There are definitely times where the OS requests a redraw in the middle of an event loop. This is not the common case, but it _does_ happen.
Here's an example demonstrating the OS requesting a redraw when a new `UIView` is created:
```
NewEvents(Init)
WindowEvent { window_id: WindowId(WindowId { window: 0x0 }), event: HiDpiFactorChanged(2.0) }
WindowEvent { window_id: WindowId(WindowId { window: 0x0 }), event: Resized(LogicalSize { width: 375.0, height: 667.0 }) }
WindowEvent { window_id: WindowId(WindowId { window: 0x105806aa0 }), event: Focused(true) }
Resumed
WindowEvent { window_id: WindowId(WindowId { …
```
=> [ios] Groundwork for new Redraw API, refactoring AppState, and bugfixes

examples/window.rs, src/platform_impl/windows/event_loop.rs
This makes the tests I outlined in https://github.com/rust-windowing/winit/pull/997#discussion_r301852354 work.
=> On Windows, fix new DPI API not setting window size properly

examples/request_redraw.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window.rs
Previously, RedrawRequested would be dispatched in the next iteration of
the event loop. This fixes that.
=> Fix request_redraw in MainEventsCleared not dispatching immediately

src/event.rs, src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/util/modifiers.rs
=> Implement WindowEvent ModifiersChanged for X11 and Wayland

src/event.rs
We wouldn't want users stumbling on it until all platforms implement it.
=> Hide `ModifiersChanged` from the docs.

CHANGELOG.md, FEATURES.md, src/event.rs, src/platform_impl/windows/dpi.rs, src/platform_impl/windows/event_loop.rs
=> Add touch pressure information for touch events on Windows

Cargo.toml, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/wayland/pointer.rs, src/platform_impl/linux/wayland/touch.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/window.rs
=> Implement DPI Usability Upgrades for X11 and Wayland

Cargo.toml, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/web_sys/mod.rs
=> Send a LoopDestroyed event when the browser is closed

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window_state.rs
Should fix #1164 and https://github.com/jwilm/alacritty/issues/2796.
=> Fix surrogate pair handling on Windows

CHANGELOG.md, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs
=> Fix null window on initial `HiDpiFactorChanged` event on iOS

CHANGELOG.md, src/platform_impl/windows/util.rs, src/platform_impl/windows/window_state.rs
=>  Fix hovering the mouse over the active window creating an endless stream of CursorMoved events

CHANGELOG.md, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/observer.rs, src/platform_impl/macos/window_delegate.rs
=> Fix events not being emitted during modal loops on macOS

CHANGELOG.md, src/platform_impl/linux/x11/window.rs
Previously, `XSetInputFocus` was called unconditionally on new windows (so long as they were visible upon creation). This was a bugfix for fullscreen windows not receiving input and locking up the user's display (rust-windowing/glutin#509). This PR moves the `XSetInputFocus` call into `Window::set_fullscreen`, preventing non-fullscreen windows from stealing focus, which may not be desired, e.g. for tooltip or notification type windows.
Fixes #1160
=> Prevent stealing focus on new windows

src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
request_redraw on web would just dispatch unbounded amounts of requestAnimationFrame, which would lead to slowdowns over time. It also wasn't dispatched in the right point of the event loop.
=> Fix web redraw requested

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop.rs
Changed SeatData to obtain a reference to the relative pointer manager proxy in SeatManager. This solves the problem that when the GlobalEvent for the "zwp_relative_pointer_manager_v1" interface comes after the "wl_seat" interfaces the SeatData still has a way to obtain the relative_pointer_manager_proxy that was created when receiving "zwp_relative_pointer_manager_v1". This is a fix for #1178
=> Wayland: Switched to using a reference to relative_pointer_manager_proxy when creating SeatData

src/platform_impl/ios/view.rs
1.38.0 changed the default formatting rules subtly for some reason.
=> Update to 1.38.0 formatting

Cargo.toml, src/platform_impl/android/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/window.rs
=> Update raw-window-handle to 0.2

CHANGELOG.md, examples/monitor_list.rs, src/event_loop.rs, src/monitor.rs, src/window.rs
Fixes #1111 
This just changes the return types to be consistent between `event_loop` and `window`. This doesn't go as far as to introduce something like `MonitorHandle::available_monitors(&EventLoop)`, but that could be amended if desired. I just didn't want to introduce a breaking change so quickly
=> Use consistent return types for available_monitors()

CHANGELOG.md, src/platform_impl/linux/x11/util/randr.rs
=> Fix use-after-free in XConnection::get_output_info

src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/window.rs, src/window.rs
=> Implement `WindowBuilder::with_outer_position` for X11

.travis.yml
=> Add web targets to travis

appveyor.yml
Expands Appveyor testing to test all combinations of `x86_64`/`i686` and `msvc`/`gnu`. Hopefully this should help narrow down why `i686-pc-windows-gnu` is failing.
=> Test all Windows targets and allow nightly Appveyor failures

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs
CursorManagers\` `grab_pointer` can only be called from a thread on which `pointer_constraints_proxy` event queue is located, so calling it directly from a Window doesn't work well, in case you've sent your window to another thread, so we need to pass cursor grab updates to the event loop and call this function from there.
The code is basically a copy of @andersrein approach for handling a cursor grab thing.
Fixes regression introdced in 5ced36e319d55178dd943de033e4aacdbd0d0327
Some explanation why things were changed in #1204.
However @andersrein approach is not a good one for `set_cursor_icon` and `set_cursor_visible`, since you can face cursor icon update delays when pressing and holding Shift for e.g., the cursor icon will be changed with a bit of a delay according to my testing. I …
=> Wayland: Fix panic when calling set_cursor_grab from a different thread than evlp's one.

CHANGELOG.md, src/window.rs
Should fix #1012. Needs to be tested on the following platforms, but I don't see there being many problems:
=> Always dispatch a RedrawRequested event after creating a new window

Cargo.toml, src/platform_impl/macos/window.rs
Currently, due to a quirk in Rust's type inference interacting with the structure of the `msg_send!` macro, a `()` return type will be inferred when the compiler cannot otherwise determine the return type. This behavior is expected to change, and in the future could resolve to a `!` return type, which results in undefined behavior.
Linting has previously been added for this in rust-lang/rust#39216, but it did not catch these cases due to SSheldon/rust-objc#62. An upcoming version of objc will be fixed to stop hiding these errors, at which point they will become compile errors.
This change fixes these errors and allows winit to compile with the fixed version of objc. It also bumps cocoa to ensure users of winit are on a version that has addressed those issues.
- I ran `cargo test` on …
=> Fix so the compiler can infer msg_send! return types

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs
Implement the RedrawRequested for linux wayland. Partial fix for #1082.
=> Implemented revamped `RedrawRequested` for linux wayland

src/platform_impl/macos/app_state.rs
Related to #1082.
I have tested this with https://github.com/hecrj/iced/pull/22 and it seems to work well.
However, I am not very familiar with macOS windowing APIs, thus I am not sure if any further changes are necessary.
The PR most likely won't compile because it needs a fix that was merged to `master` recently: https://github.com/rust-windowing/winit/commit/af3ef52252dfad178d897b036876c2575c20f1f3. I will be happy to rebase the changes once `redraw-requested-2.0` catches up!
=> Implement revamped `RedrawRequested` on macOS

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop.rs
=> on Wayland, drop resize events equal to the current window size

CHANGELOG.md, Cargo.toml, README.md, src/platform/android/mod.rs
- build check was performed and passed (`cargo build --target=aarch64-linux-android`). on a side note, should build checks like these be added to travis? Testing on mobile is hard but making sure something builds isn't very tricky.
=> fix broken / missing `raw-window-handle` implementation on android

src/platform_impl/ios/view.rs
=> Run cargo fmt on Rust stable 1.39.0

CHANGELOG.md, src/event.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
* Moves `ModifiersChanged` variant from `WindowEvent` to `DeviceEvent`
Fixes #1259
=> X11: Fix modifiers being reported after release

CHANGELOG.md, examples/timer.rs, examples/window_run_return.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
=> X11: Fix events not being reported when using `run_return`

src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/observer.rs
Without you get 
```
warning: the type `platform_impl::platform::observer::CFRunLoopSourceContext` does not permit zero-initialization
--> src/platform_impl/macos/event_loop.rs:134:55
|
134 |             let mut context: CFRunLoopSourceContext = mem::zeroed();
|                                                       ^^^^^^^^^^^^^
|                                                       |
|                                                       this code causes undefined behavior when executed
|                                                       help: use `MaybeUninit<T>` instead
|
= note: `#[warn(invalid_value)]` on by default
note: Function pointers must be non-null (in this struct field)
--> src/platform_impl/macos/observer.rs:96:5
|
96  |     pub retain: extern "C" fn(*const c_void) -> …
```
=> Fix invalid_value lint triggering on mem::zeroed of CFRunLoopSourceContext

src/dpi.rs, src/event.rs
`cargo doc` on nightly requires crate-local doc links to have the `crate::` prefix.
=> Fix `cargo doc` on nightly builds

CHANGELOG.md, examples/window_debug.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs
=> X11: Fix window creation hangs when another application is fullscreen

src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/util/input.rs, src/platform_impl/linux/x11/util/modifiers.rs
* Syncs modifier state with state data in X key/button/motion events.
* Fixes modifier state in XWayland, as xinput2 raw input events will
not be received when a window does not have focus.
* Removes `impl From<_> for ModifiersState` on X11/Wayland API types,
replacing them with `pub(crate)` methods.
Addresses an issue brought up in #1259
=> X11: Fix incorrect modifiers when events are missed

Cargo.toml
Ecosystem seems to be moving to smallvec 1.0, getting some dependency updates in to avoid duplication.
This needs to be done for glutin as well, but winit needs to land first. Would be nice if we could cut a new version after this.
=> Bump parking_lot to 0.10

CHANGELOG.md, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
This should stop some functionality on unfocused windows to automatically focus them.
This affects for example switching from fullscreen to windowed or changing the outer position of windows.
Fixes #1284.
=> Stop refocusing window when switching from fullscreen to windowed

src/lib.rs
The 'extern crate' declaration shouldn't be there even if the stdweb feature is on, unless the crate is being compiled for web.
=> Only use 'extern crate stdweb' on web targets

CHANGELOG.md, src/platform_impl/macos/view.rs
=> Stop emitting corporate characters in macOS

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
This pull requests processes WM_SYSCHAR events along with WM_CHAR events rather than ignoring them. We can combine these because they are encoded identically. See relevant docs for [WM_CHAR](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-char) and [WM_SYSCHAR](https://docs.microsoft.com/en-us/windows/win32/menurc/wm-syschar).
Fixes #1280
=> Fix ReceivedCharacter not working with Alt held on Windows

Cargo.toml, examples/web.rs, src/platform_impl/web/event_loop/runner.rs
Related to #1082.
I figured I would give this a shot and it was easier than I expected. Once this and #1299 are merged, I think #1082 will be ready to go!
I have also added a `web` example to test things out. It seems to work fine.
=> Implement revamped `RedrawRequested` on Web

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs
I'm unable to test Linux platforms, so whenever I'm doing a rebase and changes to this function create a merge conflict it's always difficult to be sure I'm resolving it correctly. This should hopefully eliminate merge conflicts going forward.
=> Make Wayland's WindowStore::for_each less terrifying to rebase

src/platform_impl/windows/event.rs
=> Fix array_into_iter warning on Windows

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/window.rs
=> X11: Fix incorrect DPI factor when waking from suspend

CHANGELOG.md, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/web/event_loop/proxy.rs, src/platform_impl/windows/event_loop.rs
(via CI, shouldn't change behavoir of user code except involved types when using `EventLoopProxy`, because the return value of `EventLoopProxy::send_event` changed)
- Created or updated an example program if it would help users understand this functionality
(appropriate example to modify would be `examples/custom_events.rs`, but I'm unsure which modification would be appropriate.)
- Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
(no appropriate section found, where this should be added)
Fixes #1292.
=> Have EventLoopClosed contain the original event

src/platform_impl/macos/view.rs
This implements the macOS portion of #1124.
=> Add ModifiersChanged event for macOS

CHANGELOG.md, src/platform_impl/linux/wayland/pointer.rs
=> On Wayland, fix cursor icon updates on window borders when using CSD

CHANGELOG.md, src/platform_impl/macos/app_state.rs
This PR fixes #1242 while keeping #1117 fixed.
According to https://stackoverflow.com/questions/48041279/stopping-the-nsapplication-main-event-loop a UI event must be happening to stop event loop actually.
So  I chose to modify the main window's title to activate `stop`.
=> Fix run_return in MacOS

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop.rs
GNOME places maximized window CSD behind the status bar, and in the same time it moves any window crossing the "bounding box"(screen edges + status bar's bottom edge on top) into it on the next resize. So the main problem is GNOME placing window in a wrong place initially.
That gif shows the behavior I'm talking about. You don't need maximize to repro it.
The question why mutter places our window in a wrong place initially is still flying in the air...
cc @Will-W
Fixes #1312
=> On Wayland, under mutter(GNOME Wayland), fix CSD being behind the status bar, when starting window in maximized mode

CHANGELOG.md, src/platform_impl/macos/util/async.rs
This PR fixes #1288 
It was crashed in `set_style_mask_sync`.
As far as I investigated, `dispatch_sync_f` must not be called in the main thread, so I added `if` clause to detect the main thread and call callback directly then.
=> FIX Crash on macOS when starting maximized without decorations

src/platform_impl/ios/app_state.rs, src/platform_impl/ios/view.rs
Hi Friends,
Saw the need to help with iOS work for the RedrawRequest 2.0 API in #1082 from @Osspial's request and thought I'd do it.
Honestly, it seemed like too little work but it's quite similar to #1235.
I've tested this with for https://github.com/hecrj/iced/pull/57 in the [ios-examples repo](https://github.com/iced-rs/ios-examples).
=> Implement revamped `RedrawRequested` on iOS.

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
=> X11: Fix CursorEntered event for non-winit window

src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs
Closes #1310.
I pretty much did exactly as https://github.com/rust-windowing/winit/issues/1310#issuecomment-561571449 said. I'm not big on the name NativeDisplayMode nor that it's nearly the exact same code from the macOS logic but I figure it's an okay first pass.
=> Reimplement NativeDisplayMode on iOS for #1310

CHANGELOG.md, Cargo.toml, examples/request_redraw.rs, examples/web.rs, examples/window.rs, examples/window_run_return.rs, src/event.rs, src/event_loop.rs, src/lib.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/view.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window.rs
Closes #1082.
I'm mainly opening this as a PR for clerical reasons and to make reviewing the diff easier; it should be merged manually, so the individual commits don't get squished together. Thank you to *everyone* that helped with writing code, giving feedback, reviewing, and shepherding this process along.
🎉
=> Implement redraw requested 2.0

CHANGELOG.md, FEATURES.md, src/event.rs, src/platform/windows.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
I had a go at adding simple support for Windows 10's "Dark Mode". The moment the title bar will set to light / dark automatically according to system theme. I did not add an option for users of `winit` to disable this behaviour, as I felt it's likely desirable for most use cases. I can change that if you prefer otherwise!
Please advise on any documentation you'd like me to update.
The "window" example when Dark Mode is enabled:
Closes #1193
=> Add support for Windows Dark Mode

CHANGELOG.md, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
This PR fixes #1269 
On macOS, we must not change fullscreen state during fullscreen transition animation.
This PR saves target fullscreen state if `set_fullscreen` is called during fullscreen transition and call `set_fullscreen` again after fullscreen transition has end.
=> macOS: Don't change fullscreen state during fullscreen transition

CHANGELOG.md, Cargo.toml, examples/cursor_grab.rs, examples/multithreaded.rs, src/event.rs, src/lib.rs, src/platform_impl/linux/wayland/keyboard.rs, src/platform_impl/linux/x11/util/input.rs, src/platform_impl/linux/x11/util/modifiers.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event.rs, src/platform_impl/macos/view.rs, src/platform_impl/web/stdweb/event.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/windows/event.rs
This addresses a pet peeve I've had for a while. The `ModifiersState` struct is logically a series of bitflags, but we've been exposing it as a series of `bool`s. This PR addresses that.
If people have objections, please bring them up, but in the absence of discussion I'm inclined to merge this.
=> Change ModifiersState to a bitflags struct

src/platform_impl/web/stdweb/timeout.rs
While working on #1233, I noticed rustc complaining about a usage of `mem::uninitialized` in the stdweb backend.
Previously: we were swapping out the `TimeoutHandle` with uninitialized memory to own it, since `TimeoutHandle::clear` takes `self`. This change replaces that swap with an `Option<TimeoutHandle>`, so we can write this code without deprecated APIs. `Option` adds a trivial amount of overhead, zero-cost alternatives could be: [`mem::ManuallyDrop::take`](https://doc.rust-lang.org/beta/std/mem/struct.ManuallyDrop.html#method.take) (when it becomes stable) or `mem::MaybeUninit`. I'm happy to add a comment in `Timeout::handle` describing why it's coded this way for posterity, if desired.
=> fix: remove deprecated usage of `mem::uninitialized`.

CHANGELOG.md, src/platform_impl/windows/window.rs
The changes in #898, updated for the modern age.
=> Fix Window::set_visible not setting internal flags correctly

src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs
I'm completely newbie about Cocoa's memory management.
Please review this carefully.
This PR contains 2 changes.
1. Fix memory leak on `run_return`
I noticed that `leaks` command shows some leaks of `NSAutoreleasePool` object when run `window_run_return` example.
I fixed it by inserting `pool.drain();` to end.
src/platform_impl/macos/event_loop.rs
2. Reduce memory usage on  `run_return`
I noticed that memory usage of `window_run_return` example is very higher than `window` example.
I fixed it by using `NSAutoreleasePool`.
src/platform_impl/macos/app_state.rs
=> [MacOS] Fix memory management

CHANGELOG.md, src/platform_impl/macos/view.rs
This PR fixes #1128 
`CursorEntered` and `CursorLeft` events fired at old window size because `TrackingRect` is not updated once initialized.
This adds an event for `NSViewFrameDidChangeNotification` to update `TrackingRect` for each window resize.
=> MacOS fix `CursorEntered` and `CursorLeft` events fired at old window size.

Cargo.toml, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs, src/window.rs
I believe both backends are implemented, but I'm not sure if just the output I'm seeing from doing `cargo web start ...` indicates it's working.
This change set it based on the MDN docs for [`Window.devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) and [this JSFiddle](https://jsfiddle.net/znuwtfca/1/).
Some points:
- Use `Window.devicePixelRatio` to get the `hidpi_factor`
- Set canvas element to the physical size and the canvas' css size to the logical size
- (not implemented yet) register an event for `hidpi_factor` changes using `matchMedia` (JSFiddle prototype here https://jsfiddle.net/b6zcg24u/)
- Note: Changing the browser's zoom level affects the `devicePixelRatio`
- Note: `winit` needs an example that outputs graphics to test this?
- TODO: …
=> Implement hidpi for web platform

src/event.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/windows/event_loop.rs
Thinking about it, the `Option` wrapper isn't really necessary - if the user doesn't want the window to resize, they can just set the size to `Window::inner_size()`.
Not 100% sure if this'll compile on macOS and iOS, but I'll update the PR if the CI fails.
=> Remove Option from HiDpiFactorChanged in favor of a bare PhysicalSize

CHANGELOG.md, src/platform_impl/linux/x11/util/randr.rs
This commit makes `WINIT_HIDPI_FACTOR` dominate `Xft.dpi` in general and
adds a special value `0` for `WINIT_HIDPI_FACTOR` to use winit computed
DPI factor with randr over Xft.dpi.
We agreed with @Osspial [here](https://github.com/rust-windowing/winit/pull/1349#discussion_r362718880) that the proposed [solution](https://github.com/rust-windowing/winit/issues/836#issuecomment-562912905) for #836 makes sense and also that `WINIT_DPI_FACTOR` should dominate `Xft.dpi`.
However I'm wondering whether I should send this PR to dpi-overhaul branch instead?
Fixes #836 #1141
cc @chrisduerr
=> On X11, make `WINIT_HIDPI_FACTOR` dominate `Xft.dpi` in some cases

src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs
* In `WindowBuilderExtUnix` methods, use `Size` instead of `LogicalSize`
Addresses #940 on X11
Fixes #1353
=> X11: Properly update window size constraints on DPI change

examples/cursor.rs, examples/cursor_grab.rs, examples/custom_events.rs, examples/min_max_size.rs, examples/minimize.rs, examples/multiwindow.rs, examples/request_redraw.rs, examples/resizable.rs, examples/transparent.rs, examples/web.rs, examples/window.rs, examples/window_icon.rs, examples/window_run_return.rs
I was talking with @grovesNL in the Rust Discord, and I noticed that a lot of the examples set `control_flow` in the event matching fallthrough case. That's a bad design pattern to be encouraging, so this PR moves the `control_flow` setters to the top of the event handler closure.
=> Make examples set control_flow in a more realistic way

src/event.rs, src/lib.rs
Basically I had questions when I started exploring the new
event API's, and as I figured out the answers I put down more info
about how everything works.  This is not final, and suggestions
are welcome -- the code example in the `event` module docs is
particularly dubious, but it's how I'm used to thinking abou things
so it only made sense to me once I wrote that.
Note that my bias is towards using winit for writing games, so that's
the sort of things I was interested in.  This may not be valid for
more general use cases.
=> Added some "how" and "why" docs to event handling.

CHANGELOG.md, Cargo.toml, examples/cursor.rs, examples/cursor_grab.rs, examples/custom_events.rs, examples/fullscreen.rs, examples/handling_close.rs, examples/min_max_size.rs, examples/minimize.rs, examples/monitor_list.rs, examples/multithreaded.rs, examples/multiwindow.rs, examples/request_redraw.rs, examples/resizable.rs, examples/timer.rs, examples/transparent.rs, examples/video_modes.rs, examples/window.rs, examples/window_debug.rs, examples/window_icon.rs, examples/window_run_return.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
See title. Bug can be reproduced with the following testcase:
```rust
use winit::{
event::{Event, WindowEvent},
event_loop::{ControlFlow, EventLoop},
window::WindowBuilder,
};
fn main() {
let event_loop = EventLoop::new();
let window = WindowBuilder::new()
.with_title("A fantastic window!")
.build(&event_loop)
.unwrap();
event_loop.run(move |event, _, control_flow| {
*control_flow = ControlFlow::Wait;
match event {
Event::WindowEvent { event, .. } => match event {
WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
_ => (),
},
Event::MainEventsCleared => {
window.request_redraw();
println!("MainEventsCleared");
}
Event::RedrawRequested(_) => {
println!("redrawing!");
}
_ => (),
}
});
}
```
The example should print the following for each iteration of the event loop:
``` …
```
=> On Windows, fix bug where RedrawRequested would only get emitted every other iteration of the event loop

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
=> X11: Fix deadlock on window state with certain window events

README.md, examples/window_run_return.rs, src/window.rs
Finishing the job of #1363. I noticed that README.md still used the old style.
=> Make docs set control_flow in a more realistic way

CHANGELOG.md, src/event.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/windows/event_loop.rs
Most platforms (X11, wayland, macos, stdweb, ...) provide physical positions in f64 units, which can contain meaningful fractional data. For example, this can be empirically observed on modern X11 using a typical laptop touchpad. This is useful for e.g. content creation tools, where cursor motion might map to brush strokes on a canvas with higher-than-screen resolution, or positioning of an object in a vector space.
I have not audited other uses of `PhysicalPosition`. IMO there's a strong case for making it non-generic; it was difficult to trace the types of all uses even for this one event, and 64 bits ought to be enough for anyone.
=> Don't discard high-precision cursor position data

src/event_loop.rs, src/icon.rs, src/lib.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/macos/event.rs, src/platform_impl/macos/view.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/windows/event_loop.rs
* Also removed an unnecessary impl trait bound that I noticed along the way
=> Fix warnings on all platforms

CHANGELOG.md, src/platform_impl/macos/app_state.rs
This PR fixes #1372 
I've found that do `postEvent` a dummy event solve this.
=> Fix run_return does not return on macOS unless it receives a message

CHANGELOG.md, src/platform_impl/linux/wayland/pointer.rs
On Wayland the mouse events are in *logical* coordinates by default, however winit decides to use *physical* ones after dpi-overhaul, so we should multiply coordinates by surface scale factor before propagating downstream.
=> On Wayland, fix coordinates in mouse events when scale factor isn't 1

CHANGELOG.md, src/platform_impl/macos/view.rs
Fixes #1371.
I found the issue described in #1371 when upgrading `iced_winit`: https://github.com/hecrj/iced/pull/147
The fix takes the same approach used in `window_delegate`. I am not sure if there is a better way to obtain the cursor position using physical coordinates.
=> Return physical position in `CursorMoved` on macOS

src/platform_impl/ios/event_loop.rs, src/platform_impl/macos/observer.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window_state.rs, src/window.rs
=> doc: change remaining EventsCleared references to MainEventsCleared

CHANGELOG.md, src/platform_impl/macos/view.rs
This PR fixes #1267 
It seems that Ctrl+Q is some prefix key when `hasMarkedText` returns `NO`.
For example, it emits '\u{1e}' when input Ctrl+Q and Arrow-up key.
So I modified `hasMarkedText` to returns YES always.
I'm not 100% sure about the mean of this change, but I think it's OK because `hasMarkedText` returns always `YES` after inputting Option+N in previous implementation.
A key with Command no longer emits ReceivedCharacter event by this change.
=> on MacOS, Fix not sending ReceivedCharacter event for some key combination

CHANGELOG.md, src/platform/web.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs
This allows Winit to take control of existing canvas elements in the
DOM, which is useful for web applications with other content in the
page.
=> Add the ability to pass a prebuilt canvas

src/platform_impl/linux/x11/mod.rs
Fixes #1407.
Can I ask why this wasn't caught before the release? It should be obvious from any app that requests redraws on X11.
=> Fix: deadlock when requesting redraw on X11

Cargo.toml, src/platform_impl/macos/util/async.rs
In addition to the `ffi` module, `dispatch` provides higher-level APIs to convert Rust closures into a format that can be used with GCD. The current implementation does not use them, instead going through a complex process of creating custom context structs and turning them into pointers to be passed to and converted by hand-written extern functions.
Perhaps the previous author attempted to use the high level APIs but was stopped because pointers do not implement `Send`. I've worked around this with a `MainThreadSafe` wrapper type that can be used to mark things as `Send`.
This also updates `dispatch` to 0.2, which plays better with Rust 2018.
This diff is a bit harder to compare than I'd like, but I've included some intermediate commits which are easier to compare.
=> Simplify code by switching to higher-level dispatch APIs

src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/mod.rs
The current implementation of the event loop runner has some significant
problems. It can't handle multiple events being emitted at once (for
example, when a keyboard event causes a key input, a text input, and a
modifier change.) It's also relatively easy to introduce bugs for the
different possible control flow states.
The new model separates intentionally emitting a NewEvents (poll
completed, wait completed, init) and emitting a normal event, as well as
providing a method for emitting multiple events in a single call.
This is pretty much required for a correct implementation of #1151
=> Web backend refactor and documentation

src/platform/macos.rs
=> Fix warnings on macos

CHANGELOG.md, src/platform_impl/macos/window.rs
=> Fix set_minimized(true) works only with decorations on macOS

CHANGELOG.md, src/platform_impl/linux/wayland/pointer.rs, src/platform_impl/linux/wayland/touch.rs
=> On Wayland, fix coordinates in touch events when scale factor isn't 1

CHANGELOG.md, src/platform/unix.rs
This change doesn't require any Wayland knowledge to review.
=> On Wayland, fix color from `close_button_icon_color` not applying

CHANGELOG.md, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/mod.rs
This restores default portable 'C' locale when target locale is unsupported
by X11 backend (Xlib).
When target locale is unsupported by X11, some locale-dependent Xlib
functions like `XSetLocaleModifiers` fail or have no effect triggering
later failures and panics.
When target locale is not valid, `setLocale` should normally leave the
locale unchanged (`setLocale` returns 'C'). However, in some situations,
locale is accepted by `setLocale` (`setLocale` returns the new locale)
but the accepted locale is unsupported by Xlib (`XSupportsLocale` returns
`false`).
Fix #636
=> Ignore locale if unsupported by X11 backend

CHANGELOG.md, src/platform_impl/macos/window.rs
This PR fixes #1420 
The window size that restored from simple_fullscreen become bit larger because when become simple_fullscreen, it remembers the frame which contains title bar and restore it by `NSWindow::setFrame_display_` which assumes the argment does not contains title bar.
This PR fix it by remember the frame which does not contains title bar.
=> On macOS, Fix `set_simple_screen` to remember frame excluding title bar

examples/control_flow.rs
User can switch between Wait, WaitUntil and Poll modes with key '1', '2' and '3' respectivly.
User can toggle request_redraw calls with the 'R' key.
Helpful for testing all control flow modes and use of request_redraw.
=> Add new example that demonstrates the different control flow schemes

examples/request_redraw_threaded.rs
reproduces https://github.com/rust-windowing/winit/issues/1466
=> Add an example that calls request_redraw() from a thread

CHANGELOG.md, src/event.rs
The current `Event::to_static` returns `None` for user events. This PR makes it return the proper event instead.
This fixes an issue reported in https://github.com/hecrj/iced/issues/188, caused by a panic here:
https://github.com/rust-windowing/winit/blob/ad7d4939a8be2e0d9436d43d0351e2f7599a4237/src/platform_impl/windows/event_loop/runner.rs#L62
=> Map `UserEvent` properly in `Event::to_static`

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
Would wait for events when now == wait_untill
=> fix issues in wait_until_time_or_msg function

src/platform_impl/linux/mod.rs
Related to, but does not necessarily entirely address #1474
=> X11: Fix deadlock when an error occurs during startup

Cargo.toml, src/event.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/inner.rs, src/platform_impl/linux/x11/ime/mod.rs, src/platform_impl/linux/x11/mod.rs
Fix #1293
Added new window events to get information about preedit status in IME: `CompositionStart`, `CompositionUpdate`, `CompositionEnd`.
This change requires x11-dl crate. I've already send a pull request for it (https://github.com/erlepereira/x11-rs/pull/107)
TODO:
- I'm not sure `ImeContextClientData` could be accessed at the same time. It might need to be wrapped with `Mutex`
- This feature only available in X11. I don't have other platform, so need to help implementing this feature for other platforms.
- We also need to provide a way to disable this feature, since some people don't want to receive these new events.
=> add composition event support

CHANGELOG.md, src/platform_impl/windows/dark_mode.rs
In general, winit should never assert on anything unless it means that
it is impossible to continue the execution of the program. There are
several assertions in the Windows dark mode code where this is not the
case.
Based on surface level inspection, all existing assertions could be
easily replaced with just simple conditional checks, allowing the
execution of the program to proceed with sane default values.
Fixes #1458.
Fixes #1405.
=> Remove assertions from Windows dark mode code

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
~~Simplifies the message loops and event handling considerably~~
~~Strongly inspired from the X11 platform~~
~~Partially reverts https://github.com/rust-windowing/winit/commit/6a330a2894873d29fbbfdeebfc1a215577213996~~
These panics were introduced by https://github.com/rust-windowing/winit/commit/6a330a2894873d29fbbfdeebfc1a215577213996
Fixes https://github.com/rust-windowing/winit/issues/1391
Fixes https://github.com/rust-windowing/winit/issues/1400
Fixes https://github.com/rust-windowing/winit/issues/1466
Fixes #1469
Probably fixes other related issues
The commit mentioned above introduced a few critical regressions.
I did quite a bit of forensic (looking at 0.19.1, 0.20.0-alpha1) to understand what was going on around the handling of request_redraw(). I also looked at how other …
=> On Windows, fix request_redraw() related panics

CHANGELOG.md, src/icon.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/util/icon.rs, src/platform_impl/macos/mod.rs, src/platform_impl/web/mod.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
To achieve this, I needed to refactor the `Icon` internals a little so that on Windows the canonical representation is the handle rather than RGBA.
I exposed this functionality as an `IconExtWindows` platform trait.
=> Add ability to create Icons from embedded resources on Windows

CHANGELOG.md, src/event.rs, src/platform_impl/windows/event_loop.rs
Fixes #1494. Not sure if it'll build on all the platforms yet, but we'll see where the CI takes us.
=> Use i32 instead of u32 for position type in WindowEvent::Moved

src/platform_impl/windows/event_loop.rs
Fixes deadlock that appears to be introduced by #1381
=> Fix freeze when pressing modifier keys on Windows

CHANGELOG.md, src/platform_impl/macos/view.rs
This reverts commit 9daa0738a9aeb60768d9b7d19f4e3deddd55958b.
This commit introduced other bug #1453 with likely much more common bindings,
so reverting it for now.
Fixes #1453.
=> Revert "on MacOS, Fix not sending ReceivedCharacter event for some key combination (#1347)"

CHANGELOG.md, Cargo.toml, README.md
There are two PRs I'm aware of that should be relatively trivial to get
merged, which would fix some issues. Other than those, I don't think it
makes sense to wait on anything.
- Fix Windows crash: https://github.com/rust-windowing/winit/pull/1459
- Fix macOS mouse reports: https://github.com/rust-windowing/winit/pull/1490
While #1459 seems pretty essential to actually make winit run, #1490 is
much less important and can probably be ignored if there aren't any
resources to merge it.
=> Bump version to 0.22.0

CHANGELOG.md, src/platform_impl/linux/x11/mod.rs
=> X11: Fix `ResumeTimeReached` being fired early

Cargo.toml
x11-dl was using std::mem::uninitialized incorrectly and when
rustlang added MaybeUninit and intrinsic panics on UB caused
by improper use of uninitialized (see rust-lang/rust/pull/69922)
it caused issues with X11 initialization. x11-dl pr
erlepereira/x11-rs/pull/101 updated x11-dl to use MaybeUninit
correctly
fixes #376 
- [NA] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [NA] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [NA] Created or updated an example program if it would help users understand this functionality
- [NA] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
=> upgrades x11-dl to 2.18.5 to fix #376

CHANGELOG.md, src/platform_impl/web/event_loop/runner.rs
=> Fix a possible double-borrow during event handling

CHANGELOG.md, src/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/state.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/stdweb/timeout.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/timeout.rs
Implementation based on discussion in #1493. I did not implement `requestPostAnimationFrame` because it's not documented properly yet and does not exist in `stdweb` or `web_sys` either.
=> Implement `requestAnimationFrame` for web

CHANGELOG.md, Cargo.toml, README.md
There are a few relatively important bugfixes with no API impact in the
master branch. We might as well release this as a non-breaking change.
=> Bump version to 0.22.1

examples/control_flow.rs
This fixes a minor issue when starting in WaitUntil control flow
=> control_flow example: fix wait_cancelled logic again

src/lib.rs
May save people some time when building or using graphics libraries with raw-window-handle support. I didn't manage to find a way to use proper intra doc links on a foreign trait method, but this works.
=> Mention raw-window-handle in library docs

Cargo.toml
This PR adds `wasm32-unknown-unknown` to docs.rs and explicitly states which targets are built for docs.rs. I tested this by doing https://github.com/rust-windowing/winit/issues/1028#issuecomment-607873122 and had mixed results with all of our targets as talked about in https://github.com/rust-windowing/winit/issues/1028#issuecomment-608645825.
`i686-unknown-linux-gnu` build is currently broken. Fix requires a PR to https://github.com/rust-lang/crates-build-env.
It doesn't look like docs.rs supports feature flag ops so I just chose `web-sys` as a default feature for all docrs targets.
=> Added more docs.rs targets

CHANGELOG.md, src/platform_impl/windows/window.rs
Closes #1510 
~On Windows, to prevent the MAXIMIZED flag from being overwritten, this only calls `Window::set_inner_size` if not MAXIMIZED or explicit window size was provided. If both `WindowBuilder::with_maximized(true)` and `WindowBuilder::with_inner_size(...)` are provided, `inner_size` will win over MAXIMIZED.~
Update: see https://github.com/rust-windowing/winit/pull/1515#issuecomment-602501576
=> Preserve with_maximized on windows

src/event.rs, src/lib.rs
The current documentation's focus on traditional GUIs is an almost constant source of confusion among gamedevs.
=> Clarify when RedrawRequested is useful

src/lib.rs
=> Document that platforms will display garbage data in the window by default

CHANGELOG.md, src/platform_impl/macos/event_loop.rs
=> Implement `Drop` for `Proxy` on macOS platform

src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs
wayland: rework scale factor handling
Fixes some hidpi use cases on wayland :
- initialize with primary scale factor (avoid flicker)
- also call Resize on scale factor changes
apps usually resize their swap chains there and don't handle the explict scalefactorchanged.
As discussed with kchibisov, calling this on any scale change even if it happens to yield same physical size (e.g move window from 4K laptop to 4K TV), as a defense in depth to try to trigger any application UI/font scale redraw (even when they don't explicitly handle scalefactorchanged).
This might make applications do an identical swap chain resize as well if they don't check, but that's okay.
- minor fix: inner_size within Resize callback (not hdpi related)
Fixes Iced
=> wayland: rework scale factor handling

CHANGELOG.md, src/platform_impl/macos/view.rs
This fixes an issue on macOS where a mouse click would be generated,
without ever getting a mouse motion to the position before the click.
This leads to the application thinking the mouse click occurred at a
position other than the actual mouse location.
This happens due to mouse motion above the window not automatically
giving focus to the window, unless it is actually clicked, making it
possible to move the window without motion events.
Fixes #942.
=> Report mouse motion before click

CHANGELOG.md, examples/window_run_return.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window_state.rs
I'll do a more detailed writeup on the rationale behind these changes when I'm more awake, but the TL;DR is that it drastically simplifies Winit's event loop model by always using the modal event loop. This PR's fixes are an alternate approach to the problems described in #1429 that simplifies the event model more than #1461 does, but it could not exist in its current form without @filnet's work and feedback in those threads.
Fixes #1477, fixes #1496.
=> Fix several crashes on Windows by heavily simplifying the event loop code

CHANGELOG.md, src/platform_impl/ios/view.rs
Looks like this got missed whenever the DPI revamp happened. Touch works great on iOS with this change, though! 
Tested on iPhone XR
=> iOS: convert touch positions to physical

CHANGELOG.md, Cargo.toml, src/platform/macos.rs
Addresses https://github.com/servo/core-foundation-rs/pull/357
- [x ] Tested on all platforms changed (only affects macos)
- [x ] Compilation warnings were addressed
- [x ] `cargo fmt` has been run on this branch
- [ x] `cargo doc` builds successfully
- [ x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [NA ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [NA ] Created or updated an example program if it would help users understand this functionality
- [NA ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
=> Update macOS dependencies

CHANGELOG.md, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs
This stops things like page scrolling on spacebar / arrow keys
Resolves #1573
=> Prevent the default browser behavior of events

CHANGELOG.md, src/platform/macos.rs
- [ x] Tested on all platforms changed
- [ x] Compilation warnings were addressed
- [ x] `cargo fmt` has been run on this branch
- [ x] `cargo doc` builds successfully
- [ x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ x] Created or updated an example program if it would help users understand this functionality
- [ x] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
Trivial addition so that downstream MacOS users can use Cmd+Option-H to hide other applications in the same way they currently use Cmd-H to hide the current one.  If approved, an issue …
=> Add function to hide other applications on MacOS

CHANGELOG.md, src/platform_impl/linux/x11/window.rs
This is a double-lock bug in windows.rs:
The first lock is at L641 in `set_fullscreen_inner()`:
https://github.com/rust-windowing/winit/blob/03335cef851495e0a2843db7019516988740688b/src/platform_impl/linux/x11/window.rs#L641-L643
Then `set_position_inner()` is called, where the second lock is at L988
https://github.com/rust-windowing/winit/blob/03335cef851495e0a2843db7019516988740688b/src/platform_impl/linux/x11/window.rs#L984-L988
The patch drops the MutexGuard before calling `set_position_inner()` in `set_fullscreen_inner()`.
=> platform_impl/linux/x11: fix deadlock in fn set_fullscreen_inner

CHANGELOG.md, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Previously the `run_return` example would freeze if you switch to fullscreen. This fixes it.
It is not a clean solution but if anybody knows more about mac than I do let me know if there is a better way.
=> Macos fullscreen & dialog support with `run_return`

CHANGELOG.md, Cargo.toml, README.md, build.rs, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
As suggested in https://github.com/rust-windowing/winit/issues/774
Wayland adds lots of dependencies when building 
I only tested on Linux/X11.  I also checked it compiles with wayland alone
=> Make wayland or X11 optional

.github/workflows/ci.yml
Follow-up to #1597, adding tests to build without optional X11 and Wayland features.
=> Add tests for X11 and Wayland features

src/platform_impl/macos/view.rs
This is my naive attempt to fix #1599. It seems to work, though I've only checked on a remote macOS machine.
Fixes #1599 (_"[macos] Click-dragging out of a window doesn't work on macOS"_) 
Related to #292 (_"Add mouse event capturing when click-dragging out of a win32 window"_)
=> macOS: Support click-dragging out of a window

CHANGELOG.md, src/platform/windows.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs
Since #1260 is stalled and based on discussion there I suggest an alternative fix for the `OleInitialize` problem (#1255). This makes drag and drop optional and allows `winit` to be used together with libraries like `cpal` without drag and drop functionality. I also improved the panic message as previous was really not informative.
=> Make drag and drop optional (fixes OleInitialize failure #1255)

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs
Fixes #1587 and #1602. Fixes #1611 .
=> On Windows, fix bug where we'd try to emit `MainEventsCleared` events during nested win32 event loops

CHANGELOG.md, src/event_loop.rs, src/monitor.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/monitor.rs, src/window.rs
I only have Linux machines, so the other platforms where not tested. This should not change behaviour though.
Fix #1566
=> Move available_monitors and primary_monitor to EventLoopWindowTarget

CHANGELOG.md, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
This resolves various problems with the documentation about platform
support on the Window struct.
It also completely removes pointless runtime errors in favor of
consistent no-ops on all platforms that do not support a feature.
=> Fix Window platform support documentation

CHANGELOG.md, src/event.rs, src/platform_impl/linux/wayland/pointer.rs, src/platform_impl/macos/view.rs, src/platform_impl/web/stdweb/event.rs, src/platform_impl/web/web_sys/event.rs
This removes the `LogicalPosition` from the `PixelDelta`, since all
other APIs have been switched to use `PhysicalPosition` instead too.
It also seems like `LineDelta` was using both logical and physical
sizes, depending on platform. I've changed this to explicitly take a
`PhysicalPosition` parameter to force a uniform return value.
I'm not entirely sure which platform uses which kind of pixel sizes by
default, so I've made the assumption that both the web and macOS
platforms deliver their events in LogicalPositions.
Fixes #1406.
=> Remove logical pixel handling from scroll events

CHANGELOG.md, src/platform_impl/web/web_sys/canvas.rs
Pointer events aren't supported on Safari yet, so this pull request uses mouse events when pointer events aren't supported on the web.
=> Web: Use mouse events instead of pointer events if the latter isn't supported

CHANGELOG.md, src/platform_impl/android/mod.rs
- Poll looper for `ControlFlow::Poll`, currently it won't progress in this case
- Don't exit the EventLoop when no new event has been polled from the Looper, which causes the program to instantly exit
fixes https://github.com/rust-windowing/winit/issues/1636
cc @VZout
=> android: fix event loop polling

CHANGELOG.md, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs
Hi Friends,
I'm messing around with adding UIKit bindings to iced. Anyway, one of the things that I think myself (and others) will want is the ability to use the [Debug View Heirarchy](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html
) feature in Xcode. Under normal conditions, when I attach to the process in Xcode and push the "Debug View Heirarchy" button I get this:
```
Error:    Unable to Capture View Hierarchy.
Details:  Log Title: Data source expression execution failure.
Log Details: error evaluating expression “(id)[[(Class)objc_getClass("DBGTargetHub") sharedHub] performRequestWithRequestInBase64:@"…"]”: error: <user expression 4>:1:89: reference to 'NSString' is ambiguous
note: candidate found by …
```
=> Renamed NSString to NSStringRust to support Debug View Heirarchy in Xcode

CHANGELOG.md, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs
PhysicalSize is recorded as canvas.size, whereas LogicalSize is stored
as canvas.style.size.
The previous cursor behavior on stdweb clobbered all style - thus losing
the LogicalSize.
- [] Created or updated an example program if it would help users understand this functionality
- [] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
Here are some before/after screencasts from the app where I encountered this bug. It's hard to make sense of looping GIFs - the video starts when my cursor is on the right DOM-inspector pane, then the canvas is made much larger as my mouse enters the canvas because our app sets the cursor icon (to "auto" so it's an invisible cursor change, but enough to trigger the bug).
You can …
=> Fix HiDPI vs. set_cursor_icon for web

CHANGELOG.md, src/platform_impl/linux/mod.rs
The `_lwp_self` function cannot be used to reliably determine the main
thread, see
https://github.com/alacritty/alacritty/issues/2631#issuecomment-676723289.
It might always be equal to the PID, but it's certainly not always 1
when the thread is the main thread.
However, Rust's built in `Thread::id` and `Thread::name` function will
always return `ThreadId(1)` and `Some("main")`. Since converting the
thread's ID to a number is not supported on stable Rust, checking that
the thread is labeled `Some("main")` seems like the most reliable
option. It should also be a good fallback in general.
=> Fix crash on NetBSD

CHANGELOG.md, src/platform_impl/web/stdweb/event.rs, src/platform_impl/web/web_sys/event.rs
Closes #1655
The code had been changed for both `stdweb` and `web-sys`, but I have only tested with `web-sys`. Though technically they both use the same web API so their behaviour should not be any different.
=> Fix vertical scroll being inverted on web targets

CHANGELOG.md, Cargo.toml, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/canvas/mouse_handler.rs, src/platform_impl/web/web_sys/canvas/pointer_handler.rs, src/platform_impl/web/web_sys/event.rs
Closes #1660
I have also refactored the pointer/mouse handling code a bit for the `web-sys` target due to it getting quite messy, and it also helps when adding touch event handling later.
The code had been changed for both `stdweb` and `web-sys`, but I have only tested with `web-sys`. Though technically they both use the same web API so their behaviour should not be any different.
=> Impl. mouse capturing on web target

CHANGELOG.md, FEATURES.md, src/dpi.rs, src/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/stdweb/scaling.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/scaling.rs
This implements scale factor change detection for the web target by using `MediaQueryList`. I've only implemented this for the `web-sys` backend. It's currently stubbed out in the `stdweb` backend.
This PR also includes a small refactor and fixes an issue with the handling of `ControlFlow::Exit` (see also #1688).
Tested on Firefox and Chrome (Windows) And Firefox (Linux).
=> Handle scale factor change on web-sys backend

CHANGELOG.md, src/event.rs, src/platform_impl/macos/view.rs
Fixes https://github.com/rust-windowing/winit/issues/1695
---
- [none] Compilation warnings were addressed
- [-] Created or updated an example program if it would help users understand this functionality
- [n/a] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
=> invert h-scroll direction for macos to be consistent with other platforms.

CHANGELOG.md, examples/multithreaded.rs, examples/window_debug.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
On certain platfroms window couldn't be on any monitor
resulting in failures of `current_monitor` function on such,
since they can't return any monitor at all.
Such issue was happening on Wayland, since the window
isn't on any monitor, unless the user has drawn something into it.
Returning `Option<MonitorHandle>` will give an ability to
handle such situations gracefully by properly indicating that
there's no current monitor.
Fixes #793.
If anyone wants to submit more specific platform implementations feel free to post a patch or open PR against my branch.
cc @murarth (X11)
cc @francesca64 (macOS/ios)
cc @Osspial (Windows)
=> Make current_monitor return `Option<MonitorHandle>` 

CHANGELOG.md, examples/video_modes.rs, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/monitor.rs, src/window.rs
Certain platforms like Wayland don't have a concept of
primary Monitor in particular. To indicate that
`primary_monitor` will return `None` as well as in cases
where the primary monitor can't be detected.
Fixes #1683.
=> Make `primary_monitor` return `Option<MonitorHandle>`

CHANGELOG.md, Cargo.toml
Tested on Linux. The other platforms affected by this change are the BSDs and Windows. Nothing stands out in the [parking_lot changelog](https://github.com/Amanieu/parking_lot/blob/master/CHANGELOG.md#parking_lot-0110-parking_lot_core-080-lock_api-040-2020-06-23) that suggests there were any platform-specific changes however.
- [N/A] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [N/A] Created or updated an example program if it would help users understand this functionality
- [N/A] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
Resolves #1657
=> Bump parking_lot to 0.11

examples/control_flow.rs, examples/cursor.rs, examples/cursor_grab.rs, examples/custom_events.rs, examples/fullscreen.rs, examples/handling_close.rs, examples/min_max_size.rs, examples/minimize.rs, examples/monitor_list.rs, examples/multithreaded.rs, examples/multiwindow.rs, examples/request_redraw.rs, examples/request_redraw_threaded.rs, examples/resizable.rs, examples/timer.rs, examples/transparent.rs, examples/video_modes.rs, examples/window.rs, examples/window_debug.rs, examples/window_icon.rs, examples/window_run_return.rs
This is only a change to the examples. Some `use` imports have an extra newline to prevent `std` imports from getting mixed in the middle of external crate imports.
This shouldn't be an issue since we're just using the newer initialization API of `simple_logger` 1.9.0
This seems internal enough, so I didn't make a changelog entry.
- [N/A] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [N/A] Created or updated an example program if it would help users understand this functionality
- [N/A] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
=> Stop using deprecated simple_logger initialization

Cargo.toml
Fix regression from #1702. `simple_logger::SimpleLogger` is not public in `simple-logger` < v1.9.
=> Fix examples build by bumping simple_logger to v1.9

CHANGELOG.md, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/stdweb/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/canvas/mouse_handler.rs, src/platform_impl/web/web_sys/canvas/pointer_handler.rs, src/platform_impl/web/web_sys/event_handle.rs, src/platform_impl/web/web_sys/media_query_handle.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/scaling.rs, src/platform_impl/web/window.rs
(copied from changelog:)
- On Web (web-sys only), the `Event::LoopDestroyed` event is correctly emitted when leaving the page.
- On Web ~~(web-sys only)~~, the `WindowEvent::Destroyed` event now gets emitted when a `Window` is dropped.
- On Web (web-sys only), the event listeners are now removed when a `Window` is dropped or when the event loop is destroyed.
- On Web ~~(web-sys only)~~, the event handler closure passed to `EventLoop::run` now gets dropped after the event loop is destroyed.
- **Breaking:** On Web, the canvas element associated to a `Window` is no longer removed from the DOM when the `Window` is dropped.
Closes #1688
=> Add cleanup code to web backend, mostly web-sys

CHANGELOG.md, examples/fullscreen.rs, examples/multithreaded.rs, examples/window_debug.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/window.rs
This changes `Fullscreen::Borderless` enum variant from
`Fullscreen::Borderless(MonitorHandle)` to
`Fullscreen::Borderless(Option<MonitorHandle>)`. Providing
`None` to it will result in picking system's preferred monitor.
This is an implementation of proposal from https://github.com/rust-windowing/winit/issues/793#issuecomment-676820743 . I can only speak for Wayland implementation here. So `macOS`,`ios`,`X11`, and `Windows`, implementations are interested and likely wrong or inefficient to do what this variant should do.
cc for checking implementations
@francesca64 (not sure if you're active checking macOS/ios stuff now, let me know if you don't want to take a look)
@Osspial (windows) The implementation I've provided needs fixing for sure, since I have a hard time understand how windows …
=> Rework Fullscreen::Borderless enum variant

CHANGELOG.md, src/platform_impl/macos/window_delegate.rs
=> Convert location to physical on Mac when `emit_move_event`

src/event_loop.rs
Make it clear that ControlFlow::Poll causing events to be sent on `requestAnimationFrame` is an implementation detail which should not be relied on.
**Rationale:**
The exact behaviour of `ControlFlow::Poll` had already been changed once in #1690, and it might be changed again in the future. It also does not expose the timestamp obtained from the `requestAnimationFrame` callback so it is not very useful to users who actually want to do rendering from `requestAnimationFrame` (#1697).
cc @ryanisaacg
=> Clarify ControlFlow::Poll doc for web

CHANGELOG.md, Cargo.toml, src/platform_impl/linux/wayland/event_loop/mod.rs
SCTK was a bit behind on Wayland protocol version, and so this release
brings it up to date. It also cleans up 'Environment'.
=> Update SCTK to 0.12

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
This patch updates the X11 `FocusIn` and `FocusOut` event processor to properly track the synthetic events produced.
fixes #1563
=> Fix missing ModifiersChanged event from start

CHANGELOG.md, src/platform_impl/android/mod.rs
Ran into the issue were `WindowEvent::Focused` would always return false on Android, which was caused by unhandled events  from`ndk-glue`. This is a simple PR that solves that issue, updated the changelog as well!
Tested locally on my Android device and works as expected.
=> Added WindowHasFocus and WindowLostFocus events to Android

src/platform_impl/web/web_sys/scaling.rs
The initial media query that's used to watch for device pixel ratio
changes should match. Unfortunately it doesn't with Safari and the
corresponding assertion fails. This is because resolution is not a
supported support property for queries. As a workaround, this patch
extends the query to optionally match for the webkit specific DPR
property directly.
This fixes #1734
=> Fix failing assertion on start-up with Safari

CHANGELOG.md, src/platform_impl/windows/window.rs
This PR is primarily here to fix a downstream bug (https://github.com/alacritty/alacritty/issues/1927). Testing the transparency feature out on Windows (both via `examples/transparency.rs` and with a build of alacritty), I was unable to reproduce the issue described in the old comment in this code. I suppose it's possible that this only manifests on some configurations though (for completeness, I'm testing on a Windows 10 environment, though I cross-compiled things on a Linux box using GNU tools). To be on the safe side, it might make sense for other people with access to a Windows environment to double check that this doesn't regress anything.
In addition, I removed a couple of redundant bits in the Windows API calls (see the description below).
---
*Original commit message follows:* …
=> Fix Windows transparency behavior to support fully-opaque regions

Cargo.toml
Wayland backend is self contained and only requires
smithay-client-toolkit to work, thus feature gate the
rest of the deps that are only for X11.
=> Feature gate more dependencies

CHANGELOG.md, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Like #1542 but just for borderless.
Fixes #1540
Closes #1542
- ~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~
- ~Created or updated an example program if it would help users understand this functionality~
- ~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~
=> Windows: Fix alt tab bordless fullscreen

CHANGELOG.md, src/platform_impl/linux/wayland/window/mod.rs
Building window with 'set_min_inner_size' was setting 'max_inner_size'
under the hood, thus completely disabling window resize, since
the window isn't resizeable on Wayland when its minimum size
is equal to its maximum size.
=> On Wayland, fix 'with_min_inner_size' disabling resize

CHANGELOG.md, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/web_sys/canvas.rs
The event was never sent to the application because of the unconditional
preventDefault()
call on keydown.
Fixes #1741
=> Fix WindowEvent::ReceivedCharacter on web

CHANGELOG.md, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs
Fixes compilation when targeting aarch64, where `objc` crate has slightly different encoding for `BOOL` type.
=> macos: Fix compile on aarch64

CHANGELOG.md, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
=> X11: Fix `request_redraw` not waking the event loop

src/platform_impl/linux/x11/mod.rs
Fixup to #1756, which could generate multiple `RedrawRequested` events for the same window id in a single event loop iteration.
=> X11: Fix multiple RedrawRequested events per event loop iteration

CHANGELOG.md, examples/window_run_return.rs, src/lib.rs, src/platform/mod.rs, src/platform/run_return.rs
Closed https://github.com/rust-windowing/winit/issues/1643
=> Rename desktop eventloop extensions to run_return extension

src/platform_impl/android/mod.rs
Is there a reason why this `println!()` call is in the event loop of Android? Would like it removed as it spams stdout :)
=> Remove println! call in Android's eventloop

CHANGELOG.md, src/platform/unix.rs
This commit increased default font size from 11 to 17 making it
identical to the one SCTK is using under the hood, since it's more
readable.
=> On Wayland, increase default font size in CSD

src/event.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/mod.rs, src/platform_impl/windows/window.rs
Ref: https://github.com/rust-windowing/winit/issues/1497#issuecomment-609060877
To avoid confusion from users, rename `CompositionEvent` to `IMEPreeditEvent` to make it clear that those events are related to IME.
Also, added documents
=> rename CompostionEvent to IMEPreeditEvent

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
Message boxes did not appear when opening them. The sound did play but they never were made visible unless the system triggers a redraw (for example when you press `alt`). The solution to this is to add the default `WM_PAINT` behavior back in. (`DefWindowProc` does this if you don't override `WM_PAINT`)
(This issue appeard in #1615)
=> Windows: Delayed Message Boxes Fix.

CHANGELOG.md, src/platform_impl/android/mod.rs
Small PR enabling multi-touch on Android :) 
Also rearranged an entry in the changelog as it was added to the top instead of the bottom.
=> Android: support multi-touch

CHANGELOG.md, FEATURES.md, src/platform_impl/android/mod.rs
In the previous implementation of multi-touch there was a issue. When having two fingers on the screen and you would release one it would result in ended events being generated for all fingers even though not all fingers were lifted. This implementation will generate started and ended events for the right finger id's. Furthermore this implementation will generate a cancelled event with different defaults. These defaults should be according to spec since the user shouldn't preform any action it would normally perform: "_You will not receive any more points in it. You should treat this as an up event, but not perform any action that you normally would_" according to the [ndk documentation](https://developer.android.com/ndk/reference/group/input#anonymous-enum-32).
=> Android: Improved multi-touch

CHANGELOG.md, Cargo.toml, src/event.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/windows/event_loop.rs
Since Wayland mouse buttons are generally u16, we can only somehow
translate them into u8 used by winit. Also, they're coming from
linux/input-event-codes.h directly, thus translating them into
something cross-platform is cumbersome, thus just passing them
downstream as 'button - BTN_LEFT' for now.
=> On Wayland, don't drop extra mouse buttons

CHANGELOG.md, Cargo.toml, examples/set_ime_position.rs, src/platform_impl/windows/window.rs, src/window.rs
I tested in Windows 10 18363.1198 with Microsoft Japanese IME. I am not tested without IME. I followed IMM documentation and implementation will not call IMM API if Windows has no IME.
IMM docs: https://docs.microsoft.com/ja-jp/windows/win32/intl/about-input-method-manager
ImmSetCompositionWindow docs: https://docs.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immsetcompositionwindow
COMPOSITIONFORM docs: https://docs.microsoft.com/en-us/windows/win32/api/imm/ns-imm-compositionform
GetSystemMetrics and SM_IMMENABLED docs: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics
=> Windows: implement Window.set_ime_position() with IMM API.

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
Our application was not exiting gracefully but crashed on `platform_impl/windows/event_loop.rs:1927`. 
`WM_DESTROY` destroys `subclass_input` but `WM_NCDESTOY` is send after `WM_DESTROY` ([See MS docs](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-ncdestroy)) which causes `subclass_input.event_loop_runner.clone();` to fail.
Examples don't repro, are the they just lucky that the memory didn't change?
Creating a minimal test case from our project would be quite a lot of work.
=> Windows: Changed thread_event_target_callback's WM_DESTROY to WM_NCDESTROY

CHANGELOG.md, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
By lining up `Window::set_fullscreen` with Chromium's [`FullscreenHandler::SetFullscreenImpl`](https://chromium.googlesource.com/chromium/src/+/40351207e40888d64d3e02711287144ede7b4454/ui/views/win/fullscreen_handler.cc#55).
**EDIT**: `Window::set_fullscreen` is now based on https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353, as it seems to be much more clean and simple compared to the Chromium way. I would also like to receive some feedback regarding the chosen method.
Fixes #1765.
=> Windows: Preserve minimized/maximized state in fullscreen

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window_state.rs
=> On Windows, fix bug causing mouse capture to not be released.

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs
This is a follow-up to #1780 and #1746.
Fixes #1795.
=> [Windows] Improve handling of window destruction

CHANGELOG.md, src/platform_impl/windows/window.rs
=> [Windows] Bring the default window size into line with other platforms

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
I'm not sure if this is the best way to address #1682 since I'm not familiar with how Windows handles cursors WRT windows, and I plan on looking further into this before converting from a draft PR to a normal PR.
Fixes #1682
=> [Windows] Set the cursor icon when the cursor first enters a window

CHANGELOG.md, src/platform_impl/android/mod.rs
Android backend doesn't handle support certain input events, but still marks them as handled, which stops eg. volume buttons from working.
=> Android: Do not mark unhandled events as handled.

src/platform_impl/android/mod.rs
ndk-glue currently sets both the `ident` field and user-data pointer to `0` or `1` for the event pipe and input queue respectively, to tell these sources apart. While it works to reinterpret this `data` pointer as integer identifier it shouldn't be abused for that, in particular when one may wish to provide extra information with an event in the future; then the `data` field is used as pointer (or abused as abstract value) for that.
---
These constants (`0` and `1`) are internal to `ndk-glue` and not publicly documented anywhere (afaik). I believe they should at least be exposed as constants, or perhaps abstracted behind a `poll` function internal to `ndk-glue`. Consequently we might want to warn API users when they try use one of these "reserved `ident`s" (but only on the thread looper …
=> android: Use event identifier instead of userdata pointer

src/platform_impl/windows/event_loop.rs
The issue was caused by calling SetCapture on a window which already
had the capture. The WM_CAPTURECHANGED handler assumed that it would
only run if the capture was lost, but that wasn't the case. This made
the handler to try to lock the window state mutex while it was already
locked.
The issue was introduced in #1797 (932cbe4).
=>  On Windows, fix deadlock caused by mouse capture

CHANGELOG.md, examples/fullscreen.rs, examples/window_debug.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
Related issues: #208 #1578
Currently, if you want to save window state to a persistent config (position, size, fullscreen/maximized flags etc) and then restore when user is relaunching your application - this is not possible for maximized window state at all. We have `Window::set_maximized` and `WindowBuilder::with_maximized` - but no way to query current state. Current maximized state can be changed outside of API (e.g. users clicking on maximize button in window frame).
Tested on Windows and macOS. This should probably be supported for Wayland/X11 - but I am not too familiar with the API and could not figure out how to implement it. Marked linux API as not implemented and set it to always return `false` for now. Maybe some linux platform maintainers could help get this functionality …
=> Add Window::is_maximized method

src/platform_impl/windows/window.rs
- Tested with `x86_64-pc-windows-gnu`, but can't get my build system to produce a 32bit version, so can't test that :/
- I didn't add it to the changelog since this is a very small fix.
We previously retrieved the value using `GetWindowLongW`, but [the documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongw) explicity says that `GetWindowLongPtrW` should be used for pointers and handles (which is what we're fetching).
=> Fix HINSTANCE returned by raw_window_handle on 64 bit Windows

CHANGELOG.md, Cargo.toml, src/platform_impl/android/mod.rs
Following the changes in [1] this bumps ndk and ndk-glue to 0.3 and uses the new constants. The minor version has been bumped to prevent applications from running an older winit (without #1826) with a newer ndk/ndk-glue that does not pass this `ident` through the `data` pointer anymore.
[1]: https://github.com/rust-windowing/android-ndk-rs/pull/112
=> Android: Bump ndk/ndk-glue to 0.3 and use constants for event ident

CHANGELOG.md, FEATURES.md, src/platform/windows.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs
Added `WindowBuilderExtWindows::with_menu`.
The primary reason for doing it here instead of just assigning a menu later on with `winapi::um::winuser::SetMenu` is to avoid that `with_inner_size` breaks, since the menu takes up some space that is not taken into account, which means the user would have to use `set_inner_size` again after adding the menu.
This, I'm guessing, could cause a jarring effect for the user (that the window resizes when starting).
Unresolved:
=> Add ability to assign a menu when creating a window on Windows

README.md, build.rs, src/platform_impl/macos/ffi.rs
This fixes an issue where cross compilation to macos was failing in our CI.
the error we were getting is
```
error: linking with `/dockercache/osxcross/target/bin/x86_64-apple-darwin17-clang` failed: exit code: 1
|
= note: "/dockercache/osxcross/target/bin/x86_64-apple-darwin17-clang" "-m64" "-L" "/root/.rustup/toolchains/nightly-2020-06-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib" "-L" "/root/.rustup/toolchains/nightly-2020-06-22-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-apple-darwin/lib/self-contained" "/builds/veloren/veloren/target/x86_64-apple-darwin/release/deps/veloren_voxygen.veloren_voxygen.7quxxn1k-cgu.4.rcgu.o" "-o" "/builds/veloren/veloren/target/x86_64-apple-darwin/release/deps/veloren_voxygen" "-Wl,-dead_strip" "-nodefaultlibs" "-L" …
```
=> Change linking of CGDisplayCreateUUIDFromDisplayID on macos

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
On Windows when clicking on the decorations bar the mouse cursor would briefly blink.  This PR fixes this by passing in the `LPARAM` received in the `WM_NCLBUTTONDOWN` when posting the message
=> fix cursor blinking when clicking decorations bar on Windows

CHANGELOG.md, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/stdweb/canvas.rs, src/platform_impl/web/stdweb/event.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/canvas/mouse_handler.rs, src/platform_impl/web/web_sys/canvas/pointer_handler.rs, src/platform_impl/web/web_sys/event.rs
I'm using winit with web/wasm via Bevy. Bevy relies on `DeviceEvent::MouseMotion` events to compute mouse movement deltas, and `DeviceEvent::MouseMotion` was not implemented for the web platform. `WindowEvent::CursorMoved` events didn't work for my use case because the x/y didn't update as the cursor moved when locked. I added a `MouseMotion` event to the web platform that uses the `movement_x/y` fields. I tested that my changes work within a Bevy web app.
I'm not sure if this is the "Device movement events" entry in the "Input handling" feature matrix?
=> Add DeviceEvent::MouseMove on web platform to support pointer lock

src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Besides its original purpose, commit 6343059b "Fix Windows transparency
behavior to support fully-opaque regions (#1621)" also included some
changes considered cleanups, one of them was:
* Remove the `CreateRectRgn` call, since we want the entire window's region to
have blur behind it, and `DwnEnableBlurBehindWindow` does that by default.
But the original code actually disabled the blur effect for the whole
window by creating an empty region for it, because that allows for the
window to be truely fully transparent. With the blur effect in place,
the areas meant to be transparent either blur the things behind it
(until Windows 8) or are darkened (since Windows 8). This also means
that on Windows 8 and newer, the resulting colors are darker than
intended in translucent areas when the blur …
=> Restore the ability to have fully transparent windows on Windows

CHANGELOG.md, src/platform_impl/windows/dark_mode.rs
This PR fixes the return value of `dark_mode::try_theme` when dark mode is supported.
Currently, `try_theme` returns `Theme::Dark` whether if the new theme is light or dark, resulting in `WindowEvent::ThemeChanged` and `window::theme` not working properly:
When returning the correct `Theme` value, everything works perfectly:
=> Fix Windows' try_theme returning Theme::Dark when new theme is light

src/window.rs
Fixes a typo where "Android" is misspelled as "Andraid".
=> Fix small typo in comments/docs

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, FEATURES.md, examples/drag_window.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
---
Partially fixes #221.
~~Still working on the other platforms, see https://github.com/rust-windowing/winit/issues/221#issuecomment-767690279 for details.
Would really appreciate somebody looking at the Wayland implementation, any bikeshedding is welcome too.~~
~~I've successfully tried all implementations, currently stuck at trying to fix the Windows implementation deadlock.~~
`cargo run --example drag_window`
~~Blocked on https://github.com/Smithay/client-toolkit/pull/174.~~
~~Blocked on [`smithay-client-toolkit`](https://crates.io/crates/smithay-client-toolkit) releasing a new version.~~
~~Wayland implementation at #1854.~~
=> Add dragging window with cursor feature

CHANGELOG.md, Cargo.toml, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/observer.rs
Fixes #1850
This moves the ownership of the callback-closure to the `EventLoop`. The colusre is now contained within an `Rc` and the global handler only has a `Weak` reference to it, in order to ensure that the closure gets dropped with the `EventLoop`. Furthermore this catches panic unwinding, coming from the user callback to prevent it from unwinding into foreign code. The application is then requested to stop and the caught unwinding is resumed at a point where the callstack doesn't contain foreign code.
=> Fix for closure-captured values not being dropped on panic

CHANGELOG.md, Cargo.toml, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
Fixes #1520.
I'm still very naive to `mio`, but this worked for me.
I replaced [`mio-extras`](https://crates.io/crates/mio-extras) with [`mio-misc`](https://crates.io/crates/mio-misc) because it didn't support the newest [`mio`](https://crates.io/crates/mio) version.
=> Upgrade `mio` to 0.7

.github/workflows/publish.yml
Currently the publish workflow attempts to publish every time a change in the `Cargo.toml` is pushed to the `master`. The publish fails if the version already exists but the failure happens only after compiling winit, wasting compute time and sending a false "publish failed" notification to the maintainer who made the merge. I understand that it's not a "serious" problem but the fix is very simple, so I think it's worth applying.
Just tagging a few maintainers for a review:  @msiglreith, @vberger, @murarth
=> Only try publishing when a version tag is pushed

CHANGELOG.md, examples/mouse_wheel.rs, src/platform_impl/windows/event_loop.rs
=> Fix communication of fractional RI_MOUSE_WHEEL events (Windows)

CHANGELOG.md, src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/windows/window.rs, src/window.rs
I think this finishes the important platforms and we could actually merge the branch to master?
cc @murarth @Osspial
=> Add WindowBuilder::with_outer_position

CHANGELOG.md, src/platform_impl/macos/app_state.rs
We allow to have RunLoop running only on the main thread. Which means if
we call Window::request_redraw() from other the thread then we have to
wait until some other event arrives on the main thread. That situation
is even worse when we have ControlFlow set to the `Wait` mode then user
will not ever render anything.
The goal of this PR is a try to fix macOS-related part of the issue #1763 I was not sure if it is a good idea to wake up RunLoop directly from the AppState, so please correct me with the right place to add this logic if needed.
=> macOS: Wake up run loop immediately when request redraw is received

CHANGELOG.md, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/view.rs
Fixes #1837, gfx-rs/wgpu-rs#536, rust-windowing/glutin#1340, servo/webrender#1640
=> Mac: Redraw immediately to prevent shaking on window resize

CHANGELOG.md, src/platform_impl/macos/window.rs
- MacOS 10.14.6
`NSApplication.finishLaunching` is called internally `NSApplication.run`, and is generally not something user code should call - I couldn't find the reasoning behind this being there in the first place, git blame reveals c38110cac from 2014, so probably a piece of legacy code.
Removing this fixes creating new windows when you have assigned a main menu to the application.
=> Don't call NSApplication.finishLaunching on window creation

CHANGELOG.md, src/dpi.rs
Having issues where LogicalPosition<f32> has no Default.
=> Derive more things

src/platform_impl/macos/window.rs
Minor nit, as recommended by [the documentation](https://developer.apple.com/documentation/appkit/nswindow/1419366-makefirstresponder?language=objc).
This changes the point at which `becomeFirstResponder` (a notification we don't use) is emitted to later on when `makeKeyAndOrderFront`/`makeKeyWindow` is called, which I think is more correct behaviour.
- MacOS 10.14.6 Mojave
=> MacOS: Use `initialFirstResponder` instead of `makeFirstResponder`

.gitignore, CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/menu.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs
The activation policy could previously be specified through the window builder. This was incorrect because the activation policy is an application-wide property, not window-specific.
=> Require setting the activation policy on the event loop

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs
The changelog is not modified, because the default menu wasn't created in the previous release.
=> Allow preventing the creation of the default menu

CHANGELOG.md, Cargo.toml, README.md, src/dpi.rs
Implement conversions for [mint](https://docs.rs/mint) (math interoperability standard types).
- `impl {From, Into}<mint::Point2> for {Physical, Logical}Position`
- `impl {From, Into}<mint::Vector2> for {Physical, Logical}Size`
Some crates that already support mint: cgmath, euclid, nalgebra, glam, kurbo, vek
=> implement mint conversions

CHANGELOG.md, Cargo.toml, README.md
I can't push directly to the master, so it's a PR. This might mean that @francesca64, you will need to push the tag to trigger the publishing workflow. (It might also be easier if you make the commit yourself and just close this PR)
Closes #1926
=> Release 0.25.0

Cargo.toml, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/menu.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Ensures the pools are released even if we panic.
Also, we no longer directly depend on `scopeguard`, so that's nice.
- MacOS 10.14.6 Mojave
=> MacOS: Use objc's autoreleasepool instead of manually with NSAutoreleasePool

src/platform_impl/windows/event_loop.rs
I was looking around winit one day and I found this method with no documentation. Upon looking further into the topic of getting the main thread id on Windows, it is more complex than the few LOC with no documentation.
Therefore I decided to add the documentation so a random onlooker is not confused when they see this method in the future.
I think I got the general idea documented, ironing out grammar can be done before merging :)
I think this one is addressed to you @msiglreith since you are listed as the maintainer.
=> Document how `main_thread_id` for Windows works

CHANGELOG.md, src/platform_impl/android/mod.rs, src/window.rs
This implements `Window::request_redraw` on Android based on the feedback given here: https://github.com/rust-windowing/winit/pull/1822#issuecomment-760769960
Fixes #1723
=> Implement `Window::request_redraw` on Android

CHANGELOG.md, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs
#1845 for X11
I confirmed that `is_maximized` itself works using  `example/fullscreen.rs`.
=> add is_maximized for x11

CHANGELOG.md, src/platform_impl/macos/event_loop.rs
=> Drop the event callback before exiting on macOS

src/dpi.rs
Changed "If a window hasn't received a ScaleFactorChanged event, then its scale factor is 1.0." to "If a window hasn't received a ScaleFactorChanged event, then its scale factor is [[window.scale_factor()]]."
The checklist isn't highly relevant because this was a simple sentence change in src/dpi.rs.
- Closes #1825
=> changed description of window scale factor in Events

Cargo.toml, src/platform/windows.rs, src/platform_impl/macos/ffi.rs
- ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- ~~Created or updated an example program if it would help users understand this functionality~~
- ~~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~~
---
We don't really need to bring in all of `libc` when all we're using is `libc::c_void`, which is just an alias for `core::ffi::c_void` after `libc = "0.2.0"` anyway.
=> Remove libc dependency on non-linux platforms

CHANGELOG.md, src/platform_impl/macos/view.rs
Checking state.is_key_down is redundant, since we are handling keyDown.
Moreover, state.is_key_down can be affected by a previous repeated key's
keyUp.
=> macOS: Only check is_repeat to send ReceivedCharacter. Fixes #1488

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window.rs
As discussed in #1891, using window subclasses exclusively to handle window messages has some unexpected edge cases, such as denying us the ability to react to `WM_NCCREATE` and `WM_CREATE`.
Moving away from subclasses may potentially fix alacritty/alacritty#4069. @desmap, if you could check if PR fixes your issue, then that would be awesome.
I'm not entirely happy with the way I solved this as the window creation code assumes that it's ok to create `WindowData` (`SubclassInput`) *after* the window has been created, which is awkward when we also need to pass a pointer to said structure to the window procedure through `CreateWindowExW`. I recall seeing that some of this logic was *inside* the window procedure on a previous trip through the repo's git history, so I'm going to dig through …
=> Remove window subclassing

CHANGELOG.md, src/platform_impl/linux/wayland/seat/pointer/mod.rs
As per the X11 implementation https://github.com/rust-windowing/winit/blob/1c4d6e7613c3a3870cecb4cfa0eecc97409d45ff/src/platform_impl/linux/x11/util/cursor.rs#L84 the Wayland implementation should load cursors `hand2` and `hand1`, since some cursor themes such as Breeze do not ship an icon named `hand`. Without this change, Alacritty falls back to the default Adwaita hand icon when setting Breeze as the cursor theme, since Adwaita symlinks `hand` to `hand2`.
=> Load "hand2" and "hand1" cursor icons for Wayland CursorIcon::Hand

Cargo.toml, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs
This change is to enable to use IME.
Before:
https://user-images.githubusercontent.com/27967726/127104794-4469f128-565b-4b56-a5a5-5a327f89a5da.mov
After:
https://user-images.githubusercontent.com/27967726/127105174-c3b703be-68f8-4354-830c-05f8e178ce27.mov
=> Add composition event on macOS

README.md
- README.md updated to show android `ndk_glue`/`winit` version matching.
=> Adds Android winit<->ndk_glue version match table

src/platform_impl/windows/window.rs
Fixes https://github.com/rust-windowing/winit/issues/1980
The `visible` attribute was not correctly applied in case the decorations were disabled. Reordering to ensure that a `WM_NCCALCSIZE` (I think that's the desired event) is triggered due to size update. 
CHANGELOG entry omitted as the regression is not in any release.
=> Fix Window visibility regression

src/platform_impl/linux/wayland/seat/pointer/mod.rs
Fixes: #1988
The inability to set the cursor using any of the named cursor files
likely indicates an error in the system on which we are running.
WinitPointer::set_cursor also does not have any way of returning an
error so just log the error to assist users in diagnosing the problem.
=> On Wayland, log error for failure to set cursor

CHANGELOG.md, Cargo.toml, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/wayland/seat/keyboard/mod.rs, src/platform_impl/linux/wayland/seat/mod.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs
This commit also drops 'Theme' trait with its support types
in favor of 'FallbackFrame' meaning that winit will use some
predefined frame for the time being, since porting 'ConceptFrame'
will require adding font rendering librarires right into winit,
which is not desired.
=> Update smithay-client-toolkit to 'v0.15.0'

CHANGELOG.md, src/platform_impl/linux/x11/window.rs
This PR fixes the broke transparency feature on X11.
Note that for this [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md) said that this already worked, but it was code as TODO and only would work if someone provide a custom visual, which is not documented. This PR fixes that, allowing winit to find an appropriate visual for transparency.
This also fix [this issue](https://github.com/gfx-rs/wgpu/issues/687) in wgpu for X11 allowing to create transparent background(I just tried that, I didn't do extensive testing).
=> Fix transparency on X11

src/platform_impl/linux/x11/window.rs
So, after my last PR I realized of at small bug that can happen if we cannot find a visual for transparency. If that is the case the code anyway will attempt to create a `ColorMap` with `ffi::CopyFromParent` which even if I'm not sure what the result would be is not the intended behavior and I think that can possible cause problems.
=> Fix potential bug

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
Fixes #1962 
When disconnect the only monitor, scale factor is reset to 1.0. We need
to set it back when the monitor is reconnected.
We previously assume current window must be on an existing monitor, but
that's not true in case of reconnecting the only one monitor.
- Tested on X11, KDE, via alacritty. (Fixes https://github.com/alacritty/alacritty/issues/5213)
=> Emit ScaleFactorChanged event on monitor reconnect

Cargo.toml, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
I also fixed a couple of clippy lints in the files relevant to the bug, but some of them I was afraid to touch. As far as I could tell, mio-misc was causing the bug, so I removed it. It was hardly used, and easily replaced. I tested it against the example in #1984 and the leak is gone.
I didn't see many bug fixes in the Changelog, so I didn't add it. No api changes were made.
No user-facing changes.
Fixes #1984
=> Fix X11 memory leak and remove mio-misc

Cargo.toml, src/dpi.rs, src/event.rs, src/lib.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/device.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/window.rs
=> Clippy fixes

CHANGELOG.md, src/platform_impl/linux/x11/util/randr.rs
Some video drivers could set display metrics to odd values, which can result in
extra large scale factors (e.g. winit is sending 720 for 5k screen on nvidia
binary drivers), so let's just drop them to prevent clients from using them.
The value 20 was picked, because the DPR for 8k @ 5 inch is ~18.36.
This PR is more of a proposal. The original issue was here https://github.com/alacritty/alacritty/issues/3214 , as you can see in a log, DPR from winit is 718, which is literally insane. I see 2 options on how to fix such issues.
1 - Make winit compute DPI only if a randr value in use, otherwise return just 1 all the time. Qt is probably doing something similar IIRC
2 - Just try to ignore odd values (this PR is doing it).
The proposed `1` change is a breaking change, so I guess `2` option …
=> On X11, if RANDR based scale factor is higher than 20 reset it to 1

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml
While winit was always using dlopen for opening system libs, it
provides a way now to disable dlopen feature helping with linking
on some targets.
Fixes #2037.
=> On Wayland, add wayland-dlopen feature to use dlopen

CHANGELOG.md, Cargo.toml, README.md
Tested with a small sample application that it still runs with the updated ndk version.
This is breaking as users need to update their version of `ndk-glue` as well as it internally has a static global variable which should be unique across crates!
https://github.com/rust-windowing/winit/issues/1995
=> Android: Bump ndk/ndk-glue version

CHANGELOG.md, Cargo.toml, src/platform_impl/windows/event_loop.rs
Addresses #2005 
Temporarily increase the timer resolution for the wait operation. By default it's around 16ms which is too long for most realtime applications and leads to unpredictable results. A future enhancement in this direction could be allow the user to control it. Possible use case would be UI application with some animations running with minimal energy impact.
Reported by https://twitter.com/olson_dan/status/1428840173354160128?s=20
With the given change for the wgpu `water` example the framerate is much closer to the target of 16.6ms on my system.
Before
```
Avg frame time 28.707153ms
Avg frame time 28.356724ms
Avg frame time 28.303003ms
Avg frame time 28.835732ms
Avg frame time 29.122643ms
Avg frame time 27.729534ms
```
After
```
Avg frame time 16.845396ms
Avg frame time …
```
=> Windows: Increase wait timer resolution

CHANGELOG.md, src/platform_impl/macos/app_state.rs
Closes https://github.com/rust-windowing/winit/issues/1779
Previously all native dialogs, such as [rfd](https://github.com/PolyMeilex/rfd), would cause the event loop (event_loop.run) to freeze.
All code by @PolyMeilex (at https://github.com/PolyMeilex/winit/commit/e4a0a15fc42496a03b76a633ea9d123209751f39)
I just opened the PR as @PolyMeilex says he doesn't have the time for it right now.
=> macOS: Fix native file dialogs freezing the event loop

CHANGELOG.md, src/platform_impl/linux/wayland/window/mod.rs
fixes #2064 
Looking at the `WAYLAND_DEBUG` output of `alacritty` shows that the initial `xdg_toplevel.configure` has a size of `1,1` set
on `kwin_wayland`. After setting the `decoration_mode` another `configure` is issued by the server and has the `min_size`
of the client set as the size, which is `2,1` in case of `alacritty`. The debug output of [toplevel_decoration.c](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/3a685b10b66b9da6e0baa3ad48409db14e76eced/examples/toplevel-decoration.c) and `kwrite` indicates that the size of the second `configure` has the size of the buffer that got attached/commited
after the first `configure`. Both clients commit the surface state after changing the decoration mode.
For reference see: …
=> On Wayland commit the window surface after setting the decoration mode

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs
Fixes https://github.com/rust-windowing/winit/issues/2060
Doing all the initialization steps inside `WM_NCCREATE` doesn't seem to work out (see issue) - aspects affecting the client area like size appear to require handling inside `WM_CREATE`.
=> Windows: Split window initialization across NCCREATE and CREATE

CHANGELOG.md, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Fixes #1195.
Following on from @cixel's work in #1326, this PR aims to fix the issue where the menu bar doesn't show up when using the borderless fullscreen mode on macOS.
#2046 was opened recently but following some discussion @francesca64 proposed reactivating this branch in a new PR.
There are a couple of edge cases that need to be manually tested, [e.g. this comment](https://github.com/rust-windowing/winit/pull/1326#issuecomment-761823885)
> Running `cargo run --example multithreaded`:
> 1. Press `esc` twice to close the first two windows
> 2. Press `alt`+`F`. The window goes into exclusive fullscreen
> 3. Press `F`. The window seems to change to borderless fullscreen which is indicated by the fact that I can use `cmd`+`tab` to switch between applications. But now the menu bar isn't …
=> Show the menu bar in borderless fullscreen on macOS

CHANGELOG.md, Cargo.toml, README.md
It's been tested on an android 12 device. The test application is [here](https://github.com/adrien-ben/vulkan-triangle-rs/tree/android)
=> bump ndk dependencies to 0.5

CHANGELOG.md, Cargo.toml, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs
Ready for when https://github.com/rust-windowing/raw-window-handle/pull/70 gets merged, and a stable version published.
=> Update `raw-window-handle` to `0.4.1`

CHANGELOG.md, Cargo.toml, README.md
Starting a new release, if someone aware of what else to include add to a blocked list.
Blocked by:
=> Release 0.26.0

CHANGELOG.md
See https://github.com/rust-windowing/winit/issues/2085. This should be changed in the [release "announcement"](https://github.com/rust-windowing/winit/releases/tag/v0.26.0) as well.
=> Add note in changelog about `cargo update` to the `raw-window-handle` update

examples/cursor.rs, examples/fullscreen.rs, examples/multithreaded.rs, examples/multiwindow.rs, examples/set_ime_position.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/inner.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/format.rs, src/platform_impl/linux/x11/util/geometry.rs, src/platform_impl/linux/x11/util/icon.rs, src/platform_impl/linux/x11/util/keys.rs, src/platform_impl/linux/x11/util/modifiers.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/util/window_property.rs, src/platform_impl/linux/x11/util/wm.rs, src/platform_impl/linux/x11/window.rs
There are still some lints left, but this should be all the non-controversial ones. The rest can be ignored or fixed in a separate PR.
I decided to just ignore new_without_default as it seems really aggressive to me. Happy to just remove the ignore and leave the decision for a follow up PR.
Make sure to review the diff with whitespace disabled to keep the match changes readable.
=> Fix clippy warnings

src/platform/unix.rs, src/window.rs
This API is easy to understand once you've seen an example, but figuring it out from just the type signature is really difficult.
So every method with args of `<S: Into<Size>>` or `<P: Into<Position>>` should have an example demonstrating how to use it.
I considered putting this documentation just once in `Size` or `Position`.
But that would have been strange as we would be documenting how to instantiate a different type on a types documentation page.
And it would be harder to find for the user.
=> Provide examples for all window position/size setters

CHANGELOG.md, Cargo.toml, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs
Fixes #2097
This reverts commit 8afeb910bdbdcaeefdcea948098c3379de3f433f.
Reverting because this change made Pinyin input unusable
(only latin characters showed even after selecting the
desired Chinese character)
Furthermore the change itself was pretty much a hack. The change allowed an application to show the preedit text. However winit doesn't yet have an API for this so the implementation simply sent `ReceivedCharacter` events for each character of the preedit text and whenever the text changed it sent 'u\{7f}' (aka DELETE) characters for each UTF32 code unit of the previous preedit text, then sent each character of the new preedit text.
For all these reasons, I believe a revert is warranted.
=> Revert "Add composition event on macOS (#1979)"

CHANGELOG.md, src/platform_impl/windows/window.rs
Maybe the transparent setting in WM_NCCREATE on Windows 11 will cause a block when callling DwmEnableBlureBehindWindow and will crash. Puts them into WM_CREATE and it works. #2082 
I have not found any details about  the behavior change on Windows 11. Perhaps it's could be a Win11 bug.
I have no win8 or earlier enviroment so I can't test them on these platforms.
=> Fix transparent window crash on Windows 11

CHANGELOG.md, src/platform_impl/macos/ffi.rs
See previous issue: https://github.com/rust-windowing/winit/pull/1626.
The `cocoa` crate links to AppKit, which made the symbol `CGDisplayCreateUUIDFromDisplayID` from ApplicationServices/ColorSync (which AppKit uses internally) available to us (on macOS 10.8 to 10.13).
However, this does not work on macOS 10.7 (where AppKit does not link to ColorSync internally). Instead of relying on this, we should just link to ApplicationServices directly.
Also, lately something changed in rustc so that the linker's macOS version is 10.7, see https://github.com/rust-lang/rust/issues/91372, which is why the nightly builds were failing.
=> Fix `CGDisplayCreateUUIDFromDisplayID` linking (again)

.github/workflows/ci.yml
The repository is configured such that specific checks are required to pass before merging; since CI doesn't run on PRs that don't change code, they can't be merged without administrator intervention.
Currently affecting https://github.com/rust-windowing/winit/pull/2126, and has affected many others in the past.
Also, while this definition is currently correct, we might in the future change something so that changes to other files (like markdown files) really should be run through CI.
=> Make CI run on changes to non-code files as well

CHANGELOG.md, Cargo.toml, README.md
v0.26.0 had a regression that made the Pinyin IME input unusable on macOS. See #2097
#2119 fixed that regression, and I think it's a good idea to publish a new release with the fix quickly.
Blocked on:
=> Release 0.26.1

.github/PULL_REQUEST_TEMPLATE.md
The more entries there are, the more likely people are to start just ignoring them all.
By removing the ones already covered by CI then the remaining entries are more likely to be followed.
=> Remove entries from PULL_REQUEST_TEMPLATE.md that are now covered by CI

src/platform_impl/ios/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs
Change a few types for more correct behaviour (e.g. using `bool` may be undefined behaviour, one should use `BOOL`).
The only critical thing here is the stuff in `unmark_text` (introduced in #2119), that part is certainly undefined behaviour, and will probably cause problems somewhere down the line.
=> Fix some invalid `msg_send!` usage

src/platform/macos.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/util/cursor.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Resolves all mac os specific warnings/errors given by `cargo +nightly clippy --target=x86_64-apple-darwin`
=> Clippy fixes macos platform

.gitattributes, CHANGELOG.md, CONTRIBUTING.md
Fixes https://github.com/rust-windowing/winit/issues/2135.
I didn't really feel this warranted an addition to the checklist in `PULL_REQUEST_TEMPLATE.md`, though we could do that as well?
=> Update changelog guidelines to prevent conflicts from blocking PRs

CHANGELOG.md, Cargo.toml, README.md
=> Bump versions of ndk to 0.6, ndk-sys to 0.3, ndk-glue to 0.6

CHANGELOG.md, src/platform_impl/linux/wayland/seat/pointer/handlers.rs
This behavior is consistent with at least the X11 backend, and is implied by the documentation:
> This represents raw, unfiltered physical motion. Not to be confused with WindowEvent::CursorMoved.
=> Wayland: Report unaccelerated mouse deltas in `DeviceEvent::MouseMotion`

CHANGELOG.md, examples/custom_events.rs, src/event_loop.rs, src/platform/macos.rs, src/platform/unix.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/mod.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/window.rs
The beginning of https://github.com/rust-windowing/winit/issues/2120.
=> Add `EventLoopBuilder`

Cargo.toml
Update:
- `image` from 0.23 to 0.24
- `simple_logger` from 1.9 to 2.1
Fixes an annoying issue on macOS where `simple_logger` sometimes fails to initialize, see https://github.com/borntyping/rust-simple_logger/issues/52.
=> Bump `dev-dependencies`

src/platform_impl/windows/window.rs
- ~~Tested on all platforms changed~~
- ~~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~~
- ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- ~~Created or updated an example program if it would help users understand this functionality~~
- ~~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~~
The nightly builds on our CI started spitting out warnings for this today.
=> Fix unsafe_op_in_unsafe_fn warning on nightly

src/platform_impl/linux/wayland/window/mod.rs, src/window.rs
This was fixed in #1848.
fix typo in wayland implementation
=> Update doc comment to reflect that `is_maximized` is implemented on X11/Wayland

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs
On Wayland window size and scaling are double buffered, so winit should
send redraw requested for a client on the next frame as well.
=> On Wayland, fix resize not propagating properly

CHANGELOG.md, Cargo.toml, src/platform/windows.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/definitions.rs, src/platform_impl/windows/dpi.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/raw_input.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Change from using the unofficial winapi bindings, to using the official windows bindings from Microsoft.
=> Adopt windows-sys

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs
If you try to use `EventLoop::run_return` API in a way that you do on
demand polling of events it won't actually poll, since in such strategy
the `ControlFlow::Exit` is sent right before Wayland backend starts to
poll.
This was observed with smithay compositor Anvil which was doing this
particular thing leading to GNOME thinking that app isn't responding.
=> On Wayland, fix consecutive run_return not polling

src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/device.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/proxy.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/drop_handler.rs
Seeing `Id` in the macOS backend has confused me _many_ times (especially because `Id` has another meaning in Objective-C), this PR is just a generalization of that problem (of structs not being named what they're exported as).
=> Rename internal structs for consistency

src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs
Resolves all windows specific warnings/errors given by `cargo +nightly clippy --target=x86_64-pc-windows-msvc`
~~The `0 as UINT` -> `0_u32` changes are the only possibly concerning change, but I think the change makes sense as its better to directly use a literal than to have to convert the type.
Rust will perform proper type checking when calling functions that take UINT so we would still catch type issues at compile time.~~
=> Clippy fixes for windows platform

CHANGELOG.md, src/platform_impl/windows/window.rs
This attempts to fix issue that looks like a messaging race of window size/position changes on window creation when using `WindowBuilder::with_fullscreen` on Windows. 
Believe it is from most using `SWP_ASYNCWINDOWPOS` but some internal one such as `ITaskbarList2::MarkFullscreenWindow` not using it causing WM_SIZE (and likely more messages) often arriving in wrong order and making the fullscreen window that was created getting the wrong intermediate size and be stuck with that. 
This slightly rearranges the Windows fullscreen window size/pos setting to be in the absolute end, and avoid redundantly setting inner size or potential maximize state that also generated window resizing.
In local testing on Windows 11 machine this have been working solid both with the `fullscreen` example and …
=> Fix fullscreen window messaging race on Windows

CHANGELOG.md, src/platform_impl/windows/window.rs
The flag is not required for OpenGL and comes with several limitations when used with other style flags.
Tested with `glutin` and `raw-gl-context` against sample applications (inlc multi window setups with shared contexts) on Windows 10. Didn't affect context handling or rendering in these scenarios.
Fixes https://github.com/rust-windowing/winit/issues/1893
=> Windows: Remove owned DC context per window

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
The scale factor being sent when the only monitor is disconnected and
reconnected is hard coded to 1.0. That may work by chance, if that's the
scale factor in use currently, but it does not work in the general case.
As a result, clients may end up with wrongly scaled or laid out window
contents after reconnect, as was reported over in
https://github.com/alacritty/alacritty/issues/5703, for example.
The problem was introduced by change 125ee0b, which caused an additional
ScaleFactorChanged event to be sent on monitor reconnect, but got the
scale factor wrong when the only monitor is disconnected and
reconnected.
This change fixes the problem by using the current monitor's scale
factor in this case. The event is still being sent as intended by
125ee0b.
Closes: #2123
=> Fix scale factor calculation when the only monitor is reconnected

CHANGELOG.md, src/platform_impl/android/mod.rs
When working on https://github.com/torokati44/ruffle-android, I discovered that all keypress events arrive with their scancode set to `0`, and their keycode set to `None`. Which I found less than useful.
The [NDK docs for AKeyEvent_getScanCode](https://developer.android.com/ndk/reference/group/input#akeyevent_getscancode) mention that "These values are not reliable and vary from device to device.".
So I guess always setting them to `0` is acceptable from their end.
Tested this on Android 12, with a keyboard connected to my computer, through wired `adb` and https://github.com/Genymobile/scrcpy/, and it seemed to work fine.
AFAICT This fixes #1867.
- Only Android is affected, and I am testing on it.
- I have not found any existing documentation that would have to be updated due to this …
=> android: Add mapping from NDK Keycode to VirtualKeyCode

CHANGELOG.md, src/platform/windows.rs, src/platform_impl/windows/definitions.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs
=> feat(Windows): add skip taskbar methods

src/platform_impl/linux/wayland/window/mod.rs, src/window.rs
This commit brings `is_resizable` and `is_decorated`. Since the client
is responsible for both of them, they could be tracked without deep
syncing with server.
=> Add `is_resizable` and `is_decorated` on Wayland

src/platform_impl/linux/wayland/window/mod.rs
The commit without buffer attached should be done after setting all
top level size/application related properties. While c4df7ad7a added
commit after setting decorations, it accounted just for decorations,
however we should account for the min/max size and other attributes.
=> On Wayland commit after setting all startup props

CHANGELOG.md, examples/control_flow.rs, examples/cursor.rs, examples/cursor_grab.rs, examples/custom_events.rs, examples/drag_window.rs, examples/fullscreen.rs, examples/handling_close.rs, examples/min_max_size.rs, examples/minimize.rs, examples/mouse_wheel.rs, examples/multithreaded.rs, examples/multiwindow.rs, examples/request_redraw.rs, examples/request_redraw_threaded.rs, examples/resizable.rs, examples/set_ime_position.rs, examples/timer.rs, examples/transparent.rs, examples/web.rs, examples/window.rs, examples/window_debug.rs, examples/window_icon.rs, examples/window_run_return.rs, src/event_loop.rs, src/lib.rs, src/window.rs
Bare-bones `winit` applications must import many different types from `winit`... this PR reduces that by adding methods so `ControlFlow` can be updated without naming its type, hopefully resulting in minor simplifications to the examples.
**(I've only tested on Windows, but I've run all examples)**
**(not applicable)**
=> Add methods to set ControlFlow

Cargo.toml
SCTK versions before 15.4 were leaking pointers when window got closed.
So the more windows you've got the pointers you'll keep around.
Fixes #2248.
=> Force SCTK version to prevent pointer leaking

CHANGELOG.md, src/platform_impl/ios/app_state.rs
For all platforms other than iOS, `RedrawEventsCleared` is sent even if there are no redraw events. This change makes iOS consistent with the other platforms.
This solves a bug on iOS where Bevy relies on this event in https://github.com/bevyengine/bevy/pull/3974
=> Always send RedrawEventsCleared

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/ime.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
This PR will add composition event support.
Related: #1497
- IME events for Windows
- Window::set_ime_allowed() for Windows
- **Breaking:** Hide OS-drawn composing text for Windows (same as the other platforms)
Tested on `ime` example (feel free to comment if you try this PR):
- Microsoft IME - Japanese (on Windows 10 19044.1620)
- Google Japanese Input - Japanese (on Windows 10 19044.1620)
- ATOK - Japanese (on Windows 10 19044.1620)
Tested on `ime` example but I am not native
- Microsoft IME - Korean (on Windows 10 19044.1620)
- Microsoft IME Pinyin - Chinese (Simplified, China) (on Windows 10 19044.1620)
- (Microsoft) Vietnamse Telex - Vietnamse (on Windows 10 19044.1620)
----
=> Windows: Add composition event support

CHANGELOG.md, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs
Both APIs are used to set application name. This commit unifies the API
between Wayland and X11, so downstream applications can remove platform
specific code here.
Fixes #1739.
cc @chrisduerr
=> Unify `with_app_id` and `with_class` methods

CHANGELOG.md, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/window.rs, src/window.rs
This makes X11 and Wayland follow Windows and macOS, so the size of the
window could be set even though it has resizable attribute set to false.
Fixes #2242.
=> Unify behavior of `resizable` across platforms

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
=> Fix assigning the wrong monitor when receiving Windows move events

src/platform_impl/windows/monitor.rs, src/platform_impl/windows/raw_input.rs, src/platform_impl/windows/util.rs
- This change fixes an error introduced in b222dde83504e402d51fa40a3c78dee40cb2ee5f, which hasn't been included in a release yet
=> Fix embedded NULs in C wide strings returned from Windows API
