.travis.yml
Cargo.toml
README.md
examples/fullscreen.rs
examples/grabbing.rs
src/api/android/ffi.rs
src/api/android/mod.rs
src/api/cocoa/mod.rs
src/api/ios/mod.rs
src/api/wayland/events.rs
src/api/win32/callback.rs
src/api/x11/events.rs
src/api/x11/input.rs
src/api/x11/window.rs
src/events.rs
src/lib.rs
src/os/macos.rs
src/platform/emscripten/mod.rs
src/platform/ios/mod.rs
src/platform/linux/api_dispatch.rs
src/platform/windows/mod.rs
src/window.rs

For https://github.com/tomaka/glutin/issues/813

Merge latest glutin

---

Cargo.toml

lazy_static: 02.0->0.2.2
shared_library: 0.1.0->0.1.5

Dependent crates version updates

---

Cargo.toml
src/api/x11/window.rs
src/os/unix.rs
src/platform/linux/api_dispatch.rs
src/platform/linux/mod.rs

My attempt at solving tomaka/glutin#834

Allow creation of X11 window with specified visual and screen

---

Cargo.toml

Reverting https://github.com/servo/cocoa-rs/pull/150

Pin down to cocoa 0.5.2

---

Cargo.toml

Update cgl to v0.2

---

.travis.yml
Cargo.toml

Published changes include #157.

Publish 0.6.3 with recent non-breaking macOS fixes

---

src/platform/linux/x11/window.rs

[ICCCM 4.1.2.5](https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS) states that:
> This property must be present when the window leaves the Withdrawn state and may be changed only while the window is in the Withdrawn state.
Previously, we would first map the window, and then set these properties, causing sadness for window managers (#167, tomaka/glutin#879). This patch changes that by setting the class and name attributes immediately after the window is created, and before it is mapped.
Fixes #167.

Set WM_CLASS and WM_NAME before mapping window

---

src/lib.rs
src/window.rs

The documentation incorrectly mentions some old stuff. I tried to fix it.

Fixed some obsolete comments and strings

---

src/lib.rs

Derive Clone on winit::EventsLoop wrapper

---

src/platform/linux/wayland/event_loop.rs

This is important for any code that re-enters `run_forever` after some previous interrupt.
cc @vberger 
Edit: The CI error seems to be an unrelated appveyor windows bug.

wayland: Reset the `interrupted` flag before breaking from run_forever

---

README.md

Update the README for the version

---

src/platform/linux/x11/mod.rs

For international users, a buffer size of 16 bytes might be too small. Take Chinese input methods as an example, people usually input a phrase instead of a single character at a time. A Chinese character is approximately 3 bytes in utf8, which means a buffer of 16 could be easily overflowed: "測試輸入中文" (test making Chinese input) is a 18-byte string. I pick a new size of 512 as an attempt since urxvt uses it as the buffer size.
Also added input context focus and unfocus actions to respective events.

XIM: Increase the string lookup buffer size and add IC focus/unfocus.

---

Cargo.toml
src/platform/windows/window.rs

Reimplement platform_window on win32

---

src/platform/linux/wayland/event_loop.rs

Fix wayland vertical scroll sign

---

src/platform/linux/x11/mod.rs

When X's evdev input module is configured to emulate scroll events (as used with e.g. trackpoints), it generates non-emulated scroll button presses and does not generate motion events. This is contrary to the
behavior of all other hardware I've tested, and contrary to the behavior of libinput, but nonetheless should be supported.

Fix evdev emulated scroll events

---

src/platform/windows/event.rs

Fixes: https://github.com/tomaka/winit/issues/74

Add missing windows virtual key codes

---

Cargo.toml

Bump version to 0.7.6
Closes #264

Release 0.7.6

---

src/events.rs
src/lib.rs

This PR completes missing documentation for notable top-level items.

Complete documentation for top-level items

---

CHANGELOG.md
Cargo.toml
src/platform/linux/wayland/keyboard.rs

Mirror x11 ISO_LEFT_TAB detection on wayland and release version 0.8.3

---

src/events.rs

I had some trouble figuring out how to use DeviceEvent::Motion to rotate a first person camera. Hopefully I found a snippet on gitter. I've decided to improve this part of the documentation to help newbies like me. 😃
I might also add an example about moving the mouse to change the window color (in glutin then). What do you think about it ?

Improve the documentation of DeviceEvent::Motion

---

CHANGELOG.md
src/platform/linux/wayland/event_loop.rs
src/platform/linux/wayland/mod.rs
src/platform/linux/wayland/pointer.rs
src/platform/linux/wayland/touch.rs

The implementation was actually pretty straightforward.
Tested on my laptop (which has a touchscreen) with weston.

Wayland: implement touch events

---

src/platform/windows/events_loop.rs

Fixes https://github.com/tomaka/winit/issues/350
Tested and works.  Event emission and ordering is correct.

Emit delete character on Windows

---

CHANGELOG.md
src/platform/emscripten/ffi.rs
src/platform/emscripten/mod.rs

Impl `ModifiersState`, `MouseMove`, `MouseInput`, `MouseMotion` for emscripten backend.

Emscripten

---

CHANGELOG.md
Cargo.toml

Not sure on your version increment procedures, but I took a stab at it.

bump for v0.9.0

---

src/platform/linux/x11/window.rs

Currently on X11 setting cursor and cursor state resets the cursor to default one. Also when cursor is hidden, setting cursor always shows it.
*Now:* default cursor. *Expected:* crosshair cursor.
```rust
window.set_cursor(MouseCursor::Crosshair);
window.set_cursor_state(CursorState::Hide).unwrap();
window.set_cursor_state(CursorState::Normal).unwrap();
```
*Now:* default cursor. *Expected:* crosshair cursor.
```rust
window.set_cursor_state(CursorState::Hide).unwrap();
window.set_cursor(MouseCursor::Crosshair);
window.set_cursor_state(CursorState::Normal).unwrap();
```
*Now:* crosshair cursor. *Expected:* no cursor.
```rust
window.set_cursor_state(CursorState::Hide).unwrap();
window.set_cursor(MouseCursor::Crosshair);
```
This pull request implements my expected behavior shown here. Do you …

x11: Remember cursor after changing cursor state

---

CHANGELOG.md
Cargo.toml

Can you merge and update crates.io?

Version 0.10.1

---

CHANGELOG.md
Cargo.toml

ref #406 
Also fixed some formatting/duplication issues that slipped into the changelog.

Version 0.11.1

---

CHANGELOG.md
Cargo.toml
src/platform/android/mod.rs

Depends on https://github.com/tomaka/winit/pull/417

Version bump

---

src/platform/windows/window.rs

[Windows] Avoid destroying the window twice

---

CHANGELOG.md
Cargo.toml

Publish 0.11.3

---

CHANGELOG.md
src/platform/macos/window.rs

fixed !decorations case and refactored logic to be a little easier to
read

macos platform attributes regression

---

Cargo.toml

Update wayland-client to version 0.20.4

---

CHANGELOG.md
Cargo.toml
README.md

I want to get #502 in first, but after that, I feel like we're ready for another release. The CHANGELOG section is somehow even longer than last time.
If anyone has any more regressions they'd like to find, now would be a good time.

Release winit 0.14.0

---

Cargo.toml
src/icon.rs

these functions should be more visible now.

compile with icon_loading feature on docs.rs

---

CHANGELOG.md
src/platform/linux/x11/mod.rs

X11: Fix scroll wheel delta on i3/etc.

---

.gitignore
CHANGELOG.md
src/os/macos.rs
src/os/unix.rs
src/platform/linux/mod.rs
src/platform/macos/window.rs

macOS: Implement with_resize_increments

---

CHANGELOG.md
src/platform/windows/event.rs
src/platform/windows/events_loop.rs

Fixes #524 
Those looking for a detailed explanation of the problem can read this enjoyable blog post: https://blog.molecular-matters.com/2011/09/05/properly-handling-keyboard-input/

Windows: Fix detection of Pause and Scroll keys

---

src/platform/macos/view.rs

* Emit `ReceivedCharacter` for key repeats
* Enter emits `\r` instead of `\n`
I also left some commented-out `println!` in, since it's a pain adding those each time just to be able to understand what's happening.

macOS: Fix keyboard regressions

---

src/platform/linux/x11/monitor.rs

Fixes #507
Apparently I understand X11 esoterica better than I understand iterators.

X11: Fix primary monitor fallback regression

---

.github/PULL_REQUEST_TEMPLATE.md

I figured this could be useful for making sure contributors are aware of what changes they have to make.

Added a GitHub PULL_REQUEST_TEMPLATE

---

CHANGELOG.md
src/platform/linux/mod.rs
src/platform/linux/x11/ime/input_method.rs

Fixes #458 
Fixes amethyst/amethyst#707
Fixes jwilm/alacritty#1344

X11: Fix super fun race conditions

---

CHANGELOG.md
src/platform/macos/events_loop.rs
src/platform/macos/view.rs

macOS: Only detect clicks+motion within client area

---

Cargo.toml
src/lib.rs
src/platform/windows/window.rs

Update to winapi 0.3.5

---

CHANGELOG.md
examples/monitor_list.rs
src/platform/android/mod.rs
src/platform/emscripten/mod.rs
src/platform/ios/mod.rs
src/platform/linux/mod.rs
src/platform/linux/wayland/event_loop.rs
src/platform/linux/wayland/window.rs
src/platform/linux/x11/window.rs
src/platform/macos/monitor.rs
src/platform/windows/monitor.rs
src/window.rs

Fixes #555
@vberger did I do this correctly on Wayland?

Mirror monitor list methods on Window

---

CHANGELOG.md
Cargo.toml
README.md

This release is a bit overdue, but on the bright side, that means I've been using it locally for quite a while.
I've got some cool stuff planned for 0.17.0, and then I hope to get #459 done for 0.18.0.

Release winit 0.16.0

---

src/dpi.rs

Just a tiny doc change.  It makes my pedant reflexes tingle.

Define "DPI" in docs.

---

.gitignore
CHANGELOG.md
Cargo.toml
src/lib.rs
src/platform/linux/x11/mod.rs
src/platform/linux/x11/monitor.rs
src/platform/linux/x11/util/geometry.rs
src/platform/linux/x11/util/input.rs
src/platform/linux/x11/util/randr.rs
src/platform/linux/x11/window.rs
src/platform/windows/monitor.rs
src/platform/windows/util.rs
src/platform/windows/window.rs

X11+Windows: Guess initial DPI factor

---

CHANGELOG.md
src/platform/linux/x11/util/format.rs

X11: Fix compilation when c_char==c_uchar

---

CHANGELOG.md
Cargo.toml

Release winit 0.16.1

---

CHANGELOG.md
src/platform/linux/x11/window.rs
src/platform/windows/window.rs

Remove incorrect unreachable usage when guessing DPI factor

---

Cargo.toml
src/platform/ios/ffi.rs
src/platform/ios/mod.rs
src/platform/macos/events_loop.rs
src/platform/macos/ffi.rs
src/platform/macos/util.rs
src/platform/macos/view.rs
src/platform/macos/window.rs

Use class macro

---

Cargo.toml

A few fixes, improvements and decoration changes

Update wayland-client and client-toolkit

---

CHANGELOG.md
Cargo.toml

version 0.17.2

---

CHANGELOG.md
Cargo.toml
examples/window_icon.rs
src/icon.rs

Tested on x11/kde and windows.
This should be merged before the release of 0.18.

update to image 0.20

---

CHANGELOG.md
src/os/macos.rs
src/platform/macos/window.rs

Support requesting user attention on macOS

---

.travis.yml

travis: freeze dependencies that silently broke 1.24.1 compat

---

.travis.yml
CHANGELOG.md
README.md
appveyor.yml

Increase MSRV to 1.28.0

---

CHANGELOG.md
Cargo.toml
src/platform/linux/wayland/event_loop.rs
src/platform/linux/wayland/window.rs

This depends on https://github.com/smithay/client-toolkit/pull/46

Use smithay-client-toolkit's dpi handling.

---

CONTRIBUTING.md

I'm happy to be the long-term maintainer for macOS and Android now, since they're directly involved in my work.

Change francesca64 to maintainer for macOS and Android

---

README.md

Add info for live chat.

---

CHANGELOG.md
src/platform/linux/x11/util/randr.rs

Fix monitor width & height sanity check

---

README.md

README: Link to FEATURES.md and missing features wiki page

---

examples/timer.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/window.rs

Fix crash caused by WM_PAINT getting invoked at inopportune times.

---

README.md

Copied from https://github.com/rust-windowing/winit/blob/master/CONTRIBUTING.md
@Osspial @ZeGentzy

Direct new contributors to the eventloop-2.0 branch

---

src/platform_impl/macos/util/async.rs
src/platform_impl/macos/window.rs

Fixes #905. See https://github.com/rust-windowing/winit/issues/905#issuecomment-501990074. I'm not sure if this should be added to the changelog, or if this is specific to the `eventloop-2.0` changes, seeing as how the "multithreaded" example does not exist in the previous branch.

Fix thread-safety of `set_maximized` and `set_title` on macOS

---

src/lib.rs
src/platform_impl/macos/app_state.rs
src/platform_impl/macos/observer.rs
tests/send_objects.rs

As mentioned on https://github.com/rust-windowing/winit/pull/922#issuecomment-502852085. This should probably not be merged as-is.

Fix warnings

---

CHANGELOG.md
src/platform_impl/windows/window_state.rs

Implement fix described in #851

---

CHANGELOG.md
src/event.rs
src/platform_impl/android/mod.rs
src/platform_impl/ios/mod.rs
src/platform_impl/ios/view.rs
src/platform_impl/macos/app_delegate.rs

Change `Suspended(true/false)` => `Suspended/Resumed`

---

src/lib.rs

This PR significantly expands the example in `lib.rs` to showcase a suggested structure for both games and GUI applications. Should close #956.

Improve the example in lib.rs

---

examples/window_icon.rs

examples/window_icon.rs: De-duplicate code

---

src/platform_impl/linux/wayland/keyboard.rs
src/platform_impl/linux/wayland/pointer.rs
src/platform_impl/linux/wayland/window.rs

Fix warnings on Linux

---

CHANGELOG.md
Cargo.toml

See https://github.com/rust-windowing/winit/pull/896#issuecomment-507315521.

Remove Metal dependency on macOS

---

src/window.rs

Fixes warning introduced by #1013.

Fix warning

---

CHANGELOG.md
src/platform_impl/windows/window_state.rs

Fix transparent window with decorations

---

CHANGELOG.md
Cargo.toml
README.md

I'd like to get a couple of the latest bugfixes merged before releasing this but we should be able to merge this later today.

Release Alpha 2

---

examples/multithreaded.rs
examples/proxy.rs
examples/request_redraw.rs
examples/timer.rs
examples/window_run_return.rs
src/event_loop.rs
src/platform_impl/web/error.rs
src/platform_impl/web/monitor.rs
tests/send_objects.rs
tests/sync_object.rs

I have fixed some issues I found with the new `web` branch. It should compile now!

Fix `web` errors

---

src/event_loop.rs
src/platform_impl/ios/app_state.rs
src/platform_impl/ios/event_loop.rs
src/platform_impl/macos/event_loop.rs
src/platform_impl/macos/observer.rs

Minor doc changes

---

Cargo.toml
src/lib.rs
src/platform_impl/web/stdweb/event.rs
src/platform_impl/web/stdweb/mod.rs

Bump the stdweb version to 0.4.18

---

CHANGELOG.md
src/platform_impl/linux/x11/mod.rs

X11: Fix events not being reported promptly

---

.travis.yml

Always use stable rustfmt for CI.

---

CHANGELOG.md
examples/proxy.rs
src/event_loop.rs

Rename `new_user_event` to `with_user_event`

---

.travis.yml
CHANGELOG.md
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs

Fix armv7-apple-ios compile target

---

FEATURES.md

This PR simply updates winit's feature support on iOS.
Window decorations on iOS is interpreted to mean the status bar.

iOS: update feature table

---

Cargo.toml

Update parking_lot to 0.9 (#1097)

---

CHANGELOG.md
Cargo.toml
README.md

Waiting on #1105 but other than that this should be good to go.

Release 0.20.0 alpha 3

---

src/platform_impl/linux/wayland/event_loop.rs

When we are woken up from calloop(mio) wait, always attempt to
dispatch pending events even though calloop should have done it.
When using OpenGL, mesa shares our wayland socket, and also reads
from it, especially if vsync is enabled as it'll do blocking reads.
When doing so, it may enqueue events in the internal buffer of our
event queue.
As the socket has been read, mio will thus not notify it to calloop
as readable, and thus calloop will not know it needs to dispatch. In some
cases this can lead to some events being delivered much later than
they should. Combined with key repetition this can actually cause some
flooding of the event queue making this effect event worse.
Fixes #1148

wayland: dispatch pending events before NewEvents

---

CHANGELOG.md

Changelog entry for #1153

---

CHANGELOG.md
src/platform_impl/macos/util/async.rs
src/platform_impl/macos/window.rs

Fix freeze upon exiting exclusive fullscreen on macOS 10.15

---

CHANGELOG.md
src/platform_impl/windows/window.rs

Addresses https://github.com/rust-windowing/winit/pull/730#issuecomment-523683986

Fix window shrinking when transitioning from fullscreen window to normal window

---

src/platform_impl/web/event_loop/runner.rs
src/platform_impl/web/event_loop/window_target.rs
src/platform_impl/web/stdweb/canvas.rs
src/platform_impl/web/window.rs

Implement WindowID on the web platform

---

CHANGELOG.md
src/dpi.rs
src/monitor.rs
src/platform/mod.rs
src/platform/web.rs
src/platform_impl/web/monitor.rs
src/platform_impl/web/window.rs
src/window.rs

Indicate which methods have platform-specific web behavior

Update the documentation to reflect web support

---

CHANGELOG.md
src/platform/windows.rs
src/platform_impl/ios/view.rs
src/platform_impl/windows/window.rs

Implemented a HINSTANCE getter function for Windows

---

src/platform_impl/windows/window.rs

Implement with_outer_position on Windows

---

FEATURES.md

Update the feature matrix for wasm

---

src/platform_impl/web/stdweb/event.rs

Fix the event key code variable name

---

src/window.rs

- [ x] `cargo fmt` has been run on this branch

Link WindowBuilder documentation to corresponding Window methods (fixes #1070)

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/platform/ios/mod.rs
src/platform/linux/mod.rs
src/platform/linux/wayland/window.rs
src/platform/linux/x11/window.rs
src/platform/macos/window.rs
src/platform/windows/window.rs
src/window.rs

Add raw-window-handle support to Winit 0.19 and bump version

---

CHANGELOG.md
Cargo.toml
README.md

I'd like to get #1168, #1171, #1175, #1180, #1186, and possibly #1121 in before this releases, but most of those PRs seem close to getting merged so that shouldn't be too much of a hassle.

Release Alpha 4

---

CHANGELOG.md
src/platform_impl/ios/view.rs
src/platform_impl/macos/app_state.rs

macOS: fixes app termination

---

src/platform_impl/macos/event.rs
src/platform_impl/macos/monitor.rs
src/platform_impl/macos/view.rs

Miscellaneous small changes

---

CHANGELOG.md
src/platform_impl/linux/x11/event_processor.rs
src/platform_impl/linux/x11/monitor.rs
src/platform_impl/linux/x11/window.rs

X11: Fix misreporting DPI factor at startup

---

.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
appveyor.yml
src/dpi.rs
src/event.rs
src/event_loop.rs
src/lib.rs
src/monitor.rs
src/window.rs

Use paths for intra-doc links, and verify that links are valid in CI

---

src/dpi.rs
src/platform_impl/ios/view.rs

Dpi Type conversions into/from arrays

---

CHANGELOG.md
Cargo.toml

Release 0.20.0-alpha5

---

CHANGELOG.md
src/platform_impl/linux/x11/util/input.rs

Fix ModifiersChanged event on X11

---

src/dpi.rs
src/event.rs

Significantly rewrites the DPI docs to better suit Winit's current state. Feedback is appreciated - both for content and spelling/grammar. Please bring up any understandability regressions compared to the previous docs.

Update the DPI module docs

---

CHANGELOG.md
Cargo.toml
README.md

Submitting as a draft so that the DPI overhaul can get merged, but... yeah. Woo! Thank you *everybody* for the hard work you've all put into this.
It's been a long time coming.

Release 0.20.0

---

CHANGELOG.md
src/window.rs

impl Default for WindowBuilder

---

src/platform_impl/web/mod.rs

Remove TODOs from the web backend

---

CHANGELOG.md
src/platform/macos.rs

add hide_application on macos

---

src/platform_impl/windows/event_loop.rs

Fix building on Windows 7 and 8

---

.github/workflows/ci.yml

Remove armv7-apple-ios target from CI

---

src/platform_impl/linux/wayland/window.rs

Fix deadlock wayland.

---

CHANGELOG.md
Cargo.toml
README.md

Release 0.21.0

---

CHANGELOG.md
Cargo.toml
src/platform_impl/linux/wayland/event_loop.rs

Fixes #727.
Note: this commit will require SCTK 0.6.6+ to work, so `Cargo.toml` was also updated to reflect this change.

on Wayland, Add HiDPI cursor support

---

src/dpi.rs
src/platform_impl/android/mod.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/macos/window_delegate.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/window.rs
src/platform_impl/windows/window_state.rs

fixes https://github.com/rust-windowing/winit/issues/1457

rename dpi_factor to scale_factor where appropriate

---

CHANGELOG.md
Cargo.toml
FEATURES.md
src/platform/web.rs
src/platform_impl/web/event_loop/window_target.rs
src/platform_impl/web/stdweb/canvas.rs
src/platform_impl/web/stdweb/mod.rs
src/platform_impl/web/web_sys/canvas.rs
src/platform_impl/web/web_sys/mod.rs

Maybe we don't want to make this target specific and just implement it for the other OS's too?

Implement ThemeChanged for web target.

---

CHANGELOG.md
src/platform_impl/linux/wayland/event_loop.rs
src/platform_impl/linux/wayland/window.rs

On Wayland, Hide CSD for fullscreen windows

---

.github/workflows/ci.yml
.github/workflows/publish.yml

* Replaces `actions/checkout@v1` with `actions/checkout@v2` to get a bug fix

Fix GitHub Actions

---

Cargo.toml
examples/window_icon.rs

Also makes use of a few ergonomics improvements that were introduced or
optimized in the more recent version.

Update image to 0.23

---

CHANGELOG.md
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/window_state.rs

windows: ignore spurious mouse move messages

---

FEATURES.md

Obviously, no testing is required.

Fixed a couple of typos in repo description

---

CHANGELOG.md
Cargo.toml
README.md

It's been a bit since the last release and there have been a good amount of bugfixes since then. I'd like to merge this within the next day or so.

Release 0.22.2

---

CHANGELOG.md
src/platform_impl/linux/wayland/event_loop.rs
src/platform_impl/linux/wayland/window.rs

Fix deadlock on calling set_inner_size in event_loop on Wayland

---

CHANGELOG.md
src/platform/desktop.rs
src/platform_impl/android/mod.rs
src/platform_impl/windows/event_loop/runner.rs

Android run return

---

CHANGELOG.md
src/platform/macos.rs
src/platform_impl/macos/window.rs

for https://github.com/rust-windowing/winit/issues/1635
I don't have much experience in winit, but this problem seem not difficult

[macos] add NSWindow.hasShadow  support

---

CHANGELOG.md
Cargo.toml

Update macOS dependencies

---

CHANGELOG.md
Cargo.toml
README.md

Android: bump ndk versions

---

CHANGELOG.md
src/platform_impl/web/event_loop/runner.rs
src/platform_impl/web/window.rs

web: Emit WindowEvent::Resized on Window::set_inner_size

---

Cargo.toml

- [N/A] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [N/A] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [N/A] Created or updated an example program if it would help users understand this functionality
- [N/A] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

Bump console_log from 0.1 to 0.2

---

CHANGELOG.md
src/platform_impl/windows/event_loop.rs

[Windows] Fix use after free during window destruction

---

src/platform_impl/android/mod.rs
src/window.rs

Looking to resolve #1588. I'm not 100% on the language used so let me know what you think. Always happy to make changes if needed.

Issue 1588

---

examples/window_icon.rs

fix depecrecated call to image::into_rgba

---

CHANGELOG.md
src/platform_impl/macos/app_state.rs
src/platform_impl/macos/util/async.rs
src/platform_impl/macos/window.rs

Fix seg-fault when using without a window

---

src/dpi.rs

Correct the false documentation about macOS dpi

---

CHANGELOG.md
src/dpi.rs

Don't know how this one slipped through, but it caused some confusion on the Rust gamedev discord.
---

Fix incorrect changelog entry for #1524

---

HALL_OF_CHAMPIONS.md

I tried to do everyone justice by using lots of flowery adverbs.

Update Hall of Champions 

---

CHANGELOG.md
Cargo.toml
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/env.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/wayland/window/shim.rs
src/window.rs

This commit implements 'request_user_attention' on Wayland with
new 'xdg_activation_v1' protocol.

On Wayland, implement 'request_user_attention'

---

CHANGELOG.md
src/platform_impl/linux/x11/mod.rs

Handle EINTR on X11

---

CHANGELOG.md
Cargo.toml

Update `mio` to 0.8

---

README.md

- ~~Tested on all platforms changed~~
- ~~Compilation warnings were addressed~~
- ~~`cargo fmt` has been run on this branch~~
- ~~`cargo doc` builds successfully~~
- ~~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~~
- ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- ~~Created or updated an example program if it would help users understand this functionality~~
- ~~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~~
See #1966

Update contact links

---

src/platform_impl/macos/app_delegate.rs
src/platform_impl/macos/mod.rs
src/platform_impl/macos/util/async.rs
src/platform_impl/macos/util/mod.rs
src/platform_impl/macos/view.rs
src/platform_impl/macos/window.rs
src/platform_impl/macos/window_delegate.rs

To make having the `trace!` calls more ergonomic.

macOS RAII trace guards

---

CHANGELOG.md
src/platform_impl/android/mod.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/web/window.rs
src/platform_impl/windows/window.rs
src/window.rs

feat: add `Window::is_decorated`

---

CHANGELOG.md
src/platform_impl/android/mod.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/web/window.rs
src/platform_impl/windows/window.rs
src/window.rs

feat: add `Window::is_resizable`

---

src/platform_impl/android/mod.rs

Fixes https://github.com/rust-windowing/winit/issues/2196 until a better solution using `ndk-context` is possible

Fix Android CI

---

CHANGELOG.md
src/platform_impl/android/mod.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/web/window.rs
src/platform_impl/windows/window.rs
src/window.rs

I am a maintainer at https://github.com/tauri-apps and a while back we forked `winit` as `tao` but recently we decided to move back to depend on `winit` directly but we need [some features ](https://matrix.to/#/!DGpLzJTRzBDTwZiogk:matrix.org/$PucGFtd5aIroCbugTCW7yIFdp0SNWaLugwb_xZwgOXc?via=libera.chat&via=matrix.org&via=community.rs) implemented at `winit` before we can make the transition. 
This PR is a first of multiple upcoming PRs hopefully but I can only provide macOS and Windows implementations.

feat: add `Window::is_visible`

---

src/platform_impl/linux/x11/window.rs

This commit adds `Window::is_visible`, `Window::is_decorated`, and
`Window::is_resizable` APIs on X11.

Add getters for visible, resizeable, etc on X11

---

src/platform_impl/linux/x11/mod.rs

Fixes #2332
- ~~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~~
- ~~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~~
- ~~Created or updated an example program if it would help users understand this functionality~~
- ~~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~~

Fix doubled device events on X11

---

Cargo.toml
src/platform_impl/linux/wayland/event_loop/mod.rs
src/platform_impl/linux/wayland/seat/keyboard/mod.rs

--
This requires bumping sctk-adwaita first.

Bump smithay-client-toolkit to v0.16.0

---

src/platform_impl/linux/wayland/window/shim.rs

On Wayland, drop wl_surface on window close

---

src/platform_impl/macos/view.rs

When confirming input in e.g. Korean IME or using characters like
`+` winit was sending those twice, once via `Ime::Commit` and the
other one via `ReceivedCharacter`, since those events weren't generating
any `Ime::Preedit` and were forwarded due to `do_command_by_selector`.

On macOS, fix confirmed character inserted

---

src/platform_impl/linux/x11/ime/context.rs
src/platform_impl/linux/x11/ime/mod.rs

On X11, fix crash when can't disable ime

---

Cargo.toml
src/lib.rs
src/platform_impl/ios/app_state.rs
src/platform_impl/ios/event_loop.rs
src/platform_impl/ios/ffi.rs
src/platform_impl/ios/mod.rs
src/platform_impl/ios/monitor.rs
src/platform_impl/ios/uikit/mod.rs
src/platform_impl/ios/uikit/responder.rs
src/platform_impl/ios/uikit/view.rs
src/platform_impl/ios/uikit/view_controller.rs
src/platform_impl/ios/uikit/window.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs

Same as https://github.com/rust-windowing/winit/pull/2458, but for iOS.
~Blocked on https://github.com/rust-windowing/winit/pull/2459.~ I've taken that part out for now

Clean up iOS class declaration

---

CHANGELOG.md
src/platform_impl/linux/x11/ime/callbacks.rs
src/platform_impl/linux/x11/ime/context.rs
src/platform_impl/linux/x11/ime/inner.rs
src/platform_impl/linux/x11/ime/input_method.rs
src/platform_impl/linux/x11/ime/mod.rs

On X11 query for XIM styles before creating IME

---

CHANGELOG.md
Cargo.toml
README.md

This commit does not represent a release and only
synchronizes CHANGELOG from the latest release.

Bump version on master

---

CHANGELOG.md
Cargo.toml
README.md
src/platform_impl/linux/x11/ime/callbacks.rs
src/platform_impl/windows/event_loop.rs

I'm still waiting for #2510 to be resolved first.

Release 0.27.4 version

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Generate docs.rs documentation with doc_auto_cfg

---

Cargo.toml
src/platform_impl/windows/window.rs

Bump `windows-sys` to 0.42

---

CHANGELOG.md
src/monitor.rs
src/platform_impl/macos/monitor.rs
src/platform_impl/windows/monitor.rs

Don't panic when get refresh rate failed

---

src/platform_impl/macos/util/async.rs
src/platform_impl/macos/window.rs

Follow-up of https://github.com/rust-windowing/winit/pull/2574.
Should improve the situation in https://github.com/rust-windowing/winit/issues/2068.

macOS: Run fullscreen code synchronously on main thread

---

src/platform_impl/ios/uikit/mod.rs
src/platform_impl/ios/view.rs

Possible now after https://github.com/rust-windowing/winit/pull/2459

Clean up `UIView` override declaration

---

README.md

Add missing closing parentheses

---

examples/child_window.rs
src/dpi.rs
src/platform_impl/ios/monitor.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/x11/event_processor.rs
src/platform_impl/linux/x11/mod.rs
src/platform_impl/linux/x11/monitor.rs
src/platform_impl/linux/x11/util/geometry.rs
src/platform_impl/linux/x11/util/hint.rs
src/platform_impl/linux/x11/util/randr.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/app.rs
src/platform_impl/macos/monitor.rs
src/platform_impl/macos/util/mod.rs
src/platform_impl/macos/view.rs
src/platform_impl/macos/window.rs
src/platform_impl/macos/window_delegate.rs
src/platform_impl/web/event_loop/runner.rs
src/platform_impl/web/event_loop/window_target.rs
src/platform_impl/windows/dpi.rs
src/platform_impl/windows/drop_handler.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/icon.rs
src/platform_impl/windows/monitor.rs
src/platform_impl/windows/window.rs

fix `unnecessary cast` lint

---

src/platform_impl/web/web_sys/scaling.rs

Swap assert by debug_assert for recovereable issue. Fixes #2597

---

.github/CODEOWNERS
.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
FEATURES.md
README.md
build.rs
examples/window_run_return.rs
src/event.rs
src/event_loop.rs
src/monitor.rs
src/platform/mod.rs
src/platform/orbital.rs
src/platform_impl/mod.rs
src/platform_impl/orbital/event_loop.rs
src/platform_impl/orbital/mod.rs
src/platform_impl/orbital/window.rs
src/window.rs

This is a draft for feedback on the implementation. Features will be added and documentation improved, but for now, this is sufficient for all the examples to run on Redox.

Redox OS support

---

Cargo.toml

Makes it so `cargo add` works properly, and also looks nicer.

chore: Alphabetize dependencies

---

CHANGELOG.md
src/platform_impl/android/mod.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/orbital/window.rs
src/platform_impl/web/window.rs
src/platform_impl/windows/util.rs
src/platform_impl/windows/window.rs
src/window.rs

Add `Window::is_minimized`

---

src/platform_impl/macos/app.rs
src/platform_impl/macos/app_state.rs
src/platform_impl/macos/view.rs
src/platform_impl/macos/window_delegate.rs

Clean up event queuing a bit on macOS

---

src/platform/ios.rs
src/platform_impl/ios/app_state.rs
src/platform_impl/ios/event_loop.rs
src/platform_impl/ios/ffi.rs
src/platform_impl/ios/uikit/mod.rs
src/platform_impl/ios/uikit/view_controller.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs

Use a bit less `unsafe` on iOS

---

CHANGELOG.md
src/platform_impl/linux/wayland/window/mod.rs

While I don't understand the root cause for this issue, we can dirty fix like that for now.

On Wayland, fix rare crash on DPI change

---

CHANGELOG.md
src/platform_impl/linux/wayland/event_loop/mod.rs

On Wayland, fix rounding issue in resizes

---

CHANGELOG.md
src/platform_impl/windows/window.rs

Check whether CoCreateInstance succeeds

---

src/event_loop.rs
src/platform/ios.rs
src/platform/macos.rs
src/platform_impl/linux/x11/util/hint.rs
src/window.rs

Fixes the new clippy warning in 1.68

Fix 1.68 clippy warnings

---

CHANGELOG.md
src/platform_impl/linux/wayland/seat/keyboard/mod.rs
src/platform_impl/linux/wayland/seat/touch/mod.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/view.rs

On macOS, fix empty marked text blocking input

---

.github/CODEOWNERS

Add daxpedda as web maintainer

---

Cargo.toml

Just updating a dev dependency ...

Bump `console_log` to v1

---

CHANGELOG.md

Fixed some changes not being properly marked as breaking in the changelog and also some inconsistencies.

Fix up changelog

---

src/platform_impl/web/web_sys/scaling.rs

Just some slight code improvements I didn't want to leave in #2859.
- Get rid of the `Option` by using `Rc::new_cyclic`.
- Don't actually send `WindowEvent::ScaleFactorChanged` unless the scale factor actually changed.
- Leave a comment on why this could actually happen (or not).

Improve media queries take 2

---

CHANGELOG.md
src/platform_impl/web/web_sys/resize_scaling.rs

Fix some typos

---

src/event.rs

Fix typos on Web

---

CHANGELOG.md
clippy.toml
src/platform_impl/web/web_sys/canvas.rs
src/platform_impl/web/web_sys/fullscreen.rs
src/platform_impl/web/web_sys/mod.rs

I wasn't sure how long we were going to take for #2929, so I didn't want to block this and risk having to rewrite it if rebasing becomes untenable.
Replaces #2937.

Add Fullscreen API compatibility for Safari

---

CHANGELOG.md
src/platform/web.rs
src/platform_impl/web/web_sys/mod.rs

This is already covered by `Window::theme()`.

On Web, remove `Window::is_dark_mode()`

---

Cargo.toml
src/platform_impl/ios/app_state.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs
src/platform_impl/macos/app_delegate.rs
src/platform_impl/macos/appkit/application.rs
src/platform_impl/macos/appkit/screen.rs
src/platform_impl/macos/appkit/view.rs
src/platform_impl/macos/appkit/window.rs
src/platform_impl/macos/view.rs
src/platform_impl/macos/window_delegate.rs

Should rid us of pre-release version errors for good.

Update icrate to v0.0.4

---

CHANGELOG.md
src/platform_impl/linux/x11/window.rs

On X11, set visual_id in raw-window-handle

---

CHANGELOG.md
src/platform_impl/linux/wayland/seat/touch/mod.rs

On Wayland, fix TouchPhase::Canceled sent for move

---

CHANGELOG.md
src/platform/web.rs
src/platform_impl/web/event_loop/runner.rs
src/platform_impl/web/event_loop/window_target.rs
src/platform_impl/web/web_sys/schedule.rs

Probably a way better name.
See #3084.

Rename `PollType` to `PollStrategy`

---

src/dpi.rs

Correct Wayland section in dpi docs

---

CHANGELOG.md
src/platform_impl/android/mod.rs

Android: Make DeviceId contain device id's

---

CHANGELOG.md
examples/window_on_demand.rs
src/platform/mod.rs
src/platform/run_on_demand.rs
src/platform_impl/android/mod.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/event_loop/mod.rs
src/platform_impl/linux/x11/mod.rs
src/platform_impl/macos/app_state.rs
src/platform_impl/macos/event_loop.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/event_loop/runner.rs

Renamed the function as discussed in https://github.com/rust-windowing/winit/issues/2900#issuecomment-1733674754

renamed run_ondemand to run_on_demand

---

src/platform_impl/linux/wayland/seat/keyboard/mod.rs
src/platform_impl/macos/event.rs
src/platform_impl/macos/view.rs

Update Clippy to v1.73

---

CHANGELOG.md
Cargo.toml
FEATURES.md
src/platform_impl/android/mod.rs
src/platform_impl/ios/window.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/state.rs
src/platform_impl/linux/wayland/types/kwin_blur.rs
src/platform_impl/linux/wayland/types/mod.rs
src/platform_impl/linux/wayland/window/mod.rs
src/platform_impl/linux/wayland/window/state.rs
src/platform_impl/linux/x11/window.rs
src/platform_impl/macos/window.rs
src/platform_impl/orbital/window.rs
src/platform_impl/web/window.rs
src/platform_impl/windows/window.rs
src/window.rs

Related to #538
- :x:  Tested on all platforms changed

Support KDE Wayland blur protocol

---

src/keyboard.rs

Why: I want to sort a bunch of rules involving `ModifiersState` (to ensure consistent serialisation).

Support ModifiersState: Ord

---

CHANGELOG.md
src/platform_impl/windows/window.rs
src/window.rs

On Windows, add support for Window::set_transparent

---

src/window.rs

Fix typo and other small grammar corrections

Fix typo in pre_present_notify docs

---

CHANGELOG.md
Cargo.toml
src/platform_impl/linux/x11/util/cursor.rs

On X11, try alternative cursor icon names as well

---

CHANGELOG.md
src/platform_impl/macos/app_state.rs

Send a Resized event after ScaleFactorChanged

---

CHANGELOG.md
src/platform_impl/macos/appkit/application.rs
src/platform_impl/macos/appkit/menu_item.rs
src/platform_impl/macos/menu.rs

feat: macos services menu added

---

CONTRIBUTING.md
FEATURES.md
HALL_OF_CHAMPIONS.md
README.md
docs/res/ATTRIBUTION.md
src/dpi.rs
src/lib.rs

I have made changes to the documentation to increase clarity and enhance the reading experience. Some of the changes are: fixed typos, removed/added commas where needed, changed/added articles before words where needed, broke down some sentences.
> -  Tested on all platforms changed - **not needed**
> - Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users - **not needed**
> - Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior - **not needed**
> - Created or updated an example program if it would help users understand this functionality - **not needed**
> - Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented - **not …

Changes and improvements to the documentation

---

Cargo.toml
src/platform_impl/linux/wayland/window/state.rs

Update `sctk-adwaita` to 0.8

---

CHANGELOG.md
src/platform_impl/linux/wayland/state.rs
src/platform_impl/linux/wayland/window/state.rs

On Wayland, fix resize being sent on focus change

---

src/window.rs

Just some stuff I noticed while working on some things.
@madsmtm I believe the iOS stuff here was fixed in https://github.com/rust-windowing/winit/pull/3045.

Fix some doc nits

---

src/platform_impl/web/web_sys/event.rs
src/platform_impl/web/web_sys/fullscreen.rs
src/platform_impl/web/web_sys/schedule.rs

Use `std::cell::OnceCell`

---

src/platform_impl/windows/window.rs

HWND in windows-sys doesn't require a newtype wrapper for Send/Sync.

On Windows, remove internal WindowWrapper

---

Cargo.toml
src/platform_impl/ios/monitor.rs
src/platform_impl/ios/view.rs
src/platform_impl/ios/window.rs
src/platform_impl/macos/app.rs
src/platform_impl/macos/app_delegate.rs
src/platform_impl/macos/appkit/cursor.rs
src/platform_impl/macos/appkit/screen.rs
src/platform_impl/macos/menu.rs
src/platform_impl/macos/view.rs
src/platform_impl/macos/window.rs
src/platform_impl/macos/window_delegate.rs

~Blocked on https://github.com/madsmtm/objc2/issues/537~.
This unblocks https://github.com/rust-windowing/winit/pull/2982.
- I don't think this needs a changelog entry

Update `objc2` and `icrate` versions

---

CHANGELOG.md
examples/util/fill.rs
examples/window_on_demand.rs
src/platform/run_on_demand.rs
src/platform_impl/android/mod.rs
src/platform_impl/linux/mod.rs
src/platform_impl/linux/wayland/event_loop/mod.rs
src/platform_impl/linux/wayland/output.rs
src/platform_impl/linux/x11/mod.rs
src/platform_impl/macos/app_state.rs
src/platform_impl/macos/event_loop.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/event_loop/runner.rs

Fix run_on_demand exiting on consequent call

---

src/platform_impl/linux/x11/monitor.rs

There are two parts to this.
First, `*monitors_lock` is an `Option<Vec<...>>`. The code here wants to clone the vector so that a copy can be returned to the caller. The way to do this was to use `.as_ref()` to get `Option<&Vec<...>>` so that .cloned() becomes available to produce a clone. In this commit, I am replacing this with a straight `.clone()` call.
Next, there was a `.map(Ok)` to turn `Option<Vec<...>>` into `Option<Result<Vec<...>>`. This resulted either in `None` or `Some(Ok(...))`. `Some(Err(...))` was impossible. Then, `.or_else()` was used to turn the `None` case into `Some(...)`, too, so that while "`None`" is still possible at the type level, it cannot actually occur any more. In the end, `unwrap()` was used to get rid of the outer `Option`.
This code confused me. This …

(Try to) simplify x11's available_monitors()

---

src/cursor.rs
src/platform/web.rs
src/window.rs

Just some random improvements of Web related documentation.

Web documentation improvements

---

src/platform_impl/linux/x11/window.rs

Change value sent to X server during minimize

---

CHANGELOG.md
src/platform_impl/linux/x11/monitor.rs
src/platform_impl/linux/x11/xdisplay.rs

Cache the XRandR extension version

---

CHANGELOG.md
src/platform_impl/linux/common/keymap.rs

Links: https://github.com/alacritty/alacritty/issues/7533

 On X11 and Wayland, fix numpad up being ArrowLeft

---

.github/workflows/ci.yml

I forgot to add proper target selection in #3356.

Fix missing target in docs.rs test

---

src/platform_impl/linux/x11/ime/callbacks.rs
src/platform_impl/linux/x11/ime/input_method.rs
src/platform_impl/linux/x11/ime/mod.rs
src/platform_impl/web/main_thread.rs
src/platform_impl/windows/window.rs

See https://github.com/rust-lang/rust/pull/118297.
Lets leave this up for now and see how Rust intends to deal with this.

Fix nightly CI

---

src/platform_impl/macos/window.rs
src/platform_impl/macos/window_delegate.rs

macOS: Remove unnecessary Mutex in window state

---

Cargo.toml

Bump `web-time` to v1

---

Cargo.toml
README.md
build.rs
examples/control_flow.rs
examples/custom_cursors.rs
examples/custom_events.rs
examples/focus.rs
examples/multithreaded.rs
examples/request_redraw_threaded.rs
examples/timer.rs
examples/web.rs
examples/web_aspect_ratio.rs
examples/window_pump_events.rs
src/event.rs
src/event_loop.rs
src/platform/mod.rs
src/platform/run_on_demand.rs
src/platform/web.rs
src/platform_impl/mod.rs

We did call it Web in most places, but there were many mentions of Wasm or WebAssembly, this PR changes all those to Web for consistency.
I also renamed the GitHub label while I'm at it.

Platform is called Web not Wasm

---

README.md

Fixes https://github.com/rust-windowing/winit/issues/3419

Fix Android examples link in README

---

src/platform_impl/ios/app_state.rs
src/platform_impl/ios/event_loop.rs
src/platform_impl/macos/app_delegate.rs
src/platform_impl/macos/event_loop.rs

This matches what's done on the other backends, and allows us to get rid of unnecessary indirection and boxing, as well as paving the way for a future where we don't have user events, only some form of event loop waker.

Refactor user event handling on macOS/iOS

---

Cargo.toml

Bump build dependency `cfg_aliases` to 0.2

---

CHANGELOG.md
src/event_loop.rs

Fix compatibility with platforms without AtomicU64

---

CHANGELOG.md
src/platform/mod.rs
src/platform_impl/orbital/event_loop.rs
src/platform_impl/orbital/mod.rs

orbital: improve keyboard handling

---

CHANGELOG.md
src/platform_impl/linux/wayland/event_loop/mod.rs

On Wayland, update title from AboutToWait

---

CONTRIBUTING.md

CC https://github.com/rust-windowing/winit/issues/3431#issuecomment-1912891145.
Once this is merged, I'll disable the wiki in the repository settings.

Remove Testers and Contributors table

---

src/platform_impl/linux/x11/event_processor.rs

Given that `ModifiersChanged` is a window event, it means that clients may track it for each window individually, thus not sending it between focus changes may result in modifiers getting desynced on the consumer side.

On X11, force resend modifiers when focus changes

---

src/platform/x11.rs
src/platform_impl/linux/x11/ime/inner.rs
src/platform_impl/windows/event_loop.rs

chore: remove repetitive words

---

src/platform_impl/linux/x11/window.rs

bugfix(x11): Fix window position calculation overflow during dragging

---

examples/window.rs

This adds the shortcut "Alt + R" to swap the size of the window axes.
I'm seeing a number of winit clients that ignore the output of `request_inner_size` on wayland. I hope having this in the example will change this.

example: Add an example of `request_inner_size`

---

src/changelog/unreleased.md

Fix copy/paste error in changelog.

---

.github/workflows/ci.yml
.github/workflows/docs.yml

ci: Update all jobs to `actions/checkout@v4`.

---

examples/window.rs

example: Fix typo: "fosus" -> "focus"

---

clippy.toml

Missed this in https://github.com/rust-windowing/winit/pull/3634, and only saw it after I went to make https://github.com/rust-windowing/glutin/pull/1673.

Fix icrate's clippy customization

---

CONTRIBUTING.md

The steps were rebased incorrectly.
Fixes: 575d978202 (docs: Rework CONTRIBUTING guidelines)

docs: fix release steps in CONTRIBUTING.md

---

.github/workflows/ci.yml
.gitignore
.swcrc
Cargo.toml
README.md
examples/window.rs
src/changelog/unreleased.md
src/changelog/v0.30.md
src/event.rs
src/platform/android.rs
src/platform/web.rs
src/platform_impl/linux/x11/ime/context.rs
src/platform_impl/macos/window_delegate.rs
src/platform_impl/web/event_loop/mod.rs
src/platform_impl/web/event_loop/runner.rs
src/platform_impl/web/event_loop/window_target.rs
src/platform_impl/web/web_sys/schedule.rs
src/platform_impl/web/web_sys/worker.js
src/platform_impl/web/web_sys/worker.min.js
src/window.rs

Winit version 0.30.3

---

.github/CODEOWNERS

I won't have time to do maintainance stuff anytime soon - so removing myself as codeowner.
Thanks everyone & cheers!

Remove myself as codeowner

---

.github/workflows/ci.yml

taiki-e/checkout-action has a few advantages over actions/checkout,
such as:
- It is written in Bash rather than Node.js
- It does not have frequent breaking changes, reducing churn

Use taiki-e/checkout-action

---

src/platform_impl/web/web_sys/schedule.rs

This has been reflected in `wasm-bindgen` itself as well for the next release, see https://github.com/rustwasm/wasm-bindgen/pull/3898.

Web: avoid using `js_sys::Reflect`

---

.cargo/config.toml
.github/workflows/ci.yml
Cargo.toml
src/event.rs
src/keyboard.rs

While running tests on Web is something not addresses here, we at least run doc tests to make sure they work correctly especially when adding web-only doc tests.

Run doc tests on Web as well

---

src/platform_impl/windows/event_loop/runner.rs

Fix spelling of "inner"

---

src/platform_impl/apple/appkit/view.rs
src/platform_impl/linux/common/xkb/mod.rs
src/platform_impl/linux/x11/activation.rs
src/platform_impl/linux/x11/mod.rs
src/platform_impl/linux/x11/monitor.rs
src/platform_impl/linux/x11/util/memory.rs
src/platform_impl/orbital/mod.rs
src/platform_impl/windows/event_loop.rs
src/platform_impl/windows/window.rs

Fix Clippy lints

---

src/changelog/unreleased.md
src/platform_impl/linux/x11/window.rs

x11: fix cursor grab mode tracking on error

---

CONTRIBUTING.md

Fixes https://github.com/rust-windowing/winit/issues/4103.

Document that we require cargo +nightly fmt

---

src/event.rs

This was unintentionally added in eccd9e415.

doc: Remove spurious derive directive

---

src/platform_impl/linux/x11/event_processor.rs
src/platform_impl/linux/x11/mod.rs
src/platform_impl/linux/x11/window.rs

This avoids an unreachable case, and allows removing the top-level `Event` enum in the future. Should be purely a refactor.

X11: Call `ApplicationHandler` directly

---

src/event.rs

https://github.com/rust-windowing/winit/pull/3517 added `ApplicationHandler` as the new preferred API, but kept the `Event` enum around because the backend platforms still depended on it.
That dependence have now been removed in https://github.com/rust-windowing/winit/pull/3753, https://github.com/rust-windowing/winit/pull/4139, https://github.com/rust-windowing/winit/pull/4140, https://github.com/rust-windowing/winit/pull/4141 and https://github.com/rust-windowing/winit/pull/4142, so we can now remove the top-level event too.

Remove top-level `Event` enum

---

examples/application.rs

Fix ALT key bindings in application.rs example on MacOS

---

src/platform_impl/linux/x11/util/memory.rs

x11: drop dead code

---

winit/src/platform/mod.rs

Fixes https://github.com/rust-windowing/winit/issues/4138. Implementation relies on us accepting https://github.com/rust-windowing/winit/pull/4274.

Document platform-specific modules

---

winit-uikit/src/app_state.rs
winit-uikit/src/event_loop.rs

Prefer `Cell` and `Copy` types instead, as those will never have crashes on re-entrancy / if forgetting to make a state transition.
Fixes https://github.com/rust-windowing/winit/issues/2867.

iOS: Avoid `RefCell` and `static mut`

---

winit-core/src/as_any.rs

The casting was doing an incorrect check on the `ref` instead of actually trying to downcast a ref as `cast_ref` does. So use `cast_ref` to check whether we can safely `cast` to owned type.

winit-core/as_any: fix `Box<AsAny>` casting
