CHANGELOG.md, src/platform_impl/linux/wayland/seat/pointer/data.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs
Fixes #2273.
The underlying method for hiding the cursor (setting its texuture to
NULL) is [`wayland_client::protocol::wl_pointer::WlPointer::set_cursor()`](https://docs.rs/wayland-client/0.29.4/wayland_client/protocol/wl_pointer/struct.WlPointer.html#method.set_cursor).
This method expects a serial number of the last **enter** event.
Right now, `latest_event` is any latest pointer event. It gets used by
the call to [`set_cursor()`](https://github.com/rust-windowing/winit/blob/ea09d1d10e59f7b44dedfd18a9170a01a4930768/src/platform_impl/linux/wayland/seat/pointer/mod.rs#L56-L116) and also to [`start_interactive_move()`](https://github.com/rust-windowing/winit/blob/ea09d1d10e59f7b44dedfd18a9170a01a4930768/src/platform_impl/linux/wayland/seat/pointer/mod.rs#L153-L155). While
`set_cursor()` …
=> Fix hiding cursor hiding on wayland

examples/ime.rs, src/event.rs, src/window.rs
See #2243.
Please correct me on the specifics here, I may very well be wrong on some of this.
=> Improve `IME` documentation

Cargo.toml
`windows-sys:0.36` should become a common version in ecosystem and be our target for the upcoming release.https://github.com/rust-windowing/winit/issues/2234#issuecomment-1114332780
`parking_lot` did a patch release for their `core` create which will automatically pull in the 0.36 version, so there are not multiple `windows-sys` version in the dependency tree.
=> Bump windows-sys version to 0.36

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, FEATURES.md, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs
Hi!
I wrote a simple CSD implementation for Smithay client toolkit, and I think it could be a good default for winit.
Here is winit running with those decorations:
|   |   |
|---|---|
|![active](https://i.imgur.com/WdO8e0i.png)|![inactive](https://i.imgur.com/MTFdSjK.png)|
Let me also answer questions that will most likely come up:
- `Why not libdecor?`
- Using libdecor from Rust Wayland ecosystem is nowhere near completion, and in my opinion it will never be. And besides some initial tests with calling it from Rust, no one is actively working on it atm.
- If I'm wrong and libdecor-rs will be a thing, then we can just drop my impl easily, so it's a win-win scenario.
- `Why  does it look like GTK/Adwaita?`
- Mutter/Gnome is probably the only big compositor that does not support SSD, so I …
=> wayland: Replace fallback CSD with proper one

CHANGELOG.md, src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs
* Fixes https://github.com/rust-windowing/winit/issues/2191
* Fixes downstream https://github.com/alacritty/alacritty/issues/5876
- (n/a) Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- (n/a) Created or updated an example program if it would help users understand this functionality
- (n/a) Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
For testing:
* First make sure "Prefer tabs" is set to "always" in macOS system preferences
* (so new windows will get grouped as tabs).
* Add a debug statements such as `println!("emitting resize event with size = {:?}", size);`
* Add to `emit_resize_event` method in src/platform_impl/macos/window_delegate.rs.
* …
=> macOS: Emit resize on frame_did_change

src/event_loop.rs
This PR modifies documentation only; I tested it by viewing local `cargo doc` output.
Since there's a "Platform-specific" header, it makes sense to put the Linux-specific part under it. On the other hand, "Can only be called on the main thread." is true for all platforms, and documented in the preceding text, not just iOS, so there is no reason to call it out for iOS specifically.
A further improvement might be to describe the specific side-effects calling the function could have on non-Linux platforms (rather than just saying "display backend initialisation"), but I don't know of any to mention.
=> Reorganize EventLoopBuilder::build() platform documentation.

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
Fixes #2300.
winit's GetModuleHandle(NULL) [returns an invalid instance handle if it were to be used inside of a DLL or other non-executable target](https://stackoverflow.com/questions/21718027/getmodulehandlenull-vs-hinstance).. Using the [pseudo-variable of the microsoft linker](https://devblogs.microsoft.com/oldnewthing/20041025-00/?p=37483) not only reduces work, but also works reliably inside both DLLs and executables. More info is inside the issue.
The documentation states that this only works with the microsoft linker, I've tested it using both the stable-GNU and stable-MSVC toolchain and it both seems to work, which suggests that on windows the microsoft linker is always used.
=> [Windows] Avoid GetModuleHandle(NULL)

src/platform_impl/windows/mod.rs
When clicking and moving the cursor out of the window negative coordinates were not handled correctly.
Changelog entry not added as this occured during the `windows-sys` transition and shouldn't affect the latest release.
> Do not use the [LOWORD](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms632659(v=vs.85)) or [HIWORD](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms632657(v=vs.85)) macros to extract the x- and y- coordinates of the cursor position because these macros return incorrect results on systems with multiple monitors. Systems with multiple monitors can have negative x- and y- coordinates, and LOWORD and HIWORD treat the coordinates as unsigned quantities.
The implementation now follows the original macro definition …
=> On Windows, fix reported cursor position.

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs
This reverts commit 78e5a395dac9604e851f781b6810247ead7928e3.
It was discovered that in some cases mesa will lock the back
buffer, e.g. when making context current, leading to resize
missing. Given that applications can restructure their rendering
to account for that, and that winit isn't limited to playing
nice with mesa reverting the original commit.
=> Revert "On Wayland, fix resize not propagating properly"

src/window.rs
Makes sense to be must_use as failing to call finish() would almost certainly indicate a bug.
=> Set WindowBuilder to must_use

CHANGELOG.md, src/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
Previously on X11, by default all global events were broadcasted to
every Winit application. This unnecessarily drains battery due to
excessive CPU usage when moving the mouse.
To resolve this, device events are now ignored by default and users must
manually opt into it using `EventLoop::set_filter_device_events`.
Fixes (#1634) on Linux.
=> Add X11 opt-in function for device events

src/platform_impl/linux/x11/ime/context.rs
Based on https://github.com/rust-windowing/winit/pull/2067
=> Prevent null dereference on X11 with bad locale

Cargo.toml, src/lib.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/atom.rs, src/platform_impl/linux/x11/util/wm.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/util.rs
`lazy_static!`, while a declarative macro, is a macro nonetheless. It can add quite a bit of additional compilation time cost. `once_cell::sync::Lazy` does the same thing with generics, and can be used more flexibly (i.e. non-static lazily initialized values), and has been [proposed to be added to `std`](https://github.com/rust-lang/rust/issues/74465).
I'm trying to reduce the compile time and dependency tree complexity of a dependent project: [bevy](https://bevyengine.org), which is using winit. `lazy_static` and `once_cell` are both in our dependency tree and both end up doing the same thing.
Migrate to `once_cell`.
---
I don't think any of the changes here are user visible beyond the dependency in the tree, and should work as-is on all of them, but I could be wrong.
=> Migrate from lazy_static to once_cell

CHANGELOG.md, src/platform_impl/macos/app_delegate.rs
=> Emit LoopDestroyed on cmd+q

Cargo.toml, src/platform_impl/android/mod.rs
The `ndk` crate now implements [`HasRawWindowHandle` directly on `NativeWindow`], relieving the burden on `winit` to carry the same implementation details.
[`HasRawWindowHandle` directly on `NativeWindow`]: https://github.com/rust-windowing/android-ndk-rs/pull/274
---
This PR is also being opened to discuss how we should proceed with up and coming `ndk` (+ `ndk_glue`) changes that are not yet published. I'd like to coordinate the next (which is going to be breaking) release of those crates with `winit` so that we're not unnecessarily creating a desync in the ecosystem (https://github.com/rust-windowing/winit/issues/1995). That'd require Android PRs to remain open until `winit` eventually starts the `0.27` cycle and I decide when and where to make the cut and publish the `ndk`. …
=> On Android, use `HasRawWindowHandle` directly from the `ndk` crate

examples/window_debug.rs, src/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/mod.rs
Commit f10a984 added `EventLoopWindowTarget::set_device_event_filter`
with for a mutable reference, however most winit APIs work with
immutable references, so altering API to play nicely with existing APIs.
This also disables device event filtering on debug example.
cc @chrisduerr
=> Make `set_device_event_filter` non-mut

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml
Fixes https://github.com/rust-windowing/winit/issues/1028. `docs.rs` has come a long way since that issue, so the problems they encountered are (probably) no more - at least `ndk` (Android) and `objc2` (iOS + macOS) all successfully build.
Tested with:
```
cargo doc --target aarch64-linux-android
cargo doc --target x86_64-apple-ios
```
We'll have to watch https://docs.rs/crate/winit/latest/builds after the next release, to ensure that everything actually works as expected!
=> Build docs on `docs.rs` for iOS and Android as well

Cargo.toml, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/monitor.rs
Hasn't been updated in over 2 years - many open PRs, seems abandoned. Is the cause of several duplicate dependencies in our dependency tree! At this point it's better to just bundle the tiny amount of functionality we need ourselves.
Fixes #1816.
=> Remove `core-video-sys` dependency

src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs
Not that anyone uses such devices any more, but I guess I like supporting old stuff.
Tested with:
```
cargo +nightly run --target i686-apple-darwin -Z build-std --example window_debug
```
=> Fix macOS 32bit

README.md, src/dpi.rs, src/event.rs, src/event_loop.rs, src/icon.rs, src/monitor.rs, src/platform/android.rs, src/platform/macos.rs, src/platform/mod.rs, src/platform/run_return.rs, src/platform/unix.rs, src/platform/web.rs, src/window.rs
Added a lot of documentation links, and a Wayland and macOS section to the README for some common issues.
=> Documentation cleanup

CHANGELOG.md, src/window.rs
This is required to help hardware accelerated libraries like glutin
that accept WindowBuilder instead of RawWindowHandle, since the api
to access builder properties directly was removed.
Follow up to 44288f6.
=> Add `WindowBuilder::transparent`

CHANGELOG.md, FEATURES.md, examples/cursor_grab.rs, examples/multithreaded.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/env.rs, src/platform_impl/linux/wayland/seat/pointer/data.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
This commit renames `Window::set_cursor_grab` to
`Window::set_cursor_grab_mode`. The new API now accepts enumeration
to control the way cursor grab is performed. The value could be: `lock`,
`confine`, or `none`.
This commit also implements `Window::set_cursor_position` for Wayland,
since it's tied to locked cursor.
Implements API from #1677.
=> Refine `Window::set_cursor_grab` API

examples/window_run_return.rs
Android also supports `EventLoopExtRunReturn`.  The user will still have to follow the README to turn this example into a `cdylib` and add the `ndk_glue::main()` initialization attribute, though.
=> examples/window_run_return: Enable on Android

CHANGELOG.md, src/platform_impl/macos/window.rs
Hi! I just made a simple change to how the `disallow_highdpi`option behaves. 
The default value of `setWantsBestResolutionOpenGLSurface_` was `false` until macos 10.14 and `true` after 10.5, we should set it to `YES` o `NO` to avoid always the default system value in favour of the user's code.
=> macOS disallow_highdpi will set explicity the value to avoid the SO value by default

.github/workflows/ci.yml, src/platform_impl/ios/app_state.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/macos/observer.rs, src/platform_impl/windows/event_loop.rs, src/window.rs
Make sure `cargo doc` runs cleanly without any warnings in the CI - some recently introduced but still allowing a PR to get merged.
In case someone wishes to add docs on private items, make sure those adhere to the same standards.
=> ci: Disallow warnings in rustdoc and test private items

CHANGELOG.md, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/event_loop/sink.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/mod.rs, src/window.rs
This should help downstream applications to expose WindowId to the end
users via e.g. IPC to control particular windows in multi window
systems.
=> Implement From<u64> for WindowId and vise-versa

examples/multiwindow.rs
Fixes #2349. Tested on X11; I don't think the rest is relevant.
=> examples/multiwindow.rs: ignore synthetic key press events

src/window.rs
These conversion methods call itself recursively so using it occurs stack overflow.
Found using `Windowid::from(u64)` in a work on https://github.com/rust-windowing/winit/pull/2246. You can see a stack overflow with this PR's commit https://github.com/rust-windowing/winit/pull/2246/commits/7a04d4073ef75fe739a0553d1d09dbb359022d2d with `cargo run --example child_window`.
- It'll be checked in CI 
- It's a bugfix so it will not change any features
- same as above
- same as above
- same as above
=> Avoid infinite recursion about WindowId conversion

CHANGELOG.md, src/monitor.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/web/monitor.rs, src/platform_impl/windows/monitor.rs
This also alters `VideoMode::refresh_rate` to return u32 which is a
monitor refresh rate in mHz.
=> Add `refresh_rate` for `MonitorHandle`

src/platform_impl/linux/wayland/window/mod.rs
On Wayland winit will always get an explicit focused event from the
system and will transfer it downstream. So send focused false to enforce
it.
--
This doesn't affect the end users, since they'll have explicit event and shouldn't make any assumption like if I documented that window is unfocused by default.
=> On Wayland send Focused(false) for new window

CHANGELOG.md, src/platform_impl/web/event_loop/window_target.rs
closes https://github.com/rust-windowing/winit/issues/2112
Reasoning is explained on the issue.
=> web: Manually emit focused event on mouse click

CHANGELOG.md, Cargo.toml, src/platform_impl/android/mod.rs, src/window.rs
This applies https://github.com/rust-windowing/android-ndk-rs/issues/117 on the `winit` side: Android destroys its window/surface as soon as the user returns from [`onNativeWindowDestroyed`], and we "fixed" this on the `ndk-glue` side by sending the `WindowDestroyed` event before locking the window and removing it: this lock has to wait for any user of `ndk-glue` - ie. `winit` - to give up its readlock on the window, which is what we utilize here to give users of `winit` "time" to destroy any resource created on top of a `RawWindowHandle`.
since we can't pass the user a `RawWindowHandle` through the `HasRawWindowHandle` trait we have to document this case explicitly and keep the lock alive on the `winit` side instead.
[`onNativeWindowDestroyed`]: …
=> android: Hold `NativeWindow` lock until after notifying the user with `Event::Suspended`

CHANGELOG.md, src/platform/web.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
`with_prevent_default` controls whether `event.preventDefault` is called
`with_focusable` controls whether `tabindex` is added
Fixes #1768
=> web: add `with_prevent_default`, `with_focusable`

src/platform_impl/windows/event_loop.rs
During the switch to windows-sys, it looks like we unintentionally started using `usButtonFlags` instead of `usButtonData` for this event.
Original winapi version: `usButtonData` is used for the delta
https://github.com/rust-windowing/winit/blob/f3f6f1008a5891ed0c9e5e8f26568f8f2d49f164/src/platform_impl/windows/event_loop.rs#L2155-L2164
After switch to windows-sys: `usButtonFlags` is used for the delta
https://github.com/rust-windowing/winit/blob/b222dde83504e402d51fa40a3c78dee40cb2ee5f/src/platform_impl/windows/event_loop.rs#L2153-L2163
=> windows: Use correct value for mouse wheel delta

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window_state.rs
Fix for issue #2102
`winit`'s notion of "focus" is very simple; you're either focused or not.
However, Windows has both notions of focused window and active window
and paying attention only to `WM_SETFOCUS`/`WM_KILLFOCUS` can cause a window
to believe the user is interacting with it when they're not. (this
manifests when a user switches to another application between when a
`winit` application starts and it creates its first window)
=> Make winit focus take activity into account on Windows

src/dpi.rs, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/window_property.rs, src/platform_impl/web/event_loop/runner.rs, src/window.rs
=> Fix some typos/spelling

Cargo.toml, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event_loop.rs
This should force the use of system libraries for Fontconfig
and freetype instead of building them with cmake if missing.
Fixes #2373.
=> Bump sctk-adwaita to 0.4.1

src/event.rs, src/event_loop.rs, src/platform/run_return.rs, src/window.rs
This fixes some minor inconsistencies that have been bothering me a bit. This includes `**macOS / X11 / Wayland / Windows:**`-style entries, which I've normalized to the form I just used, as that's what appears to already be used the most.
=> Tidy up "platform-specifc" doc sections

src/platform_impl/android/mod.rs
Calling `EventLoopProxy::send_event` while handling a UserEvent event would cause a deadlock.
edit: restored original PR template
=> Android: avoid deadlocks while handling UserEvent

CHANGELOG.md, Cargo.toml, src/event_loop.rs, src/lib.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/window.rs
This updates raw-window-handle to v0.5.0. The change is breaking
and removes the old `HasRawWindowHandle` trait implementation,
but that's intentional given that internal structs got renamed.
=> Update raw-window-handle to v0.5.0

CHANGELOG.md, src/platform/unix.rs, src/platform_impl/linux/mod.rs
This should help glutin to handle errors coming from GLX
and provide multithreading access in a safe way.
Fixes #2378.
=> Add method to hook xlib error handler

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
=> Windows: apply skip taskbar state when taskbar is restarted

CHANGELOG.md, Cargo.toml, README.md
=> Bump `ndk` and `ndk-glue` dependencies to stable `0.7.0` release

CHANGELOG.md, src/event.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop/runner.rs
To be more consistent with mobile platforms this updates the Windows,
macOS, Wayland, X11 and Web backends to all emit a Resumed event
immediately after the initial `NewEvents(StartCause::Init)` event.
The documentation for the Resumed event has also been updated to
recommend that applications should wait until they receive the Resumed
event before creating any graphics context and their first window to
help ensure portability.
This consistency makes it possible to write applications that lazily
initialize their graphics state when the application resumes without
any platform-specific knowledge. Previously, applications that wanted
to run on Android needed to have `target_os="android"` specific code
to initialize within the `Resumed` event because that same logic
would never run on …
=> Consistently deliver a `Resumed` event on all platforms

.github/workflows/ci.yml
It seems the symlink to `ndk-bundle` and this environment variable pointing to it have been removed to prevent the sdkmanager from failing, when finding the SDK setup to be in an "indeterminate" state.  It is now up to the users themselves to install an NDK through that tool or point the right variables to a preinstalled "latest" NDK.
https://github.com/actions/virtual-environments/issues/2689
https://github.com/actions/virtual-environments/issues/5879
https://github.com/actions/virtual-environments/pull/5926
---
Draft because I'm still waiting for confirmation that the removal of this env var is intended, instead of just pointing it to the latest LTS release _without going through a symlink_ to match previous behaviour.
=> ci: manually point ANDROID_NDK_ROOT to latest supplied version

CHANGELOG.md, Cargo.toml, README.md
I think it's time to cut a new release.
If there're suggestion on what should made into it let me know.
---
Blocked on:
Post release checklist:
=> Release 0.27.0 version

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, Cargo.toml, examples/fullscreen.rs, src/platform/unix.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/linux/mod.rs
This should help with distributing apps using winit.
Fixes #1075.
--
Will require a patch bump afterwards unfortunately.
=> Explicitly specify minimum supported rust version

CHANGELOG.md, src/dpi.rs, src/platform_impl/windows/window.rs
=> Windows: respect min/max sizes when creating the window

CHANGELOG.md, src/platform_impl/linux/x11/window.rs
I actually wanted to start working on #2020 almost a year after I created it, but in the process found this bug that when you move the window to another screen resize increments go poof
=> x11: Fix size hints being reset after a DPI change

CHANGELOG.md, src/event_loop.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/raw_input.rs
Addresses (#1634) on Windows.
An attempt at doing for Windows what #2195 did for X11. Device events are by default only listened to on the focused window and need to be manually opted into via `EventLoop::set_device_event_filter`.
This appears to work in a very simple test application on Windows 10 21H2. I didn't see a list of supported Windows versions, in any case I'm not able to test other ones.
=> Add Windows opt-in function for device events

.github/CODEOWNERS, CONTRIBUTING.md, HALL_OF_CHAMPIONS.md
This makes it very clear when you're stepping down from the post as a maintainer, and makes it clear for users who is expected to review their PR.
The way it works is [detailed in the docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), but in short, if edits are made to files specified here, the "code owner" will automatically be assigned as the reviewer.
An example: If I submitted a PR that edited `src/event.rs`, `src/platform/windows.rs` and `src/platform_impl/linux/wayland/output.rs`, `@msiglreith` and `@kchibisov` would automatically be marked as reviewers.
=> Add CODEOWNERS file

CHANGELOG.md, Cargo.toml, src/window.rs
This makes Winit 0.27 compatible with crates like Wgpu 0.13 that are
using the raw_window_handle v0.4 crate and aren't able to upgrade to 0.5
until they do a new release (since it requires a semver change).
The change is intended to be self-contained (instead of pushing
the details into all the platform_impl backends) since this is only
intended to be a temporary trait implementation for backwards
compatibility that will likely be removed before the next Winit release.
Addresses: #2415
**Update:** I've marked it a tested since Emil left this comment about testing this branch with Egui: https://github.com/emilk/egui/pull/1877#issuecomment-1211035430
=> Implement version 0.4 of the `HasRawWindowHandle` trait

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/event_loop/state.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs
On Waylnad when asking for redraw before `MainEventsCleared`
would result for redraw being send on the next event loop tick,
which is not expectable given that it must be delivered on the same
event loop tick.
--
Basically this change splits the inner hash map into multiple and handles them at different points of time. The requests the user is making are processed now right before `MainEventsCleared` as they should.
=> On Wayland, fix `Window::request_redraw` being delayed

CHANGELOG.md, src/platform/windows.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Alternative PR to https://github.com/rust-windowing/winit/pull/1891
- Add an option to add the drop shadow for borderless windows. This also will result in the compositor to correctly identify the window to draw the rounded corners on Windows 11. Unfortunately shows an black 1px line on top of the window.. overall just sad state of legacy stuff piled up and the compositor isn't very helpful either ):
- Support for Shake, Snap, Alt-Print, etc features which a normal window can do. This is derived by the window styles. To not show the non-client area we just spread the client area to cover it (mostly)
Non-client area hit control https://github.com/rust-windowing/winit/issues/2413 would be needed as next stop to properly emulate resize borders (not in the dropshadow tho..) and other …
=> On Windows, improve support for undecorated windows

src/event.rs
Wayland does not report the position of top-level windows to applications, so this event never gets emitted there.
=> Document `WindowEvent::Moved` as unsupported on Wayland

CHANGELOG.md
Adding a new enum variant is a breaking change in winit.
@madsmtm it's a breaking change for the reference.
=> Mark new events as breaking change

CHANGELOG.md, src/platform/unix.rs, src/platform_impl/linux/wayland/window/mod.rs, src/window.rs
On Wayland, if not otherwise specified use upstream automatic CSD theme selection.
This is available in [sctk-adwaita 0.5.1](https://github.com/PolyMeilex/sctk-adwaita/blob/master/CHANGELOG.md#051), ~so this PR requires #2438~
- ~[ ] Created or updated an example program if it would help users understand this functionality~
- ~[ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~
=> Wayland: Use sctk-adwaita 0.5.1 auto theme selection

Cargo.toml
Fixes the incompatibility of the `time` crate with the specified MSRV 1.57 by disabling the `timestamps` feature in `simple_logger`.
=> Disable default features in simple_logger, removes time dependency

src/event.rs
Follow up to https://github.com/rust-windowing/winit/pull/2434.
=> Document `WindowEvent::Moved` OS support

CHANGELOG.md, Cargo.toml, src/platform/unix.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/atom.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/linux/x11/util/wm.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
Fixes https://github.com/rust-windowing/winit/issues/650.
`std`'s `Mutex` has [recently improved a lot](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#thinner-faster-mutexes-on-linux), so there's not really a performance argument for keeping i any more. Also means we won't have to use the same `windows-sys` version as `parking_lot`
Dependency tree (Windows):
```
// Before
winit v0.27.1
├── bitflags v1.3.2
├── instant v0.1.12
│   └── cfg-if v1.0.0
├── log v0.4.17
│   └── cfg-if v1.0.0
├── once_cell v1.13.0
├── parking_lot v0.12.1
│   ├── lock_api v0.4.7
│   │   └── scopeguard v1.1.0
│   │   [build-dependencies]
│   │   └── autocfg v1.1.0
│   └── parking_lot_core v0.9.3
│       ├── cfg-if v1.0.0
│       ├── smallvec v1.9.0
│       └── windows-sys v0.36.1
│           └── …
```
=> Remove `parking_lot` dependency

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
This follows [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/win32/learnwin32/keyboard-input) on handling the `WM_SYSCHAR` and `WM_SYSKEYDOWN` events. Allows the ALT+Space menu to work.
This also allows opening the window menu in fullscreen, as tested in the "fullscreen" example. I'm not sure whether or not that is desired behavior.
Resolves #2406
=> Windows: Update handling of system keypresses

.github/CODEOWNERS
Hey @francesca64, you noted in https://github.com/rust-windowing/winit/pull/2428#issuecomment-1229605279 that you no longer have access to iOS devices (also sorry to hear you're unemployed if you're affected by that in other ways!).
I'm quite proficient in Objective-C at this point, and have access to an iOS device I can test on, and while that is of course very far from "knowing" UIKit, I think it would make sense for me to take on co-responsibility of the iOS platform. I'll probably be limiting myself to stuff relating to Objective-C to begin with, e.g. I wouldn't really feel comfortable tackling https://github.com/rust-windowing/winit/pull/2144.
=> Add myself as iOS co-maintainer

src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs
Mostly interesting for 32-bit iOS.
Found while making #2427.
=> iOS: Fix a few instances of UB

.github/CODEOWNERS, CHANGELOG.md, src/platform/android.rs, src/platform/ios.rs, src/platform/macos.rs, src/platform/mod.rs, src/platform/run_return.rs, src/platform/unix.rs, src/platform/wayland.rs, src/platform/web.rs, src/platform/windows.rs, src/platform/x11.rs, src/platform_impl/linux/mod.rs
There were basically no overlap between the platform-specific extensions in these, so it made little sense to keep them in the same file!
Will gladly rename the functions as well, e.g. `wayland_set_csd_theme -> set_csd_theme`?
~Blocked-ish on #2420~
=> Split `platform::unix` into `platform::x11` and `platform::wayland`

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, Cargo.toml, src/platform_impl/linux/x11/dnd.rs
- 1.58 needed by https://github.com/rust-windowing/winit/pull/2444
- 1.60 needed by https://github.com/rust-windowing/winit/pull/2452
Since `objc2` uses [new cargo features](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features), it is not possible to compile the dependency on 1.57, even if this is done on a platform which shouldn't need that dependency (this _could_ be reverted, but I'd rather avoid doing so, as it is a bit of a usability regression when you want to use its cargo features).
I recognize that distributions will need to have caught up with 1.60 before we can really do this, but maybe we can do this now, and then time our next breaking release of `winit` with that?
CC @Lokathor @chrisduerr @kchibisov @rib
=> Bump MSRV to 1.60

CHANGELOG.md, Cargo.toml, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/menu.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/util/cursor.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Part of https://github.com/rust-windowing/winit/pull/2427.
Concrete improvements in `objc2` which can be seen in this PR:
- `msg_send!` can now return `bool` without special handling.
- Types in `msg_send!` are now required to be `Encode`. This helped catching a lot of undefined behaviour, which are fixed in https://github.com/rust-windowing/winit/pull/2138 and https://github.com/rust-windowing/winit/pull/2428.
Checklist:
=> Initial transition to `objc2`

src/lib.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/appkit/application.rs, src/platform_impl/macos/appkit/mod.rs, src/platform_impl/macos/appkit/responder.rs, src/platform_impl/macos/appkit/view.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/util/mod.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Part of https://github.com/rust-windowing/winit/pull/2427.
Use the new `objc2::declare_class!` macro to vastly improve our code that declares custom classes. Notable improvements:
- The selector and the method implementation are right next to each other (instead of being split out over the file).
- You can use `self` very naturally
- You don't have to worry about ABI details like the extra `Sel` parameter
- You can now take and return `bool` directly in delegate methods
Further improvements (e.g. to ivar handling) will come later. Will also fix the formatting of `view.rs` and `window_delegate.rs` in a subsequent PR, to keep the diff smaller.
=> Clean up macOS class declaration

src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs
Follow-up on #2458, kept out of that to keep the diff smaller. `rustfmt` can do this automatically, if the macro syntax is `declare_class!(...);` instead of `declare_class! { ... }`.
=> Fix `declare_class!` indentation

Cargo.toml, examples/web.rs, examples/web_aspect_ratio.rs
Adds a new example that creates a web canvas that fills an aspect-ratio'd div
The main point of this example is to demonstrate the functionality provided by https://github.com/rust-windowing/winit/pull/2074
The example can land before or after, but landing it before will make it easier to test #2074
Another benefit of this example is demonstrating how to create a web canvas that fills up the available space while maintaining the same aspect ratio.
Although this is slightly out of scope of winit I believe it would be extremely useful to provide as figuring out what combination of html elements and css configuration I needed to get this to work was surprisingly difficult for me even though I've been dabbling with web technologies for ages.
Pinging @liamolucko for feedback as this relates to …
=> Add web_aspect_ratio example

CHANGELOG.md, FEATURES.md, examples/window_resize_increments.rs, src/platform/macos.rs, src/platform/x11.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Pretty basic "I hope it works" implementation, only tested on X11, can test on a mac in a few days.
Once this is reviewed->merged->released I hope to finally make Alacritty _not suck_, heh
~The branch is based on the #2410 because I kept moving the test window to the other screen, I'll rebase once it's merged,~ done
~Currently this is a draft to run your CI and to get reviews.~ should be ready
Closes #2020
=> Allow changing resize increments after window creation

.github/workflows/ci.yml
This reverts commit 4895a29e92a6fa9f7640558bd2676cdc48f66d8d.
GitHub Actions' runner-images readded this environment variable on my request [1] as it wasn't strictly related to the deprecated and removed `ndk-bundle` NDK release.  Back out of the workaround to keep CI scripts tidy.
[1]: https://github.com/actions/runner-images/issues/5879#issuecomment-1197811704
=> Revert "ci: manually point ANDROID_NDK_ROOT to latest supplied version"

src/platform_impl/macos/window.rs
Introduced in https://github.com/rust-windowing/winit/pull/2411.
=> macOS: Fix `WindowBuilder::with_resize_increments`

Cargo.toml, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/observer.rs
Use the definitions that `core_foundation` exposes (almost the same, except `CFRunLoopSourceContext::perform` is not nullable, so we account for that as well).
=> Remove custom definition of Core Foundation runloop functionality

src/platform_impl/ios/event_loop.rs, src/platform_impl/macos/observer.rs
Introduced in https://github.com/rust-windowing/winit/pull/2479; turns out the definitions were not entirely equal, the `kCFRunLoopEntry` that we were using previously was defined as `0` while the correct value is `1` (which meant the `unimplemented!()` branch suddenly started triggering)
=> Fix runloop entry

CHANGELOG.md, src/platform_impl/linux/wayland/seat/text_input/handlers.rs
=> wayland: Clear preedit if there is no pending preedit.

CHANGELOG.md, Cargo.toml
Winit uses raw-window-handle of version 0.4.3,
but only 0.4.0 was specified.
=> Specify minimum supported version for RWH 0.4

CONTRIBUTING.md
This should help maintainers to handle releases and
establish a non-blocking workflow.
Fixes #2454.
--
cc @chrisduerr since this is ported from alacritty and I'm not sure how we should do that wrt `-dev` versions in libraries.
=> Add release process

src/event_loop.rs, src/monitor.rs, src/platform/ios.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/mod.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
Change things internally such that platform implementations don't have to import `Fullscreen`, `MonitorHandle` and `VideoMode` from the top-level crate.
- This is really a "it compiles, it works" change, but have tested on macOS and iOS
=> Simplify internal type construction

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
Workaround for https://github.com/rust-windowing/winit/issues/2504 to support keybinding based on `ReceivedCharacter`. I currently don't see a possibility for a clean solution in the short run without API changes (extra fields or keybinding api)
=> Windows, emit `ReceivedCharacter` on system keybinds

CHANGELOG.md, FEATURES.md, examples/child_window.rs, src/platform/x11.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/window.rs
This PR can create windows with a user-specified parent window. It's intended to realize what discussed in issue https://github.com/rust-windowing/winit/issues/159 for X11.
This is a retry https://github.com/rust-windowing/winit/pull/2096. In that time I was not aware CI fails so passed long time, the master branch proceeds so much from that PR so I cannot follow changes.
=> [X11] Create windows with a parent window

CHANGELOG.md, src/platform_impl/linux/x11/ime/callbacks.rs
Fixes #2510.
--
I can't repro the initial issue in the first place though and it doesn't make any sense, but it was bisected to the recent change.
=> On X11, fix IME crashing without available styles

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
I am not sure if this is the right fix or not because I am not familiar with the keyboard handling in winit and win32 in general and I actually found this fix by trial and error with keyboard related handling branches.
1. winit@[92fdf5ba](https://github.com/rust-windowing/winit/commit/92fdf5ba85f920262a61cee4590f4a11ad5738d1)
2. PR@[985000e1](https://github.com/rust-windowing/winit/pull/2521/commits/985000e11170cda6a30585142e1688793734c8cd)
=> Fix menubar focus using `Alt` on Windows

CHANGELOG.md, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Porting https://github.com/tauri-apps/tao/commit/c50529b3ee453c73acf36bd7e1cd7c14669951f3
=> Add `Window::title` getter on Windows and macOS

src/platform_impl/macos/window_delegate.rs
Fixes https://github.com/rust-windowing/winit/issues/2520
These were incorrectly named (`Fullscreen` instead of `FullScreen`, notice the big "S").
- Introduced in https://github.com/rust-windowing/winit/pull/2458 which has not been released yet, so no need to note this in the changelog.
=> macOS: Fix overridden fullscreen selectors

CHANGELOG.md, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
```
panic:  uncaught panic: "expected screen" at .cargo/git/checkouts/winit-560a7c8630e332ba/a8d2a7e/src/platform_impl/macos/window.rs:1071:40
```
=> Fix panic in current_monitor_inner

CHANGELOG.md, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
=> On Windows, fix icons specified on `WindowBuilder` not taking effect for windows created after the first one

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, FEATURES.md, README.md, src/event_loop.rs, src/platform/android.rs, src/platform_impl/android/mod.rs
This is a follow up on the discussion here: https://github.com/rust-windowing/winit/issues/2293
This updates the Android backend to use the [android_activity crate](https://github.com/rib/android-activity) instead
of [ndk-glue](https://github.com/rust-windowing/android-ndk-rs/tree/master/ndk-glue). This solves a few issues:
1. The backend is agnostic of the application's choice of Activity base class
2. Indirect support for `GameActivity` also implies support for `AppCompatActivity` based applications (not possible with `NativeActivity`)
3. Winit is no longer responsible for handling any Java synchronization details, since these are encapsulated by the design of android_activity
4. The backend no longer depends on global / static getters for state such as the native_window() which puts it …
=> Android: rework backend to use android_activity crate

src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs
Fix our handling of `NSWindowLevel` values.
This worked previously because we only used `NSWindowLevel::Normal` and `NSWindowLevel::Floating`, whose values happened to be almost correct anyways.
Discovered while reviewing https://github.com/rust-windowing/winit/pull/2534
=> macOS: Fix `NSWindowLevel` values

.github/workflows/ci.yml, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/menu.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs
Since the MSRV of development dependencies can easily be bumped without it affecting the MSRV of the published version of `winit`.
Done because the `image` crate now has an MSRV of 1.61: https://github.com/image-rs/image/commit/11492233cd59fc0e2701ab12cd00607e9bbf125c
=> Only build, but don't run tests in MSRV CI

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_loop.rs
Port of https://github.com/tauri-apps/tao/commit/d2c6a91c4588bab460ef5924b10cfb224c1336c6
=> On macOS,  add `EventLoopBuilderExtMacOS::with_activate_ignoring_other_apps`

src/platform_impl/macos/app_delegate.rs
Accidentally introduced in #2551, because I forgot to actually test the thing...
=> macOS: Fix ApplicationDelegate::init

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs
Port of https://github.com/tauri-apps/tao/commit/33fdeab6291d4aef8ea9facb58fe9583f6c1aaf3
=> On macOS, add documentEdited APIs

CHANGELOG.md, src/platform_impl/windows/mod.rs
Fixes https://github.com/rust-windowing/winit/issues/2562 and probably fixes https://github.com/rust-windowing/winit/issues/2563.
This was a mistake in https://github.com/rust-windowing/winit/pull/2057.
We used `winapi`'s [`GET_XBUTTON_WPARAM`](https://docs.rs/winapi/0.3.9/src/winapi/um/winuser.rs.html#1297-1299) before which is using `HIWORD` instead of `LOWORD`.
=> Fix value in `MouseButton::Other` on Windows

.github/workflows/ci.yml
Since https://github.com/dvc94ch/cargo-subcommand/pull/23 `cargo-apk` now strictly searches for workspaces first before committing to finding the right package _within said workspace_, and bails when no package was selected since we don't support selecting (building, packaging, running) >1 target currently.
Perhaps it's a bit hash to enforce this on free-form `cargo apk --` invocations, but it is what it is.
=> ci: Specify to build `winit` package when invoking `cargo-apk`

Cargo.toml
This simply bumps the android-activity dependency from `0.4.0-beta.1` to `0.4.0` since `0.4` was release https://crates.io/crates/android-activity (https://github.com/rib/android-activity/pull/39)
=> android: depend on android-activity 0.4.0

CHANGELOG.md, src/platform_impl/windows/window.rs
=> On Windows, revert window background to an empty brush to avoid white flashes when changing scaling

CHANGELOG.md, examples/window_buttons.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/appkit/control.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
Porting https://github.com/tauri-apps/tao/commit/a50fd867b3df033dff077f5320b4b7037b04e454
=> On Windows and macOS, add API to enable/disable window controls

src/platform_impl/macos/util/async.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
=> Refactor `SharedState` so that it is no longer behind an `Arc`

CHANGELOG.md, src/platform_impl/macos/mod.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/window.rs
Part of https://github.com/rust-windowing/winit/issues/2464.
Historically we've been using `Queue::main().exec_async` (`dispatch_async_f`), tracing back to https://github.com/rust-windowing/winit/commit/b4925641c973979a38743202b4269efe09ac43b4 which was included in https://github.com/rust-windowing/winit/pull/853. This works by putting the closure onto a queue, and then executing it on the main thread at a later point (in spirit similar to doing a `thread::spawn` and forget).
While this works, it is very brittle, since any code that may run after such a call will read stale data until the event loop has run once more. Instead, we'll use `dispatch_sync_f`, which will block the calling thread until the main thread has had a chance to run it, meaning that whatever state changes may have …
=> macOS: Run tasks synchronously on main thread instead of asynchronously

src/platform/ios.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/uikit/application.rs, src/platform_impl/ios/uikit/coordinate_space.rs, src/platform_impl/ios/uikit/device.rs, src/platform_impl/ios/uikit/event.rs, src/platform_impl/ios/uikit/mod.rs, src/platform_impl/ios/uikit/screen.rs, src/platform_impl/ios/uikit/screen_mode.rs, src/platform_impl/ios/uikit/touch.rs, src/platform_impl/ios/uikit/trait_collection.rs, src/platform_impl/ios/uikit/view.rs, src/platform_impl/ios/uikit/view_controller.rs, src/platform_impl/ios/uikit/window.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs
The iOS equivalent to https://github.com/rust-windowing/winit/pull/2465.
=> Reduce amount of `unsafe` on iOS

CHANGELOG.md, src/platform/x11.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/dnd.rs, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/inner.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/ime/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/hint.rs, src/platform_impl/linux/x11/util/memory.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/util/modifiers.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs
This PR removes the `xlib_xconnection()` function from the `platform::x11` module. This was previously used by `glutin`, but is not used anymore. Removing this lets me make some types in the `platform_impl::x11` module `pub(crate)`, which makes it easier to identify what's being used and what isn't.
=> m: Remove xlib_xconnection from public interface

Cargo.toml
#2586 added `cfg` aliases, but these aliases don't match up with the `Cargo.toml` configuration, especially when it comes to `free_unix`. This PR aligns the `Cargo.toml` configuration with `build.rs`.
=> bugfix: Ensure all free unixes can build

CHANGELOG.md, FEATURES.md, examples/window_drag_resize.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/util/wm.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Implements functionality required to resolve #725 for X11. Uses the example from #2003. Only supports X11 on Linux for now. Wayland support will require a future release of sctk with the additional protocol added to the API. And there's some substantial changes in sctk at the moment so upgrading this library will be a bit of a chore. Code from #2003 for Windows support could be added on top of this.
=> feat(x11): Add Window::drag_resize_window

CHANGELOG.md, src/platform_impl/ios/event_loop.rs
Commit `ee88e38f` introduced changes to add safe abstraction over UIApplication (among other objc types). However, the assertion that the `UIApplication` shared instance should be `null` got accidentally flipped (was comparing the shared instance to null, became checking that shared instance is `Some`). This broke `winit` based iOS apps.
This PR reverses that assertion and make `winit` based iOS apps run again.
=> iOS: fix accidentally flipped assertion

FEATURES.md
Currently only macOS and Windows, since I somewhat know how versioning works there. Missing iOS and Android! Would it make sense to do a similar thing for Wayland and X11?
I think we should do something similar for WASM, but unsure how, maybe it should be as verbose as specifying each browser an the version that it is expected to work on?
Spawned by https://github.com/rust-windowing/winit/pull/2409#issuecomment-1207266938.
=> Note the platform versions that `winit` supports

CHANGELOG.md, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Provide a hint to system compositor whether the window is opaque or not. Only implemented on macOS and Wayland for now.
=> Add `Window::set_transparent`

CHANGELOG.md, src/event_loop.rs
This PR adds a `set_wait_timeout` function to compliment the `set_wait_until` function on `EventLoop`. It basically just adds the timeout to `Instant::now()` and uses that in `set_wait_until`.
=> feat(event loop): Add a function to ControlFlow for waiting on a Duration

CHANGELOG.md, src/platform_impl/windows/window.rs
=> Fix `Window::set_minimized(false)` when window was minimized by `Win+D`

CHANGELOG.md, src/platform_impl/android/mod.rs, src/platform_impl/ios/uikit/window.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/seat/keyboard/handlers.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Porting https://github.com/tauri-apps/tao/commit/7d2eeeebb4da15e9aeda9bf17e80ebdf23c95cee
=> Add `Window::has_focus`

CHANGELOG.md, src/platform/x11.rs, src/platform_impl/linux/mod.rs
This commit fixes it, by not updating the `latest_error` when any of the hooks handled the error, otherwise it'd interfere with the winit's error checking.
=> On X11, fix errors bleeding from hooks handling them

CHANGELOG.md, src/platform_impl/macos/view.rs
On macOS, `otherMouseDown:` and `otherMouseUp:` callbacks always result in a `MouseButton::Middle` event.
=> Fix middle/other mouse buttons on macOS

CHANGELOG.md, Cargo.toml, build.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/env.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/protocols.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs, src/platform_impl/linux/wayland/seat/touch/handlers.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/window.rs, wayland_protocols/fractional-scale-v1.xml
This adds support for the fractional scaling on Wayland via the wp-fractional-scale protocol.
--
Follow-up to https://github.com/rust-windowing/winit/pull/2369
cc @mahkoh given that I can't push to your branch.
=> On Wayland, add support for fractional scaling

CHANGELOG.md, Cargo.toml, src/platform_impl/web/web_sys/event_handle.rs
The web backend for `winit` registers the `onmousedown`, `onmouseup`, and `onmousemove` events on the global Javascript window object. When the `winit` window is destroyed, however, these events are not properly removed. This is because the events are registered with the `capture: true`, but `capture: true` is not passed to the appropriate `removeEventListener` call. This PR updates the web backend to pass the event creation options to the event removal function. This prevents errors in which the Javascript runtime tries to invoke the event listener closures after they are destroyed.
=> Properly remove window mouse event listeners

CHANGELOG.md, src/platform_impl/macos/app_state.rs
This sadly undos #1901 again - cc: @xiaopengli89
The problem is that `handle_redraw` has no threading/re-entrance protection whatsoever - when calling `set_maximized` from within an event it will deadlock (which is ofc much worse than what #1901 tried to address)!
I ran into this when testing this egui PR https://github.com/emilk/egui/pull/2292
-----------
=> [MacOS] Fix deadlock on maximizing window from event callback

src/event.rs
As discussed in https://github.com/rust-windowing/winit/pull/2636
=> Note status quo on macOS and iOS redraws

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
Porting https://github.com/tauri-apps/tao/commit/e42ff07190c37b6b8a7808900133838247a730df
Fixes https://github.com/rust-windowing/winit/issues/2580
=> Add `WindowBuilder::with_active`

CHANGELOG.md, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Makes WindowAttributes public and add window_attributes() getter to WindowBuilder.
In version 0.27, the WindowAttributes struct was made private, but this removed the ability to introspect the default WindowBuilder values.
=> Allow introspection of WindowBuilder default values.

src/platform_impl/ios/window.rs, src/window.rs
Adjust documentation to make it clear that `Window::set_decorations` has no effect on mobile/web platforms, and `is_decorated` always returns true on these platforms. After this doc change, it should be clear that the client should draw decorations when `window.fullscreen().is_none() && !window.is_decorated()`.
It seems there is still no explicit API to determine whether a window *should* have decorations (i.e. is on a windowing platform, not a mobile or web platform). It seems odd that `Window::fullscreen` returns `None` on Android. This is a separate issue.
To make behaviour more consistent across platforms, the `log::warn` messages were removed from iOS. (Possibly the same should be done on other methods; I didn't investigate.)
=> Clarify Window::set_decorations/is_decorated behaviour

build.rs
The docs state that it accepts `PATH`, but not like the env variable. So to make it work each `PATH` should be emmited from each `println!`.
Fixes #2657.
=> Fix rerun-if-changed emmiting from build.rs

CHANGELOG.md, examples/ime.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/seat/text_input/handlers.rs, src/platform_impl/linux/wayland/seat/text_input/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/shim.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
[Wayland](https://docs.rs/wayland-protocols/latest/wayland_protocols/wp/text_input/zv3/client/zwp_text_input_v3/enum.ContentPurpose.html) and [macOS](https://developer.apple.com/documentation/appkit/nstextcontenttype) support IME purposes. I have implemented it for Wayland only, because I don't have access to macOS. XIM and Windows IMM do not seem to support it. (Although #2614 removes XIM and the successor may support IME purposes.)
This PR adds the purpose `Password` (directly supported by both Wayland and macOS) and `Terminal` (needed for https://github.com/alacritty/alacritty/issues/6644). I don't know if it makes sense to support more purposes (for example, all that Wayland supports). The `ImePurpose` enum is non exhaustive, so new purposes can be added without breaking change.
=> Add support for setting the IME purpose

examples/monitor_list.rs
The old version of `examples/monitor_list.rs` simply used the debug repr of `MonitorHandle`, which on Wayland looks like this:
```
[examples/monitor_list.rs:11] window.available_monitors().collect::<Vec<_>>() = [
MonitorHandle {
inner: Wayland(
MonitorHandle {
proxy: wl_output@13,
},
),
},
]
[examples/monitor_list.rs:12] window.primary_monitor() = None
```
Updated version prints useful, more platform consistent info:
```
name: eDP-1-unknown (InfoVision)
size: PhysicalSize { width: 1920, height: 1200 }
position: PhysicalPosition { x: 0, y: 0 }
refresh_rate: Some(59999) mHz
scale_factor: 1.0
mode: PhysicalSize { width: 1920, height: 1200 }, depth = 32 bits, refresh rate = 59999 mHz
```
=> examples/monitor_list: properly print output

src/platform_impl/windows/event_loop.rs
Fixes #2661 by detecting if the window has a native menu before delegating to the modal menu loop.
=> Windows: Fix Alt key press entering menu loop

CHANGELOG.md, src/platform_impl/macos/view.rs
This commit clears the currently marked text on `Ime::Commit`, so normal `ReceivedCharacter` input can continue.
--
@madsmtm I was thinking of using `unmarkText` but I don't really want extra `Preedit` after the `Commit`. Do I need that extra stuff with context that is present in `unmarkText`?
=> On macOS, fix `Ime::Commit` persisting

CHANGELOG.md, Cargo.toml, README.md
Some of the patches that might be worth merging for `0.28.0`:
If I've missed something or you want some bug to be fixed for `v0.28.0` let me know.
Be aware that the next major release after the `0.28.0`(`0.29.0`) will contain the new Wayland backend (updated to new wayland-rs) and likely new X11 backend(mixture of Xlib + Xcb, instead of raw xlib).
--
CC of some main downstream consumers(if you're not interested in getting notified about release planning in winit let me know, so I won't even CC you again).
- `bevy`: @alice-i-cecile, @cart
- `egui`/`eframe`: @emilk
- `iced`: @hecrj
- `ggez`: @PSteinhaus
- `tauri` : @amrbashir
- `nannou`: @mitchmindtree
If you have some issues with winit that you want fixed for 0.28.0 let me know while we're in release preparation stage, so I include them …
=> Winit version 0.28.0

CHANGELOG.md, Cargo.toml, README.md
This commit does not represent a release and only
synchronizes CHANGELOG from the latest release.
=> Bump version on master

CHANGELOG.md, src/platform_impl/linux/wayland/seat/keyboard/handlers.rs, src/platform_impl/linux/wayland/seat/pointer/handlers.rs
In some scenarios of window dropping the callback for keyboard may run after the window was dropped.
=> Fix window drop on Wayland

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs
In the current Win32 backend, a `Lazy<u32>` is used to initialize and store `winit`-specific window messages. However, a `Lazy` incurs two extra pointers on top of the word that the `u32` takes up. I have created a new racy implementation using an `AtomicU32` that only uses one additional pointer. This should be a mild improvement over the current setup.
=> Replace lazy window message ids with a slimmer version

src/platform_impl/windows/event_loop.rs
It's easier to debug if the waiting thread has an explicit name.
Also, quick question, is there any particular reason why we use the waiter thread instead of just `WM_TIMER`? I'm guessing that `WM_TIMER` doesn't play well with `timeBeginPeriod`.
=> m(windows): Name the waiter thread

CHANGELOG.md, src/event_loop.rs
The trait is already implemented for `EventLoopWindowTarget`, which `EventLoop` derefs to, but that is not enough when using an API that takes a `T: HasRawDisplayHandle + 'static` (because the API takes ownership of the display handle, in an attempt to offer a safer API to the user than what crates typically do). Also implementing the trait for `EventLoop` itself solves this problem.
(admittedly the use cases for this are rather limited – consuming the `EventLoop` like this makes it impossible to actually handle events, and so makes windows useless too, but it *is* handy when you need a display handle without actually wanting to draw anything; in my specific use case, in order to open a connection to VA-API)
=> Implement `HasRawDisplayHandle` for `EventLoop`

CHANGELOG.md, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
=> On macOS, set resize increments only for live resize

CHANGELOG.md, src/platform_impl/web/window.rs, src/window.rs
=> Add support for `Window::theme` on the web

CHANGELOG.md, src/platform_impl/macos/window.rs
The synthetic focused event was queued after the real event was send leading to focused issues on startup.
Fixes #2695.
=> On macOS, fix initial focused state

CHANGELOG.md, examples/fullscreen.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
I'm an Alacritty user and ran into #1118 (via alacritty/alacritty#2741). It's tagged with "good first issue" and someone helpfully left some details on the AppKit side of things so I thought I'd take a crack at it. I'm kind of a Rust newb (and even bigger AppKit/ObjC newb) so happy for any feedback if this should be tackled in a different way.
=> [macOS] resize simple fullscreen windows on windowDidChangeScreen

src/event.rs
This change is motivated by the distinct use cases of the articles 'a'
and 'an'. In this case 'a' is more suitable as 'do' begins phonetically
with a consonant.
See documentation: https://en.wiktionary.org/wiki/an#Usage_notes
=> Changed 'an' to 'a' in documentation

CHANGELOG.md, Cargo.toml, src/platform_impl/macos/view.rs
Fixes https://github.com/rust-windowing/winit/issues/2722 by patching `objc2` instead, and using version ranges to allow the patched version to be selected.
If the user has `accesskit_macos` in their dependency tree, this will not work until @mwcampbell uses `objc2 = ">=0.3.0-beta.3, <0.3.0-beta.4"` in that.
- ~Currently very limited internet, and having a few problems with `cargo update`, so I can't test this fully myself right now. I have tested that the version resolution works though!~
=> Fix macos memory leaks

Cargo.toml, build.rs
This changes all uses of `target_arch = "wasm32"` to `target_family = "wasm"`, which also covers the `wasm64-unknown-unknown` target.
This was introduced in [Rust v1.54](https://github.com/rust-lang/rust/blob/1.68.0/RELEASES.md#compiler-14).
Not sure if I should add a changelog entry?
=> On Web, use `target_family = "wasm"`

.github/workflows/ci.yml, deny.toml
[cargo-deny](https://github.com/EmbarkStudios/cargo-deny) is an amazing tool that protects from:
* duplicated crates (code bloat)
* copy-left licenses in the dependency tree
* RUSTSEC advisories
Try it:
```sh
cargo install cargo-deny
cargo update
cargo deny --all-features --log-level error check
```
(**EDIT**: removed wrong stuff about rustsec and duplicated deps due to me using an outdated `Cargo.lock`)
=> Add cargo-deny check to CI

CHANGELOG.md, src/platform_impl/macos/monitor.rs
```
uncaught panic: "attempt to divide by zero" at /Users/X20230112120246_ssea_lrtse_cpfx/.cargo/git/checkouts/winit-c2fdb27092aba5a7/3fd7384/src/platform_impl/macos/monitor.rs:233:19
```
=> Fix potential panic

CHANGELOG.md, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/window.rs
Fixes #2756.
This fixes a crash when calling `Window::set_ime_position` from a thread that is not the main thread.
I'm not familiar with the codebase, so feel free to give feedback if I should change anything!
=> Run `Window::set_ime_position` on main thread on macOS

CHANGELOG.md, src/platform_impl/macos/view.rs
--
That was unfortunate, but no-one noticed because everyone was testing with IME enabled.
=> On macOS, fix `key_Up` being ignored without IME

CHANGELOG.md, src/platform_impl/macos/appkit/screen.rs
`deviceDescription` should be called in autoreleasepool.
=> Fix device description leak

CHANGELOG.md, Cargo.toml, examples/cursor.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/macos/appkit/cursor.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs, src/window.rs
This crate is aimed to simplify handling of cursor icon across various crates and be used in the public API.
=> Use `cursor-icon` crate for `CursorIcon`

CHANGELOG.md, src/platform_impl/macos/view.rs
Fixes: d15feb5cfa (On macOS, fix empty marked text)
--
Tested on macOS. Will backport to 0.28.6.
=> On macOS, fix backspace emission on preedit clear

CHANGELOG.md, src/dpi.rs, src/monitor.rs
The lowest hanging fruit tastes the sweetest.
=> Implement PartialOrd/Ord for dpi module types

src/platform_impl/linux/wayland/window/state.rs
Making the cursor back visible was simply forgotten and it was always hiding instead.
Fixes: 24960988902 (Update wayland-rs to 0.30.0)
Fixes: #2820.
=> On Wayland, fix Window::set_cursor_visible(true)

CHANGELOG.md, src/platform_impl/web/web_sys/mod.rs
See https://github.com/rust-windowing/winit/issues/2733, https://github.com/gfx-rs/wgpu/issues/3620 and https://github.com/gfx-rs/wgpu/pull/3690 for more information.
This is a follow-up to https://github.com/gfx-rs/wgpu/pull/3690. Now renderer are responsible for changing the internal canvas size. Winit will still continue to adjust the **visual** size of the canvas.
Both `wgpu` and `softbuffer` handle this correctly. Happy to check and make PR's to other crates that come to mind.
Fixes #2733.
=> Don't change the internal canvas size

CHANGELOG.md, src/platform_impl/web/event_loop/runner.rs
Currently, when calling `Window::request_redraw()` from outside the event loop, for example from an async background task, it will not wake up the event loop.
This fixes it by simply calling the same internal function used to wake up the event loop by sending a `UserEvent`, I hope that is correct.
Fixes #2019.
=> On Web, wake event loop on `request_redraw()`

src/platform/scancode.rs, src/platform_impl/linux/common/keymap.rs, src/platform_impl/linux/mod.rs
Old winit was using linux scancodes, so this should make it backward compatible with itself.
=> Use linux scancode values for KeyCodeExtScancode

CHANGELOG.md, examples/window_buttons.rs, examples/window_debug.rs, src/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/raw_input.rs
Renamed `EventLoopWindowTarget::set_device_event_filter` to `EventLoopWindowTarget::listen_device_events` and `DeviceEventFilter` to `DeviceEvents` and appropriately reversed its variants according to https://github.com/rust-windowing/winit/issues/2591#issuecomment-1353254710.
Could only test it on Linux.
Fixes #2591.
=> Renamed `DeviceEventFilter` to `DeviceEvents`

CHANGELOG.md, Cargo.toml, src/platform_impl/web/web_sys/canvas.rs, src/window.rs
Currently the behavior of `Window::set_fullscreen()` on Web queues the request to the current or next keyboard or mouse event. This doesn't work if `Window::set_fullscreen()` is called asynchronously outside the event loop.
This was probably done to satisfy the [transient activation](https://developer.mozilla.org/en-US/docs/Glossary/Transient_activation) [requirement](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#security) for `requestFullscreen()`. But transient activation doesn't run out during the event loop, it's time based, usually one second.
This PR adjusts `Window::set_fullscreen()` to immediately call `requestFullscreen()`, only on failure a request is queued. This required some custom imports because the API was changed in the spec to return a …
=> On Web, fix async `Window::set_fullscreen`

Cargo.toml, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
Closes #2763 by replacing `mio` with `calloop` in the X11 backend.
=> Replace mio with calloop in the X11 backend

CHANGELOG.md, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/canvas/mouse_handler.rs, src/platform_impl/web/web_sys/canvas/pointer_handler.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/mod.rs
When a pointer button is already pressed, new button presses/releases won't go through `pointerdown`/`pointerup`, but through `pointermove`, which is weird, but this PR now handles this correctly.
Along the way I inlined some unnecessary variables and passed button identifiers into `MouseButton::Other` directly instead of subtracting 3 (I have no clue why this was originally made).
Fixes #2455.
Cc #2475.
Replaces #2731.
=> Process pointer button events when a buttons is already pressed

CHANGELOG.md, Cargo.toml, src/keyboard.rs, src/platform/ios.rs, src/platform_impl/ios/uikit/view_controller.rs, src/platform_impl/macos/appkit/application.rs, src/platform_impl/macos/appkit/event.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/view.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/windows/keyboard_layout.rs, src/platform_impl/windows/window_state.rs, src/window.rs
- [❎] Tested on all platforms changed
- [✅] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [❎] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [❎] Created or updated an example program if it would help users understand this functionality
- [❎] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented
I used the largest set of `#[derive()]` traits on each `bitflags!` instance, so there should be no/minimal compile errors.
I have tested on windows, iOS, mac, and wasm. I have not yet been able to test on Linux or Android, but I used the widest range of derives on those platforms, so they should hopefully not break.
=> Update the `bitflags` dependency

CHANGELOG.md, src/platform_impl/web/web_sys/canvas/pointer_handler.rs, src/platform_impl/web/web_sys/event.rs
This PR handles coalesced pointer events, which dramatically increases the resolution of pointer inputs.
Safari doesn't currently supports this, which is automatically detected.
See https://www.w3.org/TR/pointerevents3/#coalesced-events for more information.
Cc https://github.com/rust-windowing/winit/issues/1392.
=> On Web, handle coalesced events

src/keyboard.rs, src/platform/ios.rs
Some bitflags in public API lost their `Hash` implementations.
Fixes: 31ebc5caf (Update `bitflags` to `2.0`)
=> Add missing `Hash` impls on bitflags

.github/workflows/ci.yml
This somehow was left un-noticed.
=> Update last action run to v3

CHANGELOG.md, Cargo.toml, examples/control_flow.rs, examples/timer.rs, src/event.rs, src/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/state.rs
This replaces [`instant`](https://crates.io/crates/instant) with [`web-time`](https://crates.io/crates/web-time).
Currently `instant` is unmaintained an has a bunch of issues:
- https://github.com/sebcrozet/instant/issues/21
- Panics in [`Instant::duration_since()`](https://github.com/sebcrozet/instant/blob/78e336db632f1f2f7350e2b2385c23d263178251/src/wasm.rs#L24-L27), [unlike std, which currently saturates](https://doc.rust-lang.org/std/time/struct.Instant.html#method.duration_since).
- https://github.com/sebcrozet/instant/issues/49
- No support for [`target_feature = "atomics"`](https://github.com/daxpedda/web-time/blob/b64662bf7aac4f856d681d0053ee1d47294820d4/src/web/instant.rs#L25-L26).
I also gated the dependency behind the Wasm target.
Replaces #2738.
=> Replace `instant` with `web-time`

CHANGELOG.md, Cargo.toml, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
Should fix the `cargo deny` errors we've been getting on #2812
=> Port to windows-sys v0.48.0

CHANGELOG.md, src/platform_impl/web/web_sys/canvas/pointer_handler.rs
Currently pen input was treated as mouse input, this PR will ignore pen input.
I believe this also aligns with other backends, but would like to get confirmation.
=> Ignore pen input on Web

CHANGELOG.md, Cargo.toml, clippy.toml, examples/web.rs, examples/web_aspect_ratio.rs, src/platform/web.rs, src/platform_impl/web/async.rs, src/platform_impl/web/event_loop/proxy.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/media_query_handle.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/web/web_sys/scaling.rs, src/platform_impl/web/web_sys/timeout.rs, src/platform_impl/web/window.rs, tests/send_objects.rs, tests/sync_object.rs
This implements `Send` and `Sync` for `Window` and `Send` for `EventLoopProxy` on Wasm to make them implement the same traits on all platforms.
I took some inspiration from [`MainThreadSafe` on macOS](https://github.com/rust-windowing/winit/blob/77f8e511e965354a4b827cfb1ca197e9e51e6ded/src/platform_impl/macos/util/async.rs).
It's implemented in a way that if you call this from the `Window` it will do nothing special and just call the appropriate method on the `Window`, as before. Therefor, except a single `Rc<Cell<bool>>` to `Arc<AtomicBool>` change, there is no overhead if Wasm is only used single-threaded.
If used in a multi-threaded environment from a worker, it will use a `mpsc::Sender` to do it's work on the main thread. Currently this is implemented by just sending a boxed function …
=> On Web, implement `Send` and `Sync` where appropriate

CHANGELOG.md, examples/web.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs
Until now the internal canvas size was used to determine it's current size, even when calculating the new size on a scale factor change, which was kind of problematic already as discussed in #2778.
This PR change that to track the canvas size we set in Winit, so we can use it for recalculations and to report to the user what we set it to when calling `Window::inner_size()`.
I briefly explore if it would be possible to query it instead of having to track it, unfortunately there is no reliable way through JS to track the CSS width and height we set ourselves. The closest is `getComputedStyle()`, which has it's own set of problems, among them the fact that it will always return zero until the canvas is actually inserted into the window.
Related #2778.
Fixes #2524.
=> Use correct canvas size for scale factor change

CHANGELOG.md, Cargo.toml, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/media_query_handle.rs, src/platform_impl/web/web_sys/scaling.rs
This improves on the original implementation: #1690.
- Remove the use of `MediaQueryListEvent`, which isn't supported by Safari until v14. The callback parameter differs depending on browser support. Without `MediaQueryListEvent` support `MediaQueryList` is passed ([spec](https://github.com/w3c/csswg-drafts/blob/2dc7a6b3ebeedb502b428c3c9a8e19e90148bd46/cssom-view/Overview.html#L843)). So we instead just clone the `MediaQueryList` into the closure.
- Use accurate scale factors in the media query instead of approximating with min/max, which should avoid any further issues as discussed in https://github.com/rust-windowing/winit/pull/2747#issuecomment-1554549488.
- Always initialize media queries. They should always work unless something is seriously wrong with our code.
Reverts #2599. …
=> Make media queries more robust

CHANGELOG.md, src/platform/android.rs, src/platform_impl/android/mod.rs
Current Android implementation will always mark the volume keys as handled by the application (window) overriding the default operating system behavior. This is a bit unexpected I would argue the opposite would be expected as default, to opt in to override default operating system behavior. 
1. By default volume keys `Volume Up/Down & Mute` will all be marked as unhandled by the application. Letting the operating system handle them.
2. Added a new function `EventLoopBuilderExtAndroid::handle_volume_keys` for applications that want to manually handle the volume keys.
This could be considered a breaking change from a users point of view, even though I would argue this is the "correct" default. So I'm not sure how or if that should be reflected in the `CHANGELOG.md`.
This PR is heavily …
=> Android: Change default implementation to ignore volume keys and let operating system handle them

clippy.toml
Future-proofing by making sure we don't use these methods again.
See #2733 and https://github.com/gfx-rs/wgpu/issues/3620.
=> Disallow more methods

CHANGELOG.md, src/platform_impl/web/event_loop/runner.rs
This makes it so users can ignore the resize suggestion provided by `ScaleFactorChanged` by setting it to the old value. Which is important when using CSS to set a specific size, like `width: 100%, height: 100%` on the canvas, which would be overwritten by Winit.
Related #1491.
Related #1661.
=> On Web, fix scale factor resize suggestion always overwriting the canvas size

src/platform_impl/linux/common/xkb_state.rs
=> Fix for linux aarch64 where c_char is not i8

CHANGELOG.md, src/platform_impl/macos/view.rs
Dropping window may cause panic.
```
thread 'main' panicked at 'view to have a window', src/platform_impl/macos/view.rs:880:32
```
=> Fix panic when destroying window

Cargo.toml, src/platform_impl/web/web_sys/event_handle.rs
I'm a bit lazy to dig up why this was used in the past, but it's definitely not used anymore.
=> Remove unused `EventListenerOptions`

src/platform_impl/web/web_sys/canvas.rs
I'm not entirely sure why `stopPropagation()` is being used, maybe because `preventDefault()` wasn't used back then. In any case, I don't think we want to prevent parents to receive events if they want to.
The call to `cancelBubble` doesn't do anything, it's a getter.
EDIT: See https://github.com/rust-windowing/winit/pull/2873#issuecomment-1586362882, I decided to keep `stopPropagation()` for now.
=> Resume propagation of events

src/platform_impl/web/event_loop/window_target.rs
I just reordered the events on key presses and releases, `ModifiersChanged` is sent first.
This is consistent with pointer events.
=> On Web, send modifiers on key events first

Cargo.toml, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/pointer.rs
Firefox has broken movement values in coalesced events ([Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1753724)), which I fixed in this PR by calculating our own deltas when detecting Firefox.
In this case I use the lack of `pointerrawupdate` support and coalesced event support to detect Firefox and differentiate it from Safari. If Safari implements coalesced events this detection would break and we would have a (very small) increased overhead on Safari because the manual delta calculations we make would be unnecessary. When that happens we would have to do proper browser detection, which we should generally avoid, see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) for more information. Browser support in general is tracked in …
=> Fix pointer deltas on Firefox and send coalesced events together

src/platform_impl/web/event_loop/window_target.rs
Reverts rust-windowing/winit#2879.
Pressing a Shift key and receiving a Shift key modifier beforehand is strange, so it was right the first time.
This aligns with Wayland as well.
=> Revert "On Web, send modifiers on key events first"

CHANGELOG.md, src/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/state.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/timeout.rs
This PR replaces the use of `Window.requestAnimationFrame` with `Window.requestIdleCallback`, which is in line with what `ControlFlow::Poll` is supposed to be:
> When the current loop iteration finishes, immediately begin a new iteration regardless of whether or not new events are available to process.
This is going to make `ControlFlow::Poll` very fast, which is much closer to how other backends work, but it is also gonna consume way more power, which may or may not be desired considering this is Web and running in the browser.
I think a lot of people are using `RedrawRequested` as a VSync source, which it is not as far as I understand. See #2412 for that.
Reverts #1519.
Related #1305.
=> Use `Window.requestIdleCallback()`

CHANGELOG.md, src/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs
This PR intends to implements all `DeviceEvent`s. Additionally `DeviceEvent`s are only emitted according to the setting in `EventLoopWindowTarget::listen_device_events()`.
---
Fixes #2036.
=> On Web, implement `DeviceEvent`s

CHANGELOG.md, examples/window_option_as_alt.rs, src/platform/macos.rs, src/platform_impl/macos/appkit/event.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs
The correct handling of this setting requires to change the events we're getting from the macOS on the fly and call `interpretKeyEvents`, which could affect handling of the next events, meaning that we can't provide them on `KeyEvent`.
--
This is basically old option we had with winit `0.28.0`.
cc @fredizzimo if you want to try it with neovide.
=> Bring `OptionAsAlt` back for macOS

src/platform_impl/linux/wayland/window/mod.rs
=> On Wayland, fix transparency hint not set in new

CHANGELOG.md, examples/ime.rs, src/event.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/ime.rs, src/platform_impl/windows/window.rs, src/window.rs
Rename `Window::set_ime_position` to `Window::set_ime_cursor_area` adding a way to create cursor exclusive zone.
Fixes #2886.
cc @fredizzimo
--
I have no clue how to add it correctly on X11 given that what exactly its area arguments do is obscured.
=> Provide a way to set cursor area for IME cursor

CHANGELOG.md, src/event_loop.rs, src/platform/web.rs, src/platform_impl/web/event_loop/mod.rs
Rebased #2720
It seems to work after rebasing but haven't been able to test in detail yet. It looks like some other recent winit changes broke my canvas sizing so I need to look into that.
=> Allow recreating wasm event loop with `spawn`

src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs
During the migration some logic wrt `none` decorations was lost along the way, however we also now try to ask for client side decorations if the user wants to disable server side decorations.
Fixes #2902.
=> On Wayland, handle `none` decorations

examples/util/fill.rs
Fixes issue on Wayland due to drop order, since TLS is being dropped after the event loop, while it shouldn't. In particular it fixes the crash in the window_run_return example.
=> Disallow cleanup for TLS in examples

Cargo.toml, deny.toml, src/platform_impl/linux/common/keymap.rs, src/platform_impl/linux/common/xkb_state.rs
The layout was hardcoded to zero, so the keys were sent for whatever user configured first.
=> On Linux, fix wrong layout for key_without_modifiers

CHANGELOG.md, Cargo.toml, src/event.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/mod.rs
I'm not certain about this being the right way, so see it as a start of discussion.
In #2261, the web backend was changed to use the `pagehide` event instead of `unload`, to allow the bfcache to be used.
See https://web.dev/bfcache/ for more information about the bfcache (back/forward cache), and https://developer.chrome.com/docs/devtools/application/back-forward-cache/ for how to test it in chrome. Summary from the first resource:
> bfcache is an in-memory cache that stores a complete snapshot of a page (including the JavaScript heap) as the user is navigating away
The problem with winit and the bfcache is that the event loop is destroyed in `pagehide` - which happens before the snapshot is put in the bfcache. So when a user navigates back to the page running a winit program it's no …
=> On Web, map bfcache load/unload to suspend/resume

src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs
Currently multiple event loops can be run at the same time when using `spawn()`, which was not the intention of #2897 and isn't documented as such.
Follow up on #2897.
Cc @grovesNL.
=> Don't allow event loops to run in parallel

src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/window.rs
The change to xinput2 completely disabled IME support, thus we've got a dead keys reporting, because nothing was eating the key events anymore, however that's not what we really need, given that not working IME makes it impossible for some users to type.
The proper solution is to not use Xlib at all for that and rely on xcb and its tooling around the XIM and text compose stuff, so we'll have full control over what is getting sent to the XIM/IC or not.
Fixes #2888.
=> On X11, fix IME not working

CHANGELOG.md, src/keyboard.rs
I'd like to be able to use the KeyCodes as a reproducable chain, so sorting would be nice to have
=> Make KeyCodes Ord

src/platform_impl/ios/ffi.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/appkit/responder.rs, src/platform_impl/macos/appkit/view.rs, src/platform_impl/macos/util/async.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
This is and has always been clear UB, and if Rust happened to optimize external function calls better using this assumption, a lot of stuff in `winit` would be broken.
Instead, we must use interior mutability.
Required to do https://github.com/rust-windowing/winit/issues/2724, since not using interior mutability is a compilation error in `objc2 v0.4`.
=> Stop using `&mut` in Objective-C delegate methods

CHANGELOG.md, src/platform_impl/linux/common/xkb_state.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
Instead of a single `bool` indicating that a key press has occurred and no key has been released since then, we store the scancode of the last pressed key (if it is a key that repeats when held). This fixes a bug where pressing a new key while one is already held down will be flagged as a repeat even though it is obviously not a repeat.
Thanks to @kchibisov for guidance :heart:
=> Improve detection of key repeats on X11

CHANGELOG.md, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/pointer.rs
We should use [`MouseEvent.offsetX`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX) when possible to avoid any inaccurate calculations.
=> On Web, fix touch location accuracy

CHANGELOG.md, examples/multithreaded.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Some systems could resize the window immediately and we'd rather inform the users right away if that was the case, so they could create e.g. EGLSurface without waiting for resize, which is really important for Wayland.
Fixes #2868.
=> Rename `Window::set_inner_size` to `Window::request_inner_size`

src/event.rs, src/platform/web.rs, src/window.rs
Just documenting some Web specific behavior to `Window::(set_)inner_size`.
Cc #2859.
=> Improve Web specific documentation for various APIs 

clippy.toml, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/resize_scaling.rs, src/platform_impl/web/window.rs
This removes unnecessary calls to get `Document` and `CssStyleDeclaration`, not only reducing calls to JS, but also removing a lot of `expect()` calls.
=> On Web, cache commonly used values

CHANGELOG.md, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs, src/window.rs
This implements a bunch of missing methods in `Window` and `WindowBuilder`:
- `Window::set_(min|max)_inner_size()` and `WindowBuilder::with_(min|max)_inner_size()`
- `WindowBuilder::with_position()`
- `WindowBuilder::with_fullscreen()`
- `Window::focus_window()` and `WindowBuilder::with_active()`
Additionally this fixes setting the cursor and the canvas position to use CSS properties instead of (partly) incorrect HTML attributes.
=> On Web, implement and fix missing methods on `Window(Builder)`

CHANGELOG.md, examples/web.rs, examples/web_aspect_ratio.rs, src/platform/web.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
This adds a convenience method, which is probably what every single use of Winit on Web does by hand, to append the canvas to the body.
=> On Web, add `WindowBuilderExtWebSys::with_append()`

CHANGELOG.md, examples/window_tabbing.rs, src/platform/macos.rs, src/platform_impl/macos/appkit/mod.rs, src/platform_impl/macos/appkit/tab_group.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs
This should let the users control macOS tabbing and allow to create windows in tab.
=> On macOS, add tabbing APIs

CHANGELOG.md, src/platform/macos.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/window.rs
Those are global for the application, so it's better to keep them on EventLoopWindowTarget.
=> On macOS, move automatic tabbing setting to ELWT

src/platform_impl/macos/appkit/mod.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs
Set tabbingMode on all macOS windows so that new tabs are correctly created as tabs, rather than separate windows.
See https://github.com/rust-windowing/winit/pull/2956#issuecomment-1634647001
=> Fix new tab creation on macOS

CHANGELOG.md, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/state.rs
It was discovered that on GNOME the click sometimes being swallowed by the mutter's wl_pointer::enter/leave sequences. This was happening due to `xdg_toplevel::move` making the pointer to leave the surface.
To make handling of that more robust, we could start the `xdg_toplevel::move` when the actual pointer motion is being performed.
Links: https://github.com/alacritty/alacritty/issues/7011
Links: https://gitlab.gnome.org/GNOME/mutter/-/issues/2669#note_1790825
=> On Wayland, make the CSD frame double click reliable

examples/window_drag_resize.rs, src/platform_impl/linux/wayland/window/state.rs
This PR makes a little change in the code in order to fix the method which check if the window have decorations by inverting the return value of the function.
This issue was detected when using the [window_resize_increments](https://github.com/rust-windowing/winit/blob/master/examples/window_resize_increments.rs) example on my Arch Linux Gnome desktop.
Additionally, this PR adds a feature on this example allowing to move the window using the system behaviors when borders are disabled
=> Fix window decoration check method for Gnome environment (using libadwaita)

CHANGELOG.md, Cargo.toml, examples/startup_notification.rs, src/event.rs, src/event_loop.rs, src/platform/mod.rs, src/platform/startup_notify.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/types/xdg_activation.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/activation.rs, src/platform_impl/linux/x11/atoms.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs, src/window.rs
The utils in this module should help the users to activate the windows they create, as well as manage activation tokens environment variables.
The API is essential for Wayland in the first place, since some compositors may decide initial focus of the window based on whether the activation token was during the window creation.
Fixes #2279.
--
I'm not sure how to properly integrate it into the winit at this very moment, because we'll have a platform specific event. Well to be fair, we have them already for macOS backend and such (see gestures things).
@notgull do you want to look into impl of X11 part? I've linked the spec in the module, but I'm not sure how to implement it, there's a libstartup-notify, but I don't think we want it? Maybe x11rb could help us here?
=> Add `platform::startup_notify` for Wayland/X11

CHANGELOG.md, FEATURES.md, src/platform_impl/windows/window.rs, src/window.rs
This implementation is based on the `drag_window` feature. Some change may be made before merging.
The documentation have been updated and the mention to the Wayland compatibility has been removed after noticing that I have been implemented by #2676
=> On Windows, add `drag_resize_window` method support

Cargo.toml, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs
We recently added `rustix` as a direct dependency of `winit`, so why not?
Unfortunately this isn't a total removal, for two reasons:
- We still need "libc" for the Xlib XIM implementation, for locales.
- BSD requires libc to check for main-threadedness.
First one we can likely resolve in the near future, not so sure about the second one without using some weird pthreads trick.
The end goal is to reduce our usage of `libc` in `winit` proper, as direct syscalls are significantly faster. Unfortunately they can't be totally removed, as we will be using `libxcb` for the foreseeable future and that uses `libc` whether we like it or not (as well as `pthreads`). Still, the less `libc` calls we make, the better.
=> Replace libc with rustix in some modules

build.rs
Winit fails compilation on unsupported targets. But we didn't account for Emscripten until now, it was recognized as a Wasm and Unix platform.
This correctly account for Emscripten.
Fixes #2970.
=> Correctly detect that we don't support Emscripten

CHANGELOG.md, src/event.rs, src/event_loop.rs, src/lib.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/observer.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs
Considering the possibility of re-running an event loop via `run_ondemand` then it's more correct to say that the loop is about to exit without assuming it's going to be destroyed.
This is one of the follow ups for #2900, assuming that #2767 hopefully lands soon.
_Note: the base for this PR isn't currently set to master, since it's stacked on the changes for #2767_
=> Rename `LoopDestroyed` to `LoopExiting`

CHANGELOG.md, examples/control_flow.rs, examples/web.rs, examples/window.rs, examples/window_ondemand.rs, examples/window_option_as_alt.rs, examples/window_pump_events.rs, examples/window_resize_increments.rs, src/event.rs, src/event_loop.rs, src/lib.rs, src/platform/pump_events.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/view.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/observer.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs
This is one of the follow ups for https://github.com/rust-windowing/winit/issues/2900, assuming that https://github.com/rust-windowing/winit/pull/2767 hopefully lands soon.
The idea that redraw events are dispatched with a specific ordering that makes it possible to specifically report when we have finished dispatching redraw events isn't portable and the way in which we dispatched RedrawEventsCleared was inconsistent across backends.
More generally speaking, there is no inherent relationship between redrawing and event loop iterations. An event loop may wake up at any frequency depending on what sources of input events are being listened to but redrawing is generally throttled and in some way synchronized with the display frequency.
Similarly there's no inherent relationship between a …
=> Remove RedrawEventsCleared + MainEventsCleared, and add AboutToWait

CHANGELOG.md, src/event.rs, src/keyboard.rs
Publically export smol_str. Closes #2996 
Implement `Ord` for `Key`, `NativeKey`. Motivation: I have a mapping from `Key` to X that I serialise to a file. This is normally stored in a `HashMap`, but sorted before serialisation to ensure the file does not constantly mutate needlessly (and make direct edits to the file more user friendly).
I *could* add a note to `Key` mentioning that ordering is arbitrary and not guaranteed to remain stable across releases, but this seems like fluff.
=> Export smol_str; impl Ord for Key

CHANGELOG.md, examples/window.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/state.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/animation_frame.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Fixes #2412.
The docs are also not updated and it would be nice to have software example showing FPS it's rendering it right now.
--
Wayland done and it works.
=> Throttle `RedrawRequested`

CHANGELOG.md, FEATURES.md, src/platform/ios.rs, src/platform/macos.rs, src/platform/wayland.rs, src/platform/windows.rs, src/platform/x11.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/windows/window.rs
It seems odd to me that we have extension methods for accessing certain raw pointers/handles, when the information is already accessible through the `raw_window_handle::RawWindowHandle` implementation (although it's maybe slightly more cumbersome, and may lead to a lot of unwrapping).
So I propose that we remove these, and direct users towards `raw-window-handle` instead.
- This hardly needs any testing
=> Remove functionality already exposed through `raw-window-handle`

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/event_loop/sink.rs, src/platform_impl/linux/wayland/state.rs, src/platform_impl/linux/wayland/window/mod.rs
Mark it as breaking, since some clients relied on that behavior, simply because dispatching clients queue always woke up a winit, meaning that they won't be able to use user events for this sake.
=> On Wayland, reduce amount of spurious wakeups

src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/windows/event_loop.rs
There's no need to force the static on the users, given that internally some backends were not using static in the first place.
- [-] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
=> Remove 'static requirement on `run`

CHANGELOG.md, src/platform/x11.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
At the moment, the with_x11_visual function takes a pointer and immediately dereferences it to get the visual info inside. As it is safe to pass a null pointer to this function, it is unsound. This commit replaces the pointer parameter with a visual ID, and then uses that ID to look up the actual visual under
the X11 setup. As this is what was already practically happening before, this change shouldn't cause any performance downgrades.
This is a breaking change, but it's done in the name of soundness so it should be okay. It should be trivial for end users to accommodate it, as it's just a matter of getting the visual ID from the pointer to the visual before passing it in.
Closes #2746
=> Make with_x11_visual take ID instead of a pointer

src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/seat/keyboard/mod.rs, src/platform_impl/linux/wayland/window/mod.rs
Force the wake up from the repeat source as well.
Fixes: cad327755 (On Wayland, reduce amount of spurious wakeups)
=> Fix event loop not waking up due to repeat source

src/platform_impl/ios/app_state.rs, src/platform_impl/ios/ffi.rs
Without this code I'm getting the following error when running in the iOS simulator with winit master (commit bd2f1e8312aab84a21ad1e3d2c0dbcb01379ef28):
> thread 'main' panicked at 'invalid message send to -[NSProcessInfo operatingSystemVersion]: expected return to have type code '{?=qqq}', but found '{NSOperatingSystemVersion=qqq}'', ~/.cargo/git/checkouts/winit-c2fdb27092aba5a7/bd2f1e8/src/platform_impl/ios/app_state.rs:978:13
To reproduce the above issue, checkout https://github.com/fornwall/wgpu-game-of-life and run `make run-ios-simulator`.
Ping @madsmtm.
=> iOS: Use NSOperatingSystemVersion from icrate

CHANGELOG.md, examples/x11_embed.rs, src/platform/x11.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/atoms.rs, src/platform_impl/linux/x11/window.rs
=> Add a way to embed the X11 window into another

CHANGELOG.md, src/platform_impl/ios/view.rs
This sets the touch force property when the touch event was made with an apple pencil.
=> Fix touch force for Apple Pencil

CHANGELOG.md, examples/child_window.rs, src/window.rs
We use raw-window-handle extensive in the public API as well as we force the users to use it to get some essential data for interop, thus reexport it.
Fixes: #2913.
=> Reexport raw-window-handle in window module

src/event.rs, src/platform/web.rs, src/platform_impl/android/keycodes.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/windows/mod.rs
We really need to work on making our CI more stable against upstream updates like this, but oh well, let's just fix it for now.
=> Fix recent CI failures

CHANGELOG.md, clippy.toml, src/platform_impl/macos/appkit/view.rs, src/platform_impl/macos/view.rs
We were invalidly using `visibleRect` where we should have been using `frame`; the former is used if your view is in e.g. a scroll view, and you want to save resources by only rendering the visible part of the view.
This _is_ confusing, since [`visibleRect` is put under the drawing collection in the documentation](https://developer.apple.com/documentation/appkit/nsview/drawing?language=objc), so I've banned it from our codebase using `clippy.toml` to avoid this issue in the future (though that will only take effect after #2982).
Fixes #2876
=> Fix invalid size when resizing

CHANGELOG.md, src/event_loop.rs, src/monitor.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/window.rs, src/window.rs
Just made it consistent really. E.g. `Window::available_monitors()` returned no monitors even though `Window::primary_monitor()` did return a handle. On Web we don't have access to the monitor and no information about it either.
=> On Web, never return a `MonitorHandle`

.github/workflows/ci.yml
Two things to discuss:
1. The move from `hecrj/setup-rust-action` to `dtolnay/rust-toolchain` (done because of slightly better performance, and it seems like this is what everyone is moving to) removes support for the problem matchers, see https://github.com/dtolnay/rust-toolchain/issues/50. We can [re-add this explicitly](https://github.com/r7kamura/rust-problem-matchers) if desired, so: Is it desired? Do people actually like this feature? I myself don't ever use it, as I find it is really cluttered anyhow (since it's run on so many platforms, and GitHub doesn't do any deduplication).
2. Would it be time to start committing the `Cargo.lock`? Because if we do, we can use [Swatinem/rust-cache](https://github.com/Swatinem/rust-cache) or do something similarly easier instead. This should …
=> Improve CI caching, and give each job names

CHANGELOG.md, src/platform/ios.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs
Part of #2464.
Now, `MonitorHandle` and `VideoMode` are usable from any thread.
Also did a few other cleanups, in preparation for making `EventLoopWindowTarget` independent of the user event type, to fix the macOS and iOS part of https://github.com/rust-windowing/winit/issues/3053.
=> Make iOS fully thread safe

CHANGELOG.md, src/platform_impl/macos/appkit/window.rs
Introduced all the way back in #2465.
=> Fix deminiaturize on macOS

CHANGELOG.md, examples/web.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/animation_frame.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/web/window.rs
This overhauls the fullscreen functionality.
Transient events are now recorded from all known events and from the window as well. See the [specification](https://html.spec.whatwg.org/multipage/interaction.html#activation-triggering-input-event) for a list of all events that trigger transient activation.
Instead of awaiting the returned `Promise`, which didn't work on Safari v<16.4, to figure out if we want to add the fullscreen request to the queue, we now listen to the `fullscreenchange` event. Which can also detect external fullscreen activation and remove the our fullscreen request from the queue.
The [`Element::request_fullscreen()`](https://docs.rs/web-sys/0.3.64/web_sys/struct.Element.html) method also included an error, which is incorrect according to the new and …
=> Web: Fullscreen Overhaul

Cargo.toml, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ffi.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/input.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs
Ports the code for the XInput and XRandr to use `x11rb` instead of Xlib.
Draft because there's still more to do, and also I seem to have broken raw event inputs.
=> Implement X11 extensions using x11rb instead of Xlib

src/window.rs
=> Fix missing quote

src/platform_impl/macos/event_loop.rs
This is required for device events and certain other events to be delivered, see `platform_impl/macos/app.rs`.
- I didn't deem this necessary
=> Ensure that winit initializes `NSApplication`

src/platform_impl/orbital/event_loop.rs
Part of https://github.com/rust-windowing/winit/issues/3053
- Can't really test it, but it's a simple change and it builds, so I'm quite confident it's correct.
=> Make `EventLoopWindowTarget` independent of the user type on Redox/Orbital

src/event.rs, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/icon.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/window.rs, src/window.rs
Helpful for pushing https://github.com/rust-windowing/winit/pull/2430 forwards a bit, and in general nice for consistency.
=> Slightly reduce number of `cfg`s

CHANGELOG.md, src/platform/startup_notify.rs
They are safe, since they use the rust `std::env` stuff. Making them safe lets downstream to determine that `std::env` is used and not the `libc` env manipulation routines, which are unsafe.
=> Mark `startup_notify` unsafe functions as safe

src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/proxy.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs
Thanks to @nerditation.
Currently our custom `Channel` type actually uses an `std::mpsc` channel to send `()` to wake up the event loop. This is obviously nonsense because the actual user event already uses an `std::mpsc` and that way it can only handle a single user event at a time. I'm working currently on a rework that simply uses a `AtomicUsize` to figure out exactly how many user events have been sent without any channel to begin with. Or maybe some other idea I can come up with :sweat_smile:.
Fixes the Web backend for #3053.
=> Web: Remove `T` from `EventLoopTargetWindow`

CHANGELOG.md, src/platform_impl/linux/mod.rs
Closes #3057 by making it so the forced backend is considered over all else.
=> Allow the user to force X11 under Wayland

src/platform_impl/linux/x11/util/input.rs
The new implementation of select_xkb_events apparently misconfigures the server. This commit does a temporary fix by just reverting it to its previous implementation.
This is temporary until I can figure out what Xlib is doing behind the scenes or until I read xkbproto.pdf.
Closes #3079 for now
- [] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
=> Revert select_xkb_events to its previous impl

CHANGELOG.md
Small fix for changelog entry of #3056.
=> Correct set_exit() -> exit() in the changelog

CHANGELOG.md, src/platform/web.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/schedule.rs
This PR builds on top of #3056 and adds a new extension method on `EventLoopWindowTarget` to set the strategy for `ControlFlow::Poll`. By default the [Prioritized Task Scheduling API](https://developer.mozilla.org/en-US/docs/Web/API/Prioritized_Task_Scheduling_API) is used, this adds the option to use [`Window.requestIdleCallback()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) instead.
Both strategies fallback on [`setTimeout()`](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) when not available.
Cc @GloopShlugger.
Originally implemented in #2880 and then reverted in #3044.
Requires #3056.
=> Add option to use `Window.requestIdleCallback()` for `ControlFlow::Poll`

.github/workflows/ci.yml, README.md
As discussed in #3000, this adopts an official MSRV policy for the rust-windowing organization. It uses Debian Testing as the definition of our support. In the future once winit becomes more stable we might want to use Debian Stable instead, in order to allow Debian to use crates like Alacritty in the stable channel.
Outstanding questions:
- What are the general thoughts on the organizational policy?
- Does this give us enough leeway to add new features?
- Are there any other Linux distros that we need to support?
=> Add an MSRV policy to the README

.github/workflows/ci.yml
I noticed that the `cargo-apk` installation fails because it's currently broken on nightly, but even if we want to test Android on nightly, we require `cargo-apk` to be installed with the nightly toolchain.
Also removed caching nightly and stable `cargo-apk` separately, the output is the same now after all.
=> Install `cargo-apk` with the stable toolchain

CHANGELOG.md, src/event.rs
Basically for the same reason as #2918
I want to use the mouse buttons for a bind, which requires sorting. I assume they are also kind of hardware keys, at least that's how i used them back then with SDL2
=> Also implement `PartialOrd` and `Ord` for `MouseButton`

CHANGELOG.md, src/platform_impl/linux/x11/mod.rs
It seems that WaitUntil is currently broken on X11: no events are received when the timer expires, unless there is an actual window event. This issue seems to be introduced in c47d08. This PR adds an additional condition to the spurious wake up check, recognizing ResumeTimeReached as a valid cause to wake up.
=> Fix WaitUntil on X11

CHANGELOG.md, src/event.rs, src/platform_impl/android/mod.rs
Adds pressure data to touch events on android
=> Pass force on touch events on android

CHANGELOG.md, src/event.rs
The event is never constructed inside the winit.
=> Remove `DeviceEvent::Text` event

src/platform_impl/linux/x11/window.rs, src/window.rs
It looks like 584aab4cd0da167f18e3907edfa8981885d7f92c broke transparent windows in X11 (at least on my computer). I fixed it, and updated the docs of `set_transparent` to note that transparent windows do work in X11.
- I tested this on my computer, running X11, which is the only platform affected.
- This is a fix of a regression, I didn't add anything to the changelog.
- `examples/transparent.rs` still works to show this.
- No features were changed.
=> Fix transparet windows in X11

CHANGELOG.md, Cargo.toml, README.md, src/platform_impl/macos/appkit/view.rs, src/platform_impl/macos/view.rs
Backport fix for https://github.com/rust-windowing/winit/issues/2876.
CC @kchibisov
=> Winit version 0.28.7

src/platform_impl/windows/dpi.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/ime.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs
Although this does increase the verbosity, it also greatly helps in auditing which parts of the codebase is actually `unsafe`, and thus need extra scrutiny. My plan is to add it to the entirety of `winit`.
[The lint](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/builtin/static.UNSAFE_OP_IN_UNSAFE_FN.html) is even stated in [the documentation for the keyword `unsafe`](https://doc.rust-lang.org/std/keyword.unsafe.html), and the desire is to make it warn by default at some point in the far future.
Related: What I'm seeing from applying this lint is that a _lot_ of the Windows backend is `unsafe`, I think we should consider working on improving that.
=> Windows: Add `#[deny(unsafe_op_in_unsafe_fn)]`

src/event.rs, src/lib.rs, src/platform_impl/ios/uikit/mod.rs, src/platform_impl/linux/common/xkb_state.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/inner.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/macos/mod.rs, src/platform_impl/windows/mod.rs, src/window.rs
Follow-up to https://github.com/rust-windowing/winit/pull/3070, add `#[deny(unsafe_op_in_unsafe_fn)]` on the remaining platform X11, such that we can now enable it for the entirety of `winit`.
CC @notgull since this may impact your x11rb work?
=> X11: Add `#[deny(unsafe_op_in_unsafe_fn)]`

README.md
The [Missing features provided by other crates](https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates) wiki page is woefully out of date, and IMO hard to maintain; so I propose we link to better maintained resources like https://areweguiyet.com and https://arewegameyet.rs (I'm maintaining the former), which will likely serve user's needs better.
I have made sure that all information contained in that page is moved to these two projects, so I'm intending to delete the page after this PR is merged.
I'm also considering deleting the [Software that uses winit](https://github.com/rust-windowing/winit/wiki/Software-that-uses-winit) page, since only four of the seven listed projects are actually maintained, and hence it's not really a good list for users that …
=> Link to areweguiyet.com and arewegameyet.rs instead of winit's wiki page

src/platform_impl/web/async.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/web/web_sys/resize_scaling.rs, src/platform_impl/web/web_sys/schedule.rs
=> Web: remove unnecessary usage of `once_cell::unsync::Lazy`

CHANGELOG.md, src/platform_impl/web/web_sys/schedule.rs
Unfortunately we were passing full milliseconds before to the corresponding Web APIs, e.g. 0.5 ms would get truncated to 0 ms, which then would wake up the event loop immediately.
=> Web: fix `ControlFlow::WaitUntil` to never wake up **before** the given time

src/window.rs
The env variable was removed a while ago, yet it was still present in the user docs.
=> Remove obsolete docs about wayland CSD env variable

src/platform_impl/linux/wayland/output.rs
The window position returned from `sctk`, which retrieved from wayland compositor, should be a logical position, to return physical position, mapping is needed
=> fix wayland MonitorHandle position

CHANGELOG.md, src/event.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/view.rs
Adopted from #2144, and updated.
From https://github.com/rust-windowing/winit/pull/2144#issuecomment-1129990322 I'm not confident on adding events `Foreground` and `Background` to Android, they seem to be equivalent to `Suspend` / `Resume` where iOS split that in two steps.
=> Add Occluded events based on foreground/background on iOS and MemoryWarning on iOS/Android

CHANGELOG.md
While the changelog entries for beta releases doesn't really matter. The change wasn't marked as breaking, while it is.
Fixes: 93f1000a0 (Add Occluded and MemoryWarning events for iOS/Android)
=> Fix CHANGELOG entry for Event::MemoryWarning

FEATURES.md, src/platform_impl/linux/x11/window.rs, src/window.rs
=> implement set_cursor_hittest for x11

CHANGELOG.md, src/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs
This should help other crates to integrate winit's event loop into their bigger event loop without adding an extra thread.
=> Implement `AsFd`/`AsRawFd` for `EventLoop<T>`

src/window.rs
Fixing this could require a massive rework to how redraw is handled on windows to the point of removing `WM_PAINT`, since it's not reliable by any means for our use case.
For now at least document that the API is broken. It was broken like that for a long while.
=> Add a note on `Window::request_redraw` on Windows

CHANGELOG.md, Cargo.toml, src/platform_impl/android/keycodes.rs, src/platform_impl/android/mod.rs
Depends on #3126, https://github.com/rust-mobile/android-activity/pull/128
CC @notgull, @kchibisov
=> Upgrade to `ndk 0.8`, `ndk-sys 0.5` and `android-activity 0.5` releases

CHANGELOG.md, src/lib.rs, src/platform/web.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs, tests/send_objects.rs, tests/sync_object.rs
The default window builder is neither `Send` nor `Sync` due to use of `RawWindowHandle` internally. While we could ensure to make the handle `Send + Sync` within our use, we can't guarantee that the same will hold true in the future.
Thus add a generic to split the builder into `MT-safe` and not `MT-safe` versions.
This could also help with the lifetimes, since default could be bound by static lifetime.
=> Make default `WindowBuilder` `Send` and `Sync`

CHANGELOG.md, src/platform_impl/macos/view.rs
Sometimes FlagsChanged events don't carry any KeyCode information, thus we can't create a synthetic presses events for them.
However in such cases, modifiers information is still accurate, thus propagate it.
Fixes #2872.
=> On macOS, fix globe key triggering assertion

Cargo.toml
The `rwh_05` feature was not enabled.
Fixes: e41fac825c2 (Update to new raw-window-handle strategy)
=> Fix examples not render on Wayland

src/platform_impl/linux/mod.rs
It's common to disable Wayland by `WAYLAND_DISPLAY= <application>`.
=> Ensure that DISPLAY vars are non-empty before using

CHANGELOG.md, src/platform_impl/macos/appkit/tab_group.rs, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/window.rs
The property is marked as `Weak`, however we used strong `Id`.
Links: https://github.com/alacritty/alacritty/issues/7249
=> On macOS, fix tabGroup misuse

CHANGELOG.md, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/platform_impl/windows/window_state.rs, src/window.rs
When calling `Window::request_redraw` from the `RedrawRequested` handler the `RedrawWindow` won't result in `WM_PAINT` being delivered due since user callback is run before `DefWindowProcW` is called.
Track whether the user called `Window::request_redraw` and ask for `RedrawWindow` after running the said function during `WM_PAINT` handling.
Fixes #3150.
=> On Windows, fix `RedrawRequested` delivery

CHANGELOG.md, src/platform_impl/windows/window.rs
Execute the calls to the IME from the main thread.
Fixes #3123.
=> On Windows, fix IME APIs MT-safety

src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs
The cursor hittest was not reloaded on window size changes, only when `Window::request_inner_size` was called leading to regions of the window being not clickable.
Links: https://github.com/alacritty/alacritty/pull/7220
=> On X11, fix cursor_hittest not reloaded on Resize

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
The lock was not released when calling back to the user.
Fixes #3171.
=> On Windows, fix deadlock during `Cursor{Enter,Leave}`

src/platform_impl/windows/event_loop.rs
The lock was still present in `None` path.
Fixes: d37d1a03b(On Windows, fix deadlock during `Cursor{Enter,Leave}`)
=> On Winows, Fix deedlock with `WM_MOUSEMOVE`

CHANGELOG.md, src/platform_impl/macos/app_state.rs
Calling [`have_callback()`](https://github.com/rust-windowing/winit/blob/62ed51a138aeb2dc7d64950e6f9877ba9d57646e/src/platform_impl/macos/app_state.rs#L308C8-L310) during the callback deadlocks. Reorder the [`get_in_callback()`](https://github.com/rust-windowing/winit/blob/62ed51a138aeb2dc7d64950e6f9877ba9d57646e/src/platform_impl/macos/app_state.rs#L300-L302) call first to avoid the deadlock.
Fixes: #3179
=> On macOS, fix deadlock during nested event loops (e.g. rfd)

src/event_loop.rs, src/lib.rs, src/platform/run_on_demand.rs, src/platform/web.rs
For https://github.com/rust-windowing/winit/commit/0d366ffbdaabab567f595b38710e8d72f150b514#r130681051
And on any other platform, emit a footnote explaining that this function is only available on wasm.
EDIT: Apologies, it looks like `gh pr create` pushed this through the main repo instead of my fork. Hence there's no `marijn/` prefix on the branchname.
=> On wasm, provide intradoc-link for `spawn()` function in `EventLoop` docs

CHANGELOG.md, src/platform_impl/linux/wayland/window/state.rs
The `dirty` is never cleared when decorations are hidden without `sctk-adwaita`.
Fixes #3177.
=> On Wayland, fix `RedrawRequsted` loop

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/monitor.rs
Keep the user provided size in the original values and convert only when we're getting a `configure` event. On some compositors will have a scale available, so it'll work, however with some we'll still have old 'pick 1` as default.
Also configure_bounds when compositor tells the user to pick the size, that will ensure that initial `with_inner_size` won't grow beyond the working area.
Fixes #3187.
@dhardy can you test this? It should probably make the `PhysicalSize` work on at least some systems and if you pass the big `with_inner_size` winit will constrain to the the size compositor wants.
=> On Wayland, improve initial user size handling

CHANGELOG.md, src/platform_impl/macos/appkit/window.rs, src/platform_impl/macos/ffi.rs, src/platform_impl/macos/window.rs, src/window.rs
--
I researched alternatives and given that apple is doing the same as well as a lot of other apps it's probably safe for the time being. The `NSVisualEffectsView` is a bit more involved and not sure that it'll provide much value. it's also not clear how it all interacts with each other.
=> On macOS, add support for `Window::set_blur`

src/dpi.rs, src/monitor.rs, src/window.rs
Wayland scales each window individually, thus make it clear. Also recommend against using the `MonitorHandle::scale_factor`.
Fixes #3183.
=> Clarify `scale_factor` docs

CHANGELOG.md, src/platform_impl/windows/window.rs
On Windows, at least, `ReleaseCapture` is documented to release the capture of the mouse on the current thread. In our application we were calling `drag_window` on another thread because we've separated the event loop out to a different thread.
=> 🐉 Support window dragging from outside the main thread

examples/util/fill.rs
- Tested on macOS and Windows
When a window is minimized on Windows, `Resized` event is emited with zero width and zero height. But examples assume that window width/height are never zero so they crash. I fixed it in this PR.
=> On Windows, fix examples crash when minimizing a window 

Cargo.toml
We decided to add `rwh_06` to the `default` list of features in the `ndk` to [nudge users to upgrade], but this forces `winit` to always (transitively) include `raw-window-handle 0.6` even if the user has set a different `rwh_xx` feature on the `winit` crate.  `winit` already forwards the respective `rwh_xx` feaure to the `ndk` crate anyway, so this default should just be turned off.
At the time of writing this is the only `default` feature of the `ndk`.
[nudge users to upgrade]: https://github.com/rust-mobile/ndk/pull/434#issuecomment-1752089087
@kchibisov what's the right way to mark this to be backported to `0.29` - open another PR targeting that branch or can you cherry-pick it?
=> Disable `default-features` for the `ndk` crate

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
In case the AboutToWait event sets the control flow to another value
Fixes https://github.com/rust-windowing/winit/issues/3215
=> Windows: move prepare_wait before querying the control_flow

clippy.toml, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/resize_scaling.rs, src/platform_impl/web/window.rs
Follow-up from here: https://github.com/rust-windowing/winit/pull/3218#discussion_r1389897492.
Let's not repeatedly call things that should be cached.
This is a bit weird because `HtmlElement.style` vs `Window.getComputedStyle` isn't the same, but that's why we should probably not use `HtmlElement.style` at all.
=> Web: forbid additional functions in favor of caching them

CHANGELOG.md, src/platform_impl/linux/wayland/window/state.rs
The surface was automatically dropped due to new RAII type in SCTK when dropping the Window, which was not the case at some point with SCTK.
Thus destroying objects associated with it where causing issues with some window managers.
Links: https://github.com/neovide/neovide/issues/2109
=> On Wayland, fix wl_surface being dropped first

CHANGELOG.md, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs
Newer versions of macOS have a feature that allows them to run iOS apps in an iPad-like form factor. Unfortunately, my game built with Bevy and winit used to [immediately crash](https://github.com/Couch-Chilis/sudoku-pi/issues/12) when trying this out. This PR fixes the crashes.
The changes in `event_loop.rs` were necessary to get the app to start, while the changes in `app_state.rs` allow the app to also exit cleanly without crashing when pressing Cmd+Q.
=> Fix crash when running iPad build on macOS

Cargo.toml, src/platform/android.rs
As discussed in https://github.com/rust-windowing/winit/pull/2324#issuecomment-1823536187.
=> Make Android docs build on docs.rs

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/window.rs
=> Reload DPI on PropertyChange

CHANGELOG.md, src/platform_impl/macos/event.rs
* Closes https://github.com/rust-windowing/winit/issues/3246
=> Mac: Remove error log when pressing Fn key

CHANGELOG.md, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
Closes #3245
notgull forgot to properly interpret float data from the X server, making him tonight's biggest loser.
=> Properly interpret float data in drag ops

CHANGELOG.md, examples/focus.rs, src/platform_impl/linux/x11/ffi.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
Closes #3248 by removing an Xlibism I forgot about
=> Use the right atom type in focus_window()

CHANGELOG.md, src/platform_impl/macos/monitor.rs
When the monitor refresh rate changes, `CVDisplayLinkGetNominalOutputVideoRefreshPeriod` still returns the previous value unless the process is restarted. I don't know the reason, but `CGDisplayModeGetRefreshRate` can return the correct result.
=> fix refresh_rate_millihertz on macOS

Cargo.toml, src/platform_impl/linux/x11/window.rs
The only breaking change is that x11rb no longer reports an error when querying the `WmSizeHints` of a window that does not have this property set. For this reason, the return type of `WmSizeHintsCookie::reply()` changed from `Result<WmSizeHints, SomeError>` to
`Result<Option<WmSizeHints>, SomeError>`.
In `update_normal_hints()`, previously a cryptic error would be reported to the caller. Instead, this now uses `unwrap_or_default()` to get a `WmSizeHints`. All fields of `WmSizeHints` are `Option`s, so this produces an empty object.
`resize_increments()` queries a value from the window and returns an Option. Previously, the error for "missing property" was turned into None via `.ok()`. This commit adds a call to `flatten()` to also turn "property not set" into None.
Finally, …
=> Update to x11rb 0.13.0

CHANGELOG.md, src/platform_impl/linux/wayland/state.rs, src/platform_impl/linux/wayland/window/state.rs
This protocol is only used for (optional) Client Side Decorations (where) the compositor still takes the burden of compositing various window parts together, via subsurfaces that all belong to a single window.
If this core protocol is not available, as is the case on gamescope, disable CSD.
Related:
https://github.com/Smithay/client-toolkit/issues/210
https://github.com/alacritty/alacritty/issues/5709
=> On Wayland, make `wl_subcompositor` protocol optional

CHANGELOG.md, src/platform_impl/linux/x11/util/randr.rs
Scale factor detection breaks for me in X11 after upgrading from `0.28.6` to `0.29.4`.
I think I corrected a typo that fixes the issue, at least for me.
=> Fix typo in `get_xft_dpi`

CHANGELOG.md, src/platform_impl/windows/window.rs
=> On Windows, fix `set_fullscreen` early return for `Fullscreen::Borderless(None)`

CHANGELOG.md, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/web/web_sys/pointer.rs, src/window.rs
I was about to improve the fullscreen code with the newly stabilized [`UserActivation`](https://developer.mozilla.org/en-US/docs/Web/API/UserActivation) API, but realized that we might want to simplify this.
The idea here is that, because I don't exactly know why this was added in the first place, I removed the whole mechanic of queuing fullscreen requests when they fail in light of a missing transient activation. This should simplify the code.
There are a couple of points that speak against such a mechanic:
- If it fails it fails, why should we queue it? This adds very platform-specific quirk that is not immediately clear.
- The browser limits fullscreen activation for a reason to a transient activation. Only user interaction should trigger it, I don't see a reason why we are trying to …
=> Web: remove queuing fullscreen request

CHANGELOG.md, src/platform_impl/web/cursor.rs, src/platform_impl/web/window.rs
Currently, on Web, when using `Window::set_cursor_icon()` or `Window::set_custom_cursor()`, cursor visibility is overridden instead of changing the cursor behind the scenes.
This PR changes that so that changing the cursor does not override cursor visibility and brings the Web backend in line with the others.
Fixes #3227.
=> On Web, fix setting cursor icon overriding cursor visibility

src/platform_impl/linux/wayland/window/state.rs
While we correctly configure the sizes, we also need to actually resize the frame on initial configure and send geometry.
Fixes #3277.
cc @eero-lehtinen 
--
Have not tested because I don't have a setup which can repro that, but it should work.
=> On Wayland, ensure initial resize delivery

CHANGELOG.md, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs
A bit unfortunate that this didn't make into v0.29.5.
=> On Web, fix context menu not being disabled by `with_prevent_default(true)`

Cargo.toml, examples/custom_cursors.rs, src/cursor.rs, src/platform/web.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/async/channel.rs, src/platform_impl/web/async/dispatcher.rs, src/platform_impl/web/async/mod.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/window.rs, tests/send_objects.rs, tests/sync_object.rs
This is a proposal to change the API as discussed before in IRC and #3218.
The API now works like this:
```rust
let custom_cursor = CustomCursor::from_rgba(rgba, width, height, hotspot_x, hotspot_y)
.unwrap()
.build(&event_loop);
window.set_custom_cursor(&custom_cursor);
```
So now building a `CustomCursor` requires access to `EventLoopWindowTarget`, the cursor itself remains `Send + Sync` (the builder itself as well).
All backends work exactly the same as before, ergo they don't implement caching. I only implemented caching for Web.
I will make follow-up PRs for Windows and MacOS, where I know caching should be pretty straightforward and uncontroversial to implement.
I also made a big improvement in the Web implementation: we now wait for cursors to actually load before applying them. We …
=> Allow custom cursor caching

CHANGELOG.md, src/platform_impl/ios/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/web/window.rs, src/window.rs
Now we don't have to set `data-raw-handle` on the canvas anymore.
=> On Web, use the new `WebCanvasWindowHandle`

CHANGELOG.md, src/platform_impl/ios/window.rs, src/platform_impl/macos/window.rs, src/window.rs
Follow-up to https://github.com/rust-windowing/winit/pull/3270.
=> Window handle: Return an error when not on main thread on macOS and iOS

.github/workflows/ci.yml, CHANGELOG.md, CONTRIBUTING.md, Cargo.toml, README.md
This bumps the MSRV from v1.65 to v1.70.
Which our current [MSRV policy](https://github.com/rust-windowing/winit/tree/4ee11018c28efccb059c9cfb577fce9305ac8f06#msrv-policy) allows.
I'm doing this mainly to get access to [`Arc::into_inner()`](https://doc.rust-lang.org/1.73.0/std/sync/struct.Arc.html#method.into_inner), so it's not totally necessary.
=> Bump MSRV to 1.70

src/cursor.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/types/cursor.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/window.rs
- Move `PlatformCustomCursorBuilder::build()` to `PlatformCustomCursor` so platforms can implement their own caching if they want to. See #3291.
- Move `Arc` in `CustomCursor` to platform implementations so platforms who have their own reference counting can use  that. E.g. MacOS with [`Id`](https://docs.rs/objc2/0.5.0/objc2/rc/struct.Id.html).
No public API or backend changes.
=> Custom cursor improvements

src/platform_impl/macos/cursor.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/window.rs
This moves the creation of `NSCursor` to `CustomCursorBuilder::build()`.
Note: no public API changes.
=> MacOS: cache custom cursor

Cargo.toml
Correct rwh_05 minimum version to support "std" feature. Fixes some scenarios where downstream bins don't `cargo update` and try to build with rwh_05 `0.5.0` or `0.5.1` which both lack the "std" feature required in the winit manifest.
Resolves #3223
- ~Tested on all platforms changed~ rwh_05 version already tested
- ~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~ n/a
- ~Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~ n/a
- ~Created or updated an example program if it would help users understand this functionality~ n/a
- ~Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented~ n/a
=> Specify rwh_05 min version 0.5.2

clippy.toml, examples/fullscreen.rs, examples/multithreaded.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/util.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
Instead of adding and subtracting heights haphazardly, let's use the built-in methods that AppKit has!
=> macOS: Clean up coordinate system calculations

CHANGELOG.md, examples/cursor.rs, examples/custom_cursors.rs, examples/multithreaded.rs, examples/window_drag_resize.rs, src/cursor.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
This merges the two methods `Window::set_cursor_icon()` and `Window::set_custom_cursor()`.
The underlying implementations were not changed at all!
This simplifies the API a bit so we don't have two methods that override each other, in the future this will allow a getter to be implemented when Linux implements caching, see #3306.
In a follow-up I will implement a custom cursor setting in `WindowBuilder`, the merged type allows `WindowAttributes` to easily expose the currently set cursor.
=> Merge `Window::set_cursor_icon()` and `Window::set_custom_cursor()`

src/event_loop.rs
This limitation was removed back in #3006.
=> Remove wrong documentation on `EventLoop::run()`

CHANGELOG.md, src/platform/web.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/web/window.rs
Current controlling if `Event.preventDefault()` is called or not could only be changed in `WindowBuilder`.
This PR introduces `Window::set_prevent_default()`, so now it can be dynamically adjusted.
=> On Web, add `Window::(set_)prevent_default()`

src/platform/web.rs, src/platform_impl/web/async/dispatcher.rs, src/platform_impl/web/async/waker.rs, src/platform_impl/web/async/wrapper.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/main_thread.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
Just extracted the Web part from #3303.
=> Make `canvas` in `WindowBuilder` safe

src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
- Instead of holding references to the cursor state of a `Window` during cursor loading, an event is sent.
- The event can now properly handle loading a cursor for multiple `Window`s.
- Reduce the amount of `Arc` upgrades to an absolute minimum.
- Drop references to `ImageBitmap`, `HTMLElementCanvas` and `ImageBitmapRenderingContext` as early as possible to free up resources.
- Drop object URLs even in case of an error.
- Always check if the cursor actually changed before updating it through `Window::set_cursor()`.
=> Web: improve custom cursor loading

src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs
This just adds a check to make sure the cursor actually changed before applying it.
=> MacOS: check if cursor changed before applying

CHANGELOG.md, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
Adds a `WindowBuilder::with_cursor()` method, which is the equivalent of `Window::set_cursor()`.
I'm unfortunately pretty clueless about the other backends, but I tried placing the call before the window becomes visible.
=> Add `WindowBuilder::with_cursor()`

CHANGELOG.md, src/lib.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/window.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/window.rs, src/window.rs
I noticed that `SendSyncWrapper` caused some real issues here and there. First #3270 and #3288, then #3297.
Also noticed that we simply used `SendSyncWrapper` on `Fullscreen` inside `WindowBuilder`, but there is a getter that exposes this information to the user, bypassing the `!Sync` on `Fullscreen` on MacOS, depending if this `!Sync` was correct or not, that may have been unsound.
Additionally on Web there was an issue where dropping `WindowBuilder` outside the main thread could cause it to try and drop `HtmlCanvasElement`, which is unsound as well (not entirely sure if that is correct, but it's at least semantically correct).
Additionally implementing `Debug` on `SendSyncWrapper` was unsound as well, because `Debug` could access the inner value off the only thread it was intended to be …
=> Remove unsound `SendSyncWrapper`

CHANGELOG.md, src/monitor.rs, src/platform/ios.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/monitor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/monitor.rs, src/platform_impl/macos/window.rs, src/platform_impl/mod.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/monitor.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/monitor.rs, src/window.rs
The point here is to reflect that `VideoMode` is not a static blob of information, but a handle that dynamically accesses that information. This is in line with our other `MonitorHandle` type.
Addresses #3258.
Cc @madsmtm.
=> Rename `VideoMode` to `VideoModeHandle`

src/window.rs
In the spirit of https://github.com/rust-windowing/winit/pull/3328#discussion_r1436613136.
=> Add deprecated `Window::set_cursor_icon()`

CHANGELOG.md, src/platform_impl/linux/x11/monitor.rs
This appears to be the solution for the elusive #3335 issue. Previously,
in the Xlib backend, we used the "XRRQueryVersion" function to query for
the Xrandr version, and used that to determine whether we should use the
"GetScreenResources" call or the "GetScreenResourcesCurrent" call.
However, we passed the version "0, 0" into "XRRQueryVersion".
Previously with Xlib this wasn't a problem, as Xlib ignores the version
you pass in and substitutes it with the version of RandR it expects.
https://gitlab.freedesktop.org/xorg/lib/libxrandr/-/blob/master/src/Xrandr.c?ref_type=heads#L386-387
The way that "XRRQueryVersion" is implemented on the server end, it
compares the version passed into the request with the version supported
by the server. If the server's version is greater than the client …
=> Query for higher Xrandr version

CHANGELOG.md, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/state.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs
The user may change the size during the on-going resize, meaning that the size will desync with winit's internal loop which breaks viewporter setup with fractional scaling.
Links: https://github.com/alacritty/alacritty/issues/7474
=> On Wayland, fix `Window::request_inner_size` during resize

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
This is required to handle xmodmap.
Fixes #3338.
=> On X11, update keymap on XkbMapNotify

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs
xdotool will update modifiers before Xkb will actually send event updating them, thus the modifiers will be updating even before the actual update, which is unfortunate.
Links: https://github.com/alacritty/alacritty/issues/7502
=> On X11, fix `ModifiersChanged` from xdotool

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs
IME events and requests where drained on one-by-one basis, however we should drain all of them at once and send to user.
Links: https://github.com/alacritty/alacritty/issues/7514
=> On X11, fix IME input lagging behind

.github/workflows/ci.yml
We currently deploy to a lot of targets on docs.rs, so we should check all of them.
Follow-up to #3076.
=> Test all docs.rs deployments

src/event_loop.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs, src/platform_impl/windows/window.rs
the `EventLoopWindowTarget` is needed for window creation. conceptually, only `EventLoop` and `EventLoopProxy` need to be parameterized, and all other parts of the backend should be agnostic about the user event type, parallel to how `Event<T>` is parameterized, but `WindowEvent` is not.
this change removes the dependency on the type of user events from the `EventLoopWindowTarget` for the Windows backend, but keep a phantom data to keep the API intact. to achieve this, I moved the `Receiver` end of the mpsc channel from `ThreadMsgTargetData` into `EventLoop` itself, so the `UserEvent` is only passed between `EventLoop` and `EventLoopProxy`, all other part of the backend just use unit type as a placeholder for user events.
it's similar to the macos backend where an erased `EventHandler` …
=> Windows: Make `EventLoopWindowTarget` independent of UserEvent type

CHANGELOG.md, src/platform_impl/macos/event.rs
* Closes https://github.com/rust-windowing/winit/issues/3078
=> On macOS, report correct logical key when Ctrl or Cmd is pressed

src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs
We might want to let `CustomCursorBuilder::build()` be able to return an error, but that's a discussion for the future.
For now, the behavior doesn't actually change, because before this PR we didn't return an error from `Window::set_custom_cursor()` as well.
=> Windows: cache custom cursor

src/platform_impl/web/event_loop/window_target.rs
Apparently under some heavy load the canvas focus event could be missed. I guess this could have also happened when supplying a custom canvas.
See https://github.com/bevyengine/bevy/issues/11232.
=> Web: account for canvas being focused already

src/platform_impl/web/web_sys/resize_scaling.rs
This only changes an `assert!` to a `debug_assert!` avoiding a Firefox bug.
No functional changes.
Fixes #3345.
=> Web: support Firefox `privacy.resistFingerprinting`

CHANGELOG.md, src/platform_impl/web/web_sys/event.rs
The current API used to get the cursor position was converting doubles to integers, therefor truncating the number and making conversions between logical and physical positions inaccurate.
Unfortunately this was caused because the `web-sys` API incorrectly returns an integer, which has happened because the spec `web-sys` gets the API from had a mistake.
This PR fixes this by redefining the API to correctly return a double.
=> Web: increase cursor position accuracy

CHANGELOG.md, Cargo.toml, examples/custom_cursors.rs, src/platform/web.rs, src/platform_impl/web/async/abortable.rs, src/platform_impl/web/async/atomic_waker.rs, src/platform_impl/web/async/channel.rs, src/platform_impl/web/async/concurrent_queue.rs, src/platform_impl/web/async/dispatcher.rs, src/platform_impl/web/async/mod.rs, src/platform_impl/web/async/notifier.rs, src/platform_impl/web/async/waker.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/main_thread.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
- Added something similar to [`futures::future::Abortable`](https://docs.rs/futures/0.3.30/futures/future/struct.Abortable.html) to abort `Future`s as soon as possible.
- Custom cursors are now await per window with a `wasm_bindgen_futures::spawn_local()` instead of going through a custom event loop event.
- Conditionally removed dependencies that aren't necessary in single-threaded Wasm (`atomic-waker` and `concurrent-queue`).
- Add `CustomCursorBuilder::build_async()`, to allow users to wait until a cursor has actually loaded and receive an appropriate error if loading wasn't successful.
- Add `CustomCursor::from_animation()` to create animated cursors from `CustomCursor`s using the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API).
Addresses …
=> Web: improve custom cursor handling and add animated cursors

CHANGELOG.md, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs
This was supposed to be rolled out with the rwh v0.6 update, but it
was left behind for some reason. I've added this type back.
Closes #3365
=> Add an owned display handle type

src/platform_impl/ios/mod.rs, src/platform_impl/ios/view.rs
This previously contained a UIScreen for some weird reason; perhaps because `DeviceId` was confused for `UIDevice`? In any case, it doesn't need to contain that.
=> Make DeviceId simpler on iOS

src/cursor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/linux/x11/window.rs
Wayland isn't really affected, just needed some slight refactoring to account for different backends.
=> X11: cache custom cursors

src/window.rs
Would appreciate any improvement on the wording.
=> Document `Window` `Drop` behavior

src/platform/ios.rs, src/platform/macos.rs, src/platform/startup_notify.rs, src/platform/wayland.rs, src/platform/web.rs, src/platform/windows.rs, src/platform/x11.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/window.rs
Fixes #3313.
Any unsoundness this expands on is addressed by #3303.
This doesn't actually implement any getters, these can be implemented in follow-ups as needed.
=> Move `PlatformSpecificWindowBuilderAttributes` into `WindowAttributes`

CHANGELOG.md, FEATURES.md, src/platform/windows.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs
Implements the changes discussed in #3404 with two exceptions:
* Window backdrop: Already implemented in #3257 
* Window border thickness: Can only be read and not written and was therefore not implemented
A beautiful window with non-rounded corners, red border, green title background, and blue title text:
=> Expose more DWM attributes on Windows

CHANGELOG.md, src/platform_impl/windows/window_state.rs
=> On Windows, Remove `WS_CAPTION`, `WS_BORDER` and `WS_EX_WINDOWEDGE` styles for child windows

CHANGELOG.md, src/platform_impl/windows/event_loop.rs
=> Send the event before waking up the message pump.

src/platform_impl/linux/mod.rs
Previously, misleading error messages were shown when the current platform (Wayland/X11) is not enabled.
Case: X11 (`DISPLAY=:0`) but only the `wayland` feature is enabled:
```
Error: EventLoop(Os(OsError { line: 776, file: "/home/dhardy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/mod.rs", error: Misc("neither WAYLAND_DISPLAY nor DISPLAY is set.") }))
```
This PR improves the error. For the above case the message is now: "WAYLAND_DISPLAY is not set; note: enable the `winit/x11` feature to support X11".
=> Improve error when the discovered Linux platform is not enabled

src/platform_impl/ios/view.rs
Introduced recently in https://github.com/rust-windowing/winit/pull/3130, I think during a rebase or something, I must've not checked properly.
=> Fix iOS gesture deltas

CHANGELOG.md, src/platform/x11.rs, src/platform_impl/linux/x11/window.rs
This fixes a bug introduced in commit d7ec899d, and brings the documentation in line with the implementation and the ICCCM standard. The commit messages contain more details.
=> Fix swapped instance and general class names on X11

Cargo.toml
We use softbuffer as a dev-dependency for rendering into our windows in examples. However, we do not support a DRM/KMS backend yet, while softbuffer comes with a DRM/KMS backend by default. This commit removes the DRM/KMS feature from softbuffer to save some build time during testing
=> Remove drm/kms features from softbuffer

CHANGELOG.md, src/error.rs, src/platform/run_on_demand.rs, src/platform_impl/android/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/event_loop/runner.rs
This is already prevented by the type-system, and as such it doesn't make sense to have an error case for this.
This was added by @rib in https://github.com/rust-windowing/winit/pull/2767, maybe you can shed some light on if this was an oversight added out of an abundance of caution, or if you think my reasoning is wrong here, and the error actually can happen?
=> Remove `EventLoopError::AlreadyRunning`

CHANGELOG.md, src/event.rs, src/platform_impl/linux/wayland/state.rs, src/platform_impl/linux/wayland/window/state.rs
Change in state requires a redraw, however drawing when getting `Occluded` with vsync will block indefinitely, thus the event in it's current state is rather useless.
To solve this issue winit needs a way to determine whether the user paused/continued their render loop, so it can commit on their behalf.
=> On Wayland, disable Occluded handling

CHANGELOG.md
They were added to 0.29.2 release.
Fixes: 8862ce01 (Add EventLoop::builder)
=> Move ::builder changes to the correct release

CHANGELOG.md, src/platform_impl/linux/wayland/seat/keyboard/mod.rs, src/platform_impl/linux/wayland/seat/mod.rs, src/platform_impl/linux/wayland/window/state.rs
Given that we merge all the seats, we should consider that window is not focused once all seats wl_keyboards are no longer present.
We use seats instead of keyboards to track focus to protect against wl_keyboard::leave not being delivered when removing the seat (usually it's not the case though).
Fixes: #3376
=> On Wayland, send `Focused(false)` once seats left

CHANGELOG.md, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs
The size is only applied on the next `wl_surface::commit` thus we must trigger the redraw.
=> On Wayland, fix min/max inner size setting

CHANGELOG.md, src/platform_impl/linux/mod.rs
=> Account for WAYLAND_SOCKET when detecting Wayland

CHANGELOG.md, src/platform_impl/orbital/event_loop.rs
This is a follow-up to #3461 to properly map all available orbital keys to the appropriate NamedKey variant
=> On Orbital, map keys to `NamedKey` when possible.

src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/linux/x11/xsettings.rs
We could fail to setup property watcher and fail to start, thus don't require XSETTINGS to work.
Fixes: df8805c0 (On X11, reload DPI on _XSETTINGS_SETTINGS)
=> On X11, don't require XSETTINGS

src/platform_impl/linux/common/xkb_state.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/atoms.rs, src/platform_impl/linux/x11/dnd.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs
--
I basically moved the code around, both commits should build and show what I've tried to achieve.
=> On X11, cleanup event processor implementation

CHANGELOG.md, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/window.rs, src/window.rs
There are quite a few stubs on Orbital that can be implemented. These were tested in Redox alongside some additions to Orbital to support them.
=> Orbital buildout

src/event.rs
Updating documentation for `ScaleFactorChanged` since it now has a `InnerSizeWriter` instead of a reference.
Relevant commit:
https://github.com/rust-windowing/winit/commit/9ac3259a79f996da63d91d5ee4b7233d14687b85#diff-14da7c350de5742eaa248de110fefeae9b4b639c0358e26024d6040ccf174a41R530
=> Fix Documentation for `ScaleFactorChanged` in `WindowEvent`.

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
In general, we may want to use xinput v2 for keyboard input in such cases, so we have compose going, but for now just don't crash if there's no XIM.
--
We can probably wire in such case the xinput v2 key input, thus will have the working dead keys, however I'd fix the crash first.
=> On X11, don't require XIM to be present

CHANGELOG.md, examples/web_aspect_ratio.rs, src/event_loop.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/ffi.rs, src/platform_impl/linux/common/xkb/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/observer.rs, src/platform_impl/web/async/dispatcher.rs, src/platform_impl/web/async/waker.rs, src/platform_impl/web/async/wrapper.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/event.rs, tests/send_objects.rs, tests/sync_object.rs
Fixes https://github.com/rust-windowing/winit/issues/3448.
=> Make `EventLoopProxy` `Sync`

CHANGELOG.md, src/platform_impl/linux/wayland/seat/pointer/relative_pointer.rs
`DeviceEvent::Motion` is supposed to be triggered on every analog device input, including mouse input
which was not the case in Wayland before. I found this bug, when launching an example from nannou wgpu_teapot_camera example, which shows the importance of this feature
This is (I think) my first PR ever, so if I missed something, please tell me
=> Wayland: Fixed DeviceEvent::Motion behaviour

src/platform_impl/ios/app_delegate.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/mod.rs, src/platform_impl/ios/view.rs, src/platform_impl/ios/view_controller.rs, src/platform_impl/ios/window.rs
This contains no functional changes, just a bit of re-organization to match the macOS backend.
=> iOS: Split classes in `view.rs` into separate files

Cargo.toml, src/lib.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/linux/common/xkb/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/util/wm.rs, src/platform_impl/macos/cursor.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/keyboard_layout.rs, src/platform_impl/windows/util.rs, src/utils.rs
A follow up to #2313. Removes the `once_cell` dependency, instead using `std::sync::OnceLock` and a minimal polyfill for `std::sync::LazyLock`, which may be stablized soon (see https://github.com/rust-lang/rust/pull/121377).
Should it be named `LazyLock` to match up with the proposed API? I kept it as `Lazy` for now.
This should not require a bump in MSRV, as `OnceLock` was stabilized in 1.70, which this crate is using.
=> Remove once_cell dependency

examples/util/fill.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/web/web_sys/schedule.rs
Fixes https://github.com/rust-windowing/winit/issues/3525.
Currently nightly fails because of FPs introduced by the new `non_local_definitions` lint.
FPs are tracked in https://github.com/rust-lang/rust/issues/121621.
=> Fix nightly CI

src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/util/xmodmap.rs
=> On X11, replay modifiers consumed by XIM

CHANGELOG.md, Cargo.toml, dpi/Cargo.toml, dpi/src/lib.rs, run-wasm/Cargo.toml, src/event.rs, src/lib.rs, src/monitor.rs, src/platform_impl/ios/window.rs, src/window.rs
Part of https://github.com/rust-windowing/winit/issues/3433.
This PR is mostly about the documentation update, the actual API changes that Tauri needs can be done in subsequent PRs.
CC @amrbashir
=> Split `dpi` module out into a separate crate

src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/event_handler.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs
This makes our use of `unsafe` to make the event handler temporarily 'static be local to a module, in a way that's (hopefully) much easier to reason about.
=> macOS: Refactor event handler storage

src/lib.rs
https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html
=> Fix feature = "cargo-clippy" deprecation

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/util/mod.rs, src/platform_impl/linux/x11/util/mouse.rs
Usually, if mouse events are equal to (0, 0) we filter them out.
However, if the event is very close to zero it will still be given to
the user. In some cases this can be caused by bad float math on the X11
server side.
I fix this by refusing to forward events where both of their deltas fall
below a certain threshold.
Closes #3500
=> Filter out tiny mouse events

CHANGELOG.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/cookie.rs, src/platform_impl/linux/x11/util/mod.rs
=> On X11, fix use after free during xinput2 processing

CHANGELOG.md, src/platform_impl/web/web_sys/schedule.rs
Apparently closing a `MessagePort` doesn't actually stop already delivered messages from triggering the message handler. So when we drop the message handler beforehand, it can cause a crash.
=> Web: fix crash with `ControlFlow::Wait|WaitUntil`

CHANGELOG.md, src/platform_impl/linux/x11/util/mouse.rs
This fixes the incorrect delta filtering. Due to a bug in the filtering
code, it would incorrectly filter out the correct mouse delta rather
than the one below zero. This fixes the order of events.
----
Closes #3558
=> Fix incorrect delta filtering

CHANGELOG.md, src/platform_impl/linux/wayland/window/state.rs
Some compositors break when re-taking the same grab.
Closes: https://github.com/rust-windowing/winit/issues/3566
=> chore(wayland): don't reapply same cursor grab

CHANGELOG.md, examples/control_flow.rs, examples/pump_events.rs, examples/run_on_demand.rs, examples/window.rs, examples/x11_embed.rs, src/application.rs, src/event.rs, src/event_loop.rs, src/lib.rs, src/platform/pump_events.rs, src/platform/run_on_demand.rs, src/platform/web.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/ios/window.rs, src/platform_impl/macos/app_delegate.rs, src/platform_impl/web/event_loop/runner.rs, src/window.rs
Winit is moving towards trait based end user application structure, thus add a simple `ApplicationHandler` trait which follows the `Event<T>`. To make use of this trait the new `run_app` group of APIs were added with the old `run` APIs being deprecated.
Part-of: #3432. Replaces https://github.com/rust-windowing/winit/pull/3386.
=> Add `ApplicationHandler` and matching run APIs

Cargo.toml
This bumps the minimal version of `x11-dl` required from v2.18.5 to v2.19.1, which is required by the changes made in #3507.
Thank you @paulcacheux for point this out.
Addresses https://github.com/rust-windowing/winit/pull/3507#issuecomment-1973316798.
=> Bump `x11-dl` to v2.19.1

CHANGELOG.md, src/platform_impl/linux/common/xkb/mod.rs
When composing the text was not reset to `None` leading to input in some applications e.g. alacritty.
Links: https://github.com/alacritty/alacritty/issues/7806
=> fix(xkb): text not being None when composing

.github/workflows/ci.yml, examples/window.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/util/xmodmap.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/windows/ime.rs, typos.toml
Same as https://github.com/rust-windowing/winit/pull/3557 but with [typos](https://github.com/crate-ci/typos)
Advantages:
-  Fast to run on monorepos
-  Low false positives so you can run on PRs
For reference typos is used in:
Bevy - https://github.com/bevyengine/bevy/pull/12036
Wgpu - https://github.com/gfx-rs/wgpu/pull/5191
=> Add typos - Source code spell checker 

dpi/CHANGELOG.md, dpi/src/lib.rs
=> Add `LogicalPoint`, `PhysicalPoint` and `Point`

CHANGELOG.md, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/util/window_property.rs, src/platform_impl/linux/x11/xsettings.rs
Don't crash when xsettings query fails with _present_ xsettings.
Closes: https://github.com/rust-windowing/winit/issues/3573
=> bugfix(x11): crash when querying xsettings prop fails

.github/workflows/ci.yml, dpi/src/lib.rs, src/cursor.rs
The conversion of PhysicalUnit was wrongly computed and the tests were not running on the CI for the dpi crate, thus it was missed, even though the test was correctly failing.
=> bugfix(dpi): `PhysicalUnit::to_logical` computation

dpi/CHANGELOG.md, dpi/src/lib.rs
---
Somehow I missed deriving those and didn't know until I tried replacing the `dpi` module in `tao` with this crate so I added a test to ensure these types will always be `Copy`.
If it is not too much to ask, could another release be made after merge?
=> Derive `Debug, Copy, Clone, PartialEq, Serialize, Deserialize` for `PixelUnit`

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/bug_android.yml, .github/ISSUE_TEMPLATE/bug_ios.yml, .github/ISSUE_TEMPLATE/bug_macos.yml, .github/ISSUE_TEMPLATE/bug_wayland.yml, .github/ISSUE_TEMPLATE/bug_web.yml, .github/ISSUE_TEMPLATE/bug_windows.yml, .github/ISSUE_TEMPLATE/bug_x11.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Add issue templates, in particular issue templates for each platform, such that we don't have to request the same information each time a new issue is opened.
You can see how it currently looks [over at my fork](https://github.com/madsmtm/winit/issues/new/choose).
I would like feedback on what each platform would like to request from the user. Feel free to edit this PR description.
=> Add issue templates

src/application.rs, src/cursor.rs, src/event.rs, src/event_loop.rs, src/keyboard.rs, src/lib.rs, src/monitor.rs, src/platform/web.rs, src/platform/windows.rs, src/platform_impl/web/web_sys/canvas.rs, src/window.rs
Follow-up to a discussion here: https://github.com/rust-windowing/winit/pull/3178#discussion_r1371280634.
The logic here is that `[foo](bar)` can be used for inline links or intra-doc links, but `[foo][bar]` can be used for labels or intra-doc links, so if no label is present, it can only be a intra-doc link, making this less ambiguous and more robust to error check.
=> Prefer `[foo][bar]` over `[foo](bar)` for intra-doc links

.github/CODEOWNERS, .github/workflows/ci.yml, Cargo.toml, dockerfiles/Dockerfile.ubuntu, it/common-tests/src/main.rs, it/gui-test-runner/Cargo.toml, it/gui-test-runner/src/command.rs, it/gui-test-runner/src/docker/command.rs, it/gui-test-runner/src/docker/linux.rs, it/gui-test-runner/src/docker/mod.rs, it/gui-test-runner/src/main.rs, it/gui-test-runner/src/stream.rs, it/gui-test/Cargo.toml, it/gui-test/src/lib.rs, it/gui-test/src/stream.rs, it/gui-test/src/user.rs
Creates a Docker image with xvfb in it and adds an option to use it to run 
integration tests.
Right now it seems that the X11 backend does not support XVFB, which requires
further investigation. So I haven't added it to CI just yet.
=> Implement Docker support in integration tests

src/changelog/unreleased.md, src/platform_impl/windows/window_state.rs
This fixes issues where a hidden and grabbed cursor could leave the window and become visible on top of the windows taskbar (and potentially leave the window altogether if the taskbar is clicked) under at least two occasions:
- When a window is overlapping the taskbar.
- When a window is maximized and `Automatically hide the taskbar` has been enabled.
This approach of confining the cursor to the center of the window is used in SDL.
=> On Windows, confine cursor to center of window when grabbed and hidden

src/error.rs, src/platform_impl/windows/window.rs
Failed job: https://github.com/rust-windowing/winit/actions/runs/8379455401/job/22946414148
=> Fix Clippy CI after Rust 1.77

src/platform_impl/linux/common/xkb/keymap.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/dnd.rs, src/platform_impl/linux/x11/util/geometry.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xsettings.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/state.rs, src/platform_impl/windows/window.rs
It appears that clippy's dead code detection has gotten better. This
commit fixes winit's code to match.
=> Silence clippy

src/changelog/unreleased.md, src/platform_impl/macos/view.rs
In particular, we don't want to emit those events inside of `pressureChangeWithEvent:`, since the mouse motion value is sometimes outdated.
Additionally, we want to ensure the events have been emitted during other gestures.
Fixes https://github.com/rust-windowing/winit/issues/3516.
=> Consistently emit extra mouse motion events

src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs
There are really stupid AV rules out there which cause almost any program that contains github URLs to become marked as malware.
While those rules are spurious, they're years old, and AV vendors have a very poor reputation at appropriately following up with these problems. I've already mailed Defender about this weeks ago and they've yet to respond.
Removing these strings from the panic data present in the binary prevents binaries linking the dependency from being spuriously marked as Trojan:Win32/Wacatac.B!ml.
It might be better to use an URL shortener or similar, but I suspect that if someone actually hits these rare cases, googling the path will be more than sufficient to get someone where they need to be.
I have tested this change by producing a release build prior to this change, …
=> windows: remove github URLs from binaries

src/platform_impl/linux/x11/ime/input_method.rs, typos.toml
[Example of failing workflow](https://github.com/rust-windowing/winit/actions/runs/8530045110/job/23367094972).
=> Fix CI failing when updating `typos` to 1.20.3

src/changelog/unreleased.md
Links: https://keepachangelog.com/en/1.0.0/
--
I was thinking maybe we can try to _link_ the changed APIs, since it should be possible now?
I'm also not really liking the way the platform changes look. Maybe use a subsection for them? And for toplevel changes write with a `implemented on X, Y, and Z`?
=> chore(changelog): use 'keep a changelog' format

src/changelog/unreleased.md
Add a migrations for the big API changes showcasing how to upgrade some common snippets of old code to new APIs.
Blocked on https://github.com/rust-windowing/winit/pull/3590.
=> chore(changelog): write migrations for 0.30

Cargo.toml, src/changelog/unreleased.md
This is a breaking change, because the system versions of the libraries used by sctk-adwaita were changed. Such changes cascade through all the deps, so all libraries using winit MUST do a breaking change.
--
Suggestions for how to handle such cascade breaking changes are much appreciated. For now I can only _warn_ in the changelog that you **must** do a breaking change as well to not break builds.
=> wayland: bump sctk-adwaita to 0.9.0

src/changelog/unreleased.md, src/window.rs
Since this is a nested struct, it was printing
`"WindowId(WindowId(2834882))"` when just printing `"WindowId(2834882)"` would be sufficient.
=> More concise `Debug` output for `WindowId`.

CONTRIBUTING.md
This is a forked version of #3549 with the following changes:
- Controversial parts (like the commit section) have been removed.
- Some of @madsmtm's nitpicks have been applied.
We can revisit those controversial parts in the future.
=> Forked version of "Rework CONTRIBUTING guidelines" without controversial changes

src/changelog/unreleased.md, src/platform_impl/linux/wayland/window/state.rs
In rare cases destroying subsurfaces before the main surface could result in a frame where the window is still shown, but decorations got hidden, right before the window itself disappears.
--
cc @Yalter
=> wayland: fix CSD decorations glitch when closing

src/platform_impl/linux/mod.rs
This replaces a reference to EventLoopBuilderExtUnix in a panic
message with EventLoopBuilderExtX11 or EventLoopBuilderExtWayland.
Closes #3488
=> Don't reference EventLoopBuildExtUnix in a panic message

Cargo.toml, src/platform_impl/windows/dpi.rs, src/platform_impl/windows/drop_handler.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/util.rs, src/platform_impl/windows/window.rs
=> windows: bump windows-sys to 0.52

src/changelog/unreleased.md, src/platform_impl/android/mod.rs
It seems that discussions around #2748 (cc @Hoodad) being a poor workaround that should rather be implemented properly/differently drowned out the fact that the workaround was implemented incorrectly to begin with.  By having the `if` inside the match arm, rather than /on/ the match arm the `keycode =>` path is /never/ used for `Volume*` keys and this event is thus never passed on to the user, defeating the purpose of calling `handle_volume_keys()`.  Only the `Handled`/`Unhandled` state is affected by the `ignore_volume_keys` workaround, as set by `EventLoopBuilderExtAndroid::handle_volume_keys()`.
Fix this by moving the `if` workaround on the match arm, so that disabling it via `EventLoopBuilderExtAndroid::handle_volume_keys()` causes `Volume*` events to be delivered to user code once …
=> bugfix(android): Allow `Volume*` keys to be passed to the user

src/changelog/unreleased.md, src/platform/windows.rs, src/platform_impl/windows/window.rs
On Windows, it is generally unsafe to use the HWND outside of the thread
that it originates from. In reality, the HWND is an index into a
thread-local table, so using it outside of the GUI thread can result in
another window being used instead, following by code unsoundness. This
is why the WindowHandle type is !Send. However, Window is Send and Sync,
which means we have to account for this.
Thus far the best solution seems to be to check if we are not in the GUI
thread. If we aren't, refuse the return the window handle.
----
=> On Windows, only return the window handle if it is on the correct thread

Cargo.toml, src/changelog/unreleased.md
=> On Android, bump to `ndk 0.9.0` and `android-activity 0.6.0`

Cargo.toml
Just in case, so the correct changelog will be rendered when pulling the crate from the crates.io as archive and trying to build it.
=> chore: ensure that `.cargo` config is not published

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/macos/window_delegate.rs, src/window.rs
Setting the background color changes how the window title bar appears, which is something that the application should customize itself if it wants this behaviour (and also, it wasn't set when calling `set_transparent`, so the behaviour wasn't consistent).
This was introduced all the way back in https://github.com/rust-windowing/winit/pull/853, so I can't really tell what the reasoning behind it was, but I assume it was for the examples to show better (i.e. setting the window as transparent worked even when not rendering into it).
Related: https://github.com/alacritty/alacritty/pull/7928
=> Don't set the background color when initializing with transparency

src/platform_impl/web/mod.rs
See https://github.com/rust-lang/rust-clippy/issues/12377, which I think should be in v1.79 again?
=> Web: fix Clippy v1.78 FPs

src/changelog/unreleased.md, src/platform_impl/macos/app_delegate.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window.rs, src/platform_impl/macos/window_delegate.rs
The delegate is only weakly referenced by NSApplication, so getting it from there may fail if the event loop has been dropped.
Fixes https://github.com/rust-windowing/winit/issues/3668.
=> Keep a reference to ApplicationDelegate in NSWindowDelegate and NSView

src/changelog/unreleased.md, src/lib.rs
When the user decides to use an older version of raw-window-handle, through the `rwh_04` or `rwh_05` features, it makes sense to reexport the crate so they don’t have to depend on it manually and can instead use `winit::raw_window_handle`.
=> Reexport older versions of raw-window-handle

src/platform_impl/linux/x11/event_processor.rs
**Reason for Pull Request:** On Raspberry Pi, using the Rust crate eframe caused the program to crash on mouse movement. The Backtrace lead to this specific line of code, and the exact error was a "misaligned pointer dereference: address must be a multiple of 0x8 but is xxxx"
The edit has been tested with the Raspberry Pi, which works now.
Technical information:
- Raspberry Pi 3 B+
- Raspbian OS Bullseye 32-Bit
- Using the Waveshare 3.5 (A) display connected via GPIO
- Using <https://github.com/goodtft/LCD-show> as display drivers
=> Replace pointer dereference with read_unaligned()

examples/child_window.rs, src/changelog/unreleased.md, src/changelog/v0.30.md, src/event_loop.rs, src/platform/pump_events.rs, src/platform/run_on_demand.rs, src/platform/web.rs, src/platform_impl/android/mod.rs, src/platform_impl/ios/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/windows/event_loop.rs
The APIs are not well suited for the `&dyn ApplicationHandler` model and
`Box<dyn EventLoop>` structure, thus remove them.
=> event_loop: remove deprecated `run` APIs

src/changelog/unreleased.md, src/platform_impl/macos/app_delegate.rs
On macOS, when dragging across monitor boundary with a different scale factor, the `QueuedEvent::ScaleFactorChanged` event will be emit.
When process this event, will [unconditionally set the content size](https://github.com/rust-windowing/winit/blob/ab33fb8eda45f9a23587465d787a70a309c67ec4/src/platform_impl/macos/app_delegate.rs#L380), which would cause some glitch.
---
Because the event is emitted with `suggested_size` set to [current frame size](https://github.com/rust-windowing/winit/blob/ab33fb8eda45f9a23587465d787a70a309c67ec4/src/platform_impl/macos/window_delegate.rs#L774).
So, if the user hasn't requested a size change, the call to `setContentSize` wouldn't actually change the size.
So, change to only call `setContentSize` if the user has requested a size change.
---
=> fix drag glitch when dragging across monitor boundary

src/changelog/unreleased.md, src/platform/wayland.rs, src/platform/x11.rs, src/platform_impl/linux/mod.rs
---
Winit v0.30 does not allow testing `is_wayland` on an `EventLoop` (but only on an `ActiveEventLoop`), though this appears to be possible. This is an issue for me.
The trait names `ActiveEventLoopExtWayland` and `ActiveEventLoopExtX11` are now inaccurate (may cause issues with future additional functionality?), but this is the most straightforward solution.
Fixes https://github.com/rust-windowing/winit/issues/3670
=> Support is_x11 and is_wayland on EventLoop

src/platform_impl/ios/app_delegate.rs, src/platform_impl/ios/app_state.rs, src/platform_impl/macos/app.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_handler.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/mod.rs, src/platform_impl/macos/observer.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs
I'm preparing to get rid of our application delegate in favour of registering notification observers, to do so I'm renaming `app_delegate.rs` to `app_state.rs`, and moving the functionality out of the Objective-C method into a normal method.
Additionally, `AppState` previously implemented `Default`, but really, this was a hack done because someone (probably myself) was too lazy to write out the full initialization in `AppDelegate::new`.
This is (deliberately) a non-functional change.
=> macOS/iOS: Various refactorings in application state

src/changelog/unreleased.md, src/platform_impl/web/async/waker.rs, src/platform_impl/web/event_loop/runner.rs
This also checks if its coming from a thread or not, in which case it doesn't queue it.
I also noticed some legacy code that deferred to `ControlFlow::Poll` when receiving events instead of waking up the event loop immediately, which I removed, so now events should come in faster regardless of `PollStrategy`.
Fixes #3715.
=> Web: queue `EventLoopProxy::send_event()` to microtask when triggered from outside the event loop

src/changelog/unreleased.md, src/platform_impl/web/cursor.rs
When setting `CursorIcon::Default` on Web, it now simply removes the `cursor` style, this prevents overwriting any user set default cursor.
Fixes #3661.
=> Web: don't overwrite cursor with `CursorIcon::Default`

src/changelog/unreleased.md, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/resize_scaling.rs
=> Web: prevent crash when using `InnerSizeWriter::request_inner_size()`

Cargo.toml, src/platform_impl/macos/window_delegate.rs, src/window.rs
Not using `NSColor::clearColor()` results in Quartz thinking that the window is not transparent at all, which results in artifacts.
However, not setting the `windowBackgroundColor` in `Window::set_transparent` results in border not properly rendered.
Fixes: 94664ff6876cd (Don't set the background color)
--
This is kind of a revert, given that https://github.com/alacritty/alacritty/pull/7965 not really doing anything and the window is not really tranparent as it should (it kind of is, but the value is different to what it should be and Quartz glitches behind the window with damage tracking).
Though, Quartz seems to generally glitch with e.g. shadows if you reload opacity with these changes as well. Maybe we should do something completely different, but I only care to fix the regression.
=> macOS: fix opacity handling

src/changelog/unreleased.md, src/platform_impl/linux/x11/ime/context.rs
The c_char type, which was used under the hood is different depending on arch, thus use it directly instead of i8.
Fixes #3735.
=> x11: fix build on arm

Cargo.toml, examples/window.rs, src/changelog/unreleased.md, src/event.rs, src/platform_impl/macos/window_delegate.rs, src/window.rs
This new implementation uses:
- The NSAppearanceCustomization protocol for retrieving the appearance of the window, instead of using the application-wide `-[NSApplication effectiveAppearance]`.
- Key-Value observing for observing the `effectiveAppearance` to compute the `ThemeChanged` event, instead of using the undocumented `AppleInterfaceThemeChangedNotification` notification.
This also fixes `WindowBuilder::with_theme` not having any effect (fixes https://github.com/alacritty/alacritty/issues/8046), and the conversion between `Theme` and `NSAppearance` is made a bit more robust.
=> macOS: Set the theme on the `NSWindow`, instead of application-wide

.github/workflows/ci.yml, .gitignore, .swcrc, Cargo.toml, src/changelog/unreleased.md, src/platform/web.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/schedule.rs, src/platform_impl/web/web_sys/worker.js, src/platform_impl/web/web_sys/worker.min.js
This implements an alternative scheduling strategy for `ControlFlow::WaitUntil` on Web to prevent throttling when the tab is not focused by using a worker, which commonly browsers don't throttle regardless of tab focus.
I also added another step to the CI to add JS minification, let me know if you want me to remove it.
Fixes #3738.
=> Web: implement `WaitUntilStrategy`

Cargo.toml
The latter syntax is deprecated and will be removed in Rust 2024 edition. This also generates a warning with current versions of Rust.
=> Use `default-features`, not `default_features`

src/platform_impl/macos/app.rs, src/platform_impl/macos/app_state.rs, src/platform_impl/macos/event_handler.rs, src/platform_impl/macos/event_loop.rs, src/platform_impl/macos/view.rs, src/platform_impl/macos/window_delegate.rs
When we added `ApplicationHandler`, the intention was always to slowly phase out `Event` - this does that in the macOS backend.
Extracted from https://github.com/rust-windowing/winit/pull/3694 to reduce the diff in that.
=> macOS: Call `ApplicationHandler` directly instead of using `Event `

src/platform_impl/mod.rs, src/platform_impl/web/mod.rs
Rust tooling generally works better this way. This includes rust-analyzer, but more noticeably the output from `tracing` typically prints the module path, which did not correspond to the actual file system before.
Concretely, tracing output from the macOS backend changes from printing `winit::platform_impl::platform::util` to printing `winit::platform_impl::macos::util`.
=> Avoid `path` when importing modules

FEATURES.md, src/changelog/unreleased.md, src/platform/ios.rs, src/platform_impl/apple/uikit/event_loop.rs
Introduced in #871 with unclear motivation.
@mtak- could you provide context for why Winit has this? Is it just for convenience?
=> Remove `EventLoopExtIOS::idiom` and `ios::Idiom`

src/changelog/unreleased.md, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/event.rs
Apparently `MouseEvent.movementX/Y` should not be used anymore.
Replacing it with `screenX/Y` simplifies the code, removes unnecessary conversion and increases accuracy.
Addresses https://github.com/rust-windowing/winit/issues/2875.
=> Web: Remove some unnecessary compatibility code

src/changelog/unreleased.md, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/windows/event_loop.rs
This PR adds `ActiveEventLoop::create_proxy()`, letting users create `EventLoopProxy` from inside the event loop.
Internally I basically just moved `backend::EventLoop::create_proxy()` to `backend::ActiveEventLoop::create_proxy()`.
Fixes #3741.
=> Add `ActiveEventLoop::create_proxy()`

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/mod.rs
This basically reverts #3766.
Reason being that `screenX/Y` doesn't work when locking the pointer. Its also not ideal because when you move the pointer out of the frame and enter it again, it pretends like the mouse moved a lot, which is quite different then what `movementX/Y` reports and probably not what we want.
Seeing that its unclear in the spec how browsers should implement `movementX/Y` I also opened https://github.com/w3c/pointerlock/issues/100.
Now that we don't have a choice but use `movementX/Y` we have to account for the following:
1. Pretend like https://github.com/w3c/pointerlock/issues/100 has been resolved and all browsers actually set values there instead of zero. Which they currently do.
2. Account for browsers not actually following the spec which coordinate system to …
=> Web: fix `MouseMotion` coordinate space

examples/child_window.rs, examples/control_flow.rs, examples/window.rs, examples/x11_embed.rs, src/changelog/unreleased.md, src/event_loop.rs, src/platform/pump_events.rs, src/platform/run_on_demand.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/windows/event_loop.rs
Since https://github.com/rust-windowing/winit/pull/3709, we do a blanket impl of `ApplicationHandler` for `&mut` references. This means that we can now change `run_app_x` methods to consume the application instead of taking a reference to it.
This allows the user more control over how they pass their application state to Winit.
Internally, each backend is free to convert the `app` to an `&mut app` (or `&mut dyn ApplicationHandler`) if that's easier for them to pass around.
=> Change `run_app(app: &mut A)` to `run_app(app: A)`

src/changelog/unreleased.md, src/event.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/web/device.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/mod.rs, src/window.rs
I'm sure this had some historical context, but none of these IDs are passed into anything anymore.
I included this in the Winit 0.30.4 milestone because this isn't a breaking change.
Let me know if this is somehow a bad idea.
=> Make `DeviceId/WindowId::dummy()` safe

src/platform/run_on_demand.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/windows/event_loop.rs
How to store and clear the internal state should be internal to the implementation on each backend.
I'm doing this because I want to refactor the macOS backend to not need to track this state manually in the future, which I so far _think_ should be possible: `NSApplication` itself already (roughly) tracks this in [`-[NSApplication isRunning]`](https://developer.apple.com/documentation/appkit/nsapplication/1428759-running?language=objc).
=> Remove internal `ActiveEventLoop::clear_exit`

Cargo.toml, deny.toml, src/platform_impl/linux/wayland/state.rs
Update SCTK as a follow-up to 1170554dbdb (ignore events to dead objects) fixing it for wl_output.
=> wayland: bump dependencies

src/changelog/unreleased.md, src/platform_impl/web/event_loop/window_target.rs
This caused two issues:
- `WindowEvent::RedrawRequested` send after an `WindowEvent::Resized` would not be throttled.
- Using `Window::request_redraw()` after an `WindowEvent::Resized` will cause two `WindowEvent::RedrawRequested` events. The first one not throttled and the second one throttled by rAF.
Probably a leftover from #2896.
=> Web: fix `WindowEvent::Resized` not using rAF

src/changelog/unreleased.md, src/platform/web.rs
=> Web: implement `Error` for `CustomCursorError`

src/changelog/unreleased.md, src/platform/web.rs
This was initially there before refactoring these errors into `BadAnimation`.
Separated from #3793 because this is a breaking change.
Missed in #3384.
=> Web: remove unused `CustomCursorError::Animation`

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/linux/x11/atoms.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs
Resolves #2153.
I only tested this on KDE so far, this probably needs more tests on other DEs and WMs.
~~One thing I'm unsure about is whether all the widely used DEs and WMs support the sync API. I know KDE and Gnome definitely do, and it seems that awesomewm also does, but I don't know if some other important ones don't. Searching around, I saw that [Qt preemptively checks if the sync extension is supported](https://github.com/qt/qtbase/blob/bcfa0102e5910d99263ebb73515cc9d35b818b5c/src/plugins/platforms/xcb/qxcbwindow.cpp#L420) through a `hasXSync` call, but I couldn't find a way to do that with `x11rb` so right now there's just no checks...~~ Done through suggestion.
~~On KDE, there's also the subtly weird behavior of the window when resizing a certain way that I mentioned in [this C …
=> Implement smooth resizing on X11 with _NET_WM_SYNC_REQUEST

src/changelog/unreleased.md, src/platform_impl/apple/appkit/window_delegate.rs
I noticed while working on MacOS that I had some build error in `rwh_04::HasRawWindowHandle`, but always thought there was just something wrong with my cross-compile setup. I believe the issue was caused in https://github.com/rust-windowing/winit/pull/3391, where all calls to `contentView()` were renamed while this one was forgotten.
This should have been caught by the CI, but we don't check these features in CI. Luckily we may not want to actually fix the CI and instead remove this compatibility layer?
If this patch is correct, it should also be broken in [v0.30](https://github.com/rust-windowing/winit/blob/v0.30.4/src/platform_impl/macos/window_delegate.rs#L1611-L1618).
Cc @madsmtm.
=> macOS: fix building with `feature = "rwh_04"`

.github/workflows/ci.yml, README.md
It makes no sense to have an MSRV policy for Redox OS and test it in CI if it requires nightly to begin with.
As discussed in https://github.com/rust-windowing/softbuffer/pull/228#discussion_r1686692401.
=> Exclude Redox OS from the MSRV policy

src/changelog/unreleased.md, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/pointer.rs
After some discussion with @kchibisov on Matrix, I came to the realization that pen input should not be blocked and instead be routed to `WindowEvent::Cursor*` as usual.
Related #3810.
=> Web: don't block pen input

src/changelog/unreleased.md, src/platform/web.rs, src/platform_impl/web/async/dispatcher.rs, src/platform_impl/web/async/notifier.rs, src/platform_impl/web/async/waker.rs, src/platform_impl/web/async/wrapper.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/proxy.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/window.rs
- Internal: Fix dropping `Notifier` without sending a result causing `Future`s to never complete. This should never happen anyway, but now we get a panic instead of nothing if we hit a bug.
- Internal: Remove a bunch of `unwrap()`s that aren't required when correctly using `MainThreadMarker`.
- `Window::canvas()` is now able to return a reference instead of an owned value.
Extracted from #3801.
=> Web: async improvements

src/changelog/unreleased.md, src/event.rs, src/platform/web.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/lock.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/window.rs
This uses [`Element.requestPointerLock` with the `unadjustedMovement` options](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock#unadjustedmovement), which is notable only supported by Chrome and even there not on Linux.
I also updated the documentation to properly reflect the current state.
Needs entry in #2875.
Fixes #3547.
=> Web: use raw data in `DeviceEvent::MouseMotion` when using `CursorGrabMode::Confined`

src/changelog/v0.20.md, src/changelog/v0.9.md, src/event.rs, src/platform/pump_events.rs, src/platform_impl/windows/raw_input.rs, src/window.rs
[`clippy::doc_lazy_continuation`](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation) was added, which needed some fixing from our side.
=> Fix CI for Rust v1.80

src/changelog/unreleased.md, src/event_loop.rs, src/monitor.rs, src/platform/windows.rs, src/window.rs
--
I think there's no reason to keep them around for the 0.31.
=> chore: drop v0.30 deprecated APIs

src/changelog/unreleased.md, src/platform/android.rs, src/platform_impl/android/mod.rs
This type comes from the user and stored for the entire lifetime, so no need to hide it from them after they've passed it to winit.
Fixes #3818.
--
I can not really test it, but it's rather trivial and should just work, I guess.
@mwcampbell I guess you need something like that?
=> android: add `ActiveEventLoopExtAndroid::android_app`

.github/dependabot.yaml
While we are at it, add GitHub Actions to Dependabot.
I didn't add Cargo because we didn't reach consensus on that in the past.
=> Add GitHub Actions to Dependabot

.github/workflows/ci.yml, .github/workflows/docs.yml, Cargo.toml, examples/child_window.rs, examples/util/fill.rs, src/changelog/unreleased.md, src/event_loop.rs, src/lib.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/window.rs
As discussed before (somewhere), this PR removes `raw-window-handle` v0.4 and v0.5 support.
Also renames the `rwh_06` feature to `raw-window-handle`.
We could also remove the whole crate feature now that we support only one version?
=> Remove `raw-window-handle` v0.4 and v0.5 support

src/platform_impl/windows/event_loop.rs
`Box::into_raw()` was used to leak a value, but we have `Box::leak()` for that.
This was detected by a new change in Nightly Rust that applied `#[must_use]` to the return value of `Box::into_raw()`.
Unbreaks the Nightly CI.
=> Windows: use `Box::leak()` instead of `Box::into_raw()`

src/monitor.rs, src/platform/web.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/monitor.rs
- Improved the documentation to point users into the right direction from all kinds of methods and types.
- De-duplicated some code and added more comments.
- Implement an ID system to correctly and efficiently implement `Eq`, `Hash`, `Ord`, `PartialEq` and `PartialOrd`.
- Fixed screen locking support being cached thread local, ergo calling from a different thread would require to make the check again, not fulfilling its purpose as a fast-path at all.
=> Web: monitor API improvements

examples/window.rs, src/changelog/unreleased.md, src/event.rs, src/platform_impl/apple/appkit/app.rs, src/platform_impl/linux/wayland/seat/pointer/relative_pointer.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop.rs
We decided to remove them because they contained too little information for the user to be useful. This was only implemented in X11, other backends were only using them to be more cross-platform consistent.
The assumption is that they were originally implemented to enable gamepad support, which we already decided we are not going to add directly to Winit, but only support events informing the user that an UUID was added or removed.
See https://github.com/rust-windowing/winit/issues/750#issuecomment-2245015159.
=> Remove `DeviceEvent::Motion` and `WindowEvent::AxisMotion`

src/changelog/unreleased.md, src/platform_impl/apple/appkit/window_delegate.rs
Prevent assertion error when trying to close a fullscreen window that was on a display that got disconnected.
---
=> Skip releasing displays that are unavailable

README.md
It has low amount of users and not active, so better direct people straight to matrix at this point.
=> chore: drop libera link

examples/window.rs, src/changelog/unreleased.md, src/cursor.rs, src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/cursor.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/window.rs
This PR changes `(Active)EventLoop::create_custom_cursor()` to return a `Result<CustomCursor, ExternalError>`.
- Android, iOS and Orbital now return `ExternalError::Unsupported`.
- MacOS, Windows and X11 can now return an error instead of panicking or doing nothing.
- Wayland doesn't implement custom cursor like other platforms (yet?) and actually creates it in `set_custom_cursor()` instead, so it currently panics there.
- Web will continue to do nothing, because errors are delivered asynchronously. However it already had `create_custom_cursor_async()` to properly return an error.
Related #3306.
Follow-up to #3749.
=> Make `(Active)EventLoop::create_custom_cursor()` return a `Result<CustomCursor, ExternalError>`

src/changelog/unreleased.md, src/event.rs, src/platform/web.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/apple/uikit/view.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/seat/touch/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/device.rs, src/platform_impl/web/event.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs
This replaces `Touch::id` with `Touch::finger_id` and introduces a new type `FingerId` instead.
Additionally on Web it exposes [`PointerEvent.isPrimary`](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/isPrimary) which tells the user if the finger is the primary/first one in a multi-touch interaction.
I also went ahead and implemented this for Windows.
@MarijnS95 pointed out how this could be implemented for Android in https://github.com/rust-windowing/winit/pull/3783#issuecomment-2227447405.
But other OSs would have to be polyfilled.
We could potentially expose this directly to the user without a platform specific extension trait if we implement enough platforms.
**Followup**
Entry in #2875: Firefox emits wrong primary fingers …
=> Introduce `FingerId`

Cargo.toml, src/changelog/unreleased.md, src/cursor.rs, src/error.rs, src/event.rs, src/event_loop.rs, src/icon.rs, src/keyboard.rs, src/monitor.rs, src/platform/ios.rs, src/platform/macos.rs, src/platform/pump_events.rs, src/platform/web.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/window.rs
Notable implementations:
- `DeviceId`: `Default`, uses `DeviceId::dumy()`.
- `ActiveEventLoop`, `EventLoop`, `EventLoopProxy`: refrained from implementing anymore then `Debug` because they should be unique.
- `EventLoopBuilder`: `Eq`, `Hash` and `PartialEq`.
- `InnerSizeWriter`: refrained from implementing `Hash`.
- `OwnedDisplayHandle`: `Eq` and `PartialEq`.
- `KeyLocation`, `ModifiersKeyState`: `Ord` and `PartialOrd`.
- `AnyThread`: `Clone`.
- `Window`: `Eq`, `Hash` and `PartialEq` via `WindowId`.
Replaced `Debug` implementations using `f.pad("Type { .. }")` with `f.debug_struct("Type").finish_non_exhaustive()`.
Let me know if anything is too contentious and I can remove it.
Follows [C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement …
=> Implement common Std traits on many types

examples/window.rs, src/changelog/unreleased.md, src/monitor.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/uikit/monitor.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/monitor.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs
After some discussion we decided its more useful to encode current monitor information into `VideoModeHandle` then move more information to `MonitorHandle`. To this end this PR implements `MonitorHandle::current_video_mode()`.
Additionally `MonitorHandle::size()` and `refresh_rate_millihertz()` were removed, because it logically fits into video modes and not the monitor itself.
To improve the output, this PR also changes `VideoModeHandle::refresh_rate_millihertz()` to return a `Option<NonZeroU32>` and `size()` and `bit_depth()` an `Option`.
Follow up to #3801.
=> Add `MonitorHandle::current_video_mode()`

src/platform/android.rs, src/platform/macos.rs, src/platform/startup_notify.rs, src/platform/wayland.rs, src/platform/web.rs, src/platform/x11.rs
This was implemented for `&dyn ActiveEventLoop` in https://github.com/rust-windowing/winit/pull/3827, but that's less general than implementing it directly for `dyn ActiveEventLoop`.
The `+ '_` is required to tell the compiler that we want to implement this for all `dyn ActiveEventLoop`s, not just `'static` ones (even though they're all going to be `'static`).
This is especially confusing because the requirement to add `+ '_` on `dyn Trait` types differs depending on the place where `dyn Trait` is used, see [the reference](https://doc.rust-lang.org/reference/lifetime-elision.html#default-trait-object-lifetimes).
- No entry added, as this isn't yet released
=> Properly implement event loop extension traits

src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/windows/event_loop.rs, src/utils.rs
This removes the direct requirement to implement `as_any` and it could be just derived.
Also implement HasDisplayHandle for dyn ActiveEventLoop + '_.
Suggested-by: @daxpedda
=> chore: use our own AsAny<T> upcasting

Cargo.toml, deny.toml, src/platform_impl/web/cursor.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/web_sys/resize_scaling.rs, src/platform_impl/web/web_sys/schedule.rs
This gets rid of:
- The shell file exceptions we accounted for in `cargo-deny`.
- The custom binding to [`queueMicrotrask()`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask).
- The deprecated setter methods.
=> Update minimum version of `wasm-bindgen`

src/changelog/unreleased.md, src/platform/web.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/window.rs, src/window.rs
- Return `MonitorHandle` in `Window::fullscreen()`
- Change `OrientationData::natural` type from `bool` to `Orientation`, just telling the user what the natural orientation is instead of letting the user "do the math".
- Fix and improve some monitor related documentation.
Follow-up to #3801.
=> Web: return `MonitorHandle` in `Window::fullscreen()`

.github/workflows/ci.yml, Cargo.toml, deny.toml, dpi/Cargo.toml, src/platform/macos.rs
This adds support for `aarch64-apple-darwin`, which includes no code related changes, just updating the CI and our other configurations.
=> Add support for MacOS ARM64

src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/event_handler.rs, src/platform_impl/apple/mod.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs
Instead of storing the event handler within the AppState, and extracting it our every time we need it, we now use the same event handling implementation as for macOS that ensures we don't re-entrantly call the event handler, and that we un-register the handler again after we're done using it (`UIApplicationMain` won't return, but may still unwind, so this is very important for panic safety).
This is the first step of me trying to untangle the inscrutable mess that is the current event handling on iOS.
=> iOS: Refactor event handling to share code with macOS

src/platform/ios.rs, src/platform/macos.rs, src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/window.rs
No longer necessary after https://github.com/rust-windowing/winit/pull/3447 and https://github.com/rust-windowing/winit/pull/3826.
- I did not feel it is necessary to note in the changelog, as this
=> macOS/iOS: Remove window activation hacks

src/platform/ios.rs, src/platform/macos.rs, src/window.rs
Improve the platform-specific documentation with:
- Somewhat, still not really happy with it.
Builds upon #3872 to avoid a rebase later on.
=> Improve iOS documentation

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/apple/uikit/view.rs, src/platform_impl/apple/uikit/window.rs, src/window.rs
This implements basic iOS IME support (typing, backspace, support for emojis etc but no autocomplete or copy / paste menu).
I've tested this with egui on winit 0.29 but unfortunately I wasn't able to test this yet with winit 0.30 since egui isn't updated yet.
This is an alternative implementation of #3571, implementing UIKeyInput for the WinitView instead of creating a extra text_field.
I'll leave this in draft until I was able to test this with egui and winit 0.30
=> Basic iOS IME support

src/platform_impl/linux/mod.rs
A panic doesn't really put any of the fields in XConnection into an invalid
state, so there is no real reason to panic when poisoning is detected.
So just ignore the poison.
Closes #3870
=> Ignore mutex poisoning in X11_BACKEND

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/linux/x11/ffi.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/util/cursor.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/linux/x11/xdisplay.rs
Another one bites the dust.
This replaces the code dependent on libxcursor with equivalent code
written using x11rb, featuring its special "cursor" module.
cc #3198
=> Replace libxcursor with custom cursor code

src/platform_impl/linux/mod.rs
This makes it so, when X11 fails to initialize due to not loading a
library, it provides more verbose information on what exactly happened.
cc #3883
Signed-off-by: John Nunley <dev@notgull.net>
=> Put more information in X11 "not supported" initialization errors

src/changelog/unreleased.md, src/changelog/v0.30.md, src/platform/macos.rs, src/platform_impl/apple/appkit/window_delegate.rs
=> macOS: add option to explicitly hide menu/dock in Borderless

Cargo.toml, examples/window.rs
Softbuffer v0.4.6 added support for UIKit, see https://github.com/rust-windowing/softbuffer/pull/234.
=> Enable drawing on iOS/UIKit in examples

src/lib.rs
As discussed in today's meeting, this commit creates two tiers of
support. Tier 1, which is what we actively test, and Tier 2, what we
hope compiles.
=> Explicitly demarcate platform support

src/event.rs
Quick documentation addition: I was looking at the docs for `CursorMoved` and wasn't sure how to correctly get relative motion for a 3D camera. I've added a x-ref doc link to `MouseMotion` to help others in a similar predicament.
=> doc: mention `DeviceEvent::MouseMotion` in `WindowEvent::CursorMoved`

src/changelog/unreleased.md, src/platform_impl/apple/appkit/window_delegate.rs
Fixes https://github.com/rust-windowing/winit/issues/1721
=> macOS: Fix move event sometimes being triggered on resize

src/changelog/unreleased.md, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/mod.rs, src/window.rs
As there shouldn't really be a need for a user-constructible `WindowId`, I assume this was used previously because `WindowId` was passed as a parameter?
~~I introduced `WindowId::to_u64()` as a replacement, but I'm not sure if this has any use case.~~
After the last meeting we decided to add conversion methods called `from_raw()` and `into_raw()`.
=> Replace `WindowId` `From/Into` `u64` with `WindowId::into_raw()` and `from_raw()`

examples/child_window.rs, examples/window.rs, src/changelog/unreleased.md, src/event.rs, src/event_loop.rs, src/platform/web.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/app.rs, src/platform_impl/apple/appkit/view.rs, src/platform_impl/apple/uikit/view.rs, src/platform_impl/linux/common/xkb/keymap.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/seat/pointer/relative_pointer.rs, src/platform_impl/linux/wayland/seat/touch/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/mod.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/util.rs
This implements #3833, please see it for all the details.
This implementation deviates on `PointerLeft::position`, which is now an `Option`, because Windows (and maybe MacOS) doesn't have this kind of information.
It also adds `FingerId` to `PointerType`, which was an oversight of #3833.
Notably I also removed pen/stylus handling in iOS and Windows, which is now emitted as `PointerType::Unknown`.
I plan to reintroduce the same code and expand on it in #3810.
#3874 was a side-product of this PR.
- Rename `CursorMoved` to `PointerMoved`.
- Rename `CursorEntered` to `PointerEntered`.
- Rename `CursorLeft` to `PointerLeft`.
- Rename `MouseInput` to `PointerButton`.
- Add `position` to every `PointerEvent`.
- Remove `Touch`, which is folded into the `Pointer*` events.
- New `PointerType` added …
=> Implement the pointer event overhaul

src/changelog/unreleased.md, src/event.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/event.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/windows/mod.rs
The same as for `WindowId`.
This also removes the internal platform ID.
--
I'm not sure what type to pick here, since some use u32, some i32. I think `i64` would be the best, but then, negative values for DeviceId are strange?
Also, it's not that clear to what IDs should be limited.
For now I'm just using `u64`.
=> api: add `DeviceId::{into,from}_raw`

src/event_loop.rs, src/platform/windows.rs, src/platform_impl/linux/mod.rs, src/platform_impl/windows/event_loop.rs
I found some documents and error messages refer to `with_any_thread()` as `any_thread()`. This pull request fixes the typo. 
Since this changes only documentation, I didn't do any tests on my local.
=> Fix function name of `with_any_thread` in doc and error message

src/changelog/unreleased.md, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/ime/mod.rs
=> x11: don't forward key events to IME when it's disabled

src/application.rs, src/changelog/unreleased.md, src/event.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/window_delegate.rs
Addresses #3779
Key them off of `onStop()` and `onStart()` which seems to match the other backends most closely.  These [Android Activity lifecycle] events denote when the application is visible on-screen, and recommend that any heavy lifting for startup and shutdown happens here, as the application may be demoted to the background and later shut down entirely unless the user navigates back to it.
EDIT: Also addresses some of the late review comments that were posted on https://github.com/rust-windowing/winit/pull/3765.
[Android Activity lifecycle]: https://developer.android.com/guide/components/activities/activity-lifecycle
=> android: Forward `suspended()` and `resumed()` events and patch up platform-specific documentation

src/changelog/unreleased.md, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/appkit/window_delegate.rs
Problem: winit would panic when `appkit::drag_window()` was called without a left click event being present. This problem was discovered while reviewing this [PR for bevy](https://github.com/bevyengine/bevy/pull/15674#issuecomment-2401699844).
Solution: Return a result from `drag_window()`. In winit 0.30.5 `drag_window()` already returned a result, but 'main' branch had no return value. So this reverts the function signature to an earlier one.
It seems like this affects macOS. I exercised this on an M2 macOS machine using the "window" example.
=> Return error on missing event instead of panicking.

Cargo.toml, src/changelog/unreleased.md, src/platform/macos.rs, src/platform_impl/apple/appkit/window_delegate.rs
---
Adds `WindowExtMacOS::set_unified_titlebar` and `WindowAttributesExtMacOS::with_unified_titlebar`, which allow you to use a larger titlebar style on macOS.
| Without unified titlebar (default)                                                                                                                | With unified titlebar                                                                                                                             |
|---------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="912" alt="Screenshot …
=> macOS: add ability to make titlebar unified

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/windows/event_loop.rs
Previous version used [`SetTimer`] with `GetMessageW` for waiting.
The downside of UI timers like ones created by `SetTimer`,
is that they may be late by up to 15-16 ms.
To fix this behaviour, I added use of high resolution timers created by [`CreateWaitableTimerExW`] with the flag `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION`.
In my previous experience, waiting on such timers have precision of roundly 0.5 ms which is the best available on Windows at the moment.
I use [`MsgWaitForMultipleObjectsEx`] to wait simultaneously for both timer and newly arriving events.
Unfortunately, high resolution timers are available only since Windows 10 1803. However:
1. Win 10 is already getting to the end of support, like all previous versions, so it is OK to rely on APIs introduced in it;
2. I use …
=> Improve waiting for messages on Windows

src/changelog/unreleased.md, src/platform_impl/linux/x11/window.rs
**Before** this PR, running the `window` example on a X11 screen that is not the first one (like `DISPLAY=0.1`) always fails with
`failed to create initial window: Os(OsError { line: 617, file: "src/platform_impl/linux/x11/window.rs", error: X11Error(X11Error { error_kind: Match, error_code: 8, sequence: 218, bad_value: 1321, minor_opcode: 0, major_opcode: 1, extension_name: None, request_name: Some("CreateWindow") }) })
`
_Here `1321` is the parent (root) window id of my screen 1, but what the X server really tries to say here (AFAICS) is "the passed visual id is not available for the passed parent window id"._
<details><summary>Full invocation</summary>
```
[tonari@tonari-prague-dev winit]$ DISPLAY=:0.1 cargo run --example window
Finished `dev` profile [unoptimized + debuginfo] …
```
=> x11: iterate only visuals from the matching screen

src/changelog/unreleased.md, src/event.rs, src/platform/mod.rs, src/platform/web.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/appkit/view.rs, src/platform_impl/apple/mod.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/apple/uikit/view.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/seat/mod.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/seat/touch/mod.rs, src/platform_impl/linux/x11/event_processor.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/event.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/web_sys/canvas.rs, src/platform_impl/web/web_sys/event.rs, src/platform_impl/web/web_sys/pointer.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/keyboard.rs, src/platform_impl/windows/mod.rs
Whether the pointer event is primary or not generally matters for the
context where all input is done by the same event, so users can
_ignore_ non-primary events since they are likely from users clicking
something else with their other fingers.
Having it only on a FingerId made it useless, since it's usually used
to avoid multi-touch, but if you start mapping on touch event you
already can track things like that yourself.
Fixes #3943.
--
@daxpedda I left the web, since it's starting to get messy with those callbacks, so you might want to refactor things to your liking. I could still plumb those bools though.
That's also the reason PR doesn't really build.
@madsmtm I did only `true` for `ios`, which is likely fine, but I guess we could track based on some `Option<Touch>`? I decided not to, …
=> api: move primary from FingerId to Pointer events

Cargo.toml, examples/util/fill.rs, src/event_loop.rs, src/lib.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/window.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/window.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/window.rs, src/window.rs
Winit is not useful without it and we don't provide older versions anymore.
=> chore: always pull raw-window-handle

examples/window.rs, src/changelog/unreleased.md, src/platform_impl/linux/x11/window.rs
This is a kind of follow-up to https://github.com/rust-windowing/winit/pull/3973.
There's an API to programmatically specify X11 screen id (override what is determined from the `DISPLAY` env variable), but it doesn't work.
Setting up X Server with 2 screens and calling `DISPLAY=:0 X11_SCREEN_ID=1 cargo run --example window` should be equivalent to calling `DISPLAY=:0.1 cargo run --example window`
The latter works now (and places the window on the correct screen), but the former yields
`failed to create initial window: Os(OsError { line: 620, file: "src/platform_impl/linux/x11/window.rs", error: X11Error(X11Error { error_kind: Match, error_code: 8, sequence: 219, bad_value: 1319, minor_opcode: 0, major_opcode: 1, extension_name: None, request_name: Some("CreateWindow") }) })`
_Here `1319` …
=> x11: fix `WindowAttributesExtX11::with_x11_screen()`, extend example

src/changelog/unreleased.md, src/platform_impl/linux/x11/window.rs, src/window.rs
XIM servers currently do not support preedit area reporting from
clients and there may be no standard way to report it.
Fcitx and iBus both place the candidate window descending descending
from the caret, with the reported X font; but since winit does not
report a font, the height of the line is assumed 0, so when we report
the top left corner of the cursor area they will tend to obscure it.
Taking this into account, the best default option is to report the
bottom right corner of the cursor area, because it will tend not to
obscure the preedit area when using `Window::set_ime_cursor_area` in
the way suggested by documentation.
Fixes #3965
=> X11: Use bottom-right corner of IME cursor area as caret position.

src/event_loop.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/wayland/window/state.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/xdisplay.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/mod.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs
This will help in case we want to linger the event loop during drop
to prevent use after free in the consumers code.f
--
Depends on #3980
=> api: make OwnedDisplayHandle wrap an opaque type

src/platform_impl/apple/appkit/window_delegate.rs
Similar to https://github.com/rust-windowing/winit/pull/4027, I didn't test the implementation of `safe_area` properly on older devices when I made it in #3890, likely after migrating that from rectangles to insets.
- Tested on macOS 14.7.1 and macOS 10.12.6
- This is going to go in the same release as the PR the bug was introduced in, so have not added a changelog entry.
=> macOS: Fix safe area on macOS 10.14 and below

src/platform_impl/apple/appkit/window_delegate.rs
I must have either been confused about what `contentRectForFrameRect:` returns when I made this in https://github.com/rust-windowing/winit/pull/3890, or perhaps it was introduced during a merge? In any case, I didn't test it properly then, and the implementation was wrong. So I've fixed that.
- This is going to go in the same release as the PR the bug was introduced in, so have not added a changelog entry.
=> macOS: Fix surface position

src/changelog/unreleased.md, src/platform_impl/apple/uikit/monitor.rs
See https://github.com/bevyengine/bevy/issues/16541, we were comparing the pointer addresses of `MonitorHandle` (which changes every time a new one is created) instead of `UIScreen` (which is more stable).
TODO:
- Tested on the iOS simulator (with a single screen) and Mac Catalyst (with two monitors).
=> Fix `MonitorHandle` `PartialEq` and `Hash` on iOS

src/changelog/unreleased.md, src/platform_impl/apple/event_handler.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/view.rs, src/platform_impl/apple/uikit/window.rs
Events like `resumed`, `new_events`, `about_to_wait`, and so on will never happen as a result of programmer action, so we'll never need to queue those. This allows us to remove the need for the old `Event` struct in the iOS backend.
Furthermore, we can now remove `InUserCallback`, since that state is already stored inside `EventHandler`.
I've tried to otherwise keep the semantics as close to the original by calling `handle_nonuser_events(mtm, [])`, which flushes pending events.
=> iOS: Never queue application-level events

src/changelog/unreleased.md, src/platform_impl/apple/appkit/cursor.rs
`AnyClass::responds_to` delegates to `class_respondsToSelector`, a function provided by the Objective-C runtime. However, at some point, this began to return `false` for selectors referring to undocumented cursors, despite the cursors remaining accessible via said selectors. That this check fails prevents the cursors from being used.
We can instead send `respondsToSelector:` to the `NSCursor` class itself. As an instance method, this is nominally impossible; however, Apple grants an [exemption](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocObjectsClasses.html#//apple_ref/doc/uid/TP30001163-CH11-TPXREF120) that permits class objects to perform instance methods defined in the root class.
Checking for the undocumented cursors in this way …
=> macOS: Fix selector response checking for undocumented cursors

Cargo.toml, src/changelog/unreleased.md, src/platform/macos.rs, src/platform_impl/apple/appkit/view.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/appkit/window_delegate.rs
Fixes https://github.com/rust-windowing/winit/issues/3894. I don't really have any experience with macOS-related programming, so not really sure if it is technically correct but it does seem to work properly
=> Implement ability to make non-activating window on macOS

src/changelog/unreleased.md, src/platform_impl/linux/x11/event_processor.rs
The filtered events were still processed even though they shouldn't once we know that they're filtered.
Fixes #4048.
=> x11: fix KeyboardInput delivered twice with IME

src/changelog/unreleased.md, src/platform_impl/windows/event_loop.rs
Fixes #4055.
It turns out this is easy to test even though AccessKit doesn't yet support winit master. If you run the `window` example on Windows with the NVDA screen reader running without this fix, NVDA doesn't read the window title, or reads it with a severe delay. With this fix, it reads the window title immediately as expected, even though the application doesn't implement accessibility.
=> windows: Fix the event loop to wake on accessibility requests

src/changelog/unreleased.md, src/platform_impl/linux/x11/ime/input_method.rs
GNOME doesn't list that there's a _NONE_ style at all, but it still works if you use it.
=> x11: add workaround for disabling IME on gnome

src/changelog/unreleased.md, src/platform/startup_notify.rs, src/platform_impl/linux/wayland/types/xdg_activation.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/linux/x11/window.rs, src/window.rs
This is needed when passing and getting token from the IPC to activate the window.
=> api: add `ActivationToken::{from,into}_raw`

src/changelog/unreleased.md, src/monitor.rs, src/platform/ios.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/apple/uikit/monitor.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/wayland/mod.rs, src/platform_impl/linux/wayland/output.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/monitor.rs, src/platform_impl/linux/x11/util/randr.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/mod.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/mod.rs, src/platform_impl/web/monitor.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/monitor.rs, src/platform_impl/windows/window.rs, src/window.rs
The video mode is generally a static data and not a reference to some video mode. This changes the exclusive fullscreen API to match that and accept a monitor now.
---
Extracted from #3927
=> api: make VideoModeHandle into VideoMode

src/platform_impl/apple/appkit/ffi.rs, src/platform_impl/apple/appkit/monitor.rs
This no longer exposes `CGDisplayCreateUUIDFromDisplayID` and instead offers a new `CfUuid` type that can be created from a display ID and also cleans itself up on drop.
Closes #4031
---
=> Use wrapper type for CFUUID

src/changelog/unreleased.md, src/platform_impl/linux/wayland/seat/text_input/mod.rs
When all we'll be doing is setting a new preedit, the preedit doesn't have to be explicitly cleared first. This change is perhaps debatable.
The direct reason for this is to make it easier to work around quirks/bugs: in [Masonry](https://github.com/linebender/xilem/masonry) we've found IBus appears to resend the IME preedit in response to `Window::set_ime_cursor_area`
(`zwp_text_input_v3::set_cursor_rectangle`). Because currently the preedit is first cleared, a new IME cursor area is sent, which again causes IBus to resend the preedit. This can loop for a while.
The Wayland protocol is mechanically quite prescriptive, it says for [`zwp_text_input_v3::done`](https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:event:done)
> 1. Replace existing preedit string with the …
=> wayland: clear IME preedit only when necessary

Cargo.toml, src/changelog/unreleased.md, src/platform/ios.rs, src/platform/macos.rs, src/platform_impl/apple/appkit/app.rs, src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/cursor.rs, src/platform_impl/apple/appkit/event.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/ffi.rs, src/platform_impl/apple/appkit/menu.rs, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/appkit/observer.rs, src/platform_impl/apple/appkit/util.rs, src/platform_impl/apple/appkit/view.rs, src/platform_impl/apple/appkit/window.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/notification_center.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/monitor.rs, src/platform_impl/apple/uikit/view.rs, src/platform_impl/apple/uikit/view_controller.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs
This adds a few new crates that have more complete bindings than their predecessors (our `ffi` module is now a lot smaller), and uses the new `available!` macro to check for availability of APIs before using them.
=> Update to `objc2` v0.6

src/changelog/unreleased.md, src/platform_impl/linux/x11/ime/callbacks.rs, src/platform_impl/linux/x11/ime/context.rs, src/platform_impl/linux/x11/ime/input_method.rs, src/platform_impl/linux/x11/ime/mod.rs
Let's just not forward events to the IME once the user requested that it should be disabled, though, still try to change its state explicitly.
Fixes #4082.
=> x11: fix crash with uim

src/platform_impl/linux/x11/event_processor.rs
The serial was not unique, thus leading to issues and replay being triggered for normal input. Track modifiers based on they keycodes instead, since it's more unique.
Links: https://github.com/alacritty/alacritty/issues/8461
=> x11: fix modifiers replay

src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/wayland/event_loop/sink.rs
To avoid an unreachable case, and to allow removing the top-level `Event` enum in the future. Should be purely a refactor.
=> Wayland: Use custom `Event` enum for buffered events

src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/web/event_loop/window_target.rs, src/platform_impl/web/web_sys/canvas.rs
This allows removing the top-level `Event` enum in the future, and makes it clearer which events the backend actually emits.
=> Web: Avoid top-level `Event`

src/platform_impl/apple/appkit/monitor.rs
`CFArrayGetValueAtIndex` does not return a retained value, so we must retain ourselves.
Introduced in #4092, so didn't add a changelog entry for it.
=> macOS: Fix crash when reconnecting monitors

src/platform_impl/apple/appkit/event.rs
Follow-up to https://github.com/rust-windowing/winit/pull/4019. These are probably all unreachable, so shouldn't really matter, but for completeness.
=> macOS: Parse more key codes into named keys

src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/event_loop_proxy.rs, src/platform_impl/apple/mod.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/apple/uikit/mod.rs
Setting an atomic in `wake_up` and relying on it being propagated by the time the run loop wakes up is brittle, the proper way of using [`CFRunLoopSource`](https://developer.apple.com/documentation/corefoundation/cfrunloopsource?language=objc) is to do your work inside the `perform` callback. This also automatically handles coalescing multiple events, and frees us from having to manually check an atomic on each iteration of the run loop.
- I decided not to, the real change is in https://github.com/rust-windowing/winit/pull/3694.
Part of https://github.com/rust-windowing/winit/issues/1029.
=> macOS/iOS: Implement wake-ups using system mechanisms

src/changelog/unreleased.md, src/event_loop.rs, src/monitor.rs, src/platform/android.rs, src/platform/ios.rs, src/platform/macos.rs, src/platform/startup_notify.rs, src/platform/wayland.rs, src/platform/web.rs, src/platform/windows.rs, src/platform/x11.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/uikit/window.rs, src/platform_impl/linux/wayland/window/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/web/web_sys/fullscreen.rs, src/platform_impl/windows/window.rs, src/utils.rs, src/window.rs
Avoids issues with calling `.as_any().downcast_ref()` on smart pointers, and makes it simpler to convert into the backend type, and clearer which kind of conversion we support. Alternative to https://github.com/rust-windowing/winit/pull/4157.
We should also be able to completely remove `AsAny` once we have MSRV 1.86, which is why I've added `Any` as a supertrait of that.
It's actually a miracle that `crate::monitor::MonitorHandle` -> `dyn crate::monitor::MonitorHandleProvider` -> `.as_any` -> `platform_impl::MonitorHandle` path that we use currently works at all (which it only does because all method calls do an implicit deref).
- Not yet, backend types aren't yet exposed.
=> Add `as_inner` helper method on trait objects

examples/application.rs, examples/util/fill.rs, examples/window.rs, src/changelog/unreleased.md, src/platform_impl/windows/event_loop.rs
When clicking the title bar on Windows, to drag the window, there is a noticeable ~500ms pause in continuous redraw requests. This was fixed in #839 and then regressed in #1852. The cursor blinks in both cases and is unrelated. The regression made the blink happen after the pause instead of immediately.
=> Fix a pause in the event loop when clicking the title bar on windows

src/changelog/unreleased.md, src/platform/macos.rs, src/platform_impl/apple/appkit/window_delegate.rs
Also fixes a panic when leaving simple fullscreen.
=> Have WindowExtMacOS::set_simple_fullscreen honor WindowExtMacOS::set_borderless_game

examples/application.rs, examples/window.rs, src/application.rs, src/changelog/unreleased.md, src/event.rs, src/event_loop.rs, src/lib.rs, src/platform/ios.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/event_handler.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/orbital/event_loop.rs, src/platform_impl/web/event_loop/runner.rs, src/platform_impl/windows/event_loop/runner.rs
Part of https://github.com/rust-windowing/winit/issues/2903, split out from https://github.com/rust-windowing/winit/pull/3895. This is the motivation for doing https://github.com/rust-windowing/winit/pull/3721.
Calling the `Drop` impl of the user's `ApplicationHandler` is important on macOS, iOS and Web, since they don't necessarily return from `EventLoop::run_app`. This PR fixes that.
And now that we reliably call `Drop`, the `ApplicationHandler::exited` event/callback is unnecessary; using `Drop` composes much better (open files etc. stored in the app state will be automatically flushed), and prevents weirdness like attempting to create a new window while exiting. So this PR also removes that method.
=> Drop application handler on run loop exit

src/changelog/unreleased.md, src/platform_impl/linux/wayland/event_loop/mod.rs, src/platform_impl/linux/x11/mod.rs
Using `Duration::Zero` with `Wait` polling mode was still blocking until the event was actually delivered. Thus when `pump_events` API is used, ensure that it's not happening.
Fixes #4130.
=> x11:wayland: fix pump_events blocking with `Wait`

src/changelog/unreleased.md, src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/event_loop.rs
This disallows carrying over open windows between calls of `run_app_on_demand` (which wasn't intended to be supported anyhow). Wasn't nearly as hard as I feared. Fixes https://github.com/rust-windowing/winit/issues/4135.
I looked a bit back, seems this was noted in https://github.com/rust-windowing/winit/pull/2767#pullrequestreview-1498222334 too, but never resolved.
=> macOS: Close windows automatically when exiting

CONTRIBUTING.md, README.md
=> README // Add formatting policy.

examples/application.rs, src/changelog/unreleased.md, src/icon.rs, src/lib.rs, src/platform/pump_events.rs, src/platform/windows.rs, src/platform_impl/android/mod.rs, src/platform_impl/apple/appkit/mod.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/mod.rs, src/platform_impl/linux/mod.rs, src/platform_impl/linux/x11/window.rs, src/platform_impl/orbital/mod.rs, src/platform_impl/web/mod.rs, src/platform_impl/windows/icon.rs, src/platform_impl/windows/mod.rs, src/platform_impl/windows/window.rs, src/window.rs
Same as for `CustomCursor`. However, the API uses `dyn` stuff only because of `Windows` backend at the time of writing, generally, platforms should just have a separate method that deals with all of that, and e.g. top-level winit only guarantees `Rgba`.
Part of https://github.com/rust-windowing/winit/issues/3433.
=> icon: refactor `Icon` to be `dyn`

Cargo.toml, src/platform_impl/apple/appkit/event.rs, src/platform_impl/apple/appkit/ffi.rs, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/appkit/observer.rs, src/platform_impl/apple/appkit/window_delegate.rs, src/platform_impl/apple/event_loop_proxy.rs, src/platform_impl/apple/uikit/app_state.rs, src/platform_impl/apple/uikit/event_loop.rs
A lot of CoreFoundation methods have been marked safe, and converted into methods. Note that the old functions are still available, just deprecated.
- Tested on macOS and Mac Catalyst.
- This is a minor version bump, not interesting.
=> Use next `objc2` version

.github/workflows/ci.yml, Cargo.toml, README.md, dpi/CHANGELOG.md, dpi/Cargo.toml, dpi/LICENSE-LIBM-MIT, dpi/README.md, dpi/src/lib.rs, dpi/src/libm.rs
This shouldn't be a breaking change, because:
1) DPI currently has no default features (so no users should have disabled default features)
2) The default configuration of DPI still compiles
This is useful for creating UI programs which can run on no_std targets, such as embedded.
=> Make DPI `no_std` compatible

src/changelog/unreleased.md, src/platform_impl/linux/wayland/window/state.rs
Only mark that the grab was applied when it actually got applied. Previously there was an issue with grab being marked as applied without a pointer over the window, when in reality it wasn't.
Fixes #4073.
--
Could you test this, @Jupeyy? It's a bit different approach, but should also solve it.
=> wayland/fix: crash due consequent calls to set_cursor_grab

Cargo.toml, src/changelog/unreleased.md, src/platform_impl/linux/wayland/event_loop/mod.rs
=> wayland: ensure external loop is notified with pump_events

src/changelog/unreleased.md, src/platform/wayland.rs, src/platform_impl/linux/wayland/window/mod.rs
I did not update changelog yet because I don't know if this change is okay or not.
Resolves #4068.
=> wayland: Add `WindowExtWayland::xdg_toplevel`

src/changelog/unreleased.md, src/platform_impl/linux/wayland/seat/mod.rs, src/platform_impl/linux/wayland/seat/pointer/mod.rs, src/platform_impl/linux/wayland/window/state.rs
Currently, winit uses an integer surface scale for custom cursor icons on the Wayland platform. When a monitor uses fractional scaling, this results in the cursor appearing slightly smaller than expected.
For example, if the desktop scale factor is 1.5, winit sets the scale factor to 2. The compositor then downscales from 2 to 1.5, while users expect the icon displayed as provided.
This change applies a fractional scale using a viewport for the custom cursor, avoiding the issue above.
=> custom cursor fractional scale support for wayland platform

src/changelog/unreleased.md, src/platform_impl/apple/appkit/monitor.rs
Do not round the refresh rate until _after_ it has been converted to millihertz.
This was introduced in https://github.com/rust-windowing/winit/pull/2352, before that PR, fractional refresh rates weren't a thing in Winit. But after that, we still rounded the refresh rate on macOS. See also https://github.com/rust-windowing/winit/pull/3254#discussion_r1412133048.
The `application.rs` example now outputs the expected values:
=> fix: Support fractional refresh rates in video modes on macOS

src/changelog/unreleased.md, src/platform_impl/apple/appkit/ffi.rs, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/appkit/window_delegate.rs
The monitor UUID is what actually represents the monitor, `CGDirectDisplayID` is closer in correspondence to a configured framebuffer. We've already been doing comparisons on the UUID for [a while](https://github.com/rust-windowing/winit/pull/925), let's finish this by also storing the UUID.
Fixes #4166.
I have created a branch for backporting this onto v0.30 [here](https://github.com/rust-windowing/winit/tree/madsmtm/macos-monitor-handle-uuid-v0.30.x).
=> macOS: Store UUID in MonitorHandle instead of CGDirectDisplayID

src/changelog/unreleased.md, src/platform_impl/apple/appkit/monitor.rs, src/platform_impl/apple/appkit/window_delegate.rs
Instead of panicking, raise a warning and return `None` or similar.
Redo of https://github.com/rust-windowing/winit/pull/4171, but for the `master` branch, and with an extra fix for `Window::current_monitor` (which could easily exhibit similar issues).
Fixes https://github.com/bevyengine/bevy/issues/17827.
- Tested in https://github.com/rust-windowing/winit/pull/4171.
=> macOS: Fix monitors connected via certain Thunderbolt hubs

src/changelog/unreleased.md, src/platform_impl/windows/ime.rs
This pull request resolves the Ime::Preedit issue reported in #3967.
The issue arises because text is based on UTF-8 while attribute is based on UTF-16, leading to misalignment in cursor positioning.
=> Windows: Fix Incorrect cursor_range Calculation in Ime::Preedit

.github/workflows/ci.yml, Cargo.toml, README.md, src/changelog/unreleased.md, src/platform_impl/linux/common/xkb/mod.rs, src/platform_impl/linux/x11/mod.rs, src/platform_impl/windows/dark_mode.rs, src/platform_impl/windows/event_loop.rs, src/platform_impl/windows/keyboard_layout.rs, src/platform_impl/windows/util.rs, src/utils.rs
Desired by https://github.com/rust-windowing/winit/pull/4208.
=> Bump MSRV to 1.80

Cargo.toml, winit-core/Cargo.toml
To reduce the amount of duplication in Cargo.tomls when we split into different crates.
Part of https://github.com/rust-windowing/winit/issues/3433.
=> Use workspace dependencies everywhere

src/platform_impl/linux/common/xkb/state.rs, winit-core/src/event.rs, winit-core/src/keyboard.rs
Emphasize the difference between logical and physical state (and a bit between side-agnostic and left/right mods), reference sticky mods
=> Update modifier state docs

winit-core/src/keyboard.rs
Following suggestion https://github.com/rust-windowing/winit/pull/4234#discussion_r2098715744 to document sticky vs toggle modifier differences, though in a properly detailed form it might seem a bit complicated
(best reviewed rendered since it has some markup)
=> doc: add info on sticky vs toggle modifier behavior

src/platform_impl/apple/appkit/app_state.rs, src/platform_impl/apple/appkit/event_loop.rs, src/platform_impl/apple/appkit/observer.rs
This was introduced in https://github.com/rust-windowing/winit/pull/1853, but is unnecessary nowadays after the introduction of `extern "C-unwind"` unwinding across FFI is safe in Rust (and it was always supported by the CF observer callbacks themselves).
Panicking elsewhere (such as in NSNotificationCenter callbacks or delegate methods) _may_ still lead to an abort, if AppKit tries to catch it with libc++, since Rust panics are not compatible with those. That's "just" a quality-of-implementation detail of current Rust though, not an inherent limitation, and should really be solved upstream.
- This is an implementation detail, only real change is that the backtrace is a bit shorter.
=> macOS: Remove panic wrapper

src/changelog/unreleased.md, src/platform_impl/apple/appkit/ffi.rs, src/platform_impl/apple/appkit/monitor.rs, winit-core/src/monitor.rs
It is unclear what values `CGDisplayModeCopyPixelEncoding` is allowed to return, so let's make sure to handle unknown cases.
Another option would be to remove it completely, and always return `None` (that'd be more in-line with what `VideoMode`s actually control on macOS nowadays). WDYT @kchibisov?
=> fix: Allow unknown bit-depth on macOS

src/event_loop.rs, src/platform_impl/web/event_loop/mod.rs, src/platform_impl/web/event_loop/runner.rs, winit-android/src/event_loop.rs, winit-appkit/src/app_state.rs, winit-appkit/src/event_loop.rs, winit-core/src/error.rs, winit-orbital/src/event_loop.rs, winit-uikit/src/event_loop.rs, winit-wayland/src/event_loop/mod.rs, winit-win32/src/event_loop.rs, winit-x11/src/event_loop.rs
This check was introduced in https://github.com/rust-windowing/winit/pull/2344 to fix https://github.com/rust-windowing/winit/issues/2166, and later relaxed on Web in https://github.com/rust-windowing/winit/pull/2720.
We need to move the check into the backends themselves though to finish https://github.com/rust-windowing/winit/pull/4249, so that is what this PR does. On a few platforms (AppKit and UIKit), I've opted to implement this using existing checks instead of a new `static`.
=> chore: Move event loop recreation check into backends themselves

examples/application.rs, examples/util/fill.rs
Was using `time` unconditionally.
=> examples/application: fix running on wasm

examples/application.rs, winit-appkit/src/window_delegate.rs, winit-core/src/window.rs, winit-wayland/src/seat/text_input/mod.rs, winit-win32/src/window.rs, winit-x11/src/window.rs
When the API is shaped so that the API user can enable capabilities from a future version of the API, e.g. with Capabilities.all(), the API user still can't supply them. The new version of the backend may reject them, causing a breakage on upgrade.
This change prevents the API user from enabling capabilities they don't know about.
* * *
I thought that winit doesn't want to have to bump the major version just because new features are added in this area.
@kchibisov
=> input method: Prevent adding caps from breaking backward-compatibility

winit-win32/src/keyboard.rs, winit/src/changelog/v0.29.md
The typos action was updated on a remote host, breaking all existing CI pipelines.
* * *
Seems that CI is set up in such a way that changes in other projects can break the pipelines here.
I made them happy again.
=> CI: fix typos

Cargo.toml, winit/src/changelog/unreleased.md
> thread 'main' panicked at /Users/robert/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/objc2-foundation-0.2.2/src/generated/NSEnumerator.rs:7:1:
> invalid message send to -[_TtGCs23_ContiguousArrayStorageCSo8NSScreen_$ countByEnumeratingWithState:objects:count:]: expected return to have type code 'q', but found 'Q'
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fixes #4299
uses suggested fix from https://github.com/madsmtm/objc2/issues/765
=> Fix runtime crash on macos26 "type code 'q', but found 'Q'"

examples/application.rs, winit-core/src/event.rs, winit-wayland/src/seat/text_input/mod.rs, winit/src/changelog/unreleased.md
This completes the basic Wayland IME compatibility.
This should work with any compatible input method, but I tested on my development versions:
Anvil: https://github.com/dcz-self/smithay/tree/im_popup_v3 `cargo run -- --winit`
Stiwri: https://codeberg.org/dcz/stiwri/src/branch/popup `WAYLAND_DISPLAY=wayland-1 cargo run --bin t9`
Because the test application doesn't actually display text, you have to track the events in its console. A delete request will get sent by the IME when the pre-edit is empty, so you need to press the red X button twice. Best try out the IME on a regular application first.
=> IME: Add delete_surrounding_text

.github/CODEOWNERS
This is making official what's basically been the
case for the past few months at this point. I no
longer have the capacity to effectively review
and merge PRs for the Windows and X11 backends.
Thanks again for having me.
=> Remove self from CODEOWNERS

winit-appkit/src/view.rs, winit/src/changelog/unreleased.md
Fixes Main Thread Panic from IME during window/view teardown
=> fix: #4333 Main Thread Panic triggered by ime during view teardown

winit-win32/src/dark_mode.rs, winit-win32/src/event_loop.rs, winit-win32/src/util.rs, winit/src/changelog/unreleased.md
The original [PR 4119](https://github.com/rust-windowing/winit/pull/4119) appears to be abandoned. This PR aims to recreate the fix, following the project guidelines.
> This PR fixes this issue: https://github.com/rust-windowing/winit/issues/4041
> 
> The code I deleted has a validation to check if the new window bounds which Windows is suggesting to move the monitor to is actually on the monitor which triggered the WM_DPI_CHANGED event. If that validation fails, it tried to move the window such that it will be on the monitor which triggered the WM_DPI_CHANGED event. However, this validation was buggy and was actually causing this bug. It was moving the window off of the intended monitor. It seems this is no longer necessary. For example, [Chromium's DPI changed …
=> prevent incorrect resizing/shifting of window when dragging onto monitor with different DPI

winit-core/src/window.rs, winit-orbital/src/window.rs, winit/src/changelog/unreleased.md
=> Add borderless fullscreen mode for orbital

winit-wayland/src/seat/pointer/mod.rs, winit/src/changelog/unreleased.md
This can be tested with the `application` example, looking at the events shown for mouse wheel movement.
`wl_pointer::axis_discrete` isn't sent in version 8 or higher of `wl_pointer`. And `sctk` doesn't convert the `value120` events, so on compositors advertising version 8, only pixel scroll events were being sent.
This sends `MouseScrollDelta::LineDelta` with a fractional value, without doing any accumulation. Given `LineDelta` contains `f32` values, this presumably is expected?
Though it might be good to change the definition of `MouseScrollDelta` to include both discrete and pixel values, when the compositor sends both. I'm not familiar with how this works on non-Wayland backends though.
=> wayland: Handle `axis_value120` scroll events
